import type { Guide } from "./types";

// Content hub. Each guide must be genuinely useful on its own, not a disguised ad.
export const guides: Guide[] = [
  {
    slug: "wedding-planning-timeline",
    title: { en: "A calm wedding timeline: what to do 6, 3 and 1 month before", ar: "جدول عرس هادئ: وش تسوين قبل ٦ و٣ وشهر" },
    excerpt: {
      en: "Most wedding stress comes from deciding things too late. Here is a simple order that works for Gulf weddings.",
      ar: "أغلب توتر العرس يجي من القرارات المتأخرة. هذا ترتيب بسيط يناسب أعراس الخليج.",
    },
    category: "wedding-events",
    readingMinutes: 5,
    relatedProduct: "oneclick-bride",
    publishedAt: "2026-10-02",
    body: {
      en: [
        "Wedding planning feels overwhelming because everything seems urgent at once. It isn't. Most decisions have a natural window, and doing them in order removes most of the stress.",
        "## Six months or more before",
        "- Agree the total budget with everyone contributing, and write it down.",
        "- Book the hall first: popular dates in wedding season go early.",
        "- Choose the dress designer, since custom dresses need several fittings.",
        "- Draft the guest list in two groups: must-invite and if-space-allows.",
        "## Three months before",
        "- Confirm the photographer and videographer, with written prices.",
        "- Plan the henna night and any other events.",
        "- Order invitations, then send them six to eight weeks ahead.",
        "- Book makeup and hair trials.",
        "## The final month",
        "- Final dress fitting.",
        "- Confirm every vendor by phone one week before, with arrival times.",
        "- Prepare an envelope of final payments, labeled by vendor.",
        "- Hand one trusted person the day-of contact list so you don't have to answer calls.",
        "## One habit that saves the most stress",
        "Write every decision in one place the moment it is made, with the amount and the vendor's number. Scattered chats are where deposits and dates get lost.",
      ],
      ar: [
        "تجهيز العرس يحسسك إن كل شي مستعجل في نفس الوقت. بس الحقيقة غير. أغلب القرارات لها وقت مناسب، ولما تمشين بالترتيب يروح أغلب التوتر.",
        "## قبل ستة أشهر أو أكثر",
        "- اتفقي على الميزانية الكلية مع كل المساهمين، واكتبيها.",
        "- احجزي القاعة أول شي: التواريخ المطلوبة في موسم الأعراس تروح بسرعة.",
        "- اختاري مصممة الفستان، لأن الفستان المفصّل يحتاج أكثر من بروفة.",
        "- جهزي قائمة الضيوف بقسمين: لازم ينعزمون، ولو فيه مكان.",
        "## قبل ثلاثة أشهر",
        "- أكدي المصورة والفيديو، والأسعار مكتوبة.",
        "- رتبي ليلة الحناء وأي مناسبات ثانية.",
        "- اطلبي بطاقات الدعوة، وأرسليها قبل ستة إلى ثمانية أسابيع.",
        "- احجزي تجربة المكياج والشعر.",
        "## الشهر الأخير",
        "- البروفة الأخيرة للفستان.",
        "- أكدي مع كل مورّد بالتلفون قبل أسبوع، مع وقت الوصول.",
        "- جهزي ظرف الدفعات الأخيرة، وعلى كل وحدة اسم المورّد.",
        "- أعطي شخص تثقين فيه قائمة أرقام يوم العرس عشان ما تردين على الاتصالات.",
        "## عادة وحدة توفر أكثر توتر",
        "اكتبي كل قرار في مكان واحد أول ما ينتخذ، مع المبلغ ورقم المورّد. المحادثات المتفرقة هي المكان اللي يضيع فيه العربون والمواعيد.",
      ],
    },
  },
  {
    slug: "grocery-list-that-sorts-itself",
    title: { en: "The grocery list that saves you a second trip", ar: "قائمة المقاضي اللي توفر عليك المشوار الثاني" },
    excerpt: {
      en: "Three small changes to how you write your list: sort by section, keep a regulars list, and add one price.",
      ar: "ثلاث تغييرات بسيطة في طريقة كتابة القائمة: رتّبها حسب القسم، خلّ لك قائمة معتادة، وأضف سعر.",
    },
    category: "shopping-home",
    readingMinutes: 4,
    relatedProduct: "oneclick-grocery",
    publishedAt: "2026-10-02",
    body: {
      en: [
        "Forgetting one item usually costs a second trip, and a second trip usually costs more than the item. A better list fixes this.",
        "## 1. Write by section, not by memory",
        "Group items the way your store is laid out: fruit and vegetables, dairy, bakery, dry goods, household. You walk each aisle once and stop zig-zagging.",
        "## 2. Keep a regulars list",
        "Most households buy the same 15 to 25 items every week. Keep them on a separate list and copy them in each week instead of remembering them.",
        "## 3. Add an expected price once",
        "Write the usual price next to each item one time. From then on, you know the total before the cashier does, and you notice when prices change.",
        "## 4. One list per household",
        "If two people shop, use one shared list so items don't get bought twice.",
      ],
      ar: [
        "نسيان غرض واحد غالبًا يكلفك مشوار ثاني، والمشوار الثاني غالبًا يكلف أكثر من الغرض نفسه. القائمة الأفضل تحل هذا.",
        "## ١. اكتب حسب القسم، مو حسب الذاكرة",
        "قسّم الأغراض مثل ترتيب المحل: خضار وفواكه، ألبان، مخبوزات، مواد جافة، منظفات. تمر على كل ممر مرة وحدة وتوقف اللف والدوران.",
        "## ٢. خلّ لك قائمة معتادة",
        "أغلب البيوت تشتري نفس ١٥ إلى ٢٥ غرض كل أسبوع. خلها في قائمة منفصلة وانسخها كل أسبوع بدل ما تتذكرها.",
        "## ٣. أضف السعر المتوقع مرة وحدة",
        "اكتب السعر المعتاد جنب كل غرض مرة وحدة. بعدها تعرف المجموع قبل الكاشير، وتنتبه لما تتغير الأسعار.",
        "## ٤. قائمة وحدة للبيت",
        "لو أكثر من شخص يتسوق، استخدموا قائمة مشتركة وحدة عشان ما ينشرى الغرض مرتين.",
      ],
    },
  },
  {
    slug: "three-priorities-a-day",
    title: { en: "Three priorities a day: the simplest planning system that sticks", ar: "ثلاث أولويات في اليوم: أبسط نظام تخطيط يكمل معك" },
    excerpt: {
      en: "Long to-do lists create guilt, not progress. Choosing three things a day is easier to keep and easier to finish.",
      ar: "قوائم المهام الطويلة تسبب إحساس بالتقصير، مو إنجاز. اختيار ثلاث أشياء في اليوم أسهل تلتزم فيه وتخلصه.",
    },
    category: "life-productivity",
    readingMinutes: 3,
    relatedProduct: "oneclick-planner",
    publishedAt: "2026-10-02",
    body: {
      en: [
        "A to-do list with 27 items is not a plan. It is an inbox. The plan is the few things that must happen today.",
        "## How it works",
        "- Each evening, or first thing in the morning, choose three priorities for the day.",
        "- At least one should move a bigger goal forward, not just answer someone else's request.",
        "- Everything else stays in an inbox list. You look at it when choosing tomorrow's three.",
        "## Why three",
        "Three is small enough to finish on a busy day and big enough to make real progress across a week: fifteen meaningful things from Sunday to Thursday.",
        "## Close the week",
        "On Thursday, spend five minutes looking back: what got done, what moved, what to drop. Then choose Sunday's three.",
      ],
      ar: [
        "قائمة فيها ٢٧ مهمة مو خطة. هي صندوق وارد. الخطة هي الأشياء القليلة اللي لازم تصير اليوم.",
        "## كيف يشتغل",
        "- كل ليلة، أو أول شي الصبح، اختر ثلاث أولويات لليوم.",
        "- وحدة منها على الأقل تقدّم هدف أكبر، مو بس ترد على طلبات الناس.",
        "- كل شي ثاني يبقى في قائمة الوارد. تشوفها لما تختار أولويات بكرة.",
        "## ليش ثلاث",
        "ثلاث صغيرة كفاية تخلصها في يوم مزحوم، وكبيرة كفاية تعطيك تقدم حقيقي خلال الأسبوع: خمس عشرة إنجاز من الأحد للخميس.",
        "## سكّر الأسبوع",
        "يوم الخميس، خذ خمس دقايق تراجع فيها: وش خلص، وش تحرك، ووش تتركه. بعدها اختر أولويات الأحد.",
      ],
    },
  },
];

export function getGuide(slug: string) {
  return guides.find((g) => g.slug === slug);
}
