import type { Localized } from "@/i18n/config";

// DRAFT LEGAL FRAMEWORK. Written for digital products (not physical goods).
// Every page is flagged for review by a lawyer licensed in Oman before public launch.
// Placeholders in [brackets] are filled from Admin > Business settings.
// Format: "## " = heading, "- " = list item, otherwise paragraph.

export type LegalPage = { slug: string; title: Localized; summary: Localized; updated: string; body: { en: string[]; ar: string[] } };

const UPDATED = "2026-10-02";

export const legalPages: LegalPage[] = [
  {
    slug: "terms",
    title: { en: "Terms of Service", ar: "شروط الخدمة" },
    summary: { en: "The agreement for using One Click Digital Hub and its products.", ar: "الاتفاقية الخاصة باستخدام ون كليك ديجيتال هب ومنتجاتها." },
    updated: UPDATED,
    body: {
      en: [
        "These Terms govern your use of the One Click Digital Hub website, accounts and digital products. One Click Digital Hub is operated by [Company legal name], registered in the Sultanate of Oman under Commercial Registration [CR number].",
        "## 1. Who can use One Click Digital Hub",
        "You must be able to form a binding contract under the laws that apply to you. If you use One Click Digital Hub on behalf of a business, you confirm you are authorized to do so.",
        "## 2. Your account",
        "- Keep your login details confidential and tell us promptly about unauthorized use.",
        "- You are responsible for activity under your account.",
        "- We may suspend accounts used for fraud, abuse or breach of these Terms.",
        "## 3. Digital products",
        "Each product page states what you receive, how access works (for example lifetime access, subscription or download), supported devices and languages. Your purchase gives you a license to use the product, not ownership of it. See the Digital Product License.",
        "## 4. Prices and payment",
        "Prices are shown in Omani Rial (OMR) unless stated otherwise and include or exclude taxes as indicated at checkout. Payments are processed by a licensed third-party payment provider. One Click Digital Hub does not store card details.",
        "## 5. Refunds",
        "Refunds are handled under the Refund Policy, which forms part of these Terms.",
        "## 6. Acceptable use",
        "You may not resell, redistribute, reverse engineer or misuse One Click Digital Hub products, or use the site to break any law. See the Acceptable Use Policy.",
        "## 7. Availability and changes",
        "We work to keep One Click Digital Hub available and may improve or change products. If we discontinue an interactive product you paid for, we will give reasonable notice and an export of your data where practical.",
        "## 8. Liability",
        "One Click Digital Hub products are organization tools. To the extent permitted by law, we are not liable for indirect losses or for decisions you make using the products. Nothing in these Terms limits rights you have under applicable consumer protection law.",
        "## 9. Governing law",
        "These Terms are governed by the laws of the Sultanate of Oman. [To be confirmed by legal counsel, including dispute resolution for international customers.]",
        "## 10. Contact",
        "Questions about these Terms: [support email].",
      ],
      ar: [
        "تنظّم هذه الشروط استخدامك لموقع ون كليك ديجيتال هب وحساباته ومنتجاته الرقمية. تُدار ون كليك ديجيتال هب من قِبل [الاسم القانوني للشركة]، المسجلة في سلطنة عُمان بموجب السجل التجاري رقم [رقم السجل].",
        "## ١. من يحق له الاستخدام",
        "يجب أن تكون أهلًا لإبرام عقد ملزم وفق القوانين المطبقة عليك. وإذا استخدمت ون كليك ديجيتال هب نيابةً عن جهة تجارية، فإنك تؤكد أنك مخوّل بذلك.",
        "## ٢. حسابك",
        "- حافظ على سرية بيانات الدخول وأبلغنا فورًا عن أي استخدام غير مصرح به.",
        "- أنت مسؤول عن النشاط الذي يتم عبر حسابك.",
        "- يجوز لنا تعليق الحسابات المستخدمة في الاحتيال أو الإساءة أو مخالفة هذه الشروط.",
        "## ٣. المنتجات الرقمية",
        "توضح صفحة كل منتج ما ستحصل عليه، وطريقة الوصول (مثل الوصول مدى الحياة أو الاشتراك أو التحميل)، والأجهزة واللغات المدعومة. يمنحك الشراء ترخيصًا باستخدام المنتج، لا ملكيته. راجع ترخيص المنتجات الرقمية.",
        "## ٤. الأسعار والدفع",
        "تُعرض الأسعار بالريال العُماني ما لم يُذكر خلاف ذلك، وتشمل الضرائب أو لا تشملها وفق ما يوضَّح عند الدفع. تتم معالجة المدفوعات عبر مزوّد دفع مرخّص، ولا تحتفظ ون كليك ديجيتال هب ببيانات البطاقات.",
        "## ٥. الاسترجاع",
        "تُعالَج طلبات الاسترجاع وفق سياسة الاسترجاع التي تُعد جزءًا من هذه الشروط.",
        "## ٦. الاستخدام المقبول",
        "لا يجوز إعادة بيع منتجات ون كليك ديجيتال هب أو إعادة توزيعها أو الهندسة العكسية لها أو إساءة استخدامها، ولا استخدام الموقع لمخالفة أي قانون. راجع سياسة الاستخدام المقبول.",
        "## ٧. التوفر والتغييرات",
        "نسعى لإبقاء ون كليك ديجيتال هب متاحة، وقد نطوّر المنتجات أو نعدّلها. وإذا أوقفنا منتجًا تفاعليًا دفعت مقابله، فسنقدم إشعارًا معقولًا وتصديرًا لبياناتك متى أمكن ذلك.",
        "## ٨. المسؤولية",
        "منتجات ون كليك ديجيتال هب أدوات تنظيمية. وفي حدود ما يسمح به القانون، لا نتحمل المسؤولية عن الخسائر غير المباشرة أو القرارات التي تتخذها باستخدام المنتجات. ولا يحد أي شيء في هذه الشروط من حقوقك بموجب قوانين حماية المستهلك المطبقة.",
        "## ٩. القانون الواجب التطبيق",
        "تخضع هذه الشروط لقوانين سلطنة عُمان. [يُؤكَّد من المستشار القانوني، بما في ذلك تسوية النزاعات للعملاء الدوليين.]",
        "## ١٠. التواصل",
        "للاستفسار عن هذه الشروط: [بريد الدعم].",
      ],
    },
  },
  {
    slug: "privacy",
    title: { en: "Privacy Policy", ar: "سياسة الخصوصية" },
    summary: { en: "What we collect, why, and your choices.", ar: "ما نجمعه، ولماذا، وخياراتك." },
    updated: UPDATED,
    body: {
      en: [
        "One Click Digital Hub collects only what it needs to run your account, deliver your products and support you. We do not sell personal data.",
        "## What we collect",
        "- Account details: name, email address, language preference.",
        "- Orders: products purchased, amounts, dates and payment status. Card details are handled by the payment provider, never by One Click Digital Hub.",
        "- Product data you enter into interactive products (for example lists or plans), stored so the product works across your devices.",
        "- Messages and requests you send us, including custom solution briefs.",
        "- With your consent only: privacy-friendly usage analytics without advertising profiles.",
        "## Why we use it",
        "To provide and secure your account, deliver products, process orders, respond to support requests, send transactional emails and, if you opt in, product news.",
        "## Product data and AI",
        "We do not send your product data to AI services. If an optional AI feature is introduced, it will be clearly disclosed and off by default.",
        "## Service providers",
        "We use trusted providers for hosting, database, email and payments. Each is listed in our third-party services register and bound to protect your data. Some may process data outside Oman.",
        "## Retention",
        "Account and product data are kept while your account is active. Order records are kept for the period required by Omani tax and commercial law. Analytics data is aggregated and deleted after [period].",
        "## Your choices and rights",
        "You can access, correct, export or delete your data from your account settings or by contacting us. You can withdraw marketing or analytics consent at any time.",
        "## Contact",
        "Privacy questions: [privacy email]. [Legal review required: alignment with Oman Personal Data Protection Law (Royal Decree 6/2022) and its executive regulations, and with GDPR for EU visitors.]",
      ],
      ar: [
        "تجمع ون كليك ديجيتال هب فقط ما تحتاجه لتشغيل حسابك وتسليم منتجاتك ودعمك. ولا نبيع البيانات الشخصية.",
        "## ما نجمعه",
        "- بيانات الحساب: الاسم والبريد الإلكتروني واللغة المفضلة.",
        "- الطلبات: المنتجات المشتراة والمبالغ والتواريخ وحالة الدفع. تتولى جهة الدفع بيانات البطاقات، ولا تتعامل معها ون كليك ديجيتال هب.",
        "- البيانات التي تدخلها في المنتجات التفاعلية (مثل القوائم والخطط)، وتُحفظ لكي يعمل المنتج على أجهزتك.",
        "- الرسائل والطلبات التي ترسلها إلينا، بما فيها طلبات الحلول الخاصة.",
        "- بموافقتك فقط: تحليلات استخدام تحترم الخصوصية دون ملفات إعلانية.",
        "## لماذا نستخدمها",
        "لتقديم حسابك وتأمينه، وتسليم المنتجات، ومعالجة الطلبات، والرد على طلبات الدعم، وإرسال الرسائل التشغيلية، وإرسال أخبار المنتجات إذا وافقت على ذلك.",
        "## بيانات المنتجات والذكاء الاصطناعي",
        "لا نرسل بيانات منتجاتك إلى خدمات الذكاء الاصطناعي. وإذا أُضيفت ميزة ذكاء اصطناعي اختيارية فسيُفصح عنها بوضوح وتكون معطّلة افتراضيًا.",
        "## مزودو الخدمات",
        "نستعين بمزودين موثوقين للاستضافة وقاعدة البيانات والبريد والدفع. وجميعهم مدرجون في سجل خدمات الأطراف الثالثة وملزمون بحماية بياناتك. وقد يعالج بعضهم البيانات خارج سلطنة عُمان.",
        "## مدة الاحتفاظ",
        "نحتفظ ببيانات الحساب والمنتجات ما دام حسابك نشطًا. ونحتفظ بسجلات الطلبات للمدة التي تقتضيها القوانين الضريبية والتجارية في عُمان. وتُجمَّع بيانات التحليلات وتُحذف بعد [المدة].",
        "## خياراتك وحقوقك",
        "يمكنك الاطلاع على بياناتك أو تصحيحها أو تصديرها أو حذفها من إعدادات حسابك أو بالتواصل معنا. ويمكنك سحب موافقتك على التسويق أو التحليلات في أي وقت.",
        "## التواصل",
        "لأسئلة الخصوصية: [بريد الخصوصية]. [مطلوب مراجعة قانونية: التوافق مع قانون حماية البيانات الشخصية العُماني (المرسوم السلطاني ٦/٢٠٢٢) ولائحته التنفيذية، ومع اللائحة الأوروبية لزوار الاتحاد الأوروبي.]",
      ],
    },
  },
  {
    slug: "cookies",
    title: { en: "Cookie Policy", ar: "سياسة ملفات الارتباط" },
    summary: { en: "Essential storage and optional analytics.", ar: "التخزين الأساسي والتحليلات الاختيارية." },
    updated: UPDATED,
    body: {
      en: [
        "One Click Digital Hub uses a small amount of browser storage. Essential storage is always on; analytics is optional.",
        "## Essential",
        "- oc_locale: remembers your language (1 year).",
        "- oc-theme: remembers light or dark mode (local storage).",
        "- oc-consent: remembers your cookie choice (local storage).",
        "- oc-favorites: products you saved as a guest (local storage).",
        "- Authentication cookies when accounts are live (session, secure, HTTP-only).",
        "## Optional analytics",
        "Only with your permission, we use a privacy-friendly analytics provider [to be named once selected]. No advertising or cross-site tracking cookies are used.",
        "## Change your choice",
        "Use “Cookie settings” in the footer at any time.",
      ],
      ar: [
        "تستخدم ون كليك ديجيتال هب قدرًا محدودًا من التخزين في المتصفح. التخزين الأساسي مفعّل دائمًا، والتحليلات اختيارية.",
        "## الأساسي",
        "- oc_locale: يتذكر لغتك (سنة واحدة).",
        "- oc-theme: يتذكر الوضع الفاتح أو الداكن (تخزين محلي).",
        "- oc-consent: يتذكر اختيارك بخصوص ملفات الارتباط (تخزين محلي).",
        "- oc-favorites: المنتجات التي حفظتها كزائر (تخزين محلي).",
        "- ملفات المصادقة عند تفعيل الحسابات (جلسة، آمنة، غير متاحة للبرمجيات).",
        "## التحليلات الاختيارية",
        "بإذنك فقط، نستخدم مزود تحليلات يحترم الخصوصية [يُسمّى بعد اختياره]. ولا نستخدم ملفات إعلانية أو تتبعًا عبر المواقع.",
        "## تغيير اختيارك",
        "استخدم «إعدادات ملفات الارتباط» في أسفل الصفحة في أي وقت.",
      ],
    },
  },
  {
    slug: "refunds",
    title: { en: "Refund Policy", ar: "سياسة الاسترجاع" },
    summary: { en: "How refunds work for digital products.", ar: "كيف يتم الاسترجاع في المنتجات الرقمية." },
    updated: UPDATED,
    body: {
      en: [
        "Digital products are delivered instantly and cannot be returned like physical goods, so we offer free demos before purchase. We still want every customer to be treated fairly.",
        "## When you can request a refund",
        "- The product does not work as described and we cannot fix it within a reasonable time.",
        "- You were charged twice or charged in error.",
        "- You could not access the product because of a problem on our side.",
        "- [Proposed: a 7-day no-questions refund for interactive products used lightly. Owner decision required.]",
        "## Downloads",
        "Downloadable files that have been downloaded are generally non-refundable unless faulty, subject to applicable consumer law.",
        "## Custom solutions",
        "Custom work follows the payment milestones in your quote and the Custom Service Terms.",
        "## How to request",
        "Contact support with your order reference. We reply within 2 working days. Approved refunds go back to the original payment method; timing depends on the bank.",
        "[Legal review required: Oman Consumer Protection Law and e-commerce requirements for digital goods.]",
      ],
      ar: [
        "المنتجات الرقمية تُسلَّم فورًا ولا يمكن إرجاعها كالسلع المادية، ولذلك نوفر عروضًا تجريبية مجانية قبل الشراء. ومع ذلك نحرص على معاملة كل عميل بإنصاف.",
        "## متى يمكنك طلب الاسترجاع",
        "- إذا لم يعمل المنتج كما هو موصوف ولم نتمكن من إصلاحه خلال مدة معقولة.",
        "- إذا خُصم المبلغ مرتين أو خُصم عن طريق الخطأ.",
        "- إذا تعذّر عليك الوصول إلى المنتج بسبب مشكلة من جهتنا.",
        "- [مقترح: استرجاع خلال ٧ أيام دون أسئلة للمنتجات التفاعلية ذات الاستخدام المحدود. يتطلب قرار المالكة.]",
        "## الملفات القابلة للتحميل",
        "الملفات التي تم تحميلها لا تُسترجع عادةً إلا إذا كانت معيبة، مع مراعاة قوانين حماية المستهلك المطبقة.",
        "## الحلول حسب الطلب",
        "تخضع الأعمال الخاصة لمراحل الدفع المحددة في عرض السعر ولشروط الخدمات الخاصة.",
        "## طريقة الطلب",
        "تواصل مع الدعم مع ذكر رقم الطلب، وسنرد خلال يومي عمل. تُعاد المبالغ المعتمدة إلى وسيلة الدفع الأصلية، وتعتمد المدة على البنك.",
        "[مطلوب مراجعة قانونية: قانون حماية المستهلك العُماني ومتطلبات التجارة الإلكترونية للسلع الرقمية.]",
      ],
    },
  },
  {
    slug: "license",
    title: { en: "Digital Product License", ar: "ترخيص المنتجات الرقمية" },
    summary: { en: "What you may and may not do with One Click Digital Hub products.", ar: "ما يحق لك وما لا يحق لك فعله بمنتجات ون كليك ديجيتال هب." },
    updated: UPDATED,
    body: {
      en: [
        "When you buy a One Click Digital Hub product, you receive a license to use it. One Click Digital Hub keeps all intellectual property rights in the product, design and content.",
        "## Personal license (default)",
        "- Use the product for yourself and your household.",
        "- Print downloadable files for personal use.",
        "- Not allowed: sharing your account, reselling, redistributing files, or uploading them to other sites.",
        "## Commercial license (future)",
        "Allows use inside one business, for example a planner used by a small company's staff. Terms will be shown on products that offer it.",
        "## Team license (future)",
        "Multiple named users within one organization. Terms will be shown on products that offer it.",
        "## Your content",
        "Everything you type into a One Click Digital Hub product belongs to you.",
      ],
      ar: [
        "عند شراء منتج من ون كليك ديجيتال هب تحصل على ترخيص لاستخدامه، وتحتفظ ون كليك ديجيتال هب بجميع حقوق الملكية الفكرية في المنتج وتصميمه ومحتواه.",
        "## الترخيص الشخصي (الافتراضي)",
        "- استخدام المنتج لنفسك ولأهل بيتك.",
        "- طباعة الملفات القابلة للتحميل للاستخدام الشخصي.",
        "- غير مسموح: مشاركة حسابك، أو إعادة البيع، أو إعادة توزيع الملفات، أو رفعها على مواقع أخرى.",
        "## الترخيص التجاري (مستقبلًا)",
        "يسمح بالاستخدام داخل منشأة واحدة، مثل مخطط يستخدمه موظفو شركة صغيرة. وتُعرض الشروط على المنتجات التي توفره.",
        "## ترخيص الفريق (مستقبلًا)",
        "عدة مستخدمين محددين داخل جهة واحدة. وتُعرض الشروط على المنتجات التي توفره.",
        "## محتواك",
        "كل ما تكتبه داخل منتجات ون كليك ديجيتال هب ملك لك.",
      ],
    },
  },
  {
    slug: "custom-terms",
    title: { en: "Custom Service Terms", ar: "شروط الخدمات الخاصة" },
    summary: { en: "How custom digital projects work.", ar: "كيف تتم المشاريع الرقمية الخاصة." },
    updated: UPDATED,
    body: {
      en: [
        "Custom projects start with a written quote describing scope, timeline, price and payment milestones. Work begins after you accept the quote.",
        "## Scope and changes",
        "Changes outside the agreed scope are quoted separately before work continues.",
        "## Your materials",
        "You confirm you have the rights to any content, logos or images you provide.",
        "## Ownership",
        "On full payment, you own the final deliverables created specifically for you. One Click Digital Hub may reuse its general frameworks, components and know-how, and may show the project in its portfolio unless you ask us not to.",
        "## Hosting and third-party costs",
        "Domains, hosting, paid services and payment gateways are paid by the client unless the quote says otherwise.",
        "[Legal review required before first paid custom project.]",
      ],
      ar: [
        "تبدأ المشاريع الخاصة بعرض سعر مكتوب يحدد النطاق والجدول الزمني والسعر ومراحل الدفع، ويبدأ العمل بعد موافقتك على العرض.",
        "## النطاق والتعديلات",
        "التعديلات خارج النطاق المتفق عليه تُسعَّر بشكل منفصل قبل مواصلة العمل.",
        "## موادك",
        "تؤكد أنك تملك حقوق أي محتوى أو شعارات أو صور تقدمها.",
        "## الملكية",
        "بعد السداد الكامل، تمتلك المخرجات النهائية المصممة خصيصًا لك. ويجوز لون كليك ديجيتال هب إعادة استخدام أطرها ومكوناتها وخبرتها العامة، وعرض المشروع ضمن أعمالها ما لم تطلب خلاف ذلك.",
        "## الاستضافة وتكاليف الأطراف الثالثة",
        "يتحمل العميل تكاليف النطاقات والاستضافة والخدمات المدفوعة وبوابات الدفع ما لم ينص العرض على غير ذلك.",
        "[مطلوب مراجعة قانونية قبل أول مشروع خاص مدفوع.]",
      ],
    },
  },
  {
    slug: "acceptable-use",
    title: { en: "Acceptable Use", ar: "الاستخدام المقبول" },
    summary: { en: "Keeping One Click Digital Hub safe for everyone.", ar: "للحفاظ على ون كليك ديجيتال هب آمنة للجميع." },
    updated: UPDATED,
    body: {
      en: [
        "Please do not use One Click Digital Hub to:",
        "- Break any law or infringe anyone's rights.",
        "- Attempt to access accounts, data or systems that are not yours.",
        "- Upload malware, spam or abusive content.",
        "- Scrape, copy or resell One Click Digital Hub products or content.",
        "We may remove content or suspend accounts that break these rules.",
      ],
      ar: [
        "يُرجى عدم استخدام ون كليك ديجيتال هب في:",
        "- مخالفة أي قانون أو التعدي على حقوق الآخرين.",
        "- محاولة الوصول إلى حسابات أو بيانات أو أنظمة لا تخصك.",
        "- رفع برمجيات ضارة أو رسائل مزعجة أو محتوى مسيء.",
        "- نسخ منتجات ون كليك ديجيتال هب أو محتواها آليًا أو إعادة بيعها.",
        "يجوز لنا إزالة المحتوى أو تعليق الحسابات المخالفة لهذه القواعد.",
      ],
    },
  },
];

export function getLegalPage(slug: string) {
  return legalPages.find((p) => p.slug === slug);
}
