import { money } from "@/lib/money";
import type { Product } from "./types";

// SAMPLE CATALOG. Every product below is marked `sample: true` until the owner
// approves final copy and pricing in Admin. Prices are the editable launch default
// (15 OMR) from the brief, stored as data. Nothing here claims sales, reviews or users.

const LAUNCH_PRICE = money(15, "OMR");
const UPDATED = "2026-10-02";

export const products: Product[] = [
  {
    id: "prd_bride",
    slug: "oneclick-bride",
    name: { en: "One Click Bride", ar: "ون كليك عروس" },
    tagline: { en: "Your whole wedding, calmly in one place.", ar: "عرسك كله، بهدوء في مكان واحد." },
    summary: {
      en: "An interactive wedding planner with a live countdown, guided checklist, budget tracker, guest list and vendor notes. Built around how weddings in the Gulf are actually planned.",
      ar: "مخطط عرس تفاعلي فيه عدّ تنازلي، قائمة مهام مرتبة، متابعة للميزانية، قائمة ضيوف وملاحظات للموردين. مصمم على طريقة تجهيز الأعراس في الخليج.",
    },
    problem: {
      en: "Wedding details end up scattered across chats, notes apps, screenshots and memory. Deadlines slip and the budget quietly grows.",
      ar: "تفاصيل العرس تتوزع بين المحادثات والملاحظات والصور والذاكرة. المواعيد تفوت والميزانية تكبر بدون ما تنتبهين.",
    },
    audience: {
      en: "Brides, grooms and the family members helping them plan, from engagement to the big day.",
      ar: "العروس والعريس وأهلهم اللي يساعدون في التجهيز، من الملكة إلى يوم العرس.",
    },
    story: {
      chaos: { en: "40 open chats, 3 notebooks, one stressed bride", ar: "٤٠ محادثة مفتوحة، ٣ دفاتر، وعروس متوترة" },
      result: { en: "One dashboard that shows what is next", ar: "لوحة واحدة توضح لك الخطوة الجاية" },
    },
    benefits: [
      { en: "Always know the next task and its deadline", ar: "تعرفين دايمًا المهمة الجاية وموعدها" },
      { en: "See planned versus actual spending instantly", ar: "تشوفين المخطط مقابل المصروف الفعلي فورًا" },
      { en: "Share progress with family without endless messages", ar: "تشاركين التقدم مع الأهل بدون رسائل لا تنتهي" },
    ],
    features: [
      { title: { en: "Countdown & timeline", ar: "عدّ تنازلي وخط زمني" }, body: { en: "Tasks are grouped by months-to-go, so you only focus on what matters now.", ar: "المهام مقسمة حسب الأشهر المتبقية، فتركزين على المهم الحين بس." } },
      { title: { en: "Guided checklist", ar: "قائمة مهام موجّهة" }, body: { en: "A starting checklist for engagement, malka, henna and wedding day that you can edit freely.", ar: "قائمة جاهزة للخطوبة والملكة والحناء ويوم العرس، وتقدرين تعدلينها بحرية." } },
      { title: { en: "Budget tracker", ar: "متابعة الميزانية" }, body: { en: "Set a budget per category and log payments and deposits as they happen.", ar: "حددي ميزانية لكل بند وسجلي الدفعات والعربون أول بأول." } },
      { title: { en: "Guests & vendors", ar: "الضيوف والموردين" }, body: { en: "Track invitations, RSVPs, vendor contacts, quotes and appointments.", ar: "تابعي الدعوات والردود وأرقام الموردين وعروض الأسعار والمواعيد." } },
    ],
    included: [
      { en: "Interactive web planner (works on phone, tablet and computer)", ar: "مخطط تفاعلي على الويب (يشتغل على الجوال والتابلت والكمبيوتر)" },
      { en: "Editable starter checklist in Arabic and English", ar: "قائمة مهام جاهزة قابلة للتعديل بالعربي والإنجليزي" },
      { en: "Printable summary view", ar: "عرض ملخص قابل للطباعة" },
      { en: "Product updates for the life of the product", ar: "تحديثات المنتج طوال عمر المنتج" },
    ],
    devices: { en: "Any modern browser on phone, tablet or computer", ar: "أي متصفح حديث على الجوال أو التابلت أو الكمبيوتر" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "lifetime",
    status: "preview",
    price: LAUNCH_PRICE,
    categories: ["wedding-events"],
    tags: ["wedding", "planner", "budget", "checklist"],
    hue: "bride",
    featured: true,
    isNew: true,
    demo: "bride",
    faqs: [
      { q: { en: "Can my mother or sister help plan?", ar: "تقدر أمي أو أختي تساعدني في التخطيط؟" }, a: { en: "Shared access is planned for a later version. At launch, you can share a read-only printable summary.", ar: "المشاركة المباشرة مخطط لها في إصدار لاحق. عند الإطلاق تقدرين تشاركين ملخص قابل للطباعة." } },
      { q: { en: "Is it only for Omani weddings?", ar: "هل هو للأعراس العمانية فقط؟" }, a: { en: "No. The starter checklist reflects Gulf traditions, and every item is editable for any wedding.", ar: "لا. القائمة الجاهزة مستوحاة من عادات الخليج، وكل بند قابل للتعديل لأي عرس." } },
    ],
    sample: true,
    updatedAt: UPDATED,
  },
  {
    id: "prd_grocery",
    slug: "oneclick-grocery",
    name: { en: "One Click Grocery", ar: "ون كليك مقاضي" },
    tagline: { en: "Shop once. Forget nothing. Know the total.", ar: "تسوّق مرة. لا تنسى شي. واعرف المجموع." },
    summary: {
      en: "A fast, reusable shopping list that groups items by aisle, remembers your regulars and estimates the total before you reach the cashier.",
      ar: "قائمة مقاضي سريعة تتكرر معك، ترتب الأغراض حسب القسم، تتذكر أغراضك المعتادة وتحسب المجموع التقريبي قبل لا توصل الكاشير.",
    },
    problem: {
      en: "Grocery lists live in chat messages and scraps of paper. Items get forgotten, duplicates get bought and the bill is always a surprise.",
      ar: "قوائم المقاضي تكون في رسائل الواتساب وأوراق متفرقة. أغراض تنتسى، وأغراض تنشرى مرتين، والفاتورة دايمًا مفاجأة.",
    },
    audience: {
      en: "Households, busy parents and anyone who shops for a family every week.",
      ar: "البيوت والأمهات والآباء المشغولين وكل من يتسوق للعائلة كل أسبوع.",
    },
    story: {
      chaos: { en: "A long chat message and two forgotten items", ar: "رسالة طويلة في الواتساب وغرضين منسيين" },
      result: { en: "A sorted list with a running total", ar: "قائمة مرتبة ومجموع يتحدث أول بأول" },
    },
    benefits: [
      { en: "Lists sorted by section, so you walk the store once", ar: "القائمة مرتبة حسب القسم، فتلف المحل مرة وحدة" },
      { en: "Regular items come back with one tap", ar: "أغراضك المعتادة ترجع بضغطة وحدة" },
      { en: "An estimated total before you pay", ar: "مجموع تقريبي قبل لا تدفع" },
    ],
    features: [
      { title: { en: "Smart sections", ar: "أقسام ذكية" }, body: { en: "Produce, dairy, bakery, household and more, in the order you shop.", ar: "خضار، ألبان، مخبوزات، منظفات وأكثر، بالترتيب اللي تتسوق فيه." } },
      { title: { en: "Favorites & regulars", ar: "المفضلة والمعتاد" }, body: { en: "Save the items you buy every week and rebuild a list in seconds.", ar: "احفظ الأغراض اللي تشتريها كل أسبوع وجهّز القائمة بثواني." } },
      { title: { en: "Price estimates", ar: "تقدير الأسعار" }, body: { en: "Add an expected price once; the list keeps a running total in your currency.", ar: "أضف السعر المتوقع مرة؛ والقائمة تحسب المجموع بعملتك." } },
      { title: { en: "Multiple lists & stores", ar: "قوائم ومحلات متعددة" }, body: { en: "Weekly shop, monthly stock-up, Ramadan list. Each with its own store.", ar: "مقاضي الأسبوع، مقاضي الشهر، قائمة رمضان. كل وحدة بمحلها." } },
    ],
    included: [
      { en: "Interactive web app, installable to your home screen", ar: "تطبيق ويب تفاعلي، تقدر تضيفه للشاشة الرئيسية" },
      { en: "Starter item library in Arabic and English", ar: "مكتبة أغراض جاهزة بالعربي والإنجليزي" },
      { en: "Unlimited lists", ar: "قوائم بلا حدود" },
    ],
    devices: { en: "Designed phone-first; works on any modern browser", ar: "مصمم للجوال أولًا؛ ويشتغل على أي متصفح حديث" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "lifetime",
    status: "preview",
    price: LAUNCH_PRICE,
    categories: ["shopping-home"],
    tags: ["grocery", "shopping", "household", "list"],
    hue: "grocery",
    featured: true,
    isNew: true,
    demo: "grocery",
    faqs: [
      { q: { en: "Does it work in the store without internet?", ar: "يشتغل في المحل بدون إنترنت؟" }, a: { en: "Offline support is planned for launch so your list opens even with weak signal.", ar: "دعم العمل بدون إنترنت مخطط عند الإطلاق، عشان تفتح قائمتك حتى لو الشبكة ضعيفة." } },
      { q: { en: "Are prices pulled from real stores?", ar: "هل الأسعار من المحلات مباشرة؟" }, a: { en: "No. You enter the prices you expect, so totals are estimates you control.", ar: "لا. أنت تدخل الأسعار المتوقعة، فالمجموع تقدير تتحكم فيه." } },
    ],
    sample: true,
    updatedAt: UPDATED,
  },
  {
    id: "prd_planner",
    slug: "oneclick-planner",
    name: { en: "One Click Planner", ar: "ون كليك مخطط" },
    tagline: { en: "A clear week, without a complicated system.", ar: "أسبوع واضح، بدون نظام معقد." },
    summary: {
      en: "A weekly planner that turns a busy week into three clear priorities a day, with time blocks, habits and a gentle end-of-week review.",
      ar: "مخطط أسبوعي يحوّل أسبوعك المزدحم إلى ثلاث أولويات واضحة كل يوم، مع فترات زمنية وعادات ومراجعة خفيفة آخر الأسبوع.",
    },
    problem: {
      en: "Work, family and personal goals compete for the same hours. Most planners are either too empty to help or too complex to keep using.",
      ar: "الشغل والعائلة والأهداف الشخصية تتنافس على نفس الساعات. وأغلب المخططات إما فاضية ما تفيد أو معقدة ما تكمل معها.",
    },
    audience: {
      en: "Working professionals, parents and students who want structure without a steep learning curve.",
      ar: "الموظفين والأهالي والطلاب اللي يبون تنظيم بدون تعقيد.",
    },
    story: {
      chaos: { en: "Twelve tabs, five sticky notes, zero focus", ar: "١٢ تبويب، ٥ أوراق لاصقة، وتركيز صفر" },
      result: { en: "Three priorities a day, visibly done", ar: "ثلاث أولويات كل يوم، وتشوفها تنجز" },
    },
    benefits: [
      { en: "Start each day knowing your top three", ar: "تبدأ يومك وأنت عارف أهم ثلاث مهام" },
      { en: "See the whole week at a glance", ar: "تشوف أسبوعك كله بنظرة وحدة" },
      { en: "Build habits with simple streaks", ar: "تبني عادات بمتابعة بسيطة" },
    ],
    features: [
      { title: { en: "Top three", ar: "أهم ثلاث" }, body: { en: "Pick three priorities per day. Everything else waits in the inbox.", ar: "اختر ثلاث أولويات لكل يوم. والباقي ينتظر في الصندوق." } },
      { title: { en: "Week view", ar: "عرض الأسبوع" }, body: { en: "Sunday to Saturday or Monday to Sunday, your choice.", ar: "من الأحد للسبت أو من الاثنين للأحد، على راحتك." } },
      { title: { en: "Habits", ar: "العادات" }, body: { en: "Track up to five habits with a calm streak view.", ar: "تابع حتى خمس عادات بعرض هادئ للاستمرارية." } },
      { title: { en: "Weekly review", ar: "مراجعة أسبوعية" }, body: { en: "Five minutes on Thursday to close the week and plan the next.", ar: "خمس دقايق يوم الخميس تقفل فيها الأسبوع وتخطط للجاي." } },
    ],
    included: [
      { en: "Interactive weekly planner", ar: "مخطط أسبوعي تفاعلي" },
      { en: "Printable weekly sheet", ar: "ورقة أسبوعية قابلة للطباعة" },
      { en: "Arabic and English interface", ar: "واجهة عربية وإنجليزية" },
    ],
    devices: { en: "Any modern browser on phone, tablet or computer", ar: "أي متصفح حديث على الجوال أو التابلت أو الكمبيوتر" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "lifetime",
    status: "preview",
    price: LAUNCH_PRICE,
    categories: ["life-productivity"],
    tags: ["planner", "weekly", "habits", "productivity"],
    hue: "planner",
    featured: true,
    isNew: false,
    demo: "planner",
    faqs: [
      { q: { en: "Does the week start on Sunday?", ar: "هل الأسبوع يبدأ يوم الأحد؟" }, a: { en: "You choose: Sunday or Monday. Sunday is the default for GCC users.", ar: "على اختيارك: الأحد أو الاثنين. الأحد هو الافتراضي لمستخدمي الخليج." } },
    ],
    sample: true,
    updatedAt: UPDATED,
  },
  {
    id: "prd_fit",
    slug: "oneclick-fit",
    name: { en: "One Click Fit", ar: "ون كليك لياقة" },
    tagline: { en: "Show up, log it, see your progress.", ar: "تمرّن، سجّل، وشوف تقدمك." },
    summary: {
      en: "A simple workout planner and log: plan your training week, record sets and reps, and watch your consistency grow.",
      ar: "مخطط وسجل تمارين بسيط: خطط أسبوع تمارينك، سجّل المجموعات والتكرارات، وشوف التزامك يزيد.",
    },
    problem: {
      en: "Workouts get planned in your head and forgotten by Wednesday. Without a record, progress is invisible and motivation fades.",
      ar: "التمارين تنخطط في الراس وتنتسى يوم الأربعاء. وبدون تسجيل ما تشوف تقدمك والحماس يخف.",
    },
    audience: {
      en: "People training at home or in the gym who want structure without a coach app subscription.",
      ar: "اللي يتمرنون في البيت أو النادي ويبون تنظيم بدون اشتراك شهري في تطبيق مدرب.",
    },
    story: {
      chaos: { en: "No plan, random sessions, no idea what you lifted last time", ar: "بدون خطة، تمارين عشوائية، وما تدري كم رفعت آخر مرة" },
      result: { en: "A weekly plan and a visible streak", ar: "خطة أسبوعية والتزام تشوفه" },
    },
    benefits: [
      { en: "Know what to train today", ar: "تعرف وش تتمرن اليوم" },
      { en: "Beat last week with your own numbers in front of you", ar: "تتفوق على أسبوعك الماضي وأرقامك قدامك" },
      { en: "Consistency you can see", ar: "التزام تقدر تشوفه" },
    ],
    features: [
      { title: { en: "Weekly schedule", ar: "جدول أسبوعي" }, body: { en: "Assign workouts to days and adjust when life happens.", ar: "وزّع التمارين على الأيام وعدّلها لما تتغير ظروفك." } },
      { title: { en: "Exercise library", ar: "مكتبة تمارين" }, body: { en: "Common exercises with clear names in Arabic and English.", ar: "تمارين شائعة بأسماء واضحة بالعربي والإنجليزي." } },
      { title: { en: "Sets & reps log", ar: "سجل المجموعات والتكرارات" }, body: { en: "Record weight, sets and reps in a few taps.", ar: "سجّل الوزن والمجموعات والتكرارات بكم ضغطة." } },
      { title: { en: "Progress view", ar: "عرض التقدم" }, body: { en: "Simple charts for consistency and volume over time.", ar: "رسوم بسيطة للالتزام والحجم مع الوقت." } },
    ],
    included: [
      { en: "Interactive workout planner and log", ar: "مخطط وسجل تمارين تفاعلي" },
      { en: "Starter exercise library", ar: "مكتبة تمارين أساسية" },
    ],
    devices: { en: "Designed phone-first for use in the gym", ar: "مصمم للجوال أولًا عشان تستخدمه في النادي" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "lifetime",
    status: "preview",
    price: LAUNCH_PRICE,
    categories: ["health-fitness"],
    tags: ["fitness", "workout", "tracker"],
    hue: "fit",
    featured: true,
    isNew: false,
    demo: "fit",
    disclaimer: {
      en: "One Click Fit is an organization tool for general wellness. It does not provide medical advice, diagnosis or treatment. Consult a qualified professional before starting a new exercise program.",
      ar: "ون كليك لياقة أداة تنظيم للعافية العامة. لا يقدم نصائح طبية أو تشخيصًا أو علاجًا. استشر مختصًا مؤهلًا قبل البدء ببرنامج تمارين جديد.",
    },
    faqs: [
      { q: { en: "Does it create a training program for me?", ar: "هل يسوي لي برنامج تمارين؟" }, a: { en: "No. It helps you organize and track the plan you choose. It is not a coaching or medical service.", ar: "لا. يساعدك تنظم وتتابع الخطة اللي تختارها. ليس خدمة تدريب أو خدمة طبية." } },
    ],
    sample: true,
    updatedAt: UPDATED,
  },
  {
    id: "prd_reset",
    slug: "weekly-reset-checklist",
    name: { en: "Weekly Reset Checklist", ar: "قائمة ترتيب الأسبوع" },
    tagline: { en: "A free 15-minute routine to start the week clear.", ar: "روتين مجاني في ١٥ دقيقة تبدأ فيه أسبوعك مرتب." },
    summary: {
      en: "A short interactive checklist for Thursday evening or Saturday morning: clear the inbox, plan meals, check the calendar, reset the house. Free, no account needed.",
      ar: "قائمة تفاعلية قصيرة لليلة الخميس أو صباح السبت: نظّف الإيميل، خطط الوجبات، راجع التقويم، رتّب البيت. مجانية وبدون حساب.",
    },
    problem: {
      en: "The week starts before you have caught up with the last one.",
      ar: "الأسبوع يبدأ قبل لا تلحق على اللي قبله.",
    },
    audience: { en: "Anyone who wants a calmer start to the week.", ar: "أي أحد يبي بداية أسبوع أهدى." },
    story: {
      chaos: { en: "Sunday morning panic", ar: "توتر صباح الأحد" },
      result: { en: "A 15-minute reset", ar: "ترتيب في ١٥ دقيقة" },
    },
    benefits: [
      { en: "Start the week with a clear head", ar: "تبدأ الأسبوع وراسك صافي" },
      { en: "Works in under 15 minutes", ar: "يخلص في أقل من ١٥ دقيقة" },
    ],
    features: [
      { title: { en: "Four short sections", ar: "أربع أقسام قصيرة" }, body: { en: "Digital, home, food and week ahead.", ar: "رقمي، البيت، الأكل، والأسبوع الجاي." } },
    ],
    included: [{ en: "Interactive checklist, free forever", ar: "قائمة تفاعلية، مجانية دائمًا" }],
    devices: { en: "Any browser", ar: "أي متصفح" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "free",
    status: "preview",
    price: null,
    categories: ["life-productivity", "templates-downloads"],
    tags: ["free", "checklist", "routine"],
    hue: "brand",
    featured: false,
    isNew: true,
    demo: "reset",
    faqs: [],
    sample: true,
    updatedAt: UPDATED,
  },
  {
    id: "prd_budget",
    slug: "oneclick-budget",
    name: { en: "One Click Budget", ar: "ون كليك ميزانية" },
    tagline: { en: "Know where the month went, and plan the next one.", ar: "اعرف وين راح الشهر، وخطط للي بعده." },
    summary: {
      en: "A monthly budget planner with salary-day planning, category limits and savings goals. Coming after the first launch wave.",
      ar: "مخطط ميزانية شهري يبدأ من يوم الراتب، مع حدود لكل بند وأهداف ادخار. ينزل بعد أول دفعة إطلاق.",
    },
    problem: { en: "Salary arrives, and by the 20th nobody knows where it went.", ar: "الراتب ينزل، ويوم ٢٠ ما أحد يدري وين راح." },
    audience: { en: "Individuals and families managing a monthly salary.", ar: "الأفراد والعائلات اللي يديرون راتب شهري." },
    story: {
      chaos: { en: "Receipts, bank SMS, guesswork", ar: "فواتير ورسائل البنك وتخمين" },
      result: { en: "A month you can see", ar: "شهر واضح قدامك" },
    },
    benefits: [{ en: "Plan from salary day", ar: "خطط من يوم الراتب" }],
    features: [],
    included: [],
    devices: { en: "Any modern browser", ar: "أي متصفح حديث" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "lifetime",
    status: "coming-soon",
    price: LAUNCH_PRICE,
    categories: ["money-budgeting"],
    tags: ["budget", "money", "savings"],
    hue: "budget",
    featured: false,
    isNew: false,
    faqs: [],
    disclaimer: { en: "An organization tool, not financial advice.", ar: "أداة تنظيم، وليست استشارة مالية." },
    sample: true,
    updatedAt: UPDATED,
  },
  {
    id: "prd_study",
    slug: "oneclick-study",
    name: { en: "One Click Study", ar: "ون كليك دراسة" },
    tagline: { en: "Exams planned backwards from the date that matters.", ar: "اختباراتك مخططة بالعكس من التاريخ المهم." },
    summary: {
      en: "A study planner that turns exam dates into a daily revision plan. Coming after the first launch wave.",
      ar: "مخطط دراسة يحوّل مواعيد الاختبارات إلى خطة مراجعة يومية. ينزل بعد أول دفعة إطلاق.",
    },
    problem: { en: "Revision starts too late because the plan only exists in your head.", ar: "المراجعة تبدأ متأخر لأن الخطة موجودة في راسك بس." },
    audience: { en: "School and university students, and parents supporting them.", ar: "طلاب المدارس والجامعات، والأهالي اللي يساعدونهم." },
    story: { chaos: { en: "Six subjects, one week", ar: "ست مواد، أسبوع واحد" }, result: { en: "A daily plan that fits", ar: "خطة يومية تمشي معك" } },
    benefits: [{ en: "Revision that starts on time", ar: "مراجعة تبدأ في وقتها" }],
    features: [],
    included: [],
    devices: { en: "Any modern browser", ar: "أي متصفح حديث" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "lifetime",
    status: "coming-soon",
    price: LAUNCH_PRICE,
    categories: ["study-education"],
    tags: ["study", "exams", "students"],
    hue: "study",
    featured: false,
    isNew: false,
    faqs: [],
    sample: true,
    updatedAt: UPDATED,
  },
  {
    id: "prd_travel",
    slug: "oneclick-travel",
    name: { en: "One Click Travel", ar: "ون كليك سفر" },
    tagline: { en: "Itinerary, packing and budget for every trip.", ar: "البرنامج والشنطة والميزانية لكل رحلة." },
    summary: {
      en: "A trip planner for itineraries, bookings, packing lists and travel budgets. Coming after the first launch wave.",
      ar: "مخطط رحلات للبرنامج والحجوزات وقائمة الشنطة وميزانية السفر. ينزل بعد أول دفعة إطلاق.",
    },
    problem: { en: "Bookings in email, plans in chat, and the charger left at home.", ar: "الحجوزات في الإيميل، والخطة في المحادثات، والشاحن نسيته في البيت." },
    audience: { en: "Families and friends planning holidays and Eid trips.", ar: "العائلات والأصدقاء اللي يخططون للإجازات ورحلات العيد." },
    story: { chaos: { en: "Bookings everywhere", ar: "حجوزات في كل مكان" }, result: { en: "One trip page", ar: "صفحة واحدة للرحلة" } },
    benefits: [{ en: "Everything for the trip in one place", ar: "كل شي للرحلة في مكان واحد" }],
    features: [],
    included: [],
    devices: { en: "Any modern browser", ar: "أي متصفح حديث" },
    languages: ["ar", "en"],
    kind: "interactive",
    access: "lifetime",
    status: "coming-soon",
    price: LAUNCH_PRICE,
    categories: ["travel"],
    tags: ["travel", "packing", "itinerary"],
    hue: "travel",
    featured: false,
    isNew: false,
    faqs: [],
    sample: true,
    updatedAt: UPDATED,
  },
];
