// Inline logo so it inherits theme tokens (light/dark) without separate files.
// Geometry is identical to public/brand/*.svg (generated by scripts/build-brand.mjs).
const MARK_PATH = "M20.5 32.5 L28.5 40.5 L47.56 16.44 A22 22 0 1 0 53.25 37.69";

export function LogoMark({ size = 32, className = "", animated = false }: { size?: number; className?: string; animated?: boolean }) {
  return (
    <svg width={size} height={size} viewBox="0 0 64 64" aria-hidden="true" className={className} style={{ overflow: "visible" }}>
      <path
        d={MARK_PATH}
        fill="none"
        stroke="var(--oc-primary)"
        strokeWidth={6.6}
        strokeLinecap="round"
        strokeLinejoin="round"
        pathLength={1}
        className={animated ? "oc-mark-draw" : undefined}
      />
      <circle cx={53.25} cy={26.31} r={4.3} fill="var(--oc-accent)" className={animated ? "oc-mark-dot" : undefined} />
    </svg>
  );
}

/** Primary lockup: mark + "One Click" with "DIGITAL HUB" beneath. Always left-to-right. */
export function Logo({ className = "" }: { className?: string }) {
  return (
    <span className={`inline-flex items-center gap-2 ${className}`} dir="ltr" style={{ fontFamily: "Geist, sans-serif" }}>
      <LogoMark size={32} />
      <span className="flex flex-col leading-none">
        <span className="text-[1.2rem] font-semibold tracking-[-0.02em] text-ink">One Click</span>
        <span className="mt-[3px] text-[0.6rem] font-semibold tracking-[0.24em] text-muted">DIGITAL HUB</span>
      </span>
    </span>
  );
}
