/* English overlay: module quiz questions, keyed by shared question ID.
   Option order and the correct answer index match the Arabic questions. */
Object.assign(EN_QUESTIONS, {
  'm1-q1': { q: 'Where do you start your day to see your overdue tasks and today’s tasks?', options: ['Home', 'The management Dashboard', 'Notification settings', 'The tag list'], why: 'Home gathers the tasks assigned to you by timing.' },
  'm1-q2': { q: 'A notification needs a reply in an hour. Where do you put it?', options: ['Cleared', 'Later', 'Other', 'Delete it'], why: 'Later is for what you want to come back to.' },
  'm1-q3': { q: 'Which of these is suitable as a task?', options: ['The reference leave policy', 'Update the audit actions log before Thursday', 'A congratulations message', 'A link to a public website'], why: 'Actionable work with a date.' },
  'm1-q4': { q: 'You want to find the “Report guide” document quickly. What is fastest?', options: ['Browse every Space', 'Search by name', 'Ask your colleagues', 'Create a new document'], why: 'Search reaches tasks and documents by name.' },
  'm2-q1': { q: 'What is the right order from the top?', options: ['Space → Workspace → List', 'Workspace → Space → List → Task', 'List → Folder → Space', 'Task → List → Workspace'], why: 'Workspace, then Space, then (optional Folder), then List, then Task.' },
  'm2-q2': { q: 'Where do tasks always live?', options: ['In a Folder', 'In a List', 'Directly in a Space', 'In a Dashboard'], why: 'No task exists outside a List.' },
  'm2-q3': { q: 'When do you add a Folder?', options: ['Always, before any List', 'When you want to group several related Lists', 'For every large task', 'It cannot be added'], why: 'A Folder is optional, for grouping related Lists.' },
  'm2-q4': { q: 'What happens when you create a Subfolder?', options: ['A List is created inside it automatically', 'A new Space is created', 'Lists are deleted', 'Nothing'], why: 'A List is created inside it automatically.' },
  'm3-q1': { q: 'Which task name is better?', options: ['Meeting', 'Prepare the minutes for the requests follow-up meeting, Sunday', 'Important', 'This week’s stuff'], why: 'Verb + specific thing + time.' },
  'm3-q2': { q: 'Part of the work is taken on by a colleague with a separate date. What fits best?', options: ['Checklist', 'Subtask', 'Tag', 'Task description'], why: 'A Subtask has an assignee, date and status.' },
  'm3-q3': { q: 'What happens to tracked time when a task recurs?', options: ['It is carried over', 'It is not carried over', 'It is doubled', 'It is emailed'], why: 'Tracked time is not carried over when a task recurs.' },
  'm3-q4': { q: 'You typed @Salim in a comment. What happens?', options: ['He becomes the task’s assignee', 'He gets a notification', 'The task is closed', 'The comment is deleted'], why: 'A mention sends a notification.' },
  'm4-q1': { q: 'You changed a task’s status in Board. What shows in List?', options: ['The old status', 'The new status', 'A duplicate task', 'The task does not appear'], why: 'Views show the same tasks.' },
  'm4-q2': { q: 'Which view shows who has more work than capacity?', options: ['Workload', 'Calendar', 'Doc', 'Form'], why: 'Workload compares work with capacity.' },
  'm4-q3': { q: 'What does a Filter do?', options: ['Deletes tasks', 'Temporarily hides what does not match', 'Moves tasks', 'Changes the assignee'], why: 'A filter only hides.' },
  'm4-q4': { q: 'Which view is best for seeing dependencies as arrows over time?', options: ['Gantt', 'Board', 'Table', 'List'], why: 'Gantt shows dependencies.' },
  'm5-q1': { q: 'Which field type keeps “Requesting department” values consistent?', options: ['Text', 'Dropdown', 'Rating', 'Phone'], why: 'A Dropdown has fixed options.' },
  'm5-q2': { q: 'Which formula calculates the days from the start date to the due date?', options: ['DAYS(field("Start date"), field("Due date"))', 'DAYS(field("Due date"), field("Start date"))', 'TODAY(field("Due date"))', 'DAYS(TODAY())'], why: 'End first, then start.' },
  'm5-q3': { q: 'What does TODAY() return?', options: ['A number', 'Today’s date', 'The user’s name', 'Nothing'], why: 'TODAY() returns today’s date.' },
  'm5-q4': { q: 'Which fields are not supported in Formula fields?', options: ['Text Custom Fields', 'Dates', 'Numbers', 'Amounts'], why: 'Text fields are not supported in formulas.' },
  'm6-q1': { q: 'What is the difference between an @mention and an assigned comment?', options: ['No difference', 'A mention asks for attention; an assigned comment is a required action that gets resolved', 'Assigned comments are for guests only', 'A mention closes the task'], why: 'An assigned comment is an action followed up until Resolve.' },
  'm6-q2': { q: 'A decision in Chat needs to be carried out. What is best?', options: ['Pin the message', 'Create a task from the message', 'React with a like', 'Copy it into a file'], why: 'A task links the decision to action.' },
  'm6-q3': { q: 'Where is the best place to keep a reference guide?', options: ['Doc', 'Chat', 'Tag', 'Clip'], why: 'Reference content goes in a Doc.' },
  'm6-q4': { q: 'What happens when an assigned comment is resolved?', options: ['It is deleted', 'Who resolved it is recorded, and whoever assigned it is notified', 'The List closes', 'It becomes a task'], why: 'Resolve records the resolution and sends a notification.' },
  'm7-q1': { q: 'Task A cannot be completed before B. What is A’s relationship?', options: ['Blocking', 'Waiting on', 'Relationship', 'Subtask'], why: 'A is waiting for B.' },
  'm7-q2': { q: 'How do you record actual time?', options: ['A timer or manual entry', 'Tag', 'Dashboard', 'Inbox'], why: 'With a timer or by hand.' },
  'm7-q3': { q: 'What is an overdue task?', options: ['Any urgent task', 'A task that is not closed and is past its due date', 'A task with no assignee', 'A completed task'], why: 'The definition depends on the due date and whether it is closed.' },
  'm7-q4': { q: 'Which command creates a normal relationship that does not force an order?', options: ['/blocking', '/waiting', '/link to', '/due'], why: '/link to is for a normal relationship.' },
  'm8-q1': { q: 'What decides which tasks a Dashboard card reads?', options: ['The colour', 'The data source and filters', 'The card size', 'The Dashboard name'], why: 'The Location and filters.' },
  'm8-q2': { q: 'A Dashboard Filter applies to…', options: ['One card', 'Every supported card on the Dashboard', 'The whole Workspace', 'Closed tasks only'], why: 'The Dashboard filter covers the supported cards.' },
  'm8-q3': { q: '3 overdue out of 6, or 4 overdue out of 40. Which is worse?', options: ['3 out of 6', '4 out of 40', 'They are equal', 'It cannot be known'], why: '50% against 10%.' },
  'm8-q4': { q: 'A rise in completions in a single week means…', options: ['A lasting improvement', 'A snapshot that needs reading as a trend across weeks', 'A certain error', 'The card should be deleted'], why: 'A trend needs several points.' },
  'm9-q1': { q: 'Which part of an automation is optional?', options: ['Trigger', 'Condition', 'Action', 'None'], why: 'The condition is optional.' },
  'm9-q2': { q: 'An action the system skipped because the condition was not met. How many actions does it use?', options: ['Zero', 'One action', 'Two actions', 'Half an action'], why: 'A skipped action uses nothing.' },
  'm9-q3': { q: 'What is the best way to turn on a new automation?', options: ['On the whole Workspace straight away', 'Test it on a small List first', 'Without conditions', 'Without a clear name'], why: 'A small test prevents surprises.' },
  'm9-q4': { q: 'In what order do multiple actions run?', options: ['From top to bottom', 'Randomly', 'From the bottom', 'Alphabetically'], why: 'In the order they were added.' },
  'm10-q1': { q: 'What does each form submission create?', options: ['A task in the chosen location', 'A Space', 'A Dashboard', 'A Doc'], why: 'Every submission is a task.' },
  'm10-q2': { q: 'Where do you choose the List for submission tasks?', options: ['Settings, After submitting form', 'Inbox', 'Personal settings', 'Gantt'], why: 'From the form settings.' },
  'm10-q3': { q: 'The target “Cut costs by 3,000 rials” is of type…', options: ['Number', 'Currency', 'True/False', 'Task'], why: 'Currency is for a financial target.' },
  'm10-q4': { q: 'What is a Goal made of?', options: ['Measurable Targets', 'Tags', 'Automations', 'Forms'], why: 'A goal is made of targets.' },
  'm11-q1': { q: 'A colleague from the organization needs one List. What role fits best?', options: ['Guest', 'Limited Member', 'Admin', 'Owner'], why: 'An organization email address is not added as a guest.' },
  'm11-q2': { q: 'Does assigning someone as Assignee give access to a private location?', options: ['Yes, always', 'No, access needs sharing', 'Only for guests', 'Only for admins'], why: 'Assigning is not access.' },
  'm11-q3': { q: 'A consultant needs one task from a private List. What do you share?', options: ['The List', 'The task only', 'The Space', 'The Workspace'], why: 'Share the least that is needed.' },
  'm11-q4': { q: 'Can a guest share an item with others?', options: ['Yes', 'No', 'Yes, with Full edit', 'Only Docs'], why: 'Guests cannot share anything.' },
  'm12-q1': { q: 'What is the default state of keyboard shortcuts?', options: ['On', 'Off', 'They do not exist', 'Admins only'], why: 'They are turned on in personal settings.' },
  'm12-q2': { q: 'How do you show the shortcut list?', options: ['Shift + ?', 'Ctrl + P', 'Alt + Tab', 'F5'], why: 'Shift + ?.' },
  'm12-q3': { q: 'How many AI conditions can one automation have?', options: ['One', 'Five', 'Unlimited', 'Zero'], why: 'One AI condition per automation.' },
  'm12-q4': { q: 'AI output in an official report should be…', options: ['Copied straight in', 'Checked against the original data first', 'Always deleted', 'Never used'], why: 'The output is a draft to review.' }
});
