/* Intermediate to Advanced course, part 2: import, calendar, Docs, sprints. */
const ADV_SRCS = () => [['monday', 'Monday.com', 'board', '#ff3d57'], ['asana', 'Asana', 'target', '#f06a6a'], ['jira', 'Jira', 'module', '#2684ff'], ['basecamp', 'Basecamp', 'compass', '#1d2d35'], ['todoist', 'Todoist', 'check', '#e44332'], ['xlsx', 'Excel / CSV', 'table', '#1f9d55']];
const ADV_PAGES = () => [{ k: 'pg1', n: ['ملخص الميزة', 'Feature summary'] }, { k: 'pg2', n: ['واجهة المستخدم', 'User interface'] }, { k: 'pg3', n: ['كود الواجهة الأمامية', 'Front-end code'], l: 1 }, { k: 'pg4', n: ['كود الواجهة الخلفية', 'Back-end code'], l: 1 }, { k: 'pg5', n: ['الاختبار', 'Testing'] }];
const ADV_DMENU = () => [['rename', 'Rename', 'tag'], ['dup', 'Duplicate', 'layers'], ['share', 'Share & permissions', 'share'], ['tpl', 'Save as template', 'template'], ['export', 'Export', 'download'], ['hist', 'Page history', 'clock'], ['cover', 'Add cover', 'star'], ['font', 'Typography', 'doc']];
const ADV_SPR = n => Array.from({ length: n }, (_, i) => ({ k: 'sp' + (i + 1), l: 2, t: 'list', n: ['Sprint ' + (i + 1), 'Sprint ' + (i + 1)], cnt: i ? 0 : 6 }));
const ADV_STREE = n => [{ k: 'sp-dev', l: 0, t: 'space', n: ['تطوير الموقع', 'Website development'], c: '#ec4899' }, { k: 'fd-spr', l: 1, t: 'folder', n: ['السبرنتات', 'Sprints'] }].concat(ADV_SPR(n));

const ADV_TOPICS_2 = [
  { sec: 'x-int', id: 'a-import', t: ['استيراد البيانات من Monday.com وAsana وJira وBasecamp وTodoist وغيرها', 'Import data from Monday.com, Asana, Jira, Basecamp, Todoist and more'], link: '#/workshops/import',
    explain: ['تنتقل إلى ClickUp دون إعادة كتابة شيء: المستورِد ينقل المهام والمسؤولين والتواريخ من أدوات مثل Monday.com وAsana وJira وBasecamp وTodoist، أو من ملف Excel/CSV.', 'Move to ClickUp without retyping anything: the importer brings tasks, assignees and dates from tools such as Monday.com, Asana, Jira, Basecamp and Todoist, or from an Excel/CSV file.'],
    more: ['أنشئ أولاً مساحة مخصصة للاستيراد حتى تراجع النتيجة قبل خلطها بعملك. من Settings ← Imports اختر الأداة. بعض الأدوات تطلب تسجيل الدخول، وبعضها يطلب رمز API (API token) تنسخه من إعدادات الأداة الأخرى. ثم طابق المستخدمين والحالات. الرمز مثل كلمة المرور: لا تضعه في رسالة أو مستند. الأدوات المتاحة وخطواتها تتغير، فاتبع صفحة الاستيراد في حسابك.', 'First create a Space just for the import so you can review the result before mixing it with your work. From Settings → Imports choose the tool. Some tools ask you to sign in, others ask for an API token you copy from the other tool’s settings. Then match users and statuses. A token is like a password: never paste it in a message or Doc. The available tools and steps change, so follow the import page in your account.'],
    like: ['مثل شركة نقل أثاث: تغلّف كل شيء وتعيده إلى نفس الغرف في البيت الجديد.', 'Like a removal company: it packs everything and puts it back in the same rooms in the new house.'],
    doit: [['أنشئ مساحة باسم «استيراد» للمراجعة.', 'Create a Space called “Import” for review.'], ['افتح Settings ← Imports واختر الأداة.', 'Open Settings → Imports and choose the tool.'], ['سجّل الدخول أو الصق رمز API من الأداة الأخرى.', 'Sign in, or paste the API token from the other tool.'], ['طابق المستخدمين والحالات، ثم ابدأ الاستيراد وراجع النتيجة.', 'Match users and statuses, then start the import and review the result.']],
    tip: ['استورد مشروعاً صغيراً واحداً أولاً كتجربة، ثم الباقي بعد التأكد من الحالات والمسؤولين.', 'Import one small project first as a test, then the rest once statuses and assignees look right.'],
    demo: { scene: 'file', steps: [
      { c: ['صفحة الاستيراد: اختر الأداة التي يعمل عليها فريقك اليوم.', 'The import page: choose the tool your team uses today.'], stage: 'source', srcs: ADV_SRCS() },
      { c: ['اختر Monday.com.', 'Choose Monday.com.'], hl: 'src-monday', click: true },
      { c: ['الصق رمز API الذي نسخته من إعدادات Monday.com.', 'Paste the API token you copied from Monday.com settings.'], stage: 'token', tokT: ['اربط Monday.com', 'Connect Monday.com'], hl: 'tokIn', type: { k: 'tokIn', x: '••••••••••••••••••' } },
      { c: ['اضغط Connect ليبدأ الاستيراد.', 'Click Connect to start the import.'], tok: '••••••••••••••••••', hl: 'tokGo', click: true, prog: 35 },
      { c: ['انتهى: المهام في المساحة الجديدة بحالاتها ومسؤوليها.', 'Done: the tasks are in the new Space with their statuses and assignees.'], stage: 'list', title: ['مستورد من Monday', 'Imported from Monday'], rows: ADV_WEB(), toast: ['اكتمل الاستيراد: 4 مهام', 'Import complete: 4 tasks'], hl: 'w2' }
    ] },
    ex: ['فريق المشاريع الرقمية انتقل من Asana. استوردوا مشروعاً صغيراً أولاً فاكتشفوا أن حالة «Waiting» تحتاج مطابقة. بعد تصحيحها استوردوا 12 مشروعاً دون مشاكل.', 'The digital projects team moved from Asana. They imported one small project first and found that the “Waiting” status needed matching. After fixing it they imported 12 projects without problems.'],
    wrong: ['استيراد كل شيء مرة واحدة مباشرة في المساحة الرئيسية.', 'Importing everything at once straight into the main Space.'],
    right: ['استورد إلى مساحة مراجعة، وجرّب مشروعاً صغيراً أولاً.', 'Import into a review Space, and test with a small project first.'],
    quiz: { q: ['كيف تتعامل مع رمز API الذي يطلبه الاستيراد؟', 'How should you treat the API token the importer asks for?'], o: [['أشاركه في الدردشة مع الفريق', 'Share it in team chat'], ['أعامله ككلمة مرور ولا أشاركه', 'Treat it like a password and never share it'], ['أكتبه في وصف المهمة', 'Write it in the task description']], a: 1, why: ['الرمز يفتح حسابك في الأداة الأخرى، فهو سري مثل كلمة المرور.', 'The token opens your account in the other tool, so it is secret like a password.'] } },

  { sec: 'x-int', id: 'a-cal', t: ['مزامنة التقويم مع ClickUp', 'Sync your calendar with ClickUp'],
    explain: ['اربط Google Calendar بمزامنة في الاتجاهين: مواعيد Google تظهر في ClickUp، ومهامك ذات التواريخ تظهر في Google. لتقويم Apple أو Outlook تتوفر مزامنة في اتجاه واحد عبر رابط iCal.', 'Connect Google Calendar with two-way sync: Google events appear in ClickUp, and your dated tasks appear in Google. For Apple or Outlook calendars, one-way sync is available with an iCal link.'],
    more: ['المزامنة في الاتجاهين تعني أن تغيير موعد مهمة في Google يغيّر تاريخها في ClickUp، والعكس. اختر بعناية أي قوائم تُزامن حتى لا يمتلئ تقويمك. في ClickUp 4.0 يظهر تقويمك أيضاً في Planner لتخطط يومك. قد تختلف الخيارات حسب الخطة وإعدادات المسؤول.', 'Two-way sync means changing a task’s time in Google changes its date in ClickUp, and the other way round. Choose carefully which Lists to sync so your calendar does not overflow. In ClickUp 4.0 your calendar also shows in Planner so you can plan your day. Options can vary by plan and admin settings.'],
    like: ['مثل ساعتين مربوطتين: تضبط إحداهما فتتغير الأخرى معها.', 'Like two linked clocks: set one and the other changes with it.'],
    doit: [['افتح عرض Calendar أو Planner.', 'Open a Calendar view or Planner.'], ['اضغط Sync calendars واختر Google Calendar.', 'Click Sync calendars and choose Google Calendar.'], ['فعّل المزامنة في الاتجاهين وسجّل الدخول.', 'Turn on two-way sync and sign in.'], ['لتقويم Apple أو Outlook: انسخ رابط iCal وأضفه هناك.', 'For Apple or Outlook: copy the iCal link and add it there.']],
    tip: ['زامن قوائمك المهمة فقط، لا مساحة العمل كلها؛ التقويم المزدحم لا يقرؤه أحد.', 'Sync only your important Lists, not the whole Workspace; a crowded calendar is one nobody reads.'],
    demo: { scene: 'calendar', steps: [
      { c: ['تقويم ClickUp يعرض مهامك ذات التواريخ.', 'The ClickUp calendar shows your dated tasks.'], syncBtn: true, items: [{ k: 'c1', d: 0, n: ['اختبار النموذج', 'Test the form'], c: '#7b68ee' }, { k: 'c2', d: 2, n: ['إطلاق الصفحة', 'Launch the page'], c: '#10b981' }] },
      { c: ['اضغط Sync calendars.', 'Click Sync calendars.'], hl: 'syncBtn', click: true },
      { c: ['اختر Google Calendar.', 'Choose Google Calendar.'], sync: 'gc-google', hl: 'gc-google' },
      { c: ['فعّل المزامنة في الاتجاهين ثم Connect.', 'Turn on two-way sync, then Connect.'], twoWay: true, hl: 'twoWay', click: true },
      { c: ['ظهرت مواعيد Google بجانب مهامك.', 'Google events now appear next to your tasks.'], sync: null, synced: true, items: [{ k: 'c1', d: 0, n: ['اختبار النموذج', 'Test the form'], c: '#7b68ee' }, { k: 'g1', d: 1, g: true, n: ['اجتماع الإدارة 10:00', 'Management meeting 10:00'] }, { k: 'c2', d: 2, n: ['إطلاق الصفحة', 'Launch the page'], c: '#10b981' }, { k: 'g2', d: 3, g: true, n: ['تدريب الفريق', 'Team training'] }], hl: 'g1', toast: ['تمت المزامنة مع Google Calendar', 'Synced with Google Calendar'] }
    ] },
    ex: ['مدير التطوير كان يكتب مواعيد التسليم في تقويمه يدوياً. بعد المزامنة صار كل تغيير في تاريخ التسليم يظهر في تقويمه تلقائياً.', 'The development manager used to copy delivery dates into his calendar by hand. After syncing, every change to a delivery date appears in his calendar automatically.'],
    wrong: ['نسخ التواريخ بين التقويمين يدوياً فتختلف مع الوقت.', 'Copying dates between calendars by hand so they drift apart.'],
    right: ['اربط Google بالمزامنة في الاتجاهين، أو iCal للتقويمات الأخرى.', 'Connect Google with two-way sync, or iCal for other calendars.'],
    quiz: { q: ['ما الفرق بين مزامنة Google ورابط iCal لتقويم Outlook؟', 'What is the difference between Google sync and an iCal link for Outlook?'], o: [['لا فرق', 'No difference'], ['Google في الاتجاهين، وiCal في اتجاه واحد', 'Google is two-way, iCal is one-way'], ['iCal يحذف المهام', 'iCal deletes tasks']], a: 1, why: ['iCal يعرض مهام ClickUp في التقويم الآخر فقط، دون إرجاع التغييرات.', 'iCal only shows ClickUp tasks in the other calendar, without sending changes back.'] } },

  /* ---------------- 4. ClickUp Docs ---------------- */
  { sec: 'x-docs', id: 'a-docs-intro', t: ['مقدمة إلى مستندات ClickUp', 'Intro to ClickUp Docs'],
    explain: ['مستندات ClickUp (Docs) تجمع توثيق المشروع في نفس مكان العمل: ملخص المنتج، والكود، والاختبار، والقرارات. المطوّر الجديد يجد كل شيء في مستند واحد مرتبط بالمهام.', 'ClickUp Docs keep project documentation in the same place as the work: product summary, code, testing and decisions. A new developer finds everything in one Doc linked to the tasks.'],
    more: ['المستند يمكن أن يعيش في مساحة أو مجلد أو قائمة، أو يُرفق بمهمة. يحتوي صفحات وصفحات فرعية، وجداول، وكتل كود، وروابط لمهام حية تتحدث حالتها تلقائياً. يمكن الكتابة معاً في الوقت نفسه، والتعليق على أي جملة وتحويل التعليق إلى مهمة.', 'A Doc can live in a Space, Folder or List, or be attached to a task. It holds pages and subpages, tables, code blocks and links to live tasks whose status updates automatically. People can write together at the same time, comment on any sentence and turn a comment into a task.'],
    like: ['مثل دليل استخدام يكتبه الفريق داخل المصنع نفسه، لا في مبنى آخر.', 'Like an instruction manual the team writes inside the factory itself, not in another building.'],
    doit: [['افتح مساحة المشروع واضغط «+» ثم Doc.', 'Open the project Space and click “+”, then Doc.'], ['سمِّ المستند باسم المشروع.', 'Name the Doc after the project.'], ['أضف صفحات: الملخص، الواجهة، الكود، الاختبار.', 'Add pages: summary, interface, code, testing.'], ['اربط المهام داخل الصفحات بكتابة @ واسم المهمة.', 'Link tasks inside pages by typing @ and the task name.']],
    tip: ['ضع رابط المستند في وصف القائمة أو ثبّته في المفضلة حتى يجده الجميع.', 'Put the Doc link in the List description or pin it in Favorites so everyone finds it.'],
    demo: { scene: 'doc', steps: [
      { c: ['مستند مشروع «نموذج ملاحظات الموقع».', 'The project Doc for the “Website feedback form”.'], noSide: true, pages: ADV_PAGES(), page: 'pg1', dname: ['نموذج الملاحظات', 'Feedback form'], title: ['ملخص الميزة', 'Feature summary'], blocks: [{ k: 'b1', x: ['نموذج يجمع ملاحظات الزوار عن الموقع ويرسلها إلى فريق الدعم.', 'A form that collects visitors’ feedback about the website and sends it to the support team.'] }] },
      { c: ['كل جزء من التوثيق صفحة مستقلة في الشريط الجانبي.', 'Each part of the documentation is its own page in the sidebar.'], hl: 'dPages' },
      { c: ['صفحة «كود الواجهة الأمامية» للمطورين.', 'The “Front-end code” page is for developers.'], page: 'pg3', title: ['كود الواجهة الأمامية', 'Front-end code'], blocks: [{ k: 'b2', ty: 'h', x: ['المكوّنات', 'Components'] }, { k: 'b3', ty: 'li', x: 'FeedbackForm.tsx' }, { k: 'b4', ty: 'li', x: 'RatingStars.tsx' }], hl: 'pg3' },
      { c: ['وصفحة «الاختبار» مرتبطة بمهمة حية.', 'And the “Testing” page is linked to a live task.'], page: 'pg5', title: ['الاختبار', 'Testing'], blocks: [{ k: 'b5', x: ['نختبر على الجوال والحاسوب قبل الإطلاق.', 'We test on mobile and desktop before launch.'] }, { k: 'b6', ty: 'task', x: ['اختبار النموذج على الجوال', 'Test the form on mobile'], who: 'noura' }], hl: 'b6' }
    ] },
    ex: ['مطوّر انضم للفريق في منتصف المشروع قرأ مستند «نموذج الملاحظات» في ساعة واحدة، وبدأ العمل في نفس اليوم دون اجتماع تعريفي طويل.', 'A developer who joined mid-project read the “Feedback form” Doc in one hour and started work the same day without a long onboarding meeting.'],
    wrong: ['توثيق المشروع في ملفات Word متفرقة على أجهزة الأشخاص.', 'Documenting the project in scattered Word files on people’s laptops.'],
    right: ['مستند واحد بصفحات واضحة، داخل مساحة المشروع ومرتبط بالمهام.', 'One Doc with clear pages, inside the project Space and linked to tasks.'],
    quiz: { q: ['ما ميزة ربط مهمة داخل المستند؟', 'What is the benefit of linking a task inside a Doc?'], o: [['تُحذف المهمة', 'The task is deleted'], ['تظهر حالتها الحية وتتحدث تلقائياً', 'Its live status shows and updates automatically'], ['يتغير اسم المستند', 'The Doc is renamed']], a: 1, why: ['الرابط الحي يجعل المستند يعكس حالة العمل الفعلية.', 'A live link makes the Doc reflect the real state of the work.'] } },

  { sec: 'x-docs', id: 'a-docs-struct', t: ['بناء هيكل المستند', 'Setting up the Doc structure'],
    explain: ['المستند الجيد مقسّم إلى صفحات بترتيب منطقي: ملخص الميزة، الواجهة، الكود الأمامي والخلفي، الأسئلة الشائعة، وحل المشكلات. الصفحات الفرعية تجمع التفاصيل تحت عنوانها.', 'A good Doc is split into pages in a logical order: feature summary, interface, front-end and back-end code, FAQs and troubleshooting. Subpages group the details under their heading.'],
    more: ['اضغط «Add page» لإضافة صفحة، واسحبها تحت صفحة أخرى لتصبح فرعية. ابدأ كل صفحة بجملة تشرح لمن هي («للمطورين»، «لفريق الدعم»). صفحة «حل المشكلات» توفر على الفريق تكرار نفس الأسئلة. يمكنك إخفاء صفحات المسودة أو مشاركة صفحات معينة فقط.', 'Click “Add page” to add a page, and drag it under another page to make it a subpage. Start each page with a sentence saying who it is for (“for developers”, “for the support team”). A troubleshooting page saves the team from answering the same questions again. You can hide draft pages or share only certain pages.'],
    like: ['مثل فهرس كتاب: فصول رئيسية، وتحت كل فصل أقسامه.', 'Like a book’s table of contents: main chapters, with sections under each.'],
    doit: [['افتح المستند واضغط Add page.', 'Open the Doc and click Add page.'], ['أضف: الملخص، الواجهة، الكود، الأسئلة، حل المشكلات.', 'Add: summary, interface, code, FAQs, troubleshooting.'], ['اسحب صفحات الكود تحت صفحة «الكود» لتصبح فرعية.', 'Drag the code pages under a “Code” page to make them subpages.'], ['اكتب في أول كل صفحة لمن هي.', 'Write at the top of each page who it is for.']],
    tip: ['احفظ هذا الهيكل كقالب مستند، واستخدمه لكل ميزة جديدة.', 'Save this structure as a Doc template and reuse it for every new feature.'],
    demo: { scene: 'doc', steps: [
      { c: ['مستند جديد فيه صفحة واحدة فقط.', 'A new Doc with only one page.'], noSide: true, pages: [{ k: 'pg1', n: ['ملخص الميزة', 'Feature summary'] }], page: 'pg1', dname: ['نموذج الملاحظات', 'Feedback form'], title: ['ملخص الميزة', 'Feature summary'], blocks: [{ k: 'b1', x: ['لمن هذه الصفحة: لكل الفريق.', 'Who this page is for: the whole team.'] }] },
      { c: ['اضغط Add page.', 'Click Add page.'], hl: 'addPage', click: true },
      { c: ['أضف صفحتي «واجهة المستخدم» و«الكود».', 'Add “User interface” and “Code” pages.'], pages: [{ k: 'pg1', n: ['ملخص الميزة', 'Feature summary'] }, { k: 'pg2', n: ['واجهة المستخدم', 'User interface'] }, { k: 'pgc', n: ['الكود', 'Code'] }], hl: 'pgc' },
      { c: ['ضع صفحتي الكود الأمامي والخلفي تحت «الكود».', 'Put the front-end and back-end pages under “Code”.'], pages: [{ k: 'pg1', n: ['ملخص الميزة', 'Feature summary'] }, { k: 'pg2', n: ['واجهة المستخدم', 'User interface'] }, { k: 'pgc', n: ['الكود', 'Code'] }, { k: 'pg3', n: ['الواجهة الأمامية', 'Front end'], l: 1 }, { k: 'pg4', n: ['الواجهة الخلفية', 'Back end'], l: 1 }], hl: 'pg3' },
      { c: ['وأخيراً: الأسئلة الشائعة وحل المشكلات.', 'Finally: FAQs and troubleshooting.'], pages: [{ k: 'pg1', n: ['ملخص الميزة', 'Feature summary'] }, { k: 'pg2', n: ['واجهة المستخدم', 'User interface'] }, { k: 'pgc', n: ['الكود', 'Code'] }, { k: 'pg3', n: ['الواجهة الأمامية', 'Front end'], l: 1 }, { k: 'pg4', n: ['الواجهة الخلفية', 'Back end'], l: 1 }, { k: 'pg6', n: ['الأسئلة الشائعة', 'FAQs'] }, { k: 'pg7', n: ['حل المشكلات', 'Troubleshooting'] }], page: 'pg7', title: ['حل المشكلات', 'Troubleshooting'], blocks: [{ k: 'b2', ty: 'li', x: ['النموذج لا يُرسل؟ تحقق من الاتصال بقاعدة البيانات.', 'Form not sending? Check the database connection.'] }], hl: 'pg7' }
    ] },
    ex: ['فريق الدعم كان يسأل المطورين نفس الأسئلة أسبوعياً. بعد إضافة صفحة «حل المشكلات» انخفضت الأسئلة إلى النصف.', 'The support team asked developers the same questions every week. After a troubleshooting page was added, the questions halved.'],
    wrong: ['مستند طويل بصفحة واحدة يصعب التنقل فيه.', 'One long single-page Doc that is hard to navigate.'],
    right: ['صفحات وصفحات فرعية بأسماء واضحة، تبدأ كل منها بـ «لمن هذه الصفحة».', 'Pages and subpages with clear names, each starting with “who this page is for”.'],
    quiz: { q: ['كيف تجعل صفحة فرعية تحت صفحة أخرى؟', 'How do you make a page a subpage of another?'], o: [['أسحبها تحت الصفحة الأم', 'Drag it under the parent page'], ['أغيّر لون المستند', 'Change the Doc colour'], ['أصدّر المستند', 'Export the Doc']], a: 0, why: ['السحب في شريط الصفحات يجعلها فرعية.', 'Dragging in the pages sidebar makes it a subpage.'] } },

  { sec: 'x-docs', id: 'a-docs-settings', t: ['التعمق في إعدادات المستندات', 'Deep dive into the Docs settings'],
    explain: ['قائمة «···» في المستند فيها أدوات قوية: إعادة التسمية، والنسخ، والمشاركة برابط، والحفظ كقالب، والتصدير. ولكل صفحة خيارات: سجل التعديلات، والمرفقات، والعلاقات، والغلاف، والخطوط.', 'The Doc’s “···” menu has powerful tools: rename, duplicate, share with a link, save as template, and export. Each page also has options: page history, attachments, relationships, cover and typography.'],
    more: ['سجل الصفحة (Page history) يعيدك لأي نسخة سابقة إذا حُذف شيء بالخطأ. المشاركة تتيح رابطاً داخلياً أو عاماً؛ لا تجعل مستنداً عاماً إن كان فيه معلومات داخلية. التصدير يعطيك PDF أو Markdown أو HTML. الغلاف والخطوط تجعل المستند أسهل قراءة، والعلاقات تربطه بمهام ومستندات أخرى.', 'Page history takes you back to any earlier version if something was deleted by mistake. Sharing gives an internal or public link; never make a Doc public if it holds internal information. Export gives you PDF, Markdown or HTML. Cover and typography make the Doc easier to read, and relationships link it to other tasks and Docs.'],
    like: ['مثل إعدادات الطباعة والحفظ في محرر النصوص، لكن مع زر «رجوع بالزمن».', 'Like the print and save settings in a word processor, but with a “go back in time” button.'],
    doit: [['افتح المستند واضغط «···» في الأعلى.', 'Open the Doc and click “···” at the top.'], ['جرّب Page history وشاهد النسخ السابقة.', 'Try Page history and look at earlier versions.'], ['أضف غلافاً واختر خطاً مريحاً من Typography.', 'Add a cover and choose a comfortable font in Typography.'], ['راجع Share & permissions قبل إرسال الرابط.', 'Check Share & permissions before sending the link.']],
    tip: ['قبل تعديل كبير على مستند مهم، استخدم Duplicate لتحتفظ بنسخة، أو اعتمد على Page history.', 'Before a big edit on an important Doc, Duplicate it to keep a copy, or rely on Page history.'],
    demo: { scene: 'doc', steps: [
      { c: ['مستند المشروع جاهز. لنرَ إعداداته.', 'The project Doc is ready. Let us look at its settings.'], noSide: true, pages: ADV_PAGES(), page: 'pg1', dname: ['نموذج الملاحظات', 'Feedback form'], title: ['ملخص الميزة', 'Feature summary'], dmore: true, blocks: [{ k: 'b1', x: ['نموذج يجمع ملاحظات الزوار عن الموقع.', 'A form that collects visitors’ feedback about the website.'] }] },
      { c: ['اضغط «···» في أعلى المستند.', 'Click “···” at the top of the Doc.'], hl: 'dMore', click: true },
      { c: ['هذه أدوات المستند: مشاركة، قالب، تصدير، سجل…', 'These are the Doc tools: share, template, export, history…'], dmenu: ADV_DMENU(), hl: 'dm-share' },
      { c: ['Page history يعيد أي نسخة سابقة.', 'Page history brings back any earlier version.'], dpick: 'hist', hl: 'dm-hist', click: true },
      { c: ['أضف غلافاً ملوناً ليسهل تمييز المستند.', 'Add a colourful cover so the Doc is easy to spot.'], dpick: 'cover', hl: 'dm-cover', click: true },
      { c: ['ظهر الغلاف.', 'The cover appears.'], dmenu: null, cover: '#0d9488', hl: 'cover' }
    ] },
    ex: ['حذف أحد الزملاء فقرة كاملة من مستند الإطلاق بالخطأ. أعادتها قائدة الفريق خلال دقيقة من Page history.', 'A colleague deleted a whole section of the launch Doc by mistake. The team lead restored it in a minute from Page history.'],
    wrong: ['مشاركة المستند برابط عام دون مراجعة محتواه.', 'Sharing the Doc with a public link without checking what is in it.'],
    right: ['راجع Share & permissions، واستخدم الرابط الداخلي للمعلومات الداخلية.', 'Check Share & permissions, and use an internal link for internal information.'],
    quiz: { q: ['أين تستعيد فقرة حُذفت من المستند بالخطأ؟', 'Where do you restore a section deleted from a Doc by mistake?'], o: [['Page history', 'Page history'], ['Typography', 'Typography'], ['Add cover', 'Add cover']], a: 0, why: ['سجل الصفحة يحفظ النسخ السابقة ويتيح استعادتها.', 'Page history keeps earlier versions and lets you restore them.'] } },

  { sec: 'x-docs', id: 'a-docs-tpl', t: ['قوالب المستندات', 'Docs templates'], link: '#/workshops/templates',
    explain: ['لا تبدأ من صفحة فارغة: قوالب المستندات جاهزة لمحاضر الاجتماعات، والفعاليات، وملخصات المنتجات، وخرائط الطريق. اختر قالباً، عدّله، ثم احفظ نسختك كقالب لفريقك.', 'Do not start from a blank page: Doc templates are ready for meeting minutes, events, product briefs and roadmaps. Pick one, adjust it, then save your version as a template for your team.'],
    more: ['افتح Template Center وابحث بكلمة مثل «meeting». المعاينة تريك الشكل قبل الاستخدام. بعد التعديل اختر «Save as template» من قائمة «···» وسمِّه بوضوح. يمكنك تحديد من يرى القالب. القوالب توحّد شكل المستندات في الفريق كله.', 'Open Template Center and search a word like “meeting”. The preview shows the layout before you use it. After editing, choose “Save as template” from the “···” menu and name it clearly. You can choose who can see the template. Templates make Docs look the same across the whole team.'],
    like: ['مثل نموذج جاهز في البنك: تملأ الفراغات بدل أن تكتب الرسالة من الصفر.', 'Like a ready form at the bank: you fill in the blanks instead of writing the letter from scratch.'],
    doit: [['افتح Template Center من «+» أو من المستند الجديد.', 'Open Template Center from “+” or from a new Doc.'], ['ابحث عن «meeting» واختر Meeting Minutes.', 'Search “meeting” and pick Meeting Minutes.'], ['عدّل الأقسام بما يناسب فريقك.', 'Adjust the sections to suit your team.'], ['احفظه كقالب باسم واضح.', 'Save it as a template with a clear name.']],
    tip: ['أضف إلى قالب المحضر قسماً للقرارات وقسماً للمهام؛ ثم حوّل كل سطر مهمة إلى مهمة حقيقية.', 'Add a Decisions section and an Actions section to your minutes template; then turn each action line into a real task.'],
    demo: { scene: 'templates', steps: [
      { c: ['مركز القوالب.', 'The Template Center.'], cards: [{ k: 'tp1', n: 'Meeting Minutes', d: 'Doc', ic: 'doc', c: '#0d9488' }, { k: 'tp2', n: 'Product Brief', d: 'Doc', ic: 'doc', c: '#7b68ee' }, { k: 'tp3', n: 'Event Plan', d: 'Doc', ic: 'calendar', c: '#f97316' }, { k: 'tp4', n: 'Roadmap', d: 'Doc', ic: 'gantt', c: '#ec4899' }] },
      { c: ['ابحث عن «meeting».', 'Search for “meeting”.'], hl: 'tSearch', type: { k: 'tSearch', x: 'meeting' } },
      { c: ['اختر Meeting Minutes لمعاينته.', 'Pick Meeting Minutes to preview it.'], q: 'meeting', preview: 'tp1', hl: 'tp1', click: true },
      { c: ['سمِّه واختر ما يتضمنه، ثم استخدمه.', 'Name it, choose what to include, then use it.'], dlg: { t: 'Meeting Minutes', n: ['محضر اجتماع الأحد', 'Sunday meeting minutes'], opts: [[['القرارات', 'Decisions'], true], [['المهام', 'Action items'], true]], b: 'Use template' }, hl: 'dlgGo', click: true }
    ] },
    ex: ['كل فرق المشروع صارت تستخدم نفس قالب المحضر. صار المدير يجد القرارات في نفس المكان في كل محضر.', 'Every project team now uses the same minutes template. The manager finds the decisions in the same place in every set of minutes.'],
    wrong: ['كل شخص يكتب المحضر بطريقته فتضيع القرارات.', 'Everyone writes minutes their own way, so decisions get lost.'],
    right: ['قالب واحد للفريق بأقسام ثابتة: الحضور، القرارات، المهام.', 'One team template with fixed sections: attendees, decisions, actions.'],
    quiz: { q: ['كيف تحفظ نسختك المعدّلة ليستخدمها الفريق؟', 'How do you save your edited version for the team to use?'], o: [['Save as template من قائمة «···»', 'Save as template from the “···” menu'], ['أطبعه', 'Print it'], ['أرسله بالبريد', 'Email it']], a: 0, why: ['الحفظ كقالب يجعله متاحاً في Template Center.', 'Saving as a template makes it available in Template Center.'] } },

  /* ---------------- 5. Sprints ---------------- */
  { sec: 'x-sprint', id: 'a-sprints', t: ['السبرنتات في ClickUp', 'Sprints in ClickUp'],
    explain: ['السبرنت دورة عمل قصيرة، غالباً أسبوعان، يلتزم فيها الفريق بمجموعة مهام محددة. في ClickUp يعيش كل سبرنت كقائمة داخل مجلد سبرنتات (Sprint Folder)، بتواريخ ونقاط جهد (Sprint Points) وشريط تقدم.', 'A sprint is a short work cycle, often two weeks, where the team commits to a set of tasks. In ClickUp each sprint lives as a List inside a Sprint Folder, with dates, effort points (Sprint Points) and a progress bar.'],
    more: ['فعّل Sprints وSprint Points من ClickApps. نقاط السبرنت تقدير نسبي للجهد (مثل 1، 2، 3، 5، 8) وليست ساعات. مجموع النقاط يخبرك هل حمّلت الفريق أكثر من طاقته. ابدأ السبرنت، تابع التقدم يومياً، وعند نهايته انقل ما لم يكتمل إلى السبرنت التالي.', 'Turn on Sprints and Sprint Points in ClickApps. Sprint Points are a relative effort estimate (like 1, 2, 3, 5, 8), not hours. The total tells you if you loaded the team beyond its capacity. Start the sprint, follow progress daily, and at the end move unfinished work to the next sprint.'],
    like: ['مثل جولات سباق قصيرة بدل ماراثون طويل: هدف واضح لكل جولة، ثم استراحة ومراجعة.', 'Like short race laps instead of one long marathon: a clear goal per lap, then a pause and review.'],
    doit: [['فعّل Sprints وSprint Points من ClickApps (أو اطلب من المسؤول).', 'Turn on Sprints and Sprint Points in ClickApps (or ask your admin).'], ['افتح Sprint 1 وراجع المهام ونقاطها.', 'Open Sprint 1 and check the tasks and their points.'], ['اضغط Start sprint.', 'Click Start sprint.'], ['تابع شريط التقدم في الاجتماع اليومي.', 'Follow the progress bar in the daily stand-up.']],
    tip: ['احسب متوسط النقاط التي ينجزها الفريق في آخر ثلاثة سبرنتات، ولا تخطط لأكثر منه.', 'Work out the average points the team finished in the last three sprints, and do not plan more than that.'],
    demo: { scene: 'sprint', steps: [
      { c: ['هذا Sprint 1 داخل مجلد السبرنتات.', 'This is Sprint 1 inside the Sprint Folder.'], group: 'none', rows: ADV_WEB().map(r => Object.assign({}, r, { st: 'todo' })), sprint: { n: 'Sprint 1', d: '6/1 - 6/14', p: 0, pts: 21 } },
      { c: ['كل مهمة لها نقاط جهد. المجموع 21 نقطة.', 'Each task has effort points. The total is 21.'], hl: 'pts' },
      { c: ['اضغط Start sprint.', 'Click Start sprint.'], hl: 'sprGo', click: true },
      { c: ['بعد أسبوع: التقدم 40٪.', 'One week later: 40% progress.'], sprint: { n: 'Sprint 1', d: '6/1 - 6/14', p: 40, pts: 21, btn: 'Complete sprint', done: true }, rows: ADV_WEB(), group: 'status', hl: 'sprBar' }
    ] },
    ex: ['فريق الموقع كان يعمل على 30 مهمة معاً دون نهاية واضحة. مع سبرنتات أسبوعين صار يسلّم ميزة كاملة كل سبرنت.', 'The website team worked on 30 tasks at once with no clear end. With two-week sprints they now ship a complete feature every sprint.'],
    wrong: ['حشو السبرنت بمهام كثيرة دون النظر إلى النقاط.', 'Stuffing the sprint with tasks without looking at the points.'],
    right: ['خطط حسب متوسط النقاط المنجزة، وابدأ السبرنت بهدف واحد واضح.', 'Plan by the average points completed, and start the sprint with one clear goal.'],
    quiz: { q: ['ماذا تقيس نقاط السبرنت (Sprint Points)؟', 'What do Sprint Points measure?'], o: [['عدد الساعات بالضبط', 'The exact number of hours'], ['الجهد النسبي للمهمة', 'The relative effort of a task'], ['عدد التعليقات', 'The number of comments']], a: 1, why: ['هي تقدير نسبي يساعد على معرفة طاقة الفريق.', 'They are a relative estimate that helps you know the team’s capacity.'] } }
];
