/* ==========================================================================
   Course: "ClickUp - The Intermediate to Advanced Training Course".
   Seven sections that follow the outline the user supplied, explained in our
   own words, in Arabic and English. Every topic has the same parts as the
   beginner course: idea, deeper idea, comparison, animated demo, steps,
   workplace example (fictional), common mistake, quiz and a pro tip.
   Some lecture names are from older ClickUp versions; the topics teach the
   current names and mention the old ones (LineUp is now Personal Priorities,
   sprints live in Sprint Folders). Menus can move between versions and plans.
   Topic: { sec, id, t, explain, doit, tip, link, more, like, demo, ex, wrong, right, quiz }
   ========================================================================== */
const ADV_SECTIONS = [
  { id: 'x-start', ic: 'rocket', c: '#0ea5e9', t: ['البداية', 'Getting started'] },
  { id: 'x-mind', ic: 'path', c: '#a855f7', t: ['الخرائط الذهنية', 'Mind Maps'] },
  { id: 'x-int', ic: 'link', c: '#f97316', t: ['التكاملات والاستيراد', 'Integrations and import'] },
  { id: 'x-docs', ic: 'doc', c: '#0d9488', t: ['مستندات ClickUp', 'ClickUp Docs'] },
  { id: 'x-sprint', ic: 'repeat', c: '#7b68ee', t: ['السبرنتات (Sprints)', 'Sprints'] },
  { id: 'x-agile', ic: 'layers', c: '#ec4899', t: ['إعداد بيئة Agile', 'Setting up for Agile'] },
  { id: 'x-pro', ic: 'star', c: '#ca8a04', t: ['ميزات خفية للمحترفين', 'Hidden pro features'] }
];
const ADV_SECT = () => ADV_SECTIONS.map(s => [s.ic, s.t, s.c]);
const ADV_WEB = () => [
  C4R('w1', ['تصميم نموذج الملاحظات', 'Design the feedback form'], { st: 'done', who: 'maryam', due: C4D(3), prio: 'high', pts: 5 }),
  C4R('w2', ['برمجة الواجهة الأمامية', 'Build the front end'], { st: 'prog', who: 'khalid', due: C4D(8), prio: 'high', pts: 8 }),
  C4R('w3', ['ربط النموذج بقاعدة البيانات', 'Connect the form to the database'], { st: 'todo', who: 'salim', due: C4D(10), prio: 'normal', pts: 5 }),
  C4R('w4', ['اختبار النموذج على الجوال', 'Test the form on mobile'], { st: 'todo', who: 'noura', due: C4D(12), prio: 'normal', pts: 3 })
];

const ADV_TOPICS_1 = [
  /* ---------------- 1. Getting started ---------------- */
  { sec: 'x-start', id: 'a-intro', t: ['مقدمة: من المستوى المتوسط إلى المتقدم', 'Introduction: from intermediate to advanced'],
    explain: ['أنت تعرف الأساسيات: المهام والقوائم وطرق العرض. هذه الدورة تأخذك إلى ما يستخدمه المحترفون فعلاً: الخرائط الذهنية، والتكاملات مع Zoom والبريد وGoogle Calendar، ومستندات منظمة، والسبرنتات، وميزات خفية لا يعرفها كثيرون.', 'You already know the basics: tasks, Lists and views. This course takes you to what professionals really use: Mind Maps, integrations with Zoom, email and Google Calendar, well-structured Docs, sprints, and hidden features few people know.'],
    more: ['الدورة سبعة أقسام. كل قسم يحل مشكلة حقيقية: كيف ترى المشروع كله في صورة واحدة، كيف تتوقف عن التنقل بين التطبيقات، كيف تحفظ معرفة الفريق في مكان واحد، وكيف تدير العمل في دورات قصيرة منتظمة. بعض الميزات تحتاج تفعيلاً من مسؤول مساحة العمل (ClickApps) أو تختلف حسب الخطة، وسننبهك في كل موضوع.', 'The course has seven sections. Each one solves a real problem: how to see the whole project in one picture, how to stop jumping between apps, how to keep the team’s knowledge in one place, and how to run work in short regular cycles. Some features need a Workspace admin to turn them on (ClickApps) or depend on your plan, and each topic tells you when.'],
    like: ['مثل الانتقال من قيادة السيارة إلى معرفة كل أزرار لوحة القيادة: نفس السيارة، لكنك تصل أسرع وبراحة أكبر.', 'Like going from driving a car to knowing every button on the dashboard: the same car, but you get there faster and more comfortably.'],
    doit: [['افتح ClickUp في نافذة بجانب هذه الصفحة.', 'Open ClickUp in a window next to this page.'], ['تأكد من الميزات المفعّلة: Settings ← ClickApps (أو اسأل المسؤول).', 'Check which features are on: Settings → ClickApps (or ask your admin).'], ['اختر مساحة تجريبية أو قائمة للتدريب حتى لا تغيّر عمل الفريق.', 'Pick a practice Space or List so you do not change the team’s real work.']],
    tip: ['أنشئ مساحة باسم «تجارب» وطبّق فيها كل موضوع. احذفها أو أرشفها بعد انتهاء الدورة.', 'Create a Space called “Sandbox” and practise every topic there. Archive it when you finish the course.'],
    demo: { scene: 'journey', steps: [
      { c: ['هذه رحلتك: سبعة أقسام من الخرائط الذهنية إلى الميزات الخفية.', 'This is your journey: seven sections from Mind Maps to hidden features.'], items: ADV_SECT(), lit: 0, hello: ['أهلاً بعودتك! جاهزة للمستوى التالي؟', 'Welcome back! Ready for the next level?'] },
      { c: ['أولاً: الخرائط الذهنية لترى المشروع كله وتعدّله بصرياً.', 'First: Mind Maps, to see the whole project and change it visually.'], lit: 2, hl: 'stop1' },
      { c: ['ثم التكاملات: Zoom والبريد وإضافة Chrome والتقويم والاستيراد.', 'Then integrations: Zoom, email, the Chrome extension, calendars and imports.'], lit: 3, hl: 'stop2' },
      { c: ['بعدها المستندات والسبرنتات وإعداد بيئة Agile.', 'Next: Docs, sprints and an Agile setup.'], lit: 6, hl: 'stop5' },
      { c: ['وأخيراً ميزات خفية: الأولويات الشخصية، وتسجيل الشاشة، والمهام المتداخلة، والعلاقات.', 'Finally hidden features: Personal Priorities, screen recording, nested subtasks and Relationships.'], lit: 7, hl: 'stop6', hello: ['كل موضوع: افهم ← شاهد ← جرّب ← اختبر نفسك.', 'Every topic: understand → watch → try → check yourself.'] }
    ] },
    ex: ['مشرف فريق الدعم الرقمي كان يقضي ساعة يومياً في نسخ رسائل البريد إلى المهام. بعد قسم التكاملات صار يرسل ويستقبل البريد من داخل المهمة نفسها.', 'The digital support supervisor spent an hour a day copying emails into tasks. After the integrations section he sends and receives email from inside the task itself.'],
    wrong: ['تجربة الميزات المتقدمة مباشرة على مشروع الفريق الحقيقي.', 'Trying advanced features directly on the team’s real project.'],
    right: ['جرّب في مساحة تجريبية أولاً، ثم طبّق ما نجح على المشروع الحقيقي.', 'Try in a sandbox Space first, then apply what works to the real project.'],
    quiz: { q: ['أين تفعّل ميزة مثل Sprints أو Nested Subtasks؟', 'Where do you turn on a feature such as Sprints or Nested Subtasks?'], o: [['من ClickApps في الإعدادات', 'In ClickApps in Settings'], ['من ملفك الشخصي فقط', 'Only from your profile'], ['لا يمكن تفعيلها', 'They cannot be turned on']], a: 0, why: ['ClickApps هي مفاتيح الميزات، ويديرها مالك أو مسؤول مساحة العمل.', 'ClickApps are the feature switches, managed by a Workspace owner or admin.'] } },

  /* ---------------- 2. Mind Maps ---------------- */
  { sec: 'x-mind', id: 'a-mm-intro', t: ['مقدمة إلى الخرائط الذهنية', 'Intro to Mind Maps'],
    explain: ['عرض الخريطة الذهنية (Mind Map) يرسم المساحة والمجلدات والقوائم والمهام كشجرة واحدة. ترى الهيكل كله في نظرة، وتفهم أين يعيش كل شيء، وتستطيع العصف الذهني عليه مباشرة.', 'The Mind Map view draws your Space, Folders, Lists and tasks as one tree. You see the whole structure at a glance, understand where everything lives, and can brainstorm right on it.'],
    more: ['هناك نوعان: خريطة مبنية على المهام (تعرض العناصر الحقيقية في الموقع الذي فتحتها منه) وخريطة فارغة لأفكار حرة. أضف العرض من «+ View» واختر Mind Map. استخدم أدوات التكبير و«ملاءمة الشاشة» حتى تتنقل بسهولة، واطوِ الفروع التي لا تحتاجها الآن.', 'There are two kinds: a task-based map (it shows the real items where you opened it) and a blank map for free ideas. Add it from “+ View” and choose Mind Map. Use zoom and “fit to screen” to move around easily, and collapse branches you do not need right now.'],
    like: ['مثل صورة جوية لمدينة بدلاً من خريطة شارع واحد.', 'Like an aerial photo of a city instead of a map of one street.'],
    doit: [['افتح مساحة أو مجلداً واضغط «+ View».', 'Open a Space or Folder and click “+ View”.'], ['اختر Mind Map ثم الخريطة المبنية على المهام.', 'Choose Mind Map, then the task-based map.'], ['استخدم «ملاءمة الشاشة» وكبّر وصغّر لتتنقل.', 'Use “fit to screen” and zoom in and out to move around.'], ['اطوِ الفروع غير المهمة الآن.', 'Collapse branches that do not matter right now.']],
    tip: ['افتح الخريطة من مستوى المجلد لا المساحة كلها، حتى تبقى الصورة واضحة.', 'Open the map at Folder level, not the whole Space, so the picture stays clear.'],
    demo: { scene: 'mindmap', steps: [
      { c: ['المساحة في الوسط: «تطوير الموقع».', 'The Space is in the centre: “Website development”.'], mtools: true, nodes: [{ k: 'n0', x: 40, y: 190, n: ['تطوير الموقع', 'Website development'], ic: 'layers' }] },
      { c: ['تظهر المجلدات كفروع.', 'Folders appear as branches.'], nodes: [{ k: 'n0', x: 40, y: 190, n: ['تطوير الموقع', 'Website development'], ic: 'layers' }, { k: 'n1', p: 'n0', x: 250, y: 110, n: ['الواجهة الأمامية', 'Front end'], ic: 'folder', c: '#f59f00' }, { k: 'n2', p: 'n0', x: 250, y: 270, n: ['الواجهة الخلفية', 'Back end'], ic: 'folder', c: '#f59f00' }], hl: 'n1' },
      { c: ['ثم القوائم داخل كل مجلد.', 'Then the Lists inside each Folder.'], nodes: [{ k: 'n0', x: 40, y: 190, n: ['تطوير الموقع', 'Website development'], ic: 'layers' }, { k: 'n1', p: 'n0', x: 250, y: 110, n: ['الواجهة الأمامية', 'Front end'], ic: 'folder', c: '#f59f00' }, { k: 'n2', p: 'n0', x: 250, y: 270, n: ['الواجهة الخلفية', 'Back end'], ic: 'folder', c: '#f59f00' }, { k: 'n3', p: 'n1', x: 460, y: 70, n: ['النماذج', 'Forms'], ic: 'list', c: '#0ea5e9' }, { k: 'n4', p: 'n2', x: 460, y: 290, n: ['قاعدة البيانات', 'Database'], ic: 'list', c: '#0ea5e9' }], hl: 'n3' },
      { c: ['والمهام في نهاية كل فرع، بحالتها ومسؤولها.', 'And the tasks at the end of each branch, with status and assignee.'], nodes: [{ k: 'n0', x: 20, y: 190, n: ['تطوير الموقع', 'Website development'], ic: 'layers' }, { k: 'n1', p: 'n0', x: 210, y: 110, n: ['الواجهة الأمامية', 'Front end'], ic: 'folder', c: '#f59f00' }, { k: 'n2', p: 'n0', x: 210, y: 270, n: ['الواجهة الخلفية', 'Back end'], ic: 'folder', c: '#f59f00' }, { k: 'n3', p: 'n1', x: 350, y: 70, n: ['النماذج', 'Forms'], ic: 'list', c: '#0ea5e9' }, { k: 'n4', p: 'n2', x: 350, y: 290, n: ['قاعدة البيانات', 'Database'], ic: 'list', c: '#0ea5e9' }, { k: 'n5', p: 'n3', x: 460, y: 20, n: ['نموذج الملاحظات', 'Feedback form'], task: true, st: 'prog', who: 'khalid' }, { k: 'n6', p: 'n4', x: 460, y: 340, n: ['جدول الردود', 'Responses table'], task: true, st: 'todo', who: 'salim' }], hl: 'n5' },
      { c: ['اضغط «ملاءمة الشاشة» لترى كل شيء مرة واحدة.', 'Click “fit to screen” to see everything at once.'], hl: 'mt-fit', click: true }
    ] },
    ex: ['مديرة مشروع الموقع الجديد عرضت الخريطة الذهنية في اجتماع الانطلاق. خلال خمس دقائق فهم الفريق كله أين يقع عمل كل شخص.', 'The new website’s project manager showed the Mind Map in the kick-off meeting. In five minutes the whole team understood where everyone’s work sits.'],
    wrong: ['فتح الخريطة على مساحة ضخمة فتصبح مزدحمة وغير مقروءة.', 'Opening the map on a huge Space so it becomes crowded and unreadable.'],
    right: ['افتحها على مجلد واحد واطوِ الفروع غير اللازمة.', 'Open it on one Folder and collapse branches you do not need.'],
    quiz: { q: ['ماذا تعرض الخريطة الذهنية المبنية على المهام؟', 'What does a task-based Mind Map show?'], o: [['أفكاراً عشوائية فقط', 'Only random ideas'], ['هيكل المساحة والمجلدات والقوائم والمهام', 'The structure of Spaces, Folders, Lists and tasks'], ['رسائل البريد', 'Emails']], a: 1, why: ['هي صورة شجرية للعناصر الحقيقية في الموقع الذي فتحتها منه.', 'It is a tree picture of the real items where you opened it.'] } },

  { sec: 'x-mind', id: 'a-mm-amend', t: ['الخرائط الذهنية لتعديل المشروع', 'Mind Maps for project amendments'],
    explain: ['الخريطة الذهنية ليست للعرض فقط: تستطيع منها تعديل المشروع. غيّر الحالة والأولوية، وأعد تسمية العناصر، وانقل مهمة إلى فرع آخر، وأضف تبعيات ومراقبين، وكل تغيير يُحفظ في المهمة الحقيقية.', 'A Mind Map is not just for looking: you can change the project from it. Change status and priority, rename items, move a task to another branch, add dependencies and watchers, and every change is saved on the real task.'],
    more: ['عندما يتغير نطاق المشروع، ترى أثر التغيير بصرياً: نقل مهمة من قائمة إلى أخرى يكون بسحب العقدة إلى الفرع الجديد. لوّن القوائم لتمييزها، وأضف المراقبين (Watchers) حتى يصل الإشعار للمعنيين. بعد التعديلات الكبيرة حدّث الخريطة لترى الشكل النهائي.', 'When the scope changes, you see the effect visually: moving a task to another List is done by dragging its node onto the new branch. Colour Lists to tell them apart and add watchers so the right people get notified. After big edits, refresh the map to see the final shape.'],
    like: ['مثل إعادة ترتيب أثاث غرفة على مخطط البيت قبل أن تحمله فعلاً… لكن هنا يتحرك الأثاث الحقيقي معك.', 'Like rearranging furniture on the house plan before moving it… except here the real furniture moves with you.'],
    doit: [['افتح Mind Map على مجلد المشروع.', 'Open the Mind Map on the project Folder.'], ['اضغط على مهمة واختر من القائمة: الحالة أو الأولوية.', 'Click a task and choose from the menu: status or priority.'], ['اسحب مهمة إلى فرع قائمة أخرى لنقلها.', 'Drag a task onto another List’s branch to move it.'], ['أضف تبعية أو مراقباً من نفس القائمة.', 'Add a dependency or a watcher from the same menu.']],
    tip: ['قبل نقل مهام كثيرة، التقط صورة للخريطة أو صدّر القائمة؛ ستعرف كيف كان الوضع لو احتجت الرجوع.', 'Before moving many tasks, screenshot the map or export the List, so you know how things were if you need to go back.'],
    demo: { scene: 'mindmap', steps: [
      { c: ['هذه خريطة مجلد «الواجهة الأمامية».', 'This is the map of the “Front end” Folder.'], nodes: [{ k: 'f0', x: 30, y: 180, n: ['الواجهة الأمامية', 'Front end'], ic: 'folder' }, { k: 'f1', p: 'f0', x: 240, y: 90, n: ['النماذج', 'Forms'], ic: 'list', c: '#0ea5e9' }, { k: 'f2', p: 'f0', x: 240, y: 280, n: ['الصفحات', 'Pages'], ic: 'list', c: '#10b981' }, { k: 'f3', p: 'f1', x: 440, y: 50, n: ['نموذج الملاحظات', 'Feedback form'], task: true, st: 'todo' }, { k: 'f4', p: 'f1', x: 440, y: 140, n: ['صفحة الأسئلة', 'FAQ page'], task: true, st: 'todo' }, { k: 'f5', p: 'f2', x: 440, y: 300, n: ['الصفحة الرئيسية', 'Home page'], task: true, st: 'prog' }] },
      { c: ['اضغط على المهمة لترى خياراتها.', 'Click the task to see its options.'], hl: 'f3', click: true, mmenu: [['Set status', 'check-circle'], ['Set priority', 'flag'], ['Add dependency', 'link'], ['Add watcher', 'eye']], mmStyle: 'top:90px;inset-inline-start:440px;width:190px' },
      { c: ['اختر الحالة: صار العمل جارياً.', 'Set the status: work has started.'], hl: 'mm0', click: true, nodes: [{ k: 'f0', x: 30, y: 180, n: ['الواجهة الأمامية', 'Front end'], ic: 'folder' }, { k: 'f1', p: 'f0', x: 240, y: 90, n: ['النماذج', 'Forms'], ic: 'list', c: '#0ea5e9' }, { k: 'f2', p: 'f0', x: 240, y: 280, n: ['الصفحات', 'Pages'], ic: 'list', c: '#10b981' }, { k: 'f3', p: 'f1', x: 440, y: 50, n: ['نموذج الملاحظات', 'Feedback form'], task: true, st: 'prog' }, { k: 'f4', p: 'f1', x: 440, y: 140, n: ['صفحة الأسئلة', 'FAQ page'], task: true, st: 'todo' }, { k: 'f5', p: 'f2', x: 440, y: 300, n: ['الصفحة الرئيسية', 'Home page'], task: true, st: 'prog' }] },
      { c: ['«صفحة الأسئلة» مكانها الصحيح «الصفحات». اسحبها إلى ذلك الفرع.', '“FAQ page” belongs in “Pages”. Drag it onto that branch.'], hl: 'f4', nodes: [{ k: 'f0', x: 30, y: 180, n: ['الواجهة الأمامية', 'Front end'], ic: 'folder' }, { k: 'f1', p: 'f0', x: 240, y: 90, n: ['النماذج', 'Forms'], ic: 'list', c: '#0ea5e9' }, { k: 'f2', p: 'f0', x: 240, y: 280, n: ['الصفحات', 'Pages'], ic: 'list', c: '#10b981' }, { k: 'f3', p: 'f1', x: 440, y: 90, n: ['نموذج الملاحظات', 'Feedback form'], task: true, st: 'prog' }, { k: 'f4', p: 'f2', x: 440, y: 240, n: ['صفحة الأسئلة', 'FAQ page'], task: true, st: 'todo' }, { k: 'f5', p: 'f2', x: 440, y: 320, n: ['الصفحة الرئيسية', 'Home page'], task: true, st: 'prog' }] },
      { c: ['أضف مراقباً حتى تعرف مريم بكل تغيير.', 'Add a watcher so Maryam hears about every change.'], hl: 'mm3', mmenu: [['Set status', 'check-circle'], ['Set priority', 'flag'], ['Add dependency', 'link'], ['Add watcher', 'eye']], mmStyle: 'top:130px;inset-inline-start:440px;width:190px' }
    ] },
    ex: ['تغيّر نطاق مشروع الموقع بعد اجتماع مع الإدارة. نقلت المديرة ست مهام بين القوائم من الخريطة في عشر دقائق بدلاً من فتح كل مهمة على حدة.', 'The website scope changed after a management meeting. The manager moved six tasks between Lists from the map in ten minutes instead of opening each task one by one.'],
    wrong: ['فتح كل مهمة وتغيير موقعها يدوياً واحدة واحدة.', 'Opening every task and changing its location by hand, one by one.'],
    right: ['عدّل بصرياً من الخريطة: اسحب، وغيّر الحالة، وأضف المراقبين.', 'Edit visually from the map: drag, change status, and add watchers.'],
    quiz: { q: ['ماذا يحدث عند سحب مهمة إلى فرع قائمة أخرى في الخريطة؟', 'What happens when you drag a task onto another List’s branch in the map?'], o: [['تُنسخ المهمة فقط', 'The task is only copied'], ['تنتقل المهمة الحقيقية إلى تلك القائمة', 'The real task moves to that List'], ['لا شيء، الخريطة للعرض فقط', 'Nothing, the map is view-only']], a: 1, why: ['الخريطة المبنية على المهام تعدّل العناصر الحقيقية.', 'A task-based map edits the real items.'] } },

  { sec: 'x-mind', id: 'a-mm-brain', t: ['الخرائط الذهنية للعصف الذهني والإبداع', 'Mind Maps for brainstorming and creativity'],
    explain: ['ابدأ بخريطة فارغة وفكرة في الوسط، ثم دع الفريق يضيف فروعاً. عندما تنضج الفكرة حوّل الفروع النهائية إلى مهام حقيقية مع مسؤولين، دون إعادة كتابة.', 'Start with a blank map and an idea in the middle, then let the team add branches. When the idea is ready, turn the final branches into real tasks with assignees, without retyping.'],
    more: ['في الخريطة الفارغة لا قيود: أضف عقدة بالزر «+» أو بمفتاح Tab، وعقدة شقيقة بمفتاح Enter. لوّن الفروع حسب الموضوع. عندما يتفق الفريق، اختر عقدة وحوّلها إلى مهمة واختر القائمة التي ستعيش فيها، ثم أسندها.', 'In a blank map there are no limits: add a node with the “+” button or Tab, and a sibling with Enter. Colour branches by theme. When the team agrees, pick a node, convert it to a task, choose the List it will live in, and assign it.'],
    like: ['مثل لوح أبيض في غرفة الاجتماعات، لكن الأفكار الجيدة تتحول بنقرة إلى عمل حقيقي.', 'Like a whiteboard in the meeting room, except good ideas turn into real work with one click.'],
    doit: [['أضف عرض Mind Map واختر «Blank».', 'Add a Mind Map view and choose “Blank”.'], ['اكتب الفكرة الرئيسية في الوسط.', 'Type the main idea in the middle.'], ['أضف الفروع بالزر «+» أو Tab، ولوّنها.', 'Add branches with “+” or Tab, and colour them.'], ['حوّل الفروع النهائية إلى مهام واختر القائمة والمسؤول.', 'Convert the final branches to tasks and pick a List and assignee.']],
    tip: ['اجعل أول عشر دقائق للأفكار فقط بلا نقد، ثم خمس دقائق للاختيار والتحويل إلى مهام.', 'Spend the first ten minutes on ideas only, no criticism, then five minutes choosing and converting to tasks.'],
    demo: { scene: 'mindmap', steps: [
      { c: ['خريطة فارغة: الفكرة في الوسط «خطة محتوى الموقع».', 'A blank map: the idea in the middle, “Website content plan”.'], mtools: true, nodes: [{ k: 'b0', x: 40, y: 190, n: ['خطة محتوى الموقع', 'Website content plan'] }] },
      { c: ['أضف فرعاً بالزر «+».', 'Add a branch with “+”.'], hl: 'mt-add', click: true, nodes: [{ k: 'b0', x: 40, y: 190, n: ['خطة محتوى الموقع', 'Website content plan'] }, { k: 'b1', p: 'b0', x: 280, y: 80, n: ['مقالات المدونة', 'Blog articles'], c: '#a855f7' }, { k: 'b2', p: 'b0', x: 280, y: 190, n: ['فيديوهات قصيرة', 'Short videos'], c: '#ec4899' }, { k: 'b3', p: 'b0', x: 280, y: 300, n: ['صفحة الأسئلة', 'FAQ page'], c: '#0ea5e9' }] },
      { c: ['قسّم كل فرع إلى أفكار أصغر.', 'Split each branch into smaller ideas.'], nodes: [{ k: 'b0', x: 20, y: 190, n: ['خطة محتوى الموقع', 'Website content plan'] }, { k: 'b1', p: 'b0', x: 230, y: 80, n: ['مقالات المدونة', 'Blog articles'], c: '#a855f7' }, { k: 'b2', p: 'b0', x: 230, y: 190, n: ['فيديوهات قصيرة', 'Short videos'], c: '#ec4899' }, { k: 'b3', p: 'b0', x: 230, y: 300, n: ['صفحة الأسئلة', 'FAQ page'], c: '#0ea5e9' }, { k: 'b4', p: 'b1', x: 450, y: 40, n: ['5 نصائح للإنترنت المنزلي', '5 home internet tips'], c: '#a855f7' }, { k: 'b5', p: 'b2', x: 450, y: 170, n: ['كيف تدفع فاتورتك', 'How to pay your bill'], c: '#ec4899' }, { k: 'b6', p: 'b3', x: 450, y: 320, n: ['أكثر 10 أسئلة', 'Top 10 questions'], c: '#0ea5e9' }] },
      { c: ['اختر فكرة جاهزة وحوّلها إلى مهمة.', 'Pick a ready idea and convert it to a task.'], hl: 'mt-task', click: true },
      { c: ['صارت مهام حقيقية مع مسؤولين.', 'They are now real tasks with assignees.'], nodes: [{ k: 'b0', x: 20, y: 190, n: ['خطة محتوى الموقع', 'Website content plan'] }, { k: 'b1', p: 'b0', x: 230, y: 80, n: ['مقالات المدونة', 'Blog articles'], c: '#a855f7' }, { k: 'b2', p: 'b0', x: 230, y: 190, n: ['فيديوهات قصيرة', 'Short videos'], c: '#ec4899' }, { k: 'b3', p: 'b0', x: 230, y: 300, n: ['صفحة الأسئلة', 'FAQ page'], c: '#0ea5e9' }, { k: 'b4', p: 'b1', x: 450, y: 40, n: ['5 نصائح للإنترنت المنزلي', '5 home internet tips'], task: true, who: 'noura' }, { k: 'b5', p: 'b2', x: 450, y: 170, n: ['كيف تدفع فاتورتك', 'How to pay your bill'], task: true, who: 'khalid' }, { k: 'b6', p: 'b3', x: 450, y: 320, n: ['أكثر 10 أسئلة', 'Top 10 questions'], task: true, who: 'maryam' }], hl: 'b5' }
    ] },
    ex: ['فريق التسويق الرقمي عقد جلسة عصف ذهني على الخريطة. خرجوا بـ 14 فكرة محتوى، وتحولت 6 منها إلى مهام مسندة قبل نهاية الاجتماع.', 'The digital marketing team held a brainstorm on the map. They came out with 14 content ideas, and 6 became assigned tasks before the meeting ended.'],
    wrong: ['كتابة الأفكار في الدردشة ثم نسيانها بعد الاجتماع.', 'Writing ideas in chat and forgetting them after the meeting.'],
    right: ['اجمع الأفكار في الخريطة وحوّل المختار منها إلى مهام فوراً.', 'Collect ideas in the map and convert the chosen ones to tasks right away.'],
    quiz: { q: ['ما الخطوة التي تحوّل فكرة في الخريطة الفارغة إلى عمل حقيقي؟', 'Which step turns an idea in a blank map into real work?'], o: [['تلوين الفرع', 'Colouring the branch'], ['تحويل العقدة إلى مهمة واختيار قائمة', 'Converting the node to a task and choosing a List'], ['تكبير الخريطة', 'Zooming the map']], a: 1, why: ['التحويل إلى مهمة يضعها في قائمة حقيقية ويمكن إسنادها.', 'Converting to a task puts it in a real List where it can be assigned.'] } },

  /* ---------------- 3. Integrations and import ---------------- */
  { sec: 'x-int', id: 'a-zoom', t: ['تكامل Zoom', 'Zoom integration'],
    explain: ['اربط Zoom مرة واحدة، ثم ابدأ اجتماعاً من داخل أي مهمة. يظهر رابط الاجتماع ورقمه في تعليق، فيعرف الجميع أين يلتقون وعن أي عمل يتحدثون.', 'Connect Zoom once, then start a meeting from inside any task. The meeting link and ID appear in a comment, so everyone knows where to meet and which work it is about.'],
    more: ['التفعيل: من App Center (أو Integrations) اختر Zoom واضغط Connect، ثم وافق على الأذونات في نافذة Zoom. بعدها في أي مهمة اكتب ‎/zoom في التعليق واضغط Enter. الاجتماع يُربط بالمهمة، فتبقى الملاحظات والقرارات بجانب العمل نفسه. قد يحتاج التفعيل لمسؤول حسب إعدادات شركتك.', 'Setup: in App Center (or Integrations) choose Zoom and click Connect, then approve the permissions in the Zoom window. After that, in any task type /zoom in the comment box and press Enter. The meeting is tied to the task, so notes and decisions stay next to the work. Your company may need an admin to allow it.'],
    like: ['مثل غرفة اجتماعات ملحقة بكل ملف عمل: تفتح الباب من الملف نفسه.', 'Like a meeting room attached to every work file: you open the door from the file itself.'],
    doit: [['افتح App Center واختر Zoom ثم Connect.', 'Open App Center, choose Zoom, then Connect.'], ['سجّل الدخول إلى Zoom ووافق على الأذونات.', 'Sign in to Zoom and approve the permissions.'], ['افتح مهمة واكتب ‎/zoom في التعليق ثم Enter.', 'Open a task, type /zoom in the comment and press Enter.'], ['شارك الرابط أو اضغط Join.', 'Share the link or click Join.']],
    tip: ['ابدأ الاجتماع من المهمة التي سيُناقش عملها، لا من التقويم؛ هكذا يبقى السياق مع الاجتماع.', 'Start the meeting from the task whose work you will discuss, not from the calendar; the context stays with the meeting.'],
    demo: { scene: 'task', steps: [
      { c: ['هذه مهمة نحتاج لمناقشتها سريعاً مع الفريق.', 'This is a task we need to discuss quickly with the team.'], title: ['مراجعة تصميم نموذج الملاحظات', 'Review the feedback form design'], title2: ['الواجهة الأمامية', 'Front end'], st: 'rev', who: ['maryam', 'khalid'], due: C4D(14), prio: 'high' },
      { c: ['اكتب ‎/zoom في مربع التعليق.', 'Type /zoom in the comment box.'], hl: 'cBox', type: { k: 'cBox', x: '/zoom' } },
      { c: ['اضغط Enter: يظهر اجتماع Zoom جديد في التعليقات.', 'Press Enter: a new Zoom meeting appears in the comments.'], cText: ['اكتب تعليقاً…', 'Write a comment…'], comments: [{ k: 'z1', w: 'me', x: ['بدأت اجتماع Zoom', 'Started a Zoom meeting'], zoom: 'ID 812 4471 0093' }], hl: 'z1' },
      { c: ['اضغط Join لتدخل الاجتماع.', 'Click Join to enter the meeting.'], hl: 'zJoin', click: true },
      { c: ['بعد الاجتماع اكتب القرار في نفس المهمة.', 'After the meeting, write the decision in the same task.'], comments: [{ k: 'z1', w: 'me', x: ['بدأت اجتماع Zoom', 'Started a Zoom meeting'], zoom: 'ID 812 4471 0093' }, { k: 'z2', w: 'maryam', x: ['اتفقنا: نعتمد التصميم مع تكبير الأزرار.', 'Agreed: we approve the design with bigger buttons.'] }], hl: 'z2' }
    ] },
    ex: ['فريق الواجهة الأمامية كان يضيع خمس دقائق قبل كل اجتماع في البحث عن الرابط. الآن يبدأ الاجتماع من المهمة ويجد الجميع الرابط في التعليقات.', 'The front-end team lost five minutes before every meeting looking for the link. Now the meeting starts from the task and everyone finds the link in the comments.'],
    wrong: ['إرسال روابط Zoom في الدردشة الخاصة بعيداً عن العمل.', 'Sending Zoom links in private chats, far from the work.'],
    right: ['ابدأ الاجتماع بـ ‎/zoom داخل المهمة، واكتب القرار فيها بعد الانتهاء.', 'Start the meeting with /zoom inside the task, and write the decision there afterwards.'],
    quiz: { q: ['كيف تبدأ اجتماع Zoom من مهمة بعد ربط التكامل؟', 'How do you start a Zoom meeting from a task once the integration is connected?'], o: [['أكتب ‎/zoom في التعليق وأضغط Enter', 'Type /zoom in the comment and press Enter'], ['أصدّر المهمة إلى Excel', 'Export the task to Excel'], ['أغيّر حالة المهمة', 'Change the task status']], a: 0, why: ['الأمر ‎/zoom ينشئ الاجتماع ويضيف رابطه في تعليق.', 'The /zoom command creates the meeting and adds its link in a comment.'] } },

  { sec: 'x-int', id: 'a-email', t: ['تكامل البريد الإلكتروني', 'Email integration'],
    explain: ['مع ميزة البريد (Email ClickApp) ترسل وتستقبل البريد من داخل المهمة. الرد يعود كتعليق، فتبقى المراسلة كلها بجانب العمل بدل أن تضيع في صندوق بريد شخصي.', 'With the Email ClickApp you send and receive email from inside the task. Replies come back as comments, so the whole conversation stays next to the work instead of getting lost in a personal inbox.'],
    more: ['يجب أن يفعّل المسؤول Email ClickApp، ثم يربط كل شخص حسابه (Gmail أو Outlook أو IMAP). في المهمة اختر «Email» بدل «Comment»، واكتب المستلم والموضوع والنص، أو استخدم قالب بريد محفوظ. يمكنك عرض الردود كتعليقات منفصلة أو كسلسلة واحدة (Threaded). لا ترسل بيانات حساسة إلا وفق سياسة شركتك.', 'An admin must turn on the Email ClickApp, then each person connects their account (Gmail, Outlook or IMAP). In the task choose “Email” instead of “Comment”, write the recipient, subject and body, or use a saved email template. Replies can show as separate comments or as one thread. Do not send sensitive data unless your company policy allows it.'],
    like: ['مثل أن يكون لكل ملف عمل صندوق بريد خاص به.', 'Like giving every work file its own mailbox.'],
    doit: [['اطلب من المسؤول تفعيل Email ClickApp.', 'Ask your admin to turn on the Email ClickApp.'], ['اربط حساب بريدك من الإعدادات.', 'Connect your email account in Settings.'], ['في المهمة اختر Email بدل Comment.', 'In the task choose Email instead of Comment.'], ['اكتب المستلم والموضوع والنص أو اختر قالباً، ثم Send.', 'Write the recipient, subject and body or pick a template, then Send.']],
    tip: ['احفظ الرسائل المتكررة (مثل «تم استلام طلبك») كقوالب بريد لتوفر الكتابة كل مرة.', 'Save repeated messages (like “we received your request”) as email templates so you do not retype them.'],
    demo: { scene: 'task', steps: [
      { c: ['مهمة تحتاج تأكيداً من المورّد.', 'A task that needs confirmation from the supplier.'], title: ['تأكيد موعد توريد الخوادم', 'Confirm the server delivery date'], title2: ['المشتريات', 'Procurement'], st: 'wait', who: ['me'], due: C4D(9), prio: 'urgent' },
      { c: ['اضغط مربع التعليق واختر تبويب Email.', 'Click the comment box and choose the Email tab.'], hl: 'cBox', click: true },
      { c: ['ظهر محرر البريد داخل المهمة.', 'The email editor appears inside the task.'], mailBox: { to: '', sub: '', body: '' }, hl: 'mTab' },
      { c: ['اكتب عنوان المورّد.', 'Type the supplier’s address.'], hl: 'mTo', type: { k: 'mTo', x: 'orders@supplier.example.com' }, mailBox: { to: '', sub: '', body: '' } },
      { c: ['اكتب الموضوع والرسالة ثم Send.', 'Write the subject and message, then Send.'], mailBox: { to: 'orders@supplier.example.com', sub: ['موعد توريد الطلب 4471', 'Delivery date for order 4471'], body: ['مرحباً، نرجو تأكيد موعد التوريد هذا الأسبوع. شكراً.', 'Hello, please confirm the delivery date this week. Thank you.'] }, hl: 'mSend', click: true },
      { c: ['وصل الرد كتعليق في نفس المهمة.', 'The reply arrives as a comment in the same task.'], mailBox: null, comments: [{ k: 'e1', w: 'me', x: ['أُرسل البريد إلى المورّد', 'Email sent to the supplier'], mail: 'orders@supplier.example.com' }, { k: 'e2', w: 'salim', x: ['رد المورّد: التوريد يوم الخميس.', 'Supplier replied: delivery on Thursday.'], mail: ['رد عبر البريد', 'Reply via email'] }], hl: 'e2' }
    ] },
    ex: ['قسم المشتريات صار يرسل بريد المتابعة من المهمة نفسها. عندما غاب الموظف المسؤول، وجد زميله المراسلة كاملة في المهمة وأكمل العمل.', 'Procurement now sends follow-up emails from the task itself. When the responsible employee was away, a colleague found the whole conversation in the task and carried on.'],
    wrong: ['متابعة الموردين من بريد شخصي لا يراه أحد غيرك.', 'Following up with suppliers from a personal inbox nobody else can see.'],
    right: ['أرسل من المهمة لتبقى المراسلة مع العمل ويراها الفريق.', 'Send from the task so the conversation stays with the work and the team can see it.'],
    quiz: { q: ['أين يظهر رد المستلم عند الإرسال من المهمة؟', 'Where does the recipient’s reply appear when you send from a task?'], o: [['في بريدك الشخصي فقط', 'Only in your personal inbox'], ['كتعليق في نفس المهمة', 'As a comment in the same task'], ['في لوحة المعلومات', 'On a Dashboard']], a: 1, why: ['الردود تعود إلى المهمة كتعليقات منفصلة أو كسلسلة.', 'Replies come back to the task as separate or threaded comments.'] } },

  { sec: 'x-int', id: 'a-chrome', t: ['إضافة ClickUp لمتصفح Chrome', 'ClickUp Chrome extension'],
    explain: ['الإضافة تجعل ClickUp معك في أي صفحة ويب: أنشئ مهمة من الصفحة التي تقرؤها، والتقط صورة للشاشة وعلّق عليها، وشغّل مؤقت الوقت، واكتب في المفكرة، واحفظ الصفحة كإشارة مرجعية.', 'The extension brings ClickUp to any web page: create a task from the page you are reading, take an annotated screenshot, run the time tracker, write in your Notepad, and bookmark the page.'],
    more: ['ثبّت الإضافة من Chrome Web Store وسجّل الدخول. اضغط أيقونة ClickUp في شريط المتصفح لتظهر تبويبات: مهمة جديدة، المفكرة، لقطة الشاشة (مع أدوات للأسهم والنص والتمويه)، تتبع الوقت، والإشارات المرجعية. في Gmail تستطيع إضافة البريد إلى مهمة. الإضافة متاحة في كل الخطط؛ قد تقيّد شركتك تثبيت الإضافات.', 'Install it from the Chrome Web Store and sign in. Click the ClickUp icon in the browser bar to see tabs: new task, Notepad, screenshot (with arrows, text and blur tools), time tracking, and bookmarks. In Gmail you can add an email to a task. It is available on every plan; your company may restrict installing extensions.'],
    like: ['مثل دفتر ملاحظات صغير في جيبك يتصل مباشرة بمكتبك.', 'Like a small notebook in your pocket that connects straight to your desk.'],
    doit: [['ثبّت ClickUp من Chrome Web Store (إن سمحت شركتك).', 'Install ClickUp from the Chrome Web Store (if your company allows).'], ['سجّل الدخول من أيقونة الإضافة.', 'Sign in from the extension icon.'], ['على أي صفحة: اكتب اسم مهمة واختر القائمة ثم Create task.', 'On any page: type a task name, pick the List, then Create task.'], ['جرّب لقطة الشاشة: حدّد جزءاً وأضف سهماً ثم أرفقه بمهمة.', 'Try a screenshot: select an area, add an arrow, then attach it to a task.']],
    tip: ['استخدم التمويه (Blur) في لقطة الشاشة لإخفاء الأسماء والأرقام قبل إرفاقها.', 'Use Blur in screenshots to hide names and numbers before attaching them.'],
    demo: { scene: 'browser', steps: [
      { c: ['أنت تقرأ طلب شراء على موقع المورّد.', 'You are reading a purchase order on the supplier’s site.'] },
      { c: ['اضغط أيقونة ClickUp في شريط المتصفح.', 'Click the ClickUp icon in the browser bar.'], hl: 'ext', click: true },
      { c: ['اكتب اسم المهمة. رابط الصفحة يُرفق تلقائياً.', 'Type the task name. The page link is attached automatically.'], ext: true, xtab: 'task', hl: 'xName', type: { k: 'xName', x: ['مراجعة طلب الشراء 4471', 'Review purchase order 4471'] } },
      { c: ['اضغط Create task.', 'Click Create task.'], xName: ['مراجعة طلب الشراء 4471', 'Review purchase order 4471'], xWho: 'salim', hl: 'xCreate', click: true },
      { c: ['جرّب لقطة الشاشة: حدّد الجزء المهم من الصفحة.', 'Try a screenshot: select the important part of the page.'], xtab: 'shot', shot: true, hl: 'shotArea', toast: null },
      { c: ['وتتبع الوقت وأنت تعمل على المهمة.', 'And track time while you work on the task.'], xtab: 'time', shot: false, tpick: ['مراجعة طلب الشراء 4471', 'Review purchase order 4471'], run: true, timer: '0:04:12', hl: 'xTimer' }
    ] },
    ex: ['موظفة المشتريات كانت تنسخ روابط الطلبات إلى ملف ثم تنساها. بالإضافة صارت تنشئ مهمة من صفحة الطلب في ثانيتين، والرابط داخلها.', 'A procurement officer used to copy order links into a file and forget them. With the extension she creates a task from the order page in two seconds, with the link inside.'],
    wrong: ['نسخ الروابط في ملاحظات متفرقة ثم البحث عنها لاحقاً.', 'Copying links into scattered notes and hunting for them later.'],
    right: ['أنشئ المهمة من الصفحة نفسها بالإضافة؛ الرابط يبقى معها.', 'Create the task from the page itself with the extension; the link stays with it.'],
    quiz: { q: ['أي أداة في الإضافة تخفي معلومات حساسة في لقطة الشاشة؟', 'Which extension tool hides sensitive information in a screenshot?'], o: [['Blur (التمويه)', 'Blur'], ['Bookmark', 'Bookmark'], ['Track time', 'Track time']], a: 0, why: ['التمويه يخفي الجزء المحدد قبل مشاركة الصورة.', 'Blur hides the selected part before you share the image.'] } }
];
