/* Intermediate to Advanced course, part 3: more sprints, Agile setup, hidden pro features. */
const ADV_TWO = () => [{ k: 'sp-dev', l: 0, t: 'space', n: ['تطوير الموقع', 'Website development'], c: '#ec4899' }, { k: 'fd-spr', l: 1, t: 'folder', n: ['السبرنتات', 'Sprints'] }, { k: 'sp1', l: 2, t: 'list', n: ['Sprint 1', 'Sprint 1'], cnt: 6 }, { k: 'sp2', l: 2, t: 'list', n: ['Sprint 2', 'Sprint 2'], cnt: 0 }, { k: 'sp-app', l: 0, t: 'space', n: ['تطبيق الجوال', 'Mobile app'], c: '#0ea5e9' }, { k: 'ls-app', l: 1, t: 'list', n: ['المهام', 'Tasks'], cnt: 8 }];
const ADV_PRIO = () => [{ k: 'q1', n: ['إصلاح خطأ إرسال النموذج', 'Fix the form sending bug'], st: 'prog', due: C4D(6) }, { k: 'q2', n: ['مراجعة تصميم صفحة الأسئلة', 'Review the FAQ page design'], st: 'rev', due: C4D(7) }, { k: 'q3', n: ['تحديث مستند الاختبار', 'Update the testing Doc'], st: 'todo', due: C4D(9) }];

const ADV_TOPICS_3 = [
  { sec: 'x-sprint', id: 'a-sprints2', t: ['السبرنتات - الجزء 2: أول سبرنت لأسبوعين', 'Sprints - Part 2: your first two-week sprint'],
    explain: ['أنشئ مجلد السبرنتات واضبط إعداداته مرة واحدة: تاريخ البدء، ومدة السبرنت (أسبوعان)، وعدد السبرنتات التي تُنشأ مقدماً. ينشئ ClickUp السبرنت الأول تلقائياً بتواريخه، ثم تراجع السبرنتات وتسند المواعيد.', 'Create the Sprint Folder and set it up once: start date, sprint length (two weeks) and how many sprints to create ahead. ClickUp creates the first sprint automatically with its dates; then you review the sprints and assign due dates.'],
    more: ['من المساحة اضغط «+» واختر Sprint Folder. الإعدادات الافتراضية للمجلد (المدة، يوم البدء، أتمتة السبرنتات) تنطبق على كل سبرنت جديد، ويمكن تخصيص سبرنت معين بمدة مختلفة. أبقِ قائمة Backlog داخل المجلد لكل المهام التي لم تُجدول بعد.', 'From the Space click “+” and choose Sprint Folder. The folder’s default settings (length, start day, sprint automations) apply to every new sprint, and you can give a single sprint a custom length. Keep a Backlog List inside the folder for all work not scheduled yet.'],
    like: ['مثل جدول مباريات الموسم: تحدده مرة، وتعرف موعد كل جولة مقدماً.', 'Like a season’s match schedule: you set it once and know when every round is.'],
    doit: [['في المساحة اضغط «+» ثم Sprint Folder.', 'In the Space click “+”, then Sprint Folder.'], ['اختر تاريخ البدء والمدة: أسبوعان.', 'Pick the start date and length: two weeks.'], ['حدد عدد السبرنتات التي تُنشأ مقدماً.', 'Set how many sprints to create ahead.'], ['اضغط Create وراجع السبرنتات في الشريط الجانبي.', 'Click Create and review the sprints in the sidebar.']],
    tip: ['اجعل السبرنت يبدأ يوم الأحد وينتهي الخميس بعد أسبوعين، ليتوافق مع أسبوع العمل.', 'Make sprints start on Sunday and end on Thursday two weeks later, to match the working week.'],
    demo: { scene: 'sprint', steps: [
      { c: ['نافذة إعداد مجلد السبرنتات.', 'The Sprint Folder setup window.'], tree: [{ k: 'sp-dev', l: 0, t: 'space', n: ['تطوير الموقع', 'Website development'], c: '#ec4899' }, { k: 'blog', l: 1, t: 'list', n: ['Backlog', 'Backlog'], cnt: 12 }], sel: 'blog', group: 'none', rows: [], sprint: { n: 'Backlog', d: '—', p: 0, pts: 0 }, dlg: { t: 'Sprint Folder', f: [['dStart', ['تاريخ البدء', 'Start date'], ''], ['dLen', ['المدة', 'Duration'], ''], ['dCount', ['عدد السبرنتات', 'Sprints to create'], '']], b: 'Create' } },
      { c: ['تاريخ البدء: الأحد 1 يونيو.', 'Start date: Sunday 1 June.'], hl: 'dStart', type: { k: 'dStart', x: ['الأحد 1 يونيو', 'Sun, Jun 1'] } },
      { c: ['المدة أسبوعان، وننشئ 6 سبرنتات مقدماً.', 'Two weeks long, and we create 6 sprints ahead.'], dlg: { t: 'Sprint Folder', f: [['dStart', ['تاريخ البدء', 'Start date'], ['الأحد 1 يونيو', 'Sun, Jun 1']], ['dLen', ['المدة', 'Duration'], ['أسبوعان', '2 weeks']], ['dCount', ['عدد السبرنتات', 'Sprints to create'], '6']], b: 'Create' }, hl: 'dCount' },
      { c: ['اضغط Create.', 'Click Create.'], hl: 'sDlgGo', click: true },
      { c: ['ظهرت 6 سبرنتات بتواريخها في الشريط الجانبي.', 'Six sprints with their dates appear in the sidebar.'], dlg: null, tree: ADV_STREE(6), sel: 'sp1', sprint: { n: 'Sprint 1', d: '6/1 - 6/14', p: 0, pts: 0 }, hl: 'sp6' }
    ] },
    ex: ['فريق تطبيق الجوال أعد ستة سبرنتات مقدماً. صار مدير المنتج يخطط ثلاثة أشهر بنظرة واحدة على الشريط الجانبي.', 'The mobile app team set up six sprints ahead. The product manager now plans three months with one look at the sidebar.'],
    wrong: ['إنشاء كل سبرنت يدوياً وكتابة تواريخه كل مرة.', 'Creating every sprint by hand and typing its dates each time.'],
    right: ['اضبط إعدادات مجلد السبرنتات مرة، ودع ClickUp ينشئ السبرنتات.', 'Set up the Sprint Folder settings once and let ClickUp create the sprints.'],
    quiz: { q: ['أين تعيش السبرنتات في ClickUp؟', 'Where do sprints live in ClickUp?'], o: [['كقوائم داخل مجلد سبرنتات', 'As Lists inside a Sprint Folder'], ['داخل لوحة معلومات', 'Inside a Dashboard'], ['في الدردشة', 'In Chat']], a: 0, why: ['كل سبرنت قائمة بتواريخ داخل Sprint Folder، ومعها Backlog.', 'Each sprint is a dated List inside a Sprint Folder, alongside the Backlog.'] } },

  { sec: 'x-sprint', id: 'a-sprint-add', t: ['إضافة سبرنتات أخرى', 'Adding additional sprints'],
    explain: ['عندما تقترب من آخر سبرنت، أضف المزيد: من مجلد السبرنتات اضغط «New sprint» واختر تاريخ البدء. ينشئ ClickUp السبرنت السابع والثامن بنفس المدة دون أي إعداد جديد.', 'When you reach the last sprint, add more: in the Sprint Folder click “New sprint” and choose the start date. ClickUp creates sprint seven and eight with the same length, with no new setup.'],
    more: ['السبرنت الجديد يأخذ الإعدادات الافتراضية للمجلد. إن احتجت سبرنتاً أطول (مثلاً قبل عطلة)، خصّص مدته وحده. يمكن أيضاً تفعيل أتمتة السبرنتات لتنشئ السبرنت التالي تلقائياً عند انتهاء الحالي.', 'A new sprint takes the folder’s default settings. If you need a longer sprint (for example before a holiday), give just that one a custom length. You can also turn on sprint automations so the next sprint is created when the current one ends.'],
    like: ['مثل إضافة صفحات جديدة لدفتر بنفس السطور.', 'Like adding new pages to a notebook with the same lines.'],
    doit: [['مرّر على مجلد السبرنتات واضغط «···».', 'Hover the Sprint Folder and click “···”.'], ['اختر New sprint.', 'Choose New sprint.'], ['حدد تاريخ البدء بعد آخر سبرنت.', 'Set the start date after the last sprint.'], ['أو فعّل أتمتة السبرنتات لإنشائها تلقائياً.', 'Or turn on sprint automations to create them automatically.']],
    tip: ['فعّل الأتمتة التي تنشئ السبرنت التالي تلقائياً؛ لن تنسى أبداً.', 'Turn on the automation that creates the next sprint for you; you will never forget.'],
    demo: { scene: 'sprint', steps: [
      { c: ['لدينا 6 سبرنتات، ووصلنا إلى الأخير.', 'We have 6 sprints and we have reached the last one.'], tree: ADV_STREE(6), sel: 'sp6', group: 'none', rows: [], sprint: { n: 'Sprint 6', d: '8/10 - 8/23', p: 70, pts: 18 } },
      { c: ['افتح قائمة مجلد السبرنتات.', 'Open the Sprint Folder menu.'], hl: 'fd-spr', click: true, menu: [['New sprint', 'plus'], ['Sprint settings', 'module'], ['Move', 'arrow-end']], menuStyle: 'top:120px;inset-inline-start:60px;width:190px' },
      { c: ['اختر New sprint.', 'Choose New sprint.'], menu: [['New sprint', 'plus'], ['Sprint settings', 'module'], ['Move', 'arrow-end']], menuStyle: 'top:120px;inset-inline-start:60px;width:190px', menuOn: 0, hl: 'sm0', click: true },
      { c: ['اختر تاريخ البدء بعد آخر سبرنت.', 'Choose the start date after the last sprint.'], menu: null, dlg: { t: 'New sprint', f: [['dStart', ['تاريخ البدء', 'Start date'], ['الأحد 24 أغسطس', 'Sun, Aug 24']], ['dCount', ['العدد', 'How many'], '2']], b: 'Create' }, hl: 'sDlgGo', click: true },
      { c: ['ظهر Sprint 7 وSprint 8.', 'Sprint 7 and Sprint 8 appear.'], dlg: null, tree: ADV_STREE(8), hl: 'sp8' }
    ] },
    ex: ['قبل إجازة العيد، أضافت قائدة الفريق سبرنتاً بمدة ثلاثة أسابيع بدل أسبوعين، ثم عادت المدة الافتراضية بعده.', 'Before the Eid holiday, the team lead added a three-week sprint instead of two, then the default length came back after it.'],
    wrong: ['إنشاء مجلد سبرنتات جديد كلما انتهت السبرنتات.', 'Creating a new Sprint Folder every time the sprints run out.'],
    right: ['أضف سبرنتات جديدة لنفس المجلد ليبقى التاريخ والتقارير متصلة.', 'Add new sprints to the same folder so history and reports stay connected.'],
    quiz: { q: ['ما الإعدادات التي يأخذها السبرنت الجديد؟', 'Which settings does a new sprint use?'], o: [['الإعدادات الافتراضية للمجلد', 'The folder’s default settings'], ['إعدادات عشوائية', 'Random settings'], ['لا إعدادات', 'No settings']], a: 0, why: ['السبرنت الجديد يرث المدة والإعدادات من المجلد، إلا إذا خصصته.', 'A new sprint inherits length and settings from the folder unless you customise it.'] } },

  { sec: 'x-sprint', id: 'a-sprint-move', t: ['نقل السبرنتات في ClickUp', 'Moving sprints in ClickUp'],
    explain: ['تستطيع نقل مجلد السبرنتات كاملاً إلى مساحة أخرى بالسحب أو من «···» ← Move. إن كانت المساحة الجديدة لا تفعّل Sprints، تختار: تفعيلها، أو تحويل المجلد إلى مجلد عادي والسبرنتات إلى قوائم.', 'You can move a whole Sprint Folder to another Space by dragging it or with “···” → Move. If the new Space does not have Sprints turned on, you choose: turn it on, or convert the folder to a normal Folder and the sprints to Lists.'],
    more: ['النقل مفيد عندما يتغير الفريق المسؤول عن المشروع. راجع بعد النقل تواريخ البدء والصلاحيات في المساحة الجديدة، لأن الأعضاء قد يختلفون. نقل مهام مفردة بين السبرنتات موضوع الدرس التالي.', 'Moving helps when a different team takes over the project. After the move, check start dates and permissions in the new Space, because members may differ. Moving single tasks between sprints is the next topic.'],
    like: ['مثل نقل خزانة ملفات كاملة إلى مكتب قسم آخر، بأدراجها كما هي.', 'Like moving a whole filing cabinet to another department’s office, drawers and all.'],
    doit: [['مرّر على مجلد السبرنتات واضغط «···» ثم Move.', 'Hover the Sprint Folder, click “···”, then Move.'], ['اختر المساحة الجديدة.', 'Choose the new Space.'], ['إن طُلب منك: فعّل Sprints أو حوّل إلى مجلد عادي.', 'If asked: turn on Sprints or convert to a normal Folder.'], ['راجع التواريخ والصلاحيات بعد النقل.', 'Check dates and permissions after the move.']],
    tip: ['اختر «تفعيل Sprints» إن أردت إبقاء النقاط والتقارير؛ التحويل لقوائم عادية يفقدك ميزات السبرنت.', 'Choose “turn on Sprints” if you want to keep points and reports; converting to normal Lists loses sprint features.'],
    demo: { scene: 'sprint', steps: [
      { c: ['مجلد السبرنتات في مساحة «تطوير الموقع».', 'The Sprint Folder is in the “Website development” Space.'], tree: ADV_TWO(), sel: 'sp1', group: 'none', rows: [], sprint: { n: 'Sprint 1', d: '6/1 - 6/14', p: 30, pts: 21 } },
      { c: ['افتح قائمة المجلد واختر Move.', 'Open the folder menu and choose Move.'], hl: 'fd-spr', click: true, menu: [['New sprint', 'plus'], ['Sprint settings', 'module'], ['Move', 'arrow-end']], menuStyle: 'top:120px;inset-inline-start:60px;width:190px', menuOn: 2 },
      { c: ['اختر المساحة الجديدة: «تطبيق الجوال».', 'Choose the new Space: “Mobile app”.'], menu: [[['تطوير الموقع', 'Website development'], 'layers'], [['تطبيق الجوال', 'Mobile app'], 'layers']], menuOn: 1, hl: 'sm1', click: true },
      { c: ['انتقل المجلد بسبرنتاته إلى المساحة الجديدة.', 'The folder moves with its sprints to the new Space.'], menu: null, tree: [{ k: 'sp-dev', l: 0, t: 'space', n: ['تطوير الموقع', 'Website development'], c: '#ec4899' }, { k: 'sp-app', l: 0, t: 'space', n: ['تطبيق الجوال', 'Mobile app'], c: '#0ea5e9' }, { k: 'ls-app', l: 1, t: 'list', n: ['المهام', 'Tasks'], cnt: 8 }, { k: 'fd-spr', l: 1, t: 'folder', n: ['السبرنتات', 'Sprints'] }, { k: 'sp1', l: 2, t: 'list', n: ['Sprint 1', 'Sprint 1'], cnt: 6 }, { k: 'sp2', l: 2, t: 'list', n: ['Sprint 2', 'Sprint 2'], cnt: 0 }], hl: 'fd-spr', toast: ['نُقل المجلد إلى «تطبيق الجوال»', 'Folder moved to “Mobile app”'] }
    ] },
    ex: ['انتقلت مسؤولية صفحة الدفع من فريق الموقع إلى فريق التطبيق. نقلوا مجلد السبرنتات كما هو، فبقيت النقاط والتقدم دون فقدان.', 'Ownership of the payment page moved from the website team to the app team. They moved the Sprint Folder as it was, so points and progress were kept.'],
    wrong: ['نسخ المهام يدوياً إلى مساحة الفريق الجديد.', 'Copying tasks by hand into the new team’s Space.'],
    right: ['انقل مجلد السبرنتات كاملاً واختر إبقاء ميزة Sprints.', 'Move the whole Sprint Folder and choose to keep Sprints on.'],
    quiz: { q: ['ماذا يحدث إن نقلت مجلد السبرنتات إلى مساحة بلا Sprints واخترت التحويل؟', 'What happens if you move a Sprint Folder to a Space without Sprints and choose to convert?'], o: [['تُحذف المهام', 'The tasks are deleted'], ['يصبح مجلداً عادياً والسبرنتات قوائم', 'It becomes a normal Folder and the sprints become Lists'], ['لا يمكن النقل', 'It cannot be moved']], a: 1, why: ['التحويل يحافظ على المهام لكن يزيل ميزات السبرنت.', 'Converting keeps the tasks but removes sprint features.'] } },

  { sec: 'x-sprint', id: 'a-sprint-tasks', t: ['نقل المهام بين السبرنتات', 'Moving tasks within sprints'],
    explain: ['عندما ينتهي السبرنت تبقى أحياناً مهام لم تكتمل (Spillover). اضغط «unfinished tasks» في الشريط أعلى السبرنت، أزل ما لا يلزم، ثم «Move tasks to the next Sprint». ولمهمة واحدة: اسحبها إلى السبرنت الآخر أو استخدم Move.', 'When a sprint ends, some tasks are often unfinished (spillover). Click “unfinished tasks” in the banner at the top of the sprint, untick what should not move, then “Move tasks to the next Sprint”. For one task: drag it to the other sprint or use Move.'],
    more: ['كل مهمة تنتقل إلى السبرنت التالي حسب قائمتها الأصلية (Home List). راجع لماذا لم تكتمل: هل كانت أكبر من تقديرها؟ هل انتظرت شخصاً آخر؟ هذه المراجعة هي ما يحسّن التخطيط في السبرنت القادم.', 'Each task moves to the next sprint based on its home List. Review why it was not finished: was it bigger than estimated? Was it waiting on someone? That review is what improves planning for the next sprint.'],
    like: ['مثل الواجبات التي لم تنتهِ يوم الجمعة: تنقلها إلى قائمة الأسبوع القادم بدل أن تنساها.', 'Like the chores you did not finish on Friday: you move them to next week’s list instead of forgetting them.'],
    doit: [['افتح السبرنت المنتهي.', 'Open the finished sprint.'], ['اضغط «unfinished tasks» في الشريط.', 'Click “unfinished tasks” in the banner.'], ['أزل علامة ما لا يجب نقله.', 'Untick what should not move.'], ['اضغط Move tasks to the next Sprint.', 'Click Move tasks to the next Sprint.']],
    tip: ['إن انتقلت نفس المهمة ثلاث مرات، قسّمها إلى مهام أصغر؛ غالباً هي أكبر مما تبدو.', 'If the same task spills over three times, split it into smaller tasks; it is usually bigger than it looks.'],
    demo: { scene: 'sprint', steps: [
      { c: ['انتهى Sprint 1 وبقيت مهمتان.', 'Sprint 1 has ended and two tasks are left.'], tree: ADV_STREE(2), sel: 'sp1', group: 'status', rows: ADV_WEB().map((r, i) => Object.assign({}, r, { st: i < 2 ? 'done' : 'todo' })), sprint: { n: 'Sprint 1', d: '6/1 - 6/14', p: 62, pts: 21, btn: 'Completed', done: true }, spill: ['2 مهام غير مكتملة', '2 unfinished tasks'] },
      { c: ['الشريط ينبهك إلى المهام غير المكتملة.', 'The banner tells you about the unfinished tasks.'], hl: 'spill' },
      { c: ['اضغط Move tasks to the next Sprint.', 'Click Move tasks to the next Sprint.'], hl: 'moveNext', click: true },
      { c: ['انتقلت المهمتان إلى Sprint 2.', 'The two tasks moved to Sprint 2.'], spill: null, rows: ADV_WEB().slice(0, 2).map(r => Object.assign({}, r, { st: 'done' })), tree: ADV_STREE(2).map(n => n.k === 'sp2' ? Object.assign({}, n, { cnt: 2 }) : n.k === 'sp1' ? Object.assign({}, n, { cnt: 2 }) : n), hl: 'sp2', toast: ['نُقلت مهمتان إلى Sprint 2', '2 tasks moved to Sprint 2'] }
    ] },
    ex: ['في مراجعة نهاية السبرنت، لاحظ الفريق أن مهام «الاختبار» تنتقل دائماً. أضافوا يوماً للاختبار في كل سبرنت فتوقف الانتقال.', 'In the sprint review the team saw that testing tasks always spilled over. They added a testing day to every sprint and the spillover stopped.'],
    wrong: ['ترك المهام غير المكتملة في سبرنت منتهٍ فتختفي عن الأنظار.', 'Leaving unfinished tasks in an ended sprint where nobody sees them.'],
    right: ['انقلها للسبرنت التالي مع مراجعة سبب عدم اكتمالها.', 'Move them to the next sprint and review why they were not finished.'],
    quiz: { q: ['أين تجد زر نقل المهام غير المكتملة؟', 'Where do you find the button to move unfinished tasks?'], o: [['في الشريط أعلى السبرنت (unfinished tasks)', 'In the banner at the top of the sprint (unfinished tasks)'], ['في إعدادات الملف الشخصي', 'In profile settings'], ['في الدردشة', 'In Chat']], a: 0, why: ['الشريط يعرض المهام غير المكتملة ويتيح نقلها للسبرنت التالي.', 'The banner lists unfinished tasks and lets you move them to the next sprint.'] } },

  { sec: 'x-sprint', id: 'a-sprint-convert', t: ['تحويل قائمة إلى عمل سبرنت', 'Convert a List to a Sprint'],
    explain: ['كانت إصدارات أقدم من ClickUp تحوي زر «Convert List to Sprint». اليوم السبرنتات تعيش في مجلد سبرنتات، فالطريقة العملية: أنشئ السبرنت ثم انقل مهام القائمة إليه دفعة واحدة باختيارها وMove.', 'Older ClickUp versions had a “Convert List to Sprint” button. Today sprints live in a Sprint Folder, so the practical way is: create the sprint, then move the List’s tasks into it in one go by selecting them and using Move.'],
    more: ['حدد كل مهام القائمة (مربع الاختيار في رأس القائمة)، ثم من شريط الإجراءات الجماعية اختر Move واختر السبرنت. أو أضف المهام إلى السبرنت من Backlog. إن رأيت في حسابك خياراً مباشراً للتحويل فاستخدمه؛ الأسماء والقوائم تتغير بين الإصدارات.', 'Select all the List’s tasks (the checkbox in the List header), then in the bulk action bar choose Move and pick the sprint. Or add tasks to the sprint from the Backlog. If your account shows a direct convert option, use it; names and menus change between versions.'],
    like: ['مثل نقل محتوى صندوق كامل إلى رف جديد مرة واحدة، بدل قطعة قطعة.', 'Like moving a whole box onto a new shelf at once, instead of piece by piece.'],
    doit: [['أنشئ السبرنت في مجلد السبرنتات.', 'Create the sprint in the Sprint Folder.'], ['افتح القائمة القديمة وحدد كل المهام.', 'Open the old List and select all tasks.'], ['من الشريط الجماعي اختر Move ثم السبرنت.', 'In the bulk bar choose Move, then the sprint.'], ['تأكد أن النقاط والتواريخ ظهرت في السبرنت.', 'Check that points and dates show in the sprint.']],
    tip: ['أضف حقل Sprint Points للمهام قبل النقل حتى يكون مجموع السبرنت صحيحاً من أول يوم.', 'Add Sprint Points to the tasks before moving so the sprint total is right from day one.'],
    demo: { scene: 'sprint', steps: [
      { c: ['قائمة «المرحلة الأولى» فيها عمل نريده سبرنتاً.', 'The “Phase 1” List holds work we want as a sprint.'], tree: [{ k: 'sp-dev', l: 0, t: 'space', n: ['تطوير الموقع', 'Website development'], c: '#ec4899' }, { k: 'ph1', l: 1, t: 'list', n: ['المرحلة الأولى', 'Phase 1'], cnt: 4 }, { k: 'fd-spr', l: 1, t: 'folder', n: ['السبرنتات', 'Sprints'] }, { k: 'sp1', l: 2, t: 'list', n: ['Sprint 1', 'Sprint 1'], cnt: 0 }], sel: 'ph1', title: ['المرحلة الأولى', 'Phase 1'], group: 'none', rows: ADV_WEB().map(r => Object.assign({}, r, { st: 'todo' })), sprint: { n: ['المرحلة الأولى', 'Phase 1'], d: '—', p: 0, pts: 21, btn: '—', done: true } },
      { c: ['حدد كل المهام.', 'Select all the tasks.'], rows: ADV_WEB().map(r => Object.assign({}, r, { st: 'todo', sel: true })), hl: 'bulk' },
      { c: ['اضغط Move.', 'Click Move.'], hl: 'bMove', click: true, menu: [['Sprint 1', 'repeat'], ['Backlog', 'list']], menuStyle: 'top:250px;inset-inline-start:330px;width:180px' },
      { c: ['اختر Sprint 1.', 'Choose Sprint 1.'], menu: [['Sprint 1', 'repeat'], ['Backlog', 'list']], menuStyle: 'top:250px;inset-inline-start:330px;width:180px', menuOn: 0, hl: 'sm0', click: true },
      { c: ['انتقل العمل إلى Sprint 1 بنقاطه.', 'The work moved to Sprint 1 with its points.'], menu: null, sel: 'sp1', title: 'Sprint 1', rows: ADV_WEB().map(r => Object.assign({}, r, { st: 'todo' })), sprint: { n: 'Sprint 1', d: '6/1 - 6/14', p: 0, pts: 21 }, tree: [{ k: 'sp-dev', l: 0, t: 'space', n: ['تطوير الموقع', 'Website development'], c: '#ec4899' }, { k: 'ph1', l: 1, t: 'list', n: ['المرحلة الأولى', 'Phase 1'], cnt: 0 }, { k: 'fd-spr', l: 1, t: 'folder', n: ['السبرنتات', 'Sprints'] }, { k: 'sp1', l: 2, t: 'list', n: ['Sprint 1', 'Sprint 1'], cnt: 4 }], hl: 'sp1' }
    ] },
    ex: ['فريق الموقع كان يدير العمل بقوائم «مراحل». حوّلوا كل مرحلة إلى سبرنت بنقل مهامها، فصار لكل مرحلة تاريخ نهاية ونقاط واضحة.', 'The website team ran work in “phase” Lists. They turned each phase into a sprint by moving its tasks, so every phase now has an end date and clear points.'],
    wrong: ['البحث طويلاً عن زر قديم لم يعد في القائمة.', 'Searching for an old button that is no longer in the menu.'],
    right: ['أنشئ السبرنت وانقل المهام إليه دفعة واحدة.', 'Create the sprint and move the tasks into it in one go.'],
    quiz: { q: ['ما الطريقة العملية اليوم لتحويل عمل قائمة إلى سبرنت؟', 'What is the practical way today to turn a List’s work into a sprint?'], o: [['حذف القائمة', 'Delete the List'], ['إنشاء السبرنت ونقل المهام إليه', 'Create the sprint and move the tasks into it'], ['تغيير لون القائمة', 'Change the List colour']], a: 1, why: ['السبرنتات قوائم داخل Sprint Folder، فننقل المهام إليها.', 'Sprints are Lists inside a Sprint Folder, so we move the tasks into them.'] } },

  /* ---------------- 6. Agile setup ---------------- */
  { sec: 'x-agile', id: 'a-agile-folders', t: ['هيكل المجلدات لبيئة Agile', 'Folder structure for Agile'],
    explain: ['نظّم المساحة كبيئة Agile: اسم واضح ورمز قصير للمساحة (مثل WEB)، ثم مجلدات بأسماء صريحة: الواجهة الخلفية، الواجهة الأمامية، السبرنتات، والأخطاء (Bugs).', 'Organise the Space like an Agile environment: a clear name and short code for the Space (such as WEB), then plainly named Folders: Back end, Front end, Sprints and Bugs.'],
    more: ['مجلدات العمل (الخلفية والأمامية) تحمل المهام حسب نوعها، ومجلد السبرنتات يحمل الدورات الزمنية، ومجلد الأخطاء يستقبل البلاغات بنموذج (Form) واحد. المهمة يمكن أن تكون في قائمتها الأصلية وفي سبرنت في نفس الوقت (Tasks in Multiple Lists)، فلا تحتاج نسخها.', 'Work Folders (back end and front end) hold tasks by type, the Sprints folder holds the time cycles, and the Bugs folder receives reports through one Form. A task can live in its home List and in a sprint at the same time (Tasks in Multiple Lists), so you never need to copy it.'],
    like: ['مثل مطبخ مطعم: محطة للمشويات، ومحطة للسلطات، ولوح طلبات، وصندوق للشكاوى.', 'Like a restaurant kitchen: a grill station, a salad station, an order board and a complaints box.'],
    doit: [['أنشئ مساحة «تطوير الموقع» واختر لها لوناً ورمزاً.', 'Create a “Website development” Space with a colour and code.'], ['أضف مجلدي «الواجهة الخلفية» و«الواجهة الأمامية».', 'Add “Back end” and “Front end” Folders.'], ['أضف مجلد سبرنتات ومجلد «الأخطاء».', 'Add a Sprint Folder and a “Bugs” Folder.'], ['اربط نموذج بلاغ الأخطاء بقائمة في مجلد الأخطاء.', 'Connect a bug report Form to a List in the Bugs Folder.']],
    tip: ['اكتب في وصف كل مجلد ماذا يدخل فيه وماذا لا يدخل؛ يقل الخلط عند الأعضاء الجدد.', 'Write in each Folder’s description what goes in and what does not; new members get less confused.'],
    demo: { scene: 'list', steps: [
      { c: ['مساحة جديدة: «تطوير الموقع».', 'A new Space: “Website development”.'], tree: [{ k: 'sp-web', l: 0, t: 'space', n: ['تطوير الموقع (WEB)', 'Website development (WEB)'], c: '#ec4899' }], sel: 'sp-web', title: ['تطوير الموقع', 'Website development'], group: 'none', rows: [] },
      { c: ['أضف مجلدي الواجهة الخلفية والأمامية.', 'Add the Back end and Front end Folders.'], tree: [{ k: 'sp-web', l: 0, t: 'space', n: ['تطوير الموقع (WEB)', 'Website development (WEB)'], c: '#ec4899' }, { k: 'fd-be', l: 1, t: 'folder', n: ['الواجهة الخلفية', 'Back end'] }, { k: 'fd-fe', l: 1, t: 'folder', n: ['الواجهة الأمامية', 'Front end'] }], hl: 'fd-fe' },
      { c: ['أضف مجلد السبرنتات.', 'Add the Sprints Folder.'], tree: [{ k: 'sp-web', l: 0, t: 'space', n: ['تطوير الموقع (WEB)', 'Website development (WEB)'], c: '#ec4899' }, { k: 'fd-be', l: 1, t: 'folder', n: ['الواجهة الخلفية', 'Back end'] }, { k: 'fd-fe', l: 1, t: 'folder', n: ['الواجهة الأمامية', 'Front end'] }, { k: 'fd-spr', l: 1, t: 'folder', n: ['السبرنتات', 'Sprints'] }, { k: 'sp1', l: 2, t: 'list', n: ['Sprint 1', 'Sprint 1'], cnt: 6 }], hl: 'fd-spr' },
      { c: ['وأخيراً مجلد الأخطاء مع قائمة البلاغات.', 'Finally the Bugs Folder with a reports List.'], tree: [{ k: 'sp-web', l: 0, t: 'space', n: ['تطوير الموقع (WEB)', 'Website development (WEB)'], c: '#ec4899' }, { k: 'fd-be', l: 1, t: 'folder', n: ['الواجهة الخلفية', 'Back end'] }, { k: 'fd-fe', l: 1, t: 'folder', n: ['الواجهة الأمامية', 'Front end'] }, { k: 'fd-spr', l: 1, t: 'folder', n: ['السبرنتات', 'Sprints'] }, { k: 'sp1', l: 2, t: 'list', n: ['Sprint 1', 'Sprint 1'], cnt: 6 }, { k: 'fd-bug', l: 1, t: 'folder', n: ['الأخطاء', 'Bugs'] }, { k: 'ls-bug', l: 2, t: 'list', n: ['البلاغات', 'Reports'], cnt: 3 }], sel: 'ls-bug', title: ['البلاغات', 'Reports'], rows: [C4R('bg1', ['زر الإرسال لا يعمل على Safari', 'Submit button fails on Safari'], { st: 'todo', who: 'khalid', prio: 'urgent', due: C4D(5) }), C4R('bg2', ['النجوم لا تظهر في الوضع الداكن', 'Stars hidden in dark mode'], { st: 'prog', who: 'noura', prio: 'normal', due: C4D(8) })], hl: 'fd-bug' }
    ] },
    ex: ['قبل التنظيم كانت أخطاء الموقع تصل بالبريد والهاتف والدردشة. بعد مجلد «الأخطاء» ونموذج واحد، صار كل بلاغ مهمة بأولوية واضحة.', 'Before the setup, website bugs arrived by email, phone and chat. After the Bugs Folder and one Form, every report is a task with a clear priority.'],
    wrong: ['قائمة واحدة ضخمة لكل شيء: ميزات وأخطاء وسبرنتات.', 'One huge List for everything: features, bugs and sprints.'],
    right: ['مجلدات واضحة حسب النوع، وسبرنتات في مجلدها، وأخطاء في مجلد خاص.', 'Clear Folders by type, sprints in their own folder, and bugs in a dedicated folder.'],
    quiz: { q: ['كيف تكون المهمة في قائمتها الأصلية وفي سبرنت دون نسخها؟', 'How can a task be in its home List and in a sprint without copying it?'], o: [['Tasks in Multiple Lists', 'Tasks in Multiple Lists'], ['تصدير المهمة', 'Exporting the task'], ['تغيير لونها', 'Changing its colour']], a: 0, why: ['هذه الميزة تجعل نفس المهمة تظهر في أكثر من قائمة.', 'This feature lets the same task show in more than one List.'] } },

  { sec: 'x-agile', id: 'a-agile-tpl', t: ['انطلق بسرعة: قالب إدارة Agile', 'Go full speed: the Agile Management template'], link: '#/workshops/templates',
    explain: ['بدل بناء كل شيء بيدك، استخدم قالب Agile من Template Center: مجلدات ومنتج وسبرنتات وحالات وحقول جاهزة. استورده ثم خصص المجلدات، مثل إدارة المنتج والمخاطر والاختبار.', 'Instead of building everything by hand, use an Agile template from Template Center: folders, product, sprints, statuses and fields ready to go. Import it, then customise the folders, such as product, risk and test management.'],
    more: ['ابحث عن «agile» واقرأ وصف القالب ومحتواه قبل استخدامه. عند الاستخدام اختر ما يُستورد: المهام، الحالات، الحقول، الأتمتة، العروض. ثم احذف ما لا تحتاجه وأضف مجلداتك. القوالب المتاحة وأسماؤها تتغير؛ اختر الأقرب لعمل فريقك.', 'Search “agile” and read the template’s description and contents before using it. When applying it, choose what to import: tasks, statuses, fields, automations, views. Then delete what you do not need and add your own folders. Available templates and their names change; pick the closest to your team’s work.'],
    like: ['مثل شراء بيت مفروش ثم تغيير بعض الأثاث، بدل البناء من الأساس.', 'Like buying a furnished house and changing some furniture, instead of building from the foundations.'],
    doit: [['افتح Template Center وابحث عن «agile».', 'Open Template Center and search “agile”.'], ['عاين القالب واقرأ ما يحتويه.', 'Preview the template and read what it contains.'], ['اختر ما تريد استيراده واضغط Use template.', 'Choose what to import and click Use template.'], ['خصص المجلدات: المنتج، المخاطر، الاختبار.', 'Customise the folders: product, risk, testing.']],
    tip: ['طبّق القالب أولاً في مساحة تجريبية، وبعد أن يناسبك احفظ نسختك المعدلة كقالب للشركة.', 'Apply the template in a sandbox Space first, and once it suits you, save your edited version as a company template.'],
    demo: { scene: 'templates', steps: [
      { c: ['مركز القوالب.', 'The Template Center.'], cards: [{ k: 'ag1', n: 'Agile Management', d: 'Space', ic: 'repeat', c: '#ec4899' }, { k: 'ag2', n: 'Scrum Board', d: 'List', ic: 'board', c: '#7b68ee' }, { k: 'ag3', n: 'Bug Tracking', d: 'List', ic: 'alert', c: '#e03131' }, { k: 'ag4', n: 'Product Roadmap', d: 'Folder', ic: 'gantt', c: '#0ea5e9' }] },
      { c: ['ابحث عن «agile».', 'Search for “agile”.'], hl: 'tSearch', type: { k: 'tSearch', x: 'agile' } },
      { c: ['عاين Agile Management.', 'Preview Agile Management.'], q: 'agile', preview: 'ag1', hl: 'ag1', click: true },
      { c: ['اختر ما يُستورد، ثم Use template.', 'Choose what to import, then Use template.'], dlg: { t: 'Agile Management', n: ['تطوير الموقع - Agile', 'Website development - Agile'], opts: [[['المهام والحالات', 'Tasks and statuses'], true], [['الحقول المخصصة', 'Custom Fields'], true], [['الأتمتة', 'Automations'], true]], b: 'Use template' }, hl: 'dlgGo', click: true }
    ] },
    ex: ['فريق التطبيق أعد بيئة Agile كاملة في 20 دقيقة باستخدام القالب، بعد أن استغرق الإعداد اليدوي في مشروع سابق يومين.', 'The app team set up a full Agile environment in 20 minutes with the template; the manual setup on a previous project had taken two days.'],
    wrong: ['تطبيق قالب كبير مباشرة على مساحة العمل الحقيقية دون معاينة.', 'Applying a big template straight onto the real Workspace without previewing.'],
    right: ['عاين، طبّق في مساحة تجريبية، خصص، ثم احفظ نسختك.', 'Preview, apply in a sandbox, customise, then save your version.'],
    quiz: { q: ['ماذا تفعل قبل استخدام قالب Agile كبير؟', 'What do you do before using a big Agile template?'], o: [['أعاينه وأقرأ محتواه', 'Preview it and read its contents'], ['أحذف مساحتي', 'Delete my Space'], ['أطفئ الإشعارات', 'Turn off notifications']], a: 0, why: ['المعاينة تريك ما سيُضاف قبل أن يغيّر مساحتك.', 'The preview shows what will be added before it changes your Space.'] } },

  /* ---------------- 7. Hidden pro features ---------------- */
  { sec: 'x-pro', id: 'a-lineup', t: ['الأولويات الشخصية (LineUp سابقاً)', 'Personal Priorities (formerly LineUp)'],
    explain: ['ميزة LineUp أصبح اسمها Personal Priorities. ترتّب فيها أهم مهامك بالترتيب، فيعرف فريقك ومديرك ما تركز عليه الآن من ملفك وفي Teams Hub.', 'LineUp is now called Personal Priorities. You rank your most important tasks in order, and your team and manager see what you are focusing on from your profile and in Teams Hub.'],
    more: ['من صفحة My Tasks (Home سابقاً) افتح بطاقة Priorities واضغط Add task لتبحث عن مهمة أو تنشئ جديدة. اسحب المهام لترتيبها. المدير يرى أولويات كل شخص في Teams Hub، فيعيد ترتيب العمل إن لزم دون اجتماع. اجعل القائمة قصيرة: ثلاث إلى خمس مهام.', 'On the My Tasks page (formerly Home) open the Priorities card and click Add task to search for a task or create one. Drag tasks to rank them. A manager sees everyone’s priorities in Teams Hub and can rebalance work without a meeting. Keep the list short: three to five tasks.'],
    like: ['مثل ورقة «أهم 3 أشياء اليوم» على باب مكتبك يراها الجميع.', 'Like a “top 3 things today” note on your office door that everyone can see.'],
    doit: [['افتح My Tasks وابحث عن بطاقة Priorities.', 'Open My Tasks and find the Priorities card.'], ['اضغط Add task وابحث عن مهمة.', 'Click Add task and search for a task.'], ['اسحب المهام لترتيبها حسب الأهمية.', 'Drag tasks to rank them by importance.'], ['افتح Teams Hub لترى أولويات الفريق.', 'Open Teams Hub to see the team’s priorities.']],
    tip: ['حدّث أولوياتك كل صباح في دقيقة؛ يقل سؤال «على ماذا تعمل؟» في الاجتماعات.', 'Update your priorities every morning in one minute; you will hear “what are you working on?” less in meetings.'],
    demo: { scene: 'prio', steps: [
      { c: ['بطاقة Priorities في My Tasks.', 'The Priorities card in My Tasks.'], nav: 'home', items: ADV_PRIO() },
      { c: ['اضغط Add task.', 'Click Add task.'], hl: 'pAdd', click: true },
      { c: ['ابحث عن المهمة.', 'Search for the task.'], search: { q: '', res: [['ربط النموذج بقاعدة البيانات', 'Connect the form to the database'], ['اختبار النموذج على الجوال', 'Test the form on mobile']] }, hl: 'pQ', type: { k: 'pQ', x: ['ربط', 'connect'] } },
      { c: ['اخترها: أُضيفت إلى أولوياتك.', 'Pick it: it is added to your priorities.'], hl: 'pr0', click: true },
      { c: ['اسحبها إلى الأعلى: صارت الأولوية رقم 1.', 'Drag it to the top: it is now priority number 1.'], search: null, items: [{ k: 'q4', n: ['ربط النموذج بقاعدة البيانات', 'Connect the form to the database'], st: 'todo', due: C4D(10) }].concat(ADV_PRIO()), hl: 'q4' },
      { c: ['في Teams Hub يرى المدير أولويات الجميع.', 'In Teams Hub the manager sees everyone’s priorities.'], view: 'team', team: [{ w: 'me', items: [['ربط النموذج', 'Connect the form'], ['إصلاح خطأ الإرسال', 'Fix sending bug']] }, { w: 'khalid', items: [['برمجة الواجهة', 'Build the front end'], ['مراجعة الكود', 'Code review']] }, { w: 'noura', items: [['اختبار الجوال', 'Mobile testing']] }], hl: 'tm-khalid' }
    ] },
    ex: ['مدير التطوير كان يعقد اجتماعاً يومياً ليعرف من يعمل على ماذا. بعد Personal Priorities صار يفتح Teams Hub ويختصر الاجتماع إلى عشر دقائق.', 'The development manager held a daily meeting just to learn who was working on what. With Personal Priorities he opens Teams Hub and the meeting is down to ten minutes.'],
    wrong: ['قائمة أولويات من عشرين مهمة؛ إن كان كل شيء أولوية فلا شيء أولوية.', 'A priority list of twenty tasks; if everything is a priority, nothing is.'],
    right: ['ثلاث إلى خمس مهام مرتبة، تُحدَّث كل صباح.', 'Three to five ranked tasks, updated every morning.'],
    quiz: { q: ['ما الاسم الحالي لميزة LineUp؟', 'What is LineUp called today?'], o: [['Personal Priorities', 'Personal Priorities'], ['Sprint Points', 'Sprint Points'], ['Notepad', 'Notepad']], a: 0, why: ['LineUp أصبحت Personal Priorities وتظهر في My Tasks وTeams Hub.', 'LineUp became Personal Priorities and shows in My Tasks and Teams Hub.'] } },

  { sec: 'x-pro', id: 'a-clip', t: ['التواصل بتسجيل الشاشة (Clip)', 'Communicate with screen recording (Clip)'],
    explain: ['بدل كتابة شرح طويل، سجّل شاشتك وصوتك بأداة Clip وأرسل التسجيل في تعليق على المهمة. زميلك في منطقة زمنية أخرى يشاهده متى شاء.', 'Instead of writing a long explanation, record your screen and voice with Clip and send it in a task comment. A colleague in another time zone watches it whenever they like.'],
    more: ['اختر ما تسجّله: الشاشة كلها، أو نافذة، أو تبويب متصفح، وفعّل الميكروفون. بعد الإيقاف يُحفظ المقطع ويمكن إضافته لتعليق والإشارة لزميل بـ @. التسجيلات تُحفظ في Clips Hub. لا تسجّل شاشة فيها بيانات عملاء أو كلمات مرور.', 'Choose what to record: the entire screen, a window or a browser tab, and turn on the microphone. When you stop, the clip is saved and can go into a comment with an @mention. Recordings are kept in the Clips Hub. Never record a screen showing customer data or passwords.'],
    like: ['مثل أن تقف خلف زميلك وتشير إلى الشاشة، لكن دون أن تكونا في نفس الغرفة أو نفس الوقت.', 'Like standing behind a colleague and pointing at the screen, without being in the same room or at the same time.'],
    doit: [['في مربع التعليق اضغط زر التسجيل (Clip).', 'In the comment box click the record (Clip) button.'], ['اختر Browser tab أو Entire screen وفعّل الميكروفون.', 'Choose Browser tab or Entire screen and turn on the microphone.'], ['اشرح وأنت تنقر، ثم Stop.', 'Explain while you click, then Stop.'], ['أرسل التعليق وأشر لزميلك بـ @.', 'Send the comment and @mention your colleague.']],
    tip: ['اجعل المقطع أقل من دقيقتين: موضوع واحد لكل تسجيل.', 'Keep clips under two minutes: one topic per recording.'],
    demo: { scene: 'task', steps: [
      { c: ['نحتاج أن نشرح لخالد خطأً في النموذج.', 'We need to show Khalid a bug in the form.'], title: ['زر الإرسال لا يعمل على Safari', 'Submit button fails on Safari'], title2: ['البلاغات', 'Reports'], st: 'prog', who: ['khalid'], prio: 'urgent', due: C4D(5), recBtn: true },
      { c: ['اضغط زر التسجيل في مربع التعليق.', 'Click the record button in the comment box.'], hl: 'recBtn', click: true },
      { c: ['اختر Browser tab وفعّل الميكروفون.', 'Choose Browser tab and turn on the microphone.'], rec: 'opts', recPick: 'ro-tab', mic: true, hl: 'ro-tab' },
      { c: ['اضغط Start recording.', 'Click Start recording.'], hl: 'recGo', click: true },
      { c: ['اشرح وأنت تنقر، ثم Stop.', 'Explain while you click, then Stop.'], rec: 'on', recT: '1:24', hl: 'recStop', click: true },
      { c: ['أُرسل المقطع في تعليق لخالد.', 'The clip is sent in a comment to Khalid.'], rec: null, comments: [{ k: 'cl1', w: 'me', x: ['@خالد شاهد الخطوات التي تُظهر المشكلة', '@Khalid watch the steps that show the problem'], clip: '1:24 · Safari bug' }], hl: 'cl1' }
    ] },
    ex: ['مصممة في مسقط ومطور يعمل من منطقة زمنية أخرى. بدل انتظار اجتماع مشترك، ترسل له مقطع Clip دقيقة واحدة، فيصلح التصميم قبل أن تبدأ يومها.', 'A designer in Muscat works with a developer in another time zone. Instead of waiting for a shared meeting, she sends a one-minute Clip, and he fixes the design before her day starts.'],
    wrong: ['كتابة عشرة أسطر لشرح خطوات يمكن إظهارها في دقيقة.', 'Writing ten lines to explain steps you could show in a minute.'],
    right: ['سجّل Clip قصيراً وأرفقه بالمهمة مع إشارة @.', 'Record a short Clip and attach it to the task with an @mention.'],
    quiz: { q: ['ماذا يجب ألا يظهر في تسجيل الشاشة؟', 'What should never appear in a screen recording?'], o: [['خطوات المشكلة', 'The steps of the problem'], ['بيانات العملاء وكلمات المرور', 'Customer data and passwords'], ['اسم المهمة', 'The task name']], a: 1, why: ['التسجيل يُشارك ويُحفظ، فلا تعرض فيه معلومات حساسة.', 'Recordings are shared and stored, so never show sensitive information.'] } },

  { sec: 'x-pro', id: 'a-nested', t: ['المهام الفرعية المتداخلة', 'Nested subtasks'],
    explain: ['المهمة الفرعية يمكن أن تحوي مهاماً فرعية أيضاً. مع ميزة Nested Subtasks تبني شجرة عمل بمستويات: الافتراضي ثلاثة، ويمكن للمسؤول رفعها حتى سبعة.', 'A subtask can have subtasks too. With the Nested Subtasks ClickApp you build a tree of work in levels: the default is three, and an admin can raise it up to seven.'],
    more: ['يفعّلها المالك أو المسؤول من ClickApps، وهي متاحة في كل الخطط. لإنشاء مستوى أعمق اضغط «+» بجانب مهمة فرعية، أو أثناء الكتابة اضغط Tab للإزاحة للداخل وShift+Tab للخارج. لا تبالغ في العمق: بعد ثلاثة مستويات يصعب رؤية الصورة؛ فكّر حينها في قائمة أو قائمة تحقق (Checklist).', 'An owner or admin turns it on in ClickApps, and it is available on all plans. To create a deeper level click “+” next to a subtask, or while typing press Tab to indent and Shift+Tab to outdent. Do not go too deep: after three levels the picture gets hard to see; then think about a List or a Checklist.'],
    like: ['مثل فهرس كتاب بفصول وأقسام وأقسام فرعية.', 'Like a book’s contents with chapters, sections and sub-sections.'],
    doit: [['اطلب تفعيل Nested Subtasks من ClickApps.', 'Ask for Nested Subtasks to be turned on in ClickApps.'], ['افتح مهمة وأضف مهمة فرعية.', 'Open a task and add a subtask.'], ['اضغط «+» بجانب المهمة الفرعية لإضافة مستوى أعمق.', 'Click “+” next to the subtask to add a deeper level.'], ['في القائمة استخدم Tab وShift+Tab للإزاحة.', 'In List view use Tab and Shift+Tab to indent and outdent.']],
    tip: ['إن احتجت أكثر من ثلاثة مستويات، غالباً تحتاج قائمة جديدة لا مهمة أعمق.', 'If you need more than three levels, you probably need a new List, not a deeper task.'],
    demo: { scene: 'list', steps: [
      { c: ['مهمة رئيسية: «إطلاق نموذج الملاحظات».', 'A parent task: “Launch the feedback form”.'], title: ['النماذج', 'Forms'], group: 'none', cols: ['assignee', 'due'], rows: [C4R('n1', ['إطلاق نموذج الملاحظات', 'Launch the feedback form'], { st: 'prog', who: 'maryam', due: C4D(20), subs: 1 })] },
      { c: ['افتح المهام الفرعية: المستوى الأول.', 'Open the subtasks: level one.'], rows: [C4R('n1', ['إطلاق نموذج الملاحظات', 'Launch the feedback form'], { st: 'prog', who: 'maryam', due: C4D(20), subs: 1, open: true }), C4R('n2', ['برمجة النموذج', 'Build the form'], { p: 'n1', st: 'prog', who: 'khalid', due: C4D(12), subs: 2 })], hl: 'n2' },
      { c: ['داخل «برمجة النموذج» مستوى ثانٍ.', 'Inside “Build the form” is a second level.'], rows: [C4R('n1', ['إطلاق نموذج الملاحظات', 'Launch the feedback form'], { st: 'prog', who: 'maryam', due: C4D(20), subs: 1, open: true }), C4R('n2', ['برمجة النموذج', 'Build the form'], { p: 'n1', st: 'prog', who: 'khalid', due: C4D(12), subs: 2, open: true }), C4R('n3', ['حقول الإدخال', 'Input fields'], { p: 'n2', st: 'done', who: 'khalid', due: C4D(8) }), C4R('n4', ['التحقق من البيانات', 'Validation'], { p: 'n2', st: 'todo', who: 'salim', due: C4D(11), subs: 1 })], hl: 'n4' },
      { c: ['اضغط Tab لإضافة مستوى ثالث تحت «التحقق».', 'Press Tab to add a third level under “Validation”.'], rows: [C4R('n1', ['إطلاق نموذج الملاحظات', 'Launch the feedback form'], { st: 'prog', who: 'maryam', due: C4D(20), subs: 1, open: true }), C4R('n2', ['برمجة النموذج', 'Build the form'], { p: 'n1', st: 'prog', who: 'khalid', due: C4D(12), subs: 2, open: true }), C4R('n3', ['حقول الإدخال', 'Input fields'], { p: 'n2', st: 'done', who: 'khalid', due: C4D(8) }), C4R('n4', ['التحقق من البيانات', 'Validation'], { p: 'n2', st: 'todo', who: 'salim', due: C4D(11), subs: 1, open: true }), C4R('n5', ['رسالة خطأ للبريد غير الصحيح', 'Error message for a wrong email'], { p: 'n4', st: 'todo', who: 'salim', due: C4D(10) })], hl: 'n5-name' }
    ] },
    ex: ['مشروع الإطلاق كان قائمة طويلة مسطحة من 40 مهمة. بعد التداخل صار ثلاث مهام رئيسية، وكل فريق يفتح فرعه فقط.', 'The launch project was a flat list of 40 tasks. After nesting it became three parent tasks, and each team opens only its own branch.'],
    wrong: ['بناء سبعة مستويات لأن الإعداد يسمح بذلك.', 'Building seven levels because the setting allows it.'],
    right: ['ابقَ في ثلاثة مستويات غالباً، وانقل ما هو أكبر إلى قائمة مستقلة.', 'Stay at three levels most of the time, and move anything bigger to its own List.'],
    quiz: { q: ['ما الاختصار الذي يزيح المهمة للداخل كمهمة فرعية أثناء الكتابة؟', 'Which shortcut indents a task as a subtask while typing?'], o: [['Tab', 'Tab'], ['Ctrl+K', 'Ctrl+K'], ['Esc', 'Esc']], a: 0, why: ['Tab يزيح للداخل مستوى واحداً، وShift+Tab يعيده للخارج.', 'Tab indents one level, and Shift+Tab outdents.'] } },

  { sec: 'x-pro', id: 'a-rel', t: ['العلاقات في ClickUp', 'Relationships in ClickUp'],
    explain: ['العلاقات (Relationships) تربط المهمة بما يتصل بها: مهام مرتبطة، وتبعيات (تنتظر أو تعطّل)، ومستندات، وعلاقات مخصصة. مثال: مهمة «تهيئة موظف جديد» مرتبطة بدليل التهيئة ومهام الحساب والجهاز.', 'Relationships link a task to what it connects with: related tasks, dependencies (waiting on or blocking), Docs, and custom relationships. Example: a “New hire onboarding” task linked to the onboarding guide and the account and laptop tasks.'],
    more: ['من قسم Related في المهمة اضغط «Relate items or add dependencies». الرابط (Link) لعلاقة عامة، و«Waiting on» تعني أن هذه المهمة لا تبدأ قبل غيرها، و«Blocking» أن غيرها ينتظرها. العلاقات المخصصة تربط بين قوائم كقاعدة بيانات بسيطة (مثل «الموظف» و«الجهاز»). يمكن إضافة علاقة تلقائياً بالأتمتة.', 'In the task’s Related section click “Relate items or add dependencies”. A link is a general connection, “Waiting on” means this task cannot start before another, and “Blocking” means another is waiting on it. Custom relationships connect Lists like a simple database (such as “Employee” and “Laptop”). An automation can add a relationship for you.'],
    like: ['مثل الخيوط على لوحة التحقيق التي تربط الصور والملاحظات ببعضها.', 'Like the strings on a detective’s board connecting photos and notes.'],
    doit: [['افتح مهمة وانزل إلى قسم Related.', 'Open a task and scroll to the Related section.'], ['اضغط Relate items or add dependencies.', 'Click Relate items or add dependencies.'], ['اختر Link tasks أو Waiting on أو Link Doc.', 'Choose Link tasks, Waiting on or Link Doc.'], ['ابحث عن العنصر واختره.', 'Search for the item and pick it.']],
    tip: ['اربط مستند التهيئة بكل مهام التهيئة؛ الموظف الجديد يجد الدليل من أي مهمة يفتحها.', 'Link the onboarding Doc to every onboarding task; the new hire finds the guide from any task they open.'],
    demo: { scene: 'task', steps: [
      { c: ['مهمة «تهيئة موظف جديد: نورة».', 'The task “Onboard new hire: Noura”.'], title: ['تهيئة موظف جديد: نورة', 'Onboard new hire: Noura'], title2: ['التهيئة', 'Onboarding'], st: 'prog', who: ['me'], due: C4D(15), prio: 'high', rel: [] },
      { c: ['اضغط «Relate items or add dependencies».', 'Click “Relate items or add dependencies”.'], hl: 'addRel', click: true },
      { c: ['اختر Link Doc واربط دليل التهيئة.', 'Choose Link Doc and connect the onboarding guide.'], relPop: 'rp-doc', hl: 'rp-doc', click: true },
      { c: ['أُضيف المستند.', 'The Doc is added.'], relPop: null, rel: [{ k: 'r1', t: 'doc', n: ['دليل تهيئة الموظفين', 'Employee onboarding guide'] }], hl: 'r1' },
      { c: ['أضف تبعية: التهيئة تنتظر «تجهيز الحاسوب».', 'Add a dependency: onboarding is waiting on “Prepare the laptop”.'], relPop: 'rp-wait', hl: 'rp-wait', click: true },
      { c: ['وارتبط بمهمة «إنشاء الحساب البريدي».', 'And link the “Create the email account” task.'], relPop: null, rel: [{ k: 'r1', t: 'doc', n: ['دليل تهيئة الموظفين', 'Employee onboarding guide'] }, { k: 'r2', t: 'block', n: ['تجهيز الحاسوب', 'Prepare the laptop'] }, { k: 'r3', t: 'link', n: ['إنشاء الحساب البريدي', 'Create the email account'] }], hl: 'r2' }
    ] },
    ex: ['الموارد البشرية ربطت دليل التهيئة ومهام تقنية المعلومات بكل مهمة تهيئة. صارت نورة تعرف من أول يوم ما ينتظرها ومن تسأل.', 'HR linked the onboarding guide and the IT tasks to every onboarding task. Noura knew from day one what was coming and whom to ask.'],
    wrong: ['كتابة «انظر المهمة الأخرى» في الوصف دون رابط.', 'Writing “see the other task” in the description with no link.'],
    right: ['استخدم Relationships: روابط وتبعيات ومستندات ظاهرة في قسم Related.', 'Use Relationships: links, dependencies and Docs visible in the Related section.'],
    quiz: { q: ['ماذا تعني علاقة «Waiting on»؟', 'What does a “Waiting on” relationship mean?'], o: [['هذه المهمة لا تبدأ قبل اكتمال الأخرى', 'This task cannot start until the other is done'], ['المهمتان متطابقتان', 'The two tasks are identical'], ['المهمة محذوفة', 'The task is deleted']], a: 0, why: ['هي تبعية: العمل ينتظر مهمة أخرى أولاً.', 'It is a dependency: the work waits for another task first.'] } }
];

const ADV_TOPICS = () => ADV_TOPICS_1.concat(ADV_TOPICS_2, ADV_TOPICS_3);
