/* ==========================================================================
   ClickUp 4.0 course, deep content part 1: Getting started and Building the
   project plan. For each topic id: a deeper explanation (more), an everyday
   comparison (like), an animated demo (scene + steps; each step is a caption
   plus changes to the simulated screen), a workplace example (ex), a common
   mistake and the right way (wrong / right), and a quick check (quiz).
   People and data are fictional training examples.
   ========================================================================== */
const C4_DEEP = {};
const C4R = (k, n, o) => Object.assign({ k, n }, o || {});
const C4D = (d, ar) => [d + ' ' + (ar || 'أكتوبر'), 'Oct ' + d];
const C4_FIB = () => [
  C4R('t1', ['مسح المواقع في صلالة', 'Survey sites in Salalah'], { st: 'done', who: 'salim', due: C4D(12), prio: 'high', region: ['صلالة', 'Salalah'] }),
  C4R('t2', ['تصميم مسار الألياف', 'Design the fibre route'], { st: 'prog', who: 'maryam', due: C4D(15), prio: 'urgent', region: ['صلالة', 'Salalah'] }),
  C4R('t3', ['طلب تصاريح البلدية', 'Request municipality permits'], { st: 'todo', who: 'khalid', due: C4D(18), prio: 'normal', region: ['ظفار', 'Dhofar'] }),
  C4R('t4', ['تجهيز فريق التمديد', 'Prepare the installation crew'], { st: 'todo', due: C4D(20), prio: 'low', region: ['صلالة', 'Salalah'] })
];
const C4_SECT = () => COURSE_SECTIONS.map(s => [s.ic, s.t, s.c]);

Object.assign(C4_DEEP, {
  intro: {
    more: ['الدورة مبنية كرحلة: كل قسم يضيف طبقة فوق التي قبلها. تبدأ بالحساب والواجهة، ثم تبني خطة مشروع حقيقية، ثم تتعلم رؤيتها بطرق مختلفة، ثم تضيف الذكاء الاصطناعي والتواصل والتقارير والأتمتة. في كل موضوع ستقرأ الفكرة، وتشاهد عرضاً متحركاً يريك أين تنقر بالضبط، ثم تجرب بنفسك وتختبر فهمك بسؤال قصير.', 'The course is built as a journey: each section adds a layer on top of the one before. You start with your account and the interface, then build a real project plan, then learn to see it in different ways, then add AI, communication, reporting and automation. In every topic you read the idea, watch an animation that shows exactly where to click, then try it yourself and check your understanding with a short question.'],
    like: ['مثل تعلم قيادة السيارة: أولاً تعرف لوحة القيادة، ثم تقود في شارع هادئ، ثم في الطريق السريع.', 'Like learning to drive: first you learn the dashboard, then you drive on a quiet street, then on the highway.'],
    demo: { scene: 'journey', steps: [
      { c: ['هذه خريطة رحلتك: 11 قسماً من البداية حتى الأتمتة.', 'This is your journey map: 11 sections from getting started to automations.'], items: C4_SECT(), lit: 0, hello: ['أهلاً أشجان! جاهزة للرحلة؟', 'Hi Ashjan! Ready for the journey?'] },
      { c: ['أولاً: الحساب والواجهة، لتعرف أين كل شيء.', 'First: your account and the interface, so you know where everything is.'], lit: 1, hl: 'stop0' },
      { c: ['ثم تبني خطة مشروع كاملة وتراها بطرق عرض مختلفة.', 'Then you build a full project plan and see it in different views.'], lit: 3, hl: 'stop2' },
      { c: ['بعدها الذكاء الاصطناعي والوكلاء، والتواصل مع الفريق ولوحات المعلومات.', 'Next come AI and agents, team communication and dashboards.'], lit: 6, hl: 'stop5' },
      { c: ['وأخيراً القوالب والإعدادات والأتمتة… لتعمل كالمحترفين.', 'Finally templates, settings and automations… so you work like a pro.'], lit: 11, hl: 'stop10', hello: ['كل موضوع: افهم ← شاهد ← جرّب ← اختبر نفسك.', 'Every topic: understand → watch → try → check yourself.'] }
    ] },
    ex: ['موظفة جديدة في قسم العمليات بدأت بموضوع واحد كل صباح لمدة 15 دقيقة. بعد أسبوعين كانت تدير قائمة طلبات فريقها كاملة في ClickUp.', 'A new employee in Operations did one topic every morning for 15 minutes. After two weeks she was running her team’s whole request List in ClickUp.'],
    wrong: ['قراءة كل الدورة في يوم واحد دون تطبيق.', 'Reading the whole course in one day without practising.'],
    right: ['موضوع واحد، ثم تطبيق فوري في ClickUp أو المختبر، ثم الموضوع التالي.', 'One topic, then practise it right away in ClickUp or the lab, then the next topic.'],
    quiz: { q: ['ما أفضل طريقة للاستفادة من هذه الدورة؟', 'What is the best way to get the most from this course?'], o: [['قراءة كل المواضيع مرة واحدة', 'Read every topic in one go'], ['موضوع واحد مع تطبيق عملي فوري', 'One topic at a time with hands-on practice'], ['مشاهدة العروض فقط', 'Only watch the animations']], a: 1, why: ['التعلم يثبت عندما تطبّق فوراً ما فهمته.', 'Learning sticks when you immediately apply what you understood.'] }
  },
  account: {
    more: ['في بيئة العمل لا تنشئ مساحة عمل خاصة بك؛ أنت تنضم إلى مساحة عمل الشركة. لذلك الخطوة الأهم هي الدعوة: يرسلها مسؤول مساحة العمل إلى بريدك، وعندما تقبلها تظهر لك المساحات المسموح لك برؤيتها فقط. إن كانت الشركة تستخدم الدخول الموحّد (SSO) فلن تحتاج كلمة مرور خاصة بـ ClickUp؛ تدخل بحساب الشركة نفسه. بعد الدخول، المنطقة الزمنية هي أهم إعداد: لو كانت خاطئة ستظهر المواعيد بساعة مختلفة وتصلك التذكيرات في وقت غير مناسب.', 'At work you do not create your own Workspace; you join the company’s. So the key step is the invite: a Workspace admin sends it to your email, and when you accept it you see only the Spaces you are allowed to see. If the company uses single sign-on (SSO), you need no separate ClickUp password; you sign in with your company account. After signing in, the time zone is the most important setting: if it is wrong, due times show at the wrong hour and reminders arrive at odd times.'],
    like: ['مثل بطاقة الدخول لمبنى الشركة: البطاقة نفسها (حسابك) تفتح فقط الأبواب المسموح لك بها.', 'Like your access card for the office building: the same card (your account) opens only the doors you are allowed through.'],
    demo: { scene: 'login', steps: [
      { c: ['افتح app.clickup.com واكتب بريد العمل.', 'Open app.clickup.com and type your work email.'], view: 'signin', hl: 'email', click: true, type: { k: 'email', x: 'ashjan@omantel.om' } },
      { c: ['إن كانت شركتك تستخدم الدخول الموحد، اختر «Continue with SSO».', 'If your company uses single sign-on, choose “Continue with SSO”.'], hl: 'sso', click: true, email: 'ashjan@omantel.om' },
      { c: ['تصلك دعوة من مسؤولة مساحة العمل. اضغط «Join Workspace».', 'An invite arrives from the Workspace admin. Click “Join Workspace”.'], view: 'invite', hl: 'join', click: true },
      { c: ['من My Settings أضف صورة واضحة؛ زملاؤك سيعرفونك بها.', 'In My Settings add a clear photo; colleagues will recognise you by it.'], view: 'profile', name: ['أشجان السناني', 'Ashjan Al Sinani'], hl: 'photo', click: true, photo: true },
      { c: ['اختر توقيت مسقط (GMT+4) حتى تظهر المواعيد صحيحة.', 'Choose the Muscat time zone (GMT+4) so due times are correct.'], hl: 'tz', click: true, type: { k: 'tz', x: 'Asia/Muscat (GMT+4)' } },
      { c: ['احفظ. حسابك جاهز!', 'Save. Your account is ready!'], tz: 'Asia/Muscat (GMT+4)', hl: 'save', click: true, toast: ['تم حفظ الإعدادات', 'Settings saved'] }
    ] },
    ex: ['خالد ضبط منطقته الزمنية على لندن بالخطأ، فكانت مهامه المستحقة الساعة 9 صباحاً تظهر له الساعة 5 صباحاً. تعديل المنطقة الزمنية حل المشكلة فوراً.', 'Khalid accidentally set his time zone to London, so tasks due at 9 a.m. showed as due at 5 a.m. for him. Fixing the time zone solved it instantly.'],
    wrong: ['إنشاء مساحة عمل شخصية جديدة والعمل فيها بعيداً عن الفريق.', 'Creating a new personal Workspace and working there, away from the team.'],
    right: ['قبول دعوة مساحة عمل الشركة والعمل داخلها، مع ضبط الصورة والمنطقة الزمنية.', 'Accepting the company Workspace invite and working inside it, with your photo and time zone set.'],
    quiz: { q: ['لماذا تهم المنطقة الزمنية في ClickUp؟', 'Why does the time zone matter in ClickUp?'], o: [['لتغيير لغة الواجهة', 'It changes the interface language'], ['لتظهر المواعيد والتذكيرات في الوقت الصحيح', 'So due dates and reminders show at the right time'], ['لتحديد صلاحياتك', 'It sets your permissions']], a: 1, why: ['كل المواعيد تُعرض حسب منطقتك الزمنية؛ الخطأ فيها يزيح كل الأوقات.', 'All dates are shown in your time zone; getting it wrong shifts every time.'] }
  },
  interface: {
    more: ['في ClickUp 4.0 الواجهة لها ثلاث مناطق ثابتة. شريط التنقل العام في الطرف (Home، Inbox، Docs، Chat، Dashboards، AI) يأخذك إلى الأدوات الكبرى. الشريط الجانبي يعرض هيكل عملك: المساحات والمجلدات والقوائم والمفضلة. والمنطقة الوسطى هي ما تعمل عليه الآن. في الأعلى يوجد البحث (Ctrl/Cmd+K) وزر Create لإنشاء أي شيء من أي مكان، وزر الذكاء الاصطناعي.', 'In ClickUp 4.0 the interface has three fixed areas. The global navigation at the edge (Home, Inbox, Docs, Chat, Dashboards, AI) takes you to the big tools. The sidebar shows the structure of your work: Spaces, Folders, Lists and Favorites. The middle area is what you are working on now. At the top you have search (Ctrl/Cmd+K), the Create button to make anything from anywhere, and the AI button.'],
    like: ['مثل مركز تسوق: الخريطة في المدخل (الشريط الجانبي)، والمحلات (القوائم)، ومكتب الاستعلامات (البحث).', 'Like a shopping mall: the map at the entrance (sidebar), the shops (Lists), and the information desk (search).'],
    demo: { scene: 'shell', steps: [
      { c: ['هذه واجهة ClickUp. لنتعرف على مناطقها الثلاث.', 'This is the ClickUp interface. Let’s meet its three areas.'], rows: C4_FIB(), sel: 'ls-plan', nav: 'home' },
      { c: ['شريط التنقل العام: الصفحة الرئيسية، صندوق الوارد، المستندات، المحادثات، اللوحات والذكاء الاصطناعي.', 'The global navigation: Home, Inbox, Docs, Chat, Dashboards and AI.'], hl: 'nav' },
      { c: ['الشريط الجانبي يعرض هيكل عملك: المساحات والمجلدات والقوائم.', 'The sidebar shows your work structure: Spaces, Folders and Lists.'], hl: 'side' },
      { c: ['في الوسط: القائمة التي تعمل عليها الآن ومهامها.', 'In the middle: the List you are working on now and its tasks.'], hl: 'main' },
      { c: ['اضغط Ctrl/Cmd+K وابحث بكلمة واحدة، مثل «تصاريح».', 'Press Ctrl/Cmd+K and search with one word, like “permits”.'], hl: 'search', click: true, searchOn: true, type: { k: 'searchText', x: ['تصاريح', 'permits'] } },
      { c: ['النتائج تظهر فوراً: مهام ومستندات وقوائم.', 'Results appear instantly: tasks, Docs and Lists.'], searchOn: true, searchText: ['تصاريح', 'permits'], results: [['checklist', ['طلب تصاريح البلدية', 'Request municipality permits']], ['doc', ['دليل التصاريح (Doc)', 'Permits guide (Doc)']], ['list', ['التخطيط', 'Planning']]], hl: 'res0' },
      { c: ['ثبّت القائمة التي تستخدمها كثيراً في المفضلة لتصل إليها بنقرة.', 'Pin the List you use most to Favorites to reach it in one click.'], searchOn: false, searchText: null, favs: [{ k: 'plan', n: ['التخطيط', 'Planning'] }], hl: 'fav-plan' }
    ] },
    ex: ['مريم كانت تفتح خمس قوائم لتجد مهمة واحدة. الآن تضغط Ctrl+K وتكتب كلمتين فتصل إليها في ثانيتين.', 'Maryam used to open five Lists to find one task. Now she presses Ctrl+K, types two words and gets there in two seconds.'],
    wrong: ['التنقل يدوياً بين المساحات والمجلدات للبحث عن مهمة.', 'Clicking through Spaces and Folders by hand to hunt for a task.'],
    right: ['استخدم البحث (Ctrl/Cmd+K) والمفضلة للوصول السريع.', 'Use search (Ctrl/Cmd+K) and Favorites for quick access.'],
    quiz: { q: ['أين تجد هيكل مساحاتك ومجلداتك وقوائمك؟', 'Where do you find the structure of your Spaces, Folders and Lists?'], o: [['في الشريط الجانبي', 'In the sidebar'], ['في زر Create', 'In the Create button'], ['في صندوق الوارد', 'In the Inbox']], a: 0, why: ['الشريط الجانبي هو خريطة عملك.', 'The sidebar is the map of your work.'] }
  },
  hierarchy: {
    more: ['كل مستوى في الهيكل له وظيفة واحدة. مساحة العمل (Workspace) تضم الجميع وتُضبط فيها إعدادات الشركة. المساحة (Space) تحدد من يرى ماذا وما الميزات المفعلة، لذلك تكون عادة لقسم أو فريق. المجلد (Folder) اختياري ويجمع قوائم مشروع واحد. القائمة (List) هي المكان الذي تعيش فيه المهام، ولها حالاتها وحقولها. والمهمة (Task) يمكن أن تحتوي مهام فرعية وقوائم تحقق. القاعدة الذهبية: ابنِ الهيكل حسب طريقة عمل فريقك، لا حسب الهيكل التنظيمي على الورق.', 'Each level of the structure has one job. The Workspace holds everyone and company settings. A Space decides who sees what and which features are on, so it is usually for a department or team. A Folder is optional and groups the Lists of one project. A List is where tasks live, with its own statuses and fields. A Task can contain subtasks and checklists. The golden rule: build the structure around how your team works, not around the org chart on paper.'],
    like: ['خزانة ملفات: الشركة هي الغرفة، والمساحة درج، والمجلد ملف، والقائمة ورقة، والمهمة سطر في الورقة.', 'A filing cabinet: the company is the room, a Space is a drawer, a Folder is a file, a List is a sheet, and a Task is a line on the sheet.'],
    demo: { scene: 'tree', steps: [
      { c: ['لنبنِ الهيكل من الأعلى. في القمة: مساحة العمل، أي الشركة كلها.', 'Let’s build the structure from the top. At the top: the Workspace, the whole company.'], level: 'ws', nodes: [{ k: 'n1', l: 0, t: 'ws', n: ['Omantel', 'Omantel'] }], hl: 'lv-ws' },
      { c: ['داخلها مساحة (Space) لكل قسم، مثل «العمليات».', 'Inside it, a Space for each department, such as “Operations”.'], level: 'space', nodes: [{ k: 'n1', l: 0, t: 'ws', n: ['Omantel', 'Omantel'] }, { k: 'n2', l: 1, t: 'space', n: ['العمليات', 'Operations'] }], hl: 'n2' },
      { c: ['داخل المساحة مجلد (Folder) للمشروع.', 'Inside the Space, a Folder for the project.'], level: 'folder', nodes: [{ k: 'n1', l: 0, t: 'ws', n: ['Omantel', 'Omantel'] }, { k: 'n2', l: 1, t: 'space', n: ['العمليات', 'Operations'] }, { k: 'n3', l: 2, t: 'folder', n: ['إطلاق الألياف - صلالة', 'Fibre launch - Salalah'] }], hl: 'n3' },
      { c: ['داخل المجلد قوائم (Lists)، واحدة لكل مرحلة.', 'Inside the Folder, Lists, one per stage.'], level: 'list', nodes: [{ k: 'n1', l: 0, t: 'ws', n: ['Omantel', 'Omantel'] }, { k: 'n2', l: 1, t: 'space', n: ['العمليات', 'Operations'] }, { k: 'n3', l: 2, t: 'folder', n: ['إطلاق الألياف - صلالة', 'Fibre launch - Salalah'] }, { k: 'n4', l: 3, t: 'list', n: ['التخطيط', 'Planning'] }, { k: 'n5', l: 3, t: 'list', n: ['التنفيذ', 'Delivery'] }], hl: 'n4' },
      { c: ['وداخل القائمة تعيش المهام: العمل الفعلي الذي ينجزه شخص.', 'And inside the List live the tasks: the actual work one person does.'], level: 'task', nodes: [{ k: 'n1', l: 0, t: 'ws', n: ['Omantel', 'Omantel'] }, { k: 'n2', l: 1, t: 'space', n: ['العمليات', 'Operations'] }, { k: 'n3', l: 2, t: 'folder', n: ['إطلاق الألياف - صلالة', 'Fibre launch - Salalah'] }, { k: 'n4', l: 3, t: 'list', n: ['التخطيط', 'Planning'] }, { k: 'n6', l: 4, t: 'task', n: ['مسح المواقع', 'Survey sites'] }, { k: 'n7', l: 4, t: 'task', n: ['طلب التصاريح', 'Request permits'] }, { k: 'n5', l: 3, t: 'list', n: ['التنفيذ', 'Delivery'] }], hl: 'n6' }
    ] },
    ex: ['قسم خدمة العملاء أنشأ مساحة واحدة، ومجلداً لكل حملة، وقوائم «الطلبات الواردة» و«المتابعة» و«المغلقة». أصبح كل موظف يعرف أين يضع الطلب الجديد دون سؤال.', 'The customer service team created one Space, a Folder per campaign, and Lists for “Incoming”, “Follow-up” and “Closed”. Everyone now knows where a new request goes without asking.'],
    wrong: ['إنشاء مساحة جديدة لكل مشروع صغير حتى يمتلئ الشريط الجانبي بعشرات المساحات.', 'Creating a new Space for every small project until the sidebar is full of dozens of Spaces.'],
    right: ['مساحة لكل قسم، ومجلد لكل مشروع، وقائمة لكل مرحلة أو نوع عمل.', 'A Space per department, a Folder per project, and a List per stage or kind of work.'],
    quiz: { q: ['أين تعيش المهام في ClickUp؟', 'Where do tasks live in ClickUp?'], o: [['داخل المجلد مباشرة', 'Directly inside a Folder'], ['داخل القائمة', 'Inside a List'], ['داخل مساحة العمل', 'Inside the Workspace']], a: 1, why: ['المهام توضع دائماً داخل قائمة؛ المجلد يجمع القوائم فقط.', 'Tasks always sit inside a List; a Folder only groups Lists.'] }
  },
  structure1: {
    more: ['عند إنشاء مساحة جديدة تقرر ثلاثة أشياء مهمة: الاسم واللون (ليميزها الجميع بسرعة)، ومن يدخلها (كل مساحة العمل أم أشخاص محددون فقط)، والميزات (ClickApps) مثل تتبع الوقت والأولويات. هذه الإعدادات تنتقل إلى كل ما بداخلها، لذلك ضبطها مرة واحدة في المساحة يوفر تكرارها في كل قائمة. ثم تضيف المجلد باسم المشروع ليجمع قوائمه.', 'When you create a new Space you decide three important things: the name and colour (so everyone spots it quickly), who can enter (the whole Workspace or specific people only), and the features (ClickApps) such as time tracking and priorities. These settings flow down to everything inside, so setting them once on the Space saves repeating them in every List. Then you add a Folder with the project name to hold its Lists.'],
    like: ['مثل تجهيز غرفة اجتماعات للمشروع: تختار اسم الغرفة، ومن يحمل مفتاحها، والأدوات الموجودة فيها.', 'Like setting up a project room: you choose the room’s name, who holds its key, and which tools are inside.'],
    demo: { scene: 'list', steps: [
      { c: ['في الشريط الجانبي اضغط «+» بجانب Spaces.', 'In the sidebar click “+” next to Spaces.'], tree: [{ k: 'sp-ops', l: 0, t: 'space', n: ['العمليات', 'Operations'] }], rows: [], cols: ['assignee', 'due'], hl: 'addSpace', click: true },
      { c: ['سمِّ المساحة باسم الفريق، مثل «فريق الألياف»، واختر لوناً وأيقونة.', 'Name the Space after the team, like “Fibre team”, and pick a colour and icon.'], tree: [{ k: 'sp-ops', l: 0, t: 'space', n: ['العمليات', 'Operations'] }, { k: 'sp-fib', l: 0, t: 'space', n: ['فريق الألياف', 'Fibre team'] }], hl: 'sp-fib', toast: ['اختر: كل مساحة العمل أو أعضاء محددون', 'Choose: whole Workspace or specific members'] },
      { c: ['داخل المساحة اضغط «+» ثم Folder.', 'Inside the Space click “+”, then Folder.'], hl: 'sp-fib', click: true, sel: 'sp-fib' },
      { c: ['سمِّ المجلد باسم المشروع: «إطلاق الألياف - صلالة».', 'Name the Folder after the project: “Fibre launch - Salalah”.'], tree: [{ k: 'sp-ops', l: 0, t: 'space', n: ['العمليات', 'Operations'] }, { k: 'sp-fib', l: 0, t: 'space', n: ['فريق الألياف', 'Fibre team'] }, { k: 'fd-fib', l: 1, t: 'folder', n: ['إطلاق الألياف - صلالة', 'Fibre launch - Salalah'] }], hl: 'fd-fib', sel: 'fd-fib', title: ['إطلاق الألياف - صلالة', 'Fibre launch - Salalah'] },
      { c: ['أصبح للمشروع مكان واحد واضح. الخطوة التالية: القوائم.', 'The project now has one clear home. Next step: the Lists.'], toast: ['تم إنشاء المجلد', 'Folder created'] }
    ] },
    ex: ['فريق التسويق جعل مساحته خاصة بأعضائه فقط، لأن خطط الحملات لا تُعلن قبل وقتها. المجلدات داخلها ورثت الخصوصية تلقائياً.', 'The marketing team made its Space private to its members, because campaign plans are confidential until launch. The Folders inside inherited the privacy automatically.'],
    wrong: ['أسماء مثل «مشروع 1» أو «جديد» لا يفهمها أحد بعد شهر.', 'Names like “Project 1” or “New” that nobody understands a month later.'],
    right: ['أسماء تصف المحتوى: «إطلاق الألياف - صلالة 2026».', 'Names that describe the contents: “Fibre launch - Salalah 2026”.'],
    quiz: { q: ['لماذا نضبط الإعدادات على مستوى المساحة؟', 'Why set things up at the Space level?'], o: [['لأنها تنتقل إلى كل ما بداخلها', 'Because they flow down to everything inside'], ['لأن القوائم لا تقبل إعدادات', 'Because Lists cannot have settings'], ['لأنها تسرّع الإنترنت', 'Because it speeds up the internet']], a: 0, why: ['ما يُضبط في المساحة تورثه المجلدات والقوائم، فلا تكرر العمل.', 'What you set on the Space is inherited by its Folders and Lists, so you do not repeat work.'] }
  },
  structure2: {
    more: ['القوائم تقسم المشروع إلى أجزاء يمكن إدارتها. يمكن أن تكون حسب المرحلة (تخطيط، تنفيذ، إطلاق) أو حسب نوع العمل (طلبات، أعطال، تقارير). ولكل قائمة حالات تصف رحلة المهمة من البداية إلى النهاية. الحالات ليست مجرد ألوان: هي أساس اللوحات والتقارير والأتمتة. لذلك اتفقوا كفريق على معنى كل حالة، مثلاً «مراجعة» تعني أن العمل انتهى وينتظر موافقة المشرف.', 'Lists split the project into manageable parts. They can follow stages (planning, delivery, launch) or kinds of work (requests, faults, reports). Each List has statuses that describe a task’s journey from start to finish. Statuses are not just colours: they power boards, reports and automations. So agree as a team on what each status means, for example “Review” means the work is finished and waiting for the supervisor’s approval.'],
    like: ['الحالات مثل محطات القطار: كل مهمة تمر بها بالترتيب حتى تصل إلى المحطة الأخيرة «مكتمل».', 'Statuses are like train stations: each task passes through them in order until it reaches the last stop, “Complete”.'],
    demo: { scene: 'board', steps: [
      { c: ['أنشأنا قائمة «التخطيط». تبدأ بحالتين فقط: TO DO وCOMPLETE.', 'We created the “Planning” List. It starts with just two statuses: TO DO and COMPLETE.'], title: ['التخطيط', 'Planning'], tree: TREE_C4(), sel: 'ls-plan', cols: [{ st: 'todo', cards: [C4R('b1', ['مسح المواقع', 'Survey sites'], { who: 'salim' }), C4R('b2', ['تصميم المسار', 'Design the route'], { who: 'maryam' })] }, { st: 'done', cards: [] }] },
      { c: ['من إعدادات القائمة ← Statuses نضيف «IN PROGRESS» لنعرف ما يُعمل عليه الآن.', 'From List settings → Statuses we add “IN PROGRESS” to see what is being worked on now.'], cols: [{ st: 'todo', cards: [C4R('b2', ['تصميم المسار', 'Design the route'], { who: 'maryam' })] }, { st: 'prog', cards: [C4R('b1', ['مسح المواقع', 'Survey sites'], { who: 'salim' })] }, { st: 'done', cards: [] }], hl: 'col-prog' },
      { c: ['ونضيف «REVIEW»: العمل انتهى وينتظر موافقة المشرف.', 'And we add “REVIEW”: the work is done and waiting for the supervisor’s approval.'], cols: [{ st: 'todo', cards: [C4R('b2', ['تصميم المسار', 'Design the route'], { who: 'maryam' })] }, { st: 'prog', cards: [] }, { st: 'rev', cards: [C4R('b1', ['مسح المواقع', 'Survey sites'], { who: 'salim' })] }, { st: 'done', cards: [] }], hl: 'col-rev' },
      { c: ['بعد الموافقة تنتقل المهمة إلى COMPLETE. الرحلة واضحة للجميع.', 'After approval the task moves to COMPLETE. The journey is clear to everyone.'], cols: [{ st: 'todo', cards: [C4R('b2', ['تصميم المسار', 'Design the route'], { who: 'maryam' })] }, { st: 'prog', cards: [] }, { st: 'rev', cards: [] }, { st: 'done', cards: [C4R('b1', ['مسح المواقع', 'Survey sites'], { who: 'salim' })] }], hl: 'b1' },
      { c: ['احفظ مجموعة الحالات كقالب لتستخدمها في قوائم أخرى.', 'Save the status set as a template to reuse in other Lists.'], toast: ['تم حفظ قالب الحالات', 'Status template saved'] }
    ] },
    ex: ['فريق الصيانة أضاف حالة «بانتظار قطع الغيار». فجأة ظهر في اللوحة أن ثلث الأعطال متوقفة بسبب القطع، فتحركت الإدارة لحل المشكلة.', 'The maintenance team added a “Waiting for parts” status. Suddenly the board showed a third of the faults were stuck on parts, and management acted to fix it.'],
    wrong: ['12 حالة متشابهة لا يعرف أحد الفرق بينها.', 'Twelve similar statuses that nobody can tell apart.'],
    right: ['4 إلى 5 حالات واضحة متفق على معناها.', 'Four or five clear statuses with an agreed meaning.'],
    quiz: { q: ['ماذا تعني حالة «REVIEW» في مثالنا؟', 'What does the “REVIEW” status mean in our example?'], o: [['لم يبدأ العمل بعد', 'Work has not started yet'], ['العمل انتهى وينتظر الموافقة', 'The work is done and waiting for approval'], ['المهمة أُلغيت', 'The task was cancelled']], a: 1, why: ['الفريق اتفق أن المراجعة تعني انتظار موافقة المشرف.', 'The team agreed that Review means waiting for the supervisor’s approval.'] }
  },
  subtasks: {
    more: ['المهمة الفرعية مهمة كاملة تعيش داخل مهمة أكبر: لها مسؤول وحالة وموعد، وتظهر في «مهامي» لمن أُسندت إليه. لذلك هي مثالية عندما يتقاسم عدة أشخاص عملاً واحداً. أما قائمة التحقق (Checklist) فهي خطوات بسيطة داخل المهمة، تُعلَّم بصح ولا تظهر كمهام مستقلة. وتستطيع رؤية تقدم المهمة الكبيرة من عدد المهام الفرعية المكتملة.', 'A subtask is a full task living inside a bigger task: it has an assignee, a status and a date, and it shows up in the My Tasks of whoever it is assigned to. That makes it ideal when several people share one piece of work. A checklist is simple steps inside the task that you tick off; they do not appear as separate tasks. You can see the big task’s progress from how many subtasks are complete.'],
    like: ['المهمة الكبيرة وجبة كاملة، والمهام الفرعية أطباقها، وكل طبق يطبخه شخص مختلف.', 'The big task is a full meal, the subtasks are its dishes, and each dish is cooked by a different person.'],
    demo: { scene: 'task', steps: [
      { c: ['افتح المهمة الكبيرة: «تجهيز موقع البرج».', 'Open the big task: “Prepare the tower site”.'], title: ['تجهيز موقع البرج', 'Prepare the tower site'], st: 'prog', who: ['maryam'], due: C4D(25), prio: 'high', subs: [], act: [['أنشأت مريم المهمة', 'Maryam created this task']] },
      { c: ['اضغط «Add subtask» واكتب الجزء الأول.', 'Click “Add subtask” and type the first part.'], hl: 'addSub', click: true, type: { k: 'newSub', x: ['استخراج التصريح', 'Get the permit'] } },
      { c: ['أضف بقية الأجزاء. كل جزء مهمة مستقلة.', 'Add the other parts. Each part is its own task.'], subs: [C4R('s1', ['استخراج التصريح', 'Get the permit']), C4R('s2', ['توصيل الكهرباء', 'Connect power']), C4R('s3', ['تركيب الهوائي', 'Install the antenna'])], newSub: null, hl: 's3' },
      { c: ['أسند كل مهمة فرعية لشخص وحدد موعدها.', 'Assign each subtask to a person and give it a date.'], subs: [C4R('s1', ['استخراج التصريح', 'Get the permit'], { who: 'khalid', due: C4D(18) }), C4R('s2', ['توصيل الكهرباء', 'Connect power'], { who: 'salim', due: C4D(21) }), C4R('s3', ['تركيب الهوائي', 'Install the antenna'], { who: 'maryam', due: C4D(24) })], hl: 's2' },
      { c: ['وعندما ينجز خالد جزءه، يظهر التقدم في المهمة الكبيرة.', 'When Khalid finishes his part, the progress shows on the big task.'], subs: [C4R('s1', ['استخراج التصريح', 'Get the permit'], { who: 'khalid', due: C4D(18), st: 'done' }), C4R('s2', ['توصيل الكهرباء', 'Connect power'], { who: 'salim', due: C4D(21), st: 'prog' }), C4R('s3', ['تركيب الهوائي', 'Install the antenna'], { who: 'maryam', due: C4D(24) })], hl: 's1', toast: ['1 من 3 مهام فرعية مكتملة', '1 of 3 subtasks complete'] }
    ] },
    ex: ['مهمة «إعداد تقرير الربع» كانت متأخرة دائماً. بعد تقسيمها إلى 4 مهام فرعية لكل قسم، أصبح واضحاً أي قسم يتأخر في تسليم أرقامه.', 'The “Quarterly report” task was always late. After splitting it into four subtasks, one per department, it became clear which department was late with its numbers.'],
    wrong: ['مهمة واحدة ضخمة باسم «المشروع كله» مسندة لخمسة أشخاص.', 'One huge task called “The whole project” assigned to five people.'],
    right: ['مهمة كبيرة بمهام فرعية، لكل منها مسؤول واحد وموعد.', 'A big task with subtasks, each with one owner and a date.'],
    quiz: { q: ['متى تستخدم مهمة فرعية بدل قائمة تحقق؟', 'When do you use a subtask instead of a checklist?'], o: [['عندما يعمل عليها شخص آخر أو تحتاج موعداً خاصاً', 'When someone else works on it or it needs its own date'], ['عندما تكون الخطوة صغيرة جداً', 'When the step is very small'], ['دائماً، قوائم التحقق قديمة', 'Always; checklists are outdated']], a: 0, why: ['المهمة الفرعية لها مسؤول وموعد وحالة؛ قائمة التحقق لا.', 'A subtask has its own owner, date and status; a checklist item does not.'] }
  },
  invite: {
    more: ['هناك فرق بين أن يكون الزميل عضواً في مساحة العمل وبين أن يرى قائمتك. الدعوة تجعله عضواً، والمشاركة (Share) تعطيه الوصول إلى مكان محدد، والإسناد (Assignee) يجعله مسؤولاً عن مهمة. عندما تسند مهمة يصله إشعار، وتظهر في صفحة «مهامي» الخاصة به، فلا يحتاج أن يبحث عنها. والمتابعون (Watchers) يتلقون التحديثات دون أن يكونوا مسؤولين.', 'There is a difference between a colleague being a member of the Workspace and seeing your List. An invite makes them a member, Share gives them access to a specific place, and Assignee makes them responsible for a task. When you assign a task they are notified and it appears in their My Tasks, so they do not have to look for it. Watchers get updates without being responsible.'],
    like: ['الدعوة تعطي الزميل مفتاح المبنى، والمشاركة تفتح له غرفة المشروع، والإسناد يضع المهمة على مكتبه.', 'The invite gives a colleague the building key, sharing opens the project room, and assigning puts the task on their desk.'],
    demo: { scene: 'list', steps: [
      { c: ['يدعو المسؤول خالد إلى مساحة العمل ببريده.', 'An admin invites Khalid to the Workspace by email.'], rows: C4_FIB().map(r => r.k === 't3' ? Object.assign(r, { who: null }) : r), cols: ['assignee', 'due', 'prio'], hl: 'ws', click: true, toast: ['تم إرسال الدعوة إلى خالد', 'Invite sent to Khalid'] },
      { c: ['مهمة «طلب تصاريح البلدية» بلا مسؤول. اضغط خانة Assignee.', 'The “Request municipality permits” task has no owner. Click its Assignee cell.'], hl: 't3-assignee', click: true },
      { c: ['اختر خالد من القائمة.', 'Pick Khalid from the list.'], pop: 'assignee', hl: 'p-khalid', click: true },
      { c: ['أصبح خالد المسؤول، ووصله إشعار، وظهرت المهمة في «مهامي» عنده.', 'Khalid is now the owner, he got a notification, and the task is in his My Tasks.'], rows: C4_FIB(), hl: 't3-assignee', toast: ['تم إشعار خالد', 'Khalid was notified'] }
    ] },
    ex: ['سالم كان يرسل المهام عبر البريد ثم يسأل «هل وصلتك؟». بعد الإسناد في ClickUp أصبح يرى أن المهمة عند زميله وحالتها «قيد العمل» دون أي سؤال.', 'Salim used to email tasks and then ask “did you get it?”. With assigning in ClickUp he now sees the task is with his colleague and In Progress without asking.'],
    wrong: ['إسناد المهمة لخمسة أشخاص «حتى يتابع الجميع».', 'Assigning a task to five people “so everyone follows”.'],
    right: ['مسؤول واحد، والبقية متابعون (Watchers).', 'One owner, and the others as watchers.'],
    quiz: { q: ['ماذا يحدث عندما تسند مهمة لزميل؟', 'What happens when you assign a task to a colleague?'], o: [['يصبح مالك مساحة العمل', 'They become the Workspace owner'], ['يصله إشعار وتظهر في «مهامي» عنده', 'They are notified and it appears in their My Tasks'], ['تُحذف المهمة من قائمتك', 'The task is removed from your List']], a: 1, why: ['الإسناد يحدد المسؤول ويوصل المهمة إليه مباشرة.', 'Assigning sets the owner and delivers the task straight to them.'] }
  },
  dates: {
    more: ['تاريخ البدء يقول متى يبدأ العمل، وتاريخ الاستحقاق متى يجب أن ينتهي. معاً يحددان طول المهمة، فتظهر كشريط في غانت والخط الزمني، وتحسب عبء العمل. المهمة المتأخرة يصبح تاريخها أحمر تلقائياً. وللأعمال الدورية مثل التقرير الأسبوعي فعّل التكرار (Recurring): عند إغلاق المهمة تُنشأ نسخة جديدة بالموعد التالي.', 'The start date says when work begins and the due date when it must end. Together they set the task’s length, so it shows as a bar in Gantt and Timeline and counts in workload. A late task’s date turns red automatically. For routine work like a weekly report, turn on Recurring: when you close the task, a new copy is created with the next date.'],
    like: ['مثل حجز تذكرة طيران: موعد الإقلاع (البدء) وموعد الوصول (الاستحقاق).', 'Like booking a flight: the departure time (start) and the arrival time (due).'],
    demo: { scene: 'list', steps: [
      { c: ['مهمة «تجهيز فريق التمديد» بلا موعد. اضغط خانة التاريخ.', 'The “Prepare the installation crew” task has no date. Click its date cell.'], rows: C4_FIB().map(r => r.k === 't4' ? Object.assign(r, { due: null }) : r), cols: ['assignee', 'due', 'prio'], hl: 't4-due', click: true },
      { c: ['اختر يوم الاستحقاق من التقويم.', 'Pick the due day on the calendar.'], pop: 'date', hl: 'd20', click: true },
      { c: ['ظهر الموعد في القائمة، وسيظهر في التقويم وغانت أيضاً.', 'The date shows in the List, and will appear in Calendar and Gantt too.'], rows: C4_FIB(), hl: 't4-due' },
      { c: ['للأعمال الدورية فعّل «Recurring» من نفس النافذة.', 'For routine work turn on “Recurring” in the same window.'], pop: 'date', pick: 20, hl: 'rec', click: true, recurring: true },
      { c: ['وعندما يفوت الموعد يصبح أحمر تلقائياً لتنتبه.', 'And when a date passes it turns red automatically so you notice.'], recurring: false, rows: C4_FIB().map(r => r.k === 't2' ? Object.assign(r, { late: true }) : r), hl: 't2-due' }
    ] },
    ex: ['التقرير الأسبوعي في قسم الشبكات كان يُنسى كل شهر مرة. بعد تفعيل التكرار كل أحد، تظهر المهمة تلقائياً كل أسبوع في «مهامي».', 'The network team’s weekly report was forgotten about once a month. With recurrence every Sunday, the task appears automatically every week in My Tasks.'],
    wrong: ['كتابة الموعد في اسم المهمة: «التقرير – الخميس».', 'Writing the date in the task name: “Report – Thursday”.'],
    right: ['استخدم حقل التاريخ نفسه، ليظهر في التقويم ويتحول للأحمر عند التأخر.', 'Use the date field itself, so it shows on the calendar and turns red when late.'],
    quiz: { q: ['ما فائدة خيار Recurring؟', 'What does the Recurring option do?'], o: [['يحذف المهمة بعد إنجازها', 'Deletes the task after it is done'], ['ينشئ نسخة جديدة بالموعد التالي تلقائياً', 'Automatically creates a new copy with the next date'], ['يرسل المهمة لكل الفريق', 'Sends the task to the whole team']], a: 1, why: ['التكرار مثالي للأعمال الدورية مثل التقارير الأسبوعية.', 'Recurrence is perfect for routine work like weekly reports.'] }
  },
  columns: {
    more: ['كل عمود في عرض القائمة هو حقل من حقول المهمة. بعضها جاهز (المسؤول، الموعد، الأولوية، الوقت المقدّر) وبعضها تنشئه أنت كحقل مخصص. عندما تضيف عموداً ترى المعلومة لكل المهام في صف واحد وتستطيع تعديلها مباشرة دون فتح المهمة. وترتيب الأعمدة وإظهارها يُحفظ مع العرض، فيرى الفريق نفس الصورة.', 'Each column in List view is one of the task’s fields. Some are built in (assignee, due date, priority, time estimate) and some you create as Custom Fields. When you add a column you see that information for every task in one row and can edit it directly without opening the task. The order and visibility of columns are saved with the view, so the team sees the same picture.'],
    like: ['مثل إضافة عمود في جدول Excel: فجأة ترى معلومة جديدة لكل الصفوف.', 'Like adding a column in an Excel sheet: suddenly you see a new piece of information for every row.'],
    demo: { scene: 'list', steps: [
      { c: ['القائمة تعرض الاسم والمسؤول والموعد فقط. نريد رؤية الأولوية.', 'The List shows only name, assignee and due date. We want to see priority.'], rows: C4_FIB(), cols: ['assignee', 'due'] },
      { c: ['اضغط «+» في نهاية رؤوس الأعمدة.', 'Click “+” at the end of the column headers.'], hl: 'addCol', click: true },
      { c: ['ظهر عمود Priority لكل المهام دفعة واحدة.', 'A Priority column appears for every task at once.'], cols: ['assignee', 'due', 'prio'], hl: 'col-prio' },
      { c: ['أضف حقلاً مخصصاً من نوع Dropdown باسم «المنطقة».', 'Add a Dropdown Custom Field called “Region”.'], hl: 'addCol', click: true, pop: 'col' },
      { c: ['الآن ترى المنطقة لكل مهمة، ويمكنك تعديلها مباشرة.', 'Now you see the region of every task and can edit it directly.'], cols: ['assignee', 'due', 'prio', 'region'], hl: 'col-region', dirty: true },
      { c: ['احفظ العرض ليرى الفريق نفس الأعمدة.', 'Save the view so the team sees the same columns.'], hl: 'saveView', click: true, toast: ['تم حفظ العرض', 'View saved'] }
    ] },
    ex: ['مشرفة المبيعات أضافت عمود «قيمة الصفقة». أصبحت ترى في نظرة واحدة أي الطلبات أكبر قيمة وتعطيها الأولوية.', 'The sales supervisor added a “Deal value” column. She now sees at a glance which requests are worth most and prioritises them.'],
    wrong: ['إظهار 15 عموداً حتى لا يمكن قراءة اسم المهمة.', 'Showing 15 columns until the task name is unreadable.'],
    right: ['3 إلى 5 أعمدة تحتاجها يومياً، والباقي مخفي.', 'Three to five columns you need daily, with the rest hidden.'],
    quiz: { q: ['ماذا يمثل كل عمود في عرض القائمة؟', 'What does each column in List view represent?'], o: [['حقلاً من حقول المهمة', 'One of the task’s fields'], ['قائمة مختلفة', 'A different List'], ['شخصاً في الفريق', 'A person on the team']], a: 0, why: ['الأعمدة تعرض حقول المهام، الجاهزة والمخصصة.', 'Columns show task fields, both built-in and custom.'] }
  },
  grouping: {
    more: ['التجميع لا يغيّر المهام؛ يغير طريقة ترتيبها على الشاشة. التجميع حسب الحالة يريك مراحل العمل، وحسب المسؤول يريك حمل كل شخص، وحسب الأولوية يرفع العاجل للأعلى، وحسب الموعد يفصل المتأخر عن القادم. ويمكنك طي المجموعات التي لا تهمك لتركز على المهم فقط.', 'Grouping does not change the tasks; it changes how they are arranged on screen. Grouping by status shows the stages of work, by assignee shows each person’s load, by priority lifts the urgent to the top, and by due date separates the late from the upcoming. You can collapse groups you do not care about and focus only on what matters.'],
    like: ['مثل ترتيب الملابس في الخزانة: حسب اللون أو حسب الموسم. الملابس نفسها، لكن ترتيبها يجعلك تجد ما تريد.', 'Like sorting clothes in a wardrobe: by colour or by season. Same clothes, but the arrangement helps you find what you need.'],
    demo: { scene: 'list', steps: [
      { c: ['المهام الآن غير مجمعة.', 'The tasks are not grouped yet.'], rows: C4_FIB().concat([C4R('t5', ['تحديث خريطة الشبكة', 'Update the network map'], { st: 'prog', who: 'salim', due: C4D(16), prio: 'high' })]), cols: ['assignee', 'due', 'prio'] },
      { c: ['اضغط Group.', 'Click Group.'], hl: 'grp', click: true },
      { c: ['اختر Assignee.', 'Choose Assignee.'], pop: 'group', hl: 'gp-assignee', click: true },
      { c: ['انظر: المهام تحركت تحت اسم كل شخص. سالم عنده مهمتان.', 'Look: the tasks moved under each person’s name. Salim has two.'], group: 'assignee', hl: 'g-salim' },
      { c: ['جرّب التجميع حسب الحالة لترى مراحل العمل.', 'Try grouping by status to see the stages of work.'], group: 'status', hl: 'g-prog' }
    ] },
    ex: ['في اجتماع الأحد، يفتح قائد الفريق القائمة مجمعة حسب المسؤول. كل شخص يرى مهامه ويحدّث حالتها في دقيقتين.', 'In the Sunday meeting the team lead opens the List grouped by assignee. Everyone sees their tasks and updates them in two minutes.'],
    wrong: ['التمرير في قائمة طويلة بحثاً عن مهام شخص معين.', 'Scrolling a long List looking for one person’s tasks.'],
    right: ['جمّع حسب المسؤول ثم اطوِ المجموعات الأخرى.', 'Group by assignee, then collapse the other groups.'],
    quiz: { q: ['ماذا يفعل التجميع (Group by)؟', 'What does Group by do?'], o: [['يحذف المهام المكتملة', 'Deletes completed tasks'], ['يرتب المهام في مجموعات دون تغييرها', 'Arranges tasks into groups without changing them'], ['ينقل المهام إلى قوائم أخرى', 'Moves tasks to other Lists']], a: 1, why: ['التجميع طريقة عرض فقط؛ المهام نفسها لا تتغير.', 'Grouping is only a way of viewing; the tasks themselves do not change.'] }
  },
  filter: {
    more: ['الفلتر يجيب عن سؤال محدد: «ما مهامي العاجلة؟» أو «ما الذي يستحق هذا الأسبوع؟». تضيف شرطاً أو أكثر، وكل شرط يضيق النتائج. والفلاتر يمكن حفظها مع العرض، فتصبح لديك «نظارات» جاهزة. أما البحث فيجد أي شيء في كل مساحة العمل بكلمة واحدة، حتى داخل المستندات والتعليقات.', 'A filter answers a specific question: “What are my urgent tasks?” or “What is due this week?”. You add one or more rules, and each rule narrows the results. Filters can be saved with the view, so you have ready-made “lenses”. Search, on the other hand, finds anything in the whole Workspace with a single word, even inside Docs and comments.'],
    like: ['الفلتر مثل مصفاة القهوة: يمر فقط ما تحتاجه.', 'A filter is like a coffee filter: only what you need gets through.'],
    demo: { scene: 'list', steps: [
      { c: ['عندنا مهام كثيرة لأشخاص مختلفين.', 'We have many tasks for different people.'], rows: C4_FIB().concat([C4R('t5', ['مراجعة عقد المورد', 'Review the vendor contract'], { st: 'todo', who: 'me', due: C4D(14), prio: 'urgent' }), C4R('t6', ['تحديث سجل المخاطر', 'Update the risk log'], { st: 'todo', who: 'me', due: C4D(22), prio: 'low' })]), cols: ['assignee', 'due', 'prio'] },
      { c: ['اضغط Filter وأضف شرط: المسؤول = أنا.', 'Click Filter and add a rule: Assignee = me.'], hl: 'flt', click: true, pop: 'filter' },
      { c: ['أضف شرطاً ثانياً: الأولوية = عاجل.', 'Add a second rule: Priority = Urgent.'], pop: 'filter', rule2: true, hl: 'addRule', click: true },
      { c: ['النتيجة: مهمة واحدة عاجلة لك. هذا ما تبدأ به اليوم.', 'The result: one urgent task for you. That is what you start with today.'], rows: [C4R('t5', ['مراجعة عقد المورد', 'Review the vendor contract'], { st: 'todo', who: 'me', due: C4D(14), prio: 'urgent' })], filter: ['2 فلتر', '2 filters'], hl: 't5' },
      { c: ['وللبحث في كل مكان: Ctrl/Cmd+K واكتب كلمة.', 'To search everywhere: Ctrl/Cmd+K and type a word.'], hl: 'search', click: true, searchOn: true, type: { k: 'searchText', x: ['عقد', 'contract'] } }
    ] },
    ex: ['مديرة المشروع حفظت عرضاً باسم «متأخرات هذا الأسبوع» بفلتر جاهز. كل خميس تفتحه وتعرف ما يحتاج تدخلاً.', 'The project manager saved a view called “This week’s overdue” with a ready filter. Every Thursday she opens it and knows what needs attention.'],
    wrong: ['إعادة بناء نفس الفلتر يدوياً كل يوم.', 'Rebuilding the same filter by hand every day.'],
    right: ['احفظ الفلتر مع العرض، أو استخدم زر «Me» للمهام الخاصة بك.', 'Save the filter with the view, or use the “Me” button for your own tasks.'],
    quiz: { q: ['ماذا يحدث عند إضافة شرط ثانٍ للفلتر؟', 'What happens when you add a second filter rule?'], o: [['تزيد النتائج', 'More results appear'], ['تضيق النتائج أكثر', 'The results narrow further'], ['يُلغى الشرط الأول', 'The first rule is removed']], a: 1, why: ['كل شرط إضافي يجب أن ينطبق أيضاً، فتقل النتائج.', 'Every extra rule must also match, so fewer results remain.'] }
  },
  bulk: {
    more: ['الإجراءات الجماعية تطبق نفس التغيير على عدة مهام دفعة واحدة. حدد المربعات بجانب المهام (أو حدد الكل)، فيظهر شريط في الأسفل يتيح تغيير المسؤول أو الحالة أو التواريخ أو الأولوية، أو النقل لقائمة أخرى، أو الدمج، أو الحذف. مفيدة جداً عند غياب زميل، أو إغلاق مرحلة كاملة، أو نقل مهام إلى مشروع جديد.', 'Bulk actions apply the same change to several tasks at once. Tick the boxes next to the tasks (or select all), and a bar appears at the bottom to change assignee, status, dates or priority, move them to another List, merge, or delete. Very handy when a colleague is away, when closing a whole stage, or when moving tasks to a new project.'],
    like: ['مثل اختيار عدة رسائل في البريد ونقلها إلى مجلد واحد بنقرة.', 'Like selecting several emails and moving them to one folder in a single click.'],
    demo: { scene: 'list', steps: [
      { c: ['خالد في إجازة. مهامه تحتاج مسؤولاً آخر.', 'Khalid is on leave. His tasks need another owner.'], rows: [C4R('k1', ['طلب تصاريح البلدية', 'Request municipality permits'], { who: 'khalid', due: C4D(18), prio: 'normal' }), C4R('k2', ['متابعة المقاول', 'Follow up the contractor'], { who: 'khalid', due: C4D(19), prio: 'high' }), C4R('k3', ['تحديث المخطط', 'Update the drawing'], { who: 'khalid', due: C4D(21), prio: 'low' }), C4R('k4', ['مسح المواقع', 'Survey sites'], { who: 'salim', due: C4D(12), st: 'done' })], cols: ['assignee', 'due', 'prio'] },
      { c: ['حدد المربع بجانب كل مهمة من مهامه.', 'Tick the box next to each of his tasks.'], hl: 'k3-cb', click: true, rows: C4_KH(true, 'khalid') },
      { c: ['ظهر شريط الإجراءات الجماعية في الأسفل.', 'The bulk action bar appears at the bottom.'], hl: 'bulk' },
      { c: ['اختر Assignee ثم سالم.', 'Choose Assignee, then Salim.'], hl: 'bAssign', click: true, pop: 'assignee' },
      { c: ['ثلاث مهام انتقلت لسالم بنقرة واحدة.', 'Three tasks moved to Salim in one click.'], rows: C4_KH(false, 'salim'), hl: 'k2-assignee', toast: ['تم تحديث 3 مهام', '3 tasks updated'] }
    ] },
    ex: ['في نهاية الربع أغلقت مديرة المشروع 40 مهمة مكتملة بالتحديد الجماعي في دقيقة واحدة بدلاً من ساعة.', 'At quarter end the project manager closed 40 finished tasks with a bulk selection in one minute instead of an hour.'],
    wrong: ['حذف جماعي سريع دون مراجعة التحديد.', 'A quick bulk delete without checking the selection.'],
    right: ['راجع عدد المهام المحددة قبل أي إجراء، خاصة الحذف.', 'Check how many tasks are selected before any action, especially delete.'],
    quiz: { q: ['متى تفيدك الإجراءات الجماعية؟', 'When do bulk actions help you?'], o: [['عند تغيير مهمة واحدة', 'When changing a single task'], ['عند تطبيق نفس التغيير على عدة مهام', 'When applying the same change to several tasks'], ['عند كتابة تعليق', 'When writing a comment']], a: 1, why: ['التحديد الجماعي يوفر تكرار نفس الخطوة لكل مهمة.', 'Bulk selection saves repeating the same step for every task.'] }
  },
  finalize: {
    more: ['العرض المحفوظ هو مزيج من: الأعمدة الظاهرة، والتجميع، والترتيب (Sort)، والفلاتر. عندما تضغط «Save view» يصبح هذا المزيج هو الشكل الذي يراه الجميع. ويمكنك إنشاء عدة عروض لنفس القائمة: «خطة المشروع» للمدير، و«مهامي» لك، و«المتأخرات» للمتابعة، دون تكرار أي مهمة.', 'A saved view is a mix of: visible columns, grouping, sorting and filters. When you click “Save view” that mix becomes what everyone sees. You can create several views of the same List: “Project plan” for the manager, “My tasks” for you, “Overdue” for follow-up, without copying a single task.'],
    like: ['مثل حفظ إعدادات المقعد في السيارة: كل مرة تركب تجده كما تحب.', 'Like saving your seat settings in a car: every time you get in, it is just how you like it.'],
    demo: { scene: 'list', steps: [
      { c: ['القائمة فيها كل شيء لكنها غير مرتبة.', 'The List has everything but is not tidy.'], rows: [C4_FIB()[3], C4_FIB()[1], C4_FIB()[0], C4_FIB()[2]], cols: ['assignee', 'due', 'prio', 'region'] },
      { c: ['رتّب حسب تاريخ الاستحقاق: الأقرب أولاً.', 'Sort by due date: soonest first.'], hl: 'sort', click: true, pop: 'sort' },
      { c: ['المهام أعادت ترتيب نفسها.', 'The tasks rearranged themselves.'], rows: C4_FIB(), sort: 'Due date', hl: 't1' },
      { c: ['أخفِ عمود «المنطقة» لأنه لا يهم هذا العرض.', 'Hide the “Region” column because this view does not need it.'], cols: ['assignee', 'due', 'prio'], hl: 'col-prio', dirty: true },
      { c: ['اضغط «Save view». الآن يرى الجميع نفس الخطة المرتبة.', 'Click “Save view”. Now everyone sees the same tidy plan.'], hl: 'saveView', click: true },
      { c: ['تم الحفظ.', 'Saved.'], dirty: false, toast: ['تم حفظ عرض «خطة المشروع»', '“Project plan” view saved'] }
    ] },
    ex: ['قائد فريق أنشأ ثلاثة عروض لنفس القائمة: واحد للاجتماع الأسبوعي، وواحد للمدير، وواحد للفنيين في الموقع. لم يكرر أي مهمة.', 'A team lead created three views of the same List: one for the weekly meeting, one for the manager, and one for technicians on site. Not one task was duplicated.'],
    wrong: ['نسخ القائمة كلها لتصنع شكلاً مختلفاً للمدير.', 'Copying the whole List to make a different layout for the manager.'],
    right: ['أنشئ عرضاً جديداً لنفس القائمة واحفظه.', 'Create a new view of the same List and save it.'],
    quiz: { q: ['ماذا يحفظ «Save view»؟', 'What does “Save view” save?'], o: [['نسخة جديدة من المهام', 'A new copy of the tasks'], ['الأعمدة والتجميع والترتيب والفلاتر', 'The columns, grouping, sorting and filters'], ['كلمة مرورك', 'Your password']], a: 1, why: ['العرض يحفظ طريقة الرؤية، والمهام تبقى واحدة.', 'A view saves the way of looking; the tasks stay the same.'] }
  },
  customfields: {
    more: ['الحقول الجاهزة تغطي الأساسيات، لكن كل فريق له بيانات خاصة: رقم الطلب، المنطقة، نوع العطل، قيمة العقد. الحقول المخصصة تضيف هذه البيانات بشكل منظم. اختيار النوع الصحيح مهم: القائمة المنسدلة للخيارات الثابتة، والرقم أو المبلغ للحساب، والتاريخ للمواعيد الإضافية، والمعادلة لحساب قيمة من حقول أخرى. البيانات المنظمة هي التي تجعل الفلاتر واللوحات صحيحة.', 'Built-in fields cover the basics, but every team has its own data: request number, region, fault type, contract value. Custom Fields add this data in a structured way. Choosing the right type matters: Dropdown for fixed choices, Number or Money for maths, Date for extra dates, and Formula to calculate a value from other fields. Structured data is what makes filters and dashboards accurate.'],
    like: ['مثل نموذج حكومي بخانات محددة بدلاً من ورقة بيضاء: الجميع يكتب نفس المعلومات بنفس الشكل.', 'Like a government form with set boxes instead of a blank page: everyone writes the same information in the same way.'],
    demo: { scene: 'list', steps: [
      { c: ['نريد معرفة منطقة كل مهمة. اضغط «+» لإضافة حقل.', 'We want each task’s region. Click “+” to add a field.'], rows: C4_FIB().map(r => Object.assign(r, { region: null })), cols: ['assignee', 'due'], hl: 'addCol', click: true },
      { c: ['اختر نوع Dropdown لأن المناطق خيارات ثابتة.', 'Choose Dropdown because regions are fixed choices.'], pop: 'col', hl: 'ft-dd', click: true },
      { c: ['أضف الخيارات: مسقط، صلالة، صحار، ظفار.', 'Add the options: Muscat, Salalah, Sohar, Dhofar.'], pop: 'dd', ddOpts: [['مسقط', 'Muscat'], ['صلالة', 'Salalah'], ['صحار', 'Sohar'], ['ظفار', 'Dhofar']], hl: 'o1' },
      { c: ['اختر المنطقة لكل مهمة من القائمة المنسدلة.', 'Pick each task’s region from the dropdown.'], cols: ['assignee', 'due', 'region'], rows: C4_FIB(), hl: 't3-region', click: true },
      { c: ['الآن يمكنك التصفية حسب المنطقة: «صلالة» فقط.', 'Now you can filter by region: “Salalah” only.'], rows: C4_FIB().filter(r => r.k !== 't3'), filter: ['المنطقة: صلالة', 'Region: Salalah'], hl: 'flt' }
    ] },
    ex: ['فريق الأعطال أضاف حقل «نوع العطل» كقائمة منسدلة. في لوحة المعلومات ظهر أن 40% من الأعطال من نوع واحد، فتم إصلاح سببه الجذري.', 'The faults team added a “Fault type” dropdown. The dashboard showed 40% of faults were one type, so its root cause was fixed.'],
    wrong: ['حقل نص حر يكتب فيه كل شخص المنطقة بطريقة مختلفة: «صلاله»، «Salalah»، «صلالة».', 'A free-text field where everyone writes the region differently: “Salala”, “salalah”, “SLL”.'],
    right: ['قائمة منسدلة بخيارات ثابتة، فتصبح التقارير صحيحة.', 'A dropdown with fixed options, so reports are accurate.'],
    quiz: { q: ['ما أفضل نوع حقل لاختيار المنطقة من قائمة ثابتة؟', 'Which field type is best for choosing a region from a fixed list?'], o: [['Text', 'Text'], ['Dropdown', 'Dropdown'], ['Number', 'Number']], a: 1, why: ['القائمة المنسدلة تمنع الاختلاف في الكتابة وتجعل الفلترة دقيقة.', 'A dropdown prevents spelling differences and makes filtering precise.'] }
  },
  changes: {
    more: ['عندما يتغير شيء في الخطة اسأل ثلاثة أسئلة: ما المهام المتأثرة؟ من يجب أن يعرف؟ وهل تتأثر المهام التي تعتمد عليها؟ في غانت ترى الاعتماديات، فإذا تأخرت مهمة ترى ما يتأخر بعدها. اسحب التواريخ، أعد الإسناد، واكتب تعليقاً يشرح السبب. سجل النشاط يحفظ من غيّر ماذا ومتى، فلا ضياع للمعلومة.', 'When something changes in the plan, ask three questions: which tasks are affected? who needs to know? and are the tasks that depend on it affected? In Gantt you see dependencies, so if one task slips you see what slips after it. Drag the dates, reassign, and write a comment explaining why. The Activity log records who changed what and when, so nothing gets lost.'],
    like: ['مثل تغيير مسار رحلة بسبب ازدحام: تعدّل الطريق وتخبر من ينتظرك.', 'Like rerouting a trip because of traffic: you change the route and tell whoever is waiting for you.'],
    demo: { scene: 'gantt', steps: [
      { c: ['هذه خطة المشروع في غانت. التصاريح ثم التمديد ثم التشغيل.', 'This is the project plan in Gantt. Permits, then installation, then go-live.'], rows: [C4R('g1', ['التصاريح', 'Permits'], { s: 0, w: 3, c: '#0ea5e9', who: 'khalid' }), C4R('g2', ['التمديد', 'Installation'], { s: 3, w: 4, c: '#7b68ee', who: 'salim' }), C4R('g3', ['التشغيل', 'Go-live'], { s: 7, w: 2, c: '#10b981', who: 'maryam' })], deps: [['g1', 'g2'], ['g2', 'g3']], today: 1 },
      { c: ['البلدية أخّرت التصاريح يومين. اسحب نهاية الشريط.', 'The municipality delayed the permits by two days. Drag the end of the bar.'], hl: 'g1', click: true },
      { c: ['لاحظ: كل المهام المعتمدة عليها تحركت معها.', 'Notice: every task that depends on it moved too.'], rows: [C4R('g1', ['التصاريح', 'Permits'], { s: 0, w: 5, c: '#0ea5e9', who: 'khalid' }), C4R('g2', ['التمديد', 'Installation'], { s: 5, w: 4, c: '#7b68ee', who: 'salim' }), C4R('g3', ['التشغيل', 'Go-live'], { s: 9, w: 1, c: '#10b981', who: 'maryam' })], hl: 'g3' },
      { c: ['سالم في دورة تدريبية ذلك الأسبوع. أعد إسناد التمديد إلى خالد.', 'Salim is on training that week. Reassign installation to Khalid.'], rows: [C4R('g1', ['التصاريح', 'Permits'], { s: 0, w: 5, c: '#0ea5e9', who: 'khalid' }), C4R('g2', ['التمديد', 'Installation'], { s: 5, w: 4, c: '#7b68ee', who: 'khalid' }), C4R('g3', ['التشغيل', 'Go-live'], { s: 9, w: 1, c: '#10b981', who: 'maryam' })], hl: 'g2', click: true },
      { c: ['اكتب تعليقاً يشرح التغيير ليعرف الجميع السبب.', 'Write a comment explaining the change so everyone knows why.'], toast: ['تم إشعار الفريق بالتغيير', 'Team notified of the change'] }
    ] },
    ex: ['عندما تأخر وصول المعدات أسبوعاً، سحبت مديرة المشروع شريطاً واحداً في غانت فتحدثت كل المواعيد التالية، وأرسلت تعليقاً للفريق. بدون اجتماع طارئ.', 'When equipment arrived a week late, the project manager dragged one bar in Gantt, all later dates updated, and she posted a comment to the team. No emergency meeting.'],
    wrong: ['تغيير التواريخ بصمت ثم تفاجؤ الفريق.', 'Changing dates silently and surprising the team.'],
    right: ['عدّل، ثم أخبر الفريق بتعليق يشرح السبب.', 'Make the change, then tell the team in a comment explaining why.'],
    quiz: { q: ['ما فائدة الاعتماديات عند تأخر مهمة؟', 'How do dependencies help when a task slips?'], o: [['تخفي المهمة المتأخرة', 'They hide the late task'], ['تُظهر وتحرك المهام التي تعتمد عليها', 'They show and move the tasks that depend on it'], ['تحذف المواعيد', 'They delete the dates']], a: 1, why: ['الاعتمادية تربط المهام فترى أثر التأخير مباشرة.', 'A dependency links tasks so you see the knock-on effect immediately.'] }
  }
});
function TREE_C4() { return [{ k: 'sp-ops', l: 0, t: 'space', n: ['العمليات', 'Operations'] }, { k: 'fd-fib', l: 1, t: 'folder', n: ['إطلاق الألياف - صلالة', 'Fibre launch - Salalah'] }, { k: 'ls-plan', l: 2, t: 'list', n: ['التخطيط', 'Planning'] }, { k: 'ls-del', l: 2, t: 'list', n: ['التنفيذ', 'Delivery'] }]; }
function C4_KH(sel, w) { return [C4R('k1', ['طلب تصاريح البلدية', 'Request municipality permits'], { who: w, due: C4D(18), prio: 'normal', sel }), C4R('k2', ['متابعة المقاول', 'Follow up the contractor'], { who: w, due: C4D(19), prio: 'high', sel }), C4R('k3', ['تحديث المخطط', 'Update the drawing'], { who: w, due: C4D(21), prio: 'low', sel }), C4R('k4', ['مسح المواقع', 'Survey sites'], { who: 'salim', due: C4D(12), st: 'done' })]; }
