/* ==========================================================================
   ClickUp 4.0 course, deep content part 2: Views, and AI (Brain and agents).
   AI features depend on the ClickUp plan and on what Workspace admins turned
   on; the explanations say so. Fictional people and data.
   ========================================================================== */
const C4_BOARD = (stTodo, stProg, stRev, stDone) => [{ st: 'todo', cards: stTodo }, { st: 'prog', cards: stProg }, { st: 'rev', cards: stRev }, { st: 'done', cards: stDone }];
const C4_CARD = (k, n, o) => C4R(k, n, o);
const C4_GANTT = () => [C4R('g1', ['المسح', 'Survey'], { s: 0, w: 2, c: '#0ea5e9', who: 'salim' }), C4R('g2', ['التصاريح', 'Permits'], { s: 2, w: 3, c: '#7b68ee', who: 'khalid' }), C4R('g3', ['التمديد', 'Installation'], { s: 5, w: 3, c: '#e8590c', who: 'salim' }), C4R('g4', ['الإطلاق', 'Launch'], { s: 8, w: 0, ms: true })];
const C4_AIQ = (k, w, x, o) => Object.assign({ k, w, x }, o || {});

Object.assign(C4_DEEP, {
  list: {
    more: ['عرض القائمة يعرض المهام كصفوف، ولكل صف أعمدة تعرض بياناته. هو أفضل مكان لإدخال المهام بسرعة ومراجعة تفاصيلها ومقارنتها. ويمكن توسيع المهمة لرؤية مهامها الفرعية داخل نفس الجدول. كل ما تضبطه هنا (أعمدة، تجميع، فلاتر) يمكن حفظه كعرض باسم واضح.', 'List view shows tasks as rows, and each row has columns for its data. It is the best place to enter tasks quickly, check details and compare them. You can expand a task to see its subtasks in the same table. Everything you set here (columns, grouping, filters) can be saved as a clearly named view.'],
    like: ['مثل قائمة المشتريات المرتبة: كل شيء في سطر، وتشطب ما أنجزته.', 'Like a tidy shopping list: everything on one line, and you cross off what is done.'],
    demo: { scene: 'list', steps: [
      { c: ['هذا عرض List: كل مهمة في صف واحد.', 'This is List view: one task per row.'], rows: C4_FIB(), cols: ['assignee', 'due', 'prio'] },
      { c: ['اضغط «Add Task» واكتب اسماً، ثم Enter.', 'Click “Add Task”, type a name, then Enter.'], hl: 'addTask', click: true, type: { k: 'newTask', x: ['حجز الرافعة', 'Book the crane'] } },
      { c: ['ظهرت المهمة فوراً. كرر بسرعة لإضافة المزيد.', 'The task appears instantly. Repeat quickly to add more.'], rows: C4_FIB().concat([C4R('t5', ['حجز الرافعة', 'Book the crane'], { prio: 'normal' })]), newTask: null, hl: 't5' },
      { c: ['المهام ذات المهام الفرعية تُظهر عدّاداً. اضغط لتوسيعها.', 'Tasks with subtasks show a counter. Click to expand.'], rows: C4_FIB().map(r => r.k === 't2' ? Object.assign(r, { subs: 2 }) : r).concat([C4R('t5', ['حجز الرافعة', 'Book the crane'], { prio: 'normal' })]), hl: 't2-subs', click: true },
      { c: ['المهام الفرعية تظهر تحت مهمتها الأم داخل نفس الجدول.', 'The subtasks appear under their parent in the same table.'], rows: C4_FIB().map(r => r.k === 't2' ? Object.assign(r, { subs: 2, open: true }) : r).concat([C4R('s1', ['المسار الشمالي', 'Northern route'], { p: 't2', who: 'maryam', due: C4D(14) }), C4R('s2', ['المسار الجنوبي', 'Southern route'], { p: 't2', who: 'salim', due: C4D(15) })]), hl: 's1' }
    ] },
    ex: ['في اجتماع التخطيط، كتب الفريق 25 مهمة في عرض القائمة خلال 10 دقائق، ثم وزعوها على الأشخاص من نفس الشاشة.', 'In the planning meeting the team typed 25 tasks in List view in 10 minutes, then shared them out from the same screen.'],
    wrong: ['فتح نافذة إنشاء كاملة لكل مهمة صغيرة.', 'Opening the full create window for every small task.'],
    right: ['اكتب بسرعة في «Add Task» واضغط Enter، ثم أكمل التفاصيل لاحقاً.', 'Type quickly in “Add Task” and press Enter, then fill in details later.'],
    quiz: { q: ['ما أفضل استخدام لعرض القائمة؟', 'What is List view best for?'], o: [['رؤية المهام على خريطة', 'Seeing tasks on a map'], ['إدخال المهام بسرعة ومراجعة تفاصيلها', 'Entering tasks quickly and checking their details'], ['تسجيل الاجتماعات', 'Recording meetings']], a: 1, why: ['القائمة جدول مرتب مثالي للإدخال والمراجعة.', 'The List is a tidy table, ideal for entry and review.'] }
  },
  board: {
    more: ['عرض اللوحة (Kanban) يجعل سير العمل مرئياً: كل عمود حالة، وكل بطاقة مهمة. عندما تسحب البطاقة إلى عمود آخر تتغير حالتها تلقائياً. أهم فائدة: ترى أين يتكدس العمل. لو امتلأ عمود «مراجعة» فالمراجعة هي عنق الزجاجة. ويمكن تجميع اللوحة حسب المسؤول أو الأولوية بدلاً من الحالة.', 'Board (Kanban) view makes the workflow visible: each column is a status and each card a task. When you drag a card to another column its status changes automatically. The biggest benefit: you see where work piles up. If the Review column is full, review is the bottleneck. You can also group the board by assignee or priority instead of status.'],
    like: ['مثل لوحة الملاحظات اللاصقة على حائط المكتب، لكنها تتحدث وحدها للجميع.', 'Like a sticky-note wall in the office, but it updates itself for everyone.'],
    demo: { scene: 'board', steps: [
      { c: ['هذا عرض Board: أعمدة الحالات وبطاقات المهام.', 'This is Board view: status columns and task cards.'], cols: C4_BOARD([C4_CARD('c1', ['طلب التصاريح', 'Request permits'], { who: 'khalid', prio: 'normal' }), C4_CARD('c2', ['تجهيز الفريق', 'Prepare the crew'], { who: 'salim', prio: 'low' })], [C4_CARD('c3', ['تصميم المسار', 'Design the route'], { who: 'maryam', prio: 'urgent' })], [], [C4_CARD('c4', ['مسح المواقع', 'Survey sites'], { who: 'salim' })]) },
      { c: ['مريم أنهت التصميم. اسحب بطاقتها إلى REVIEW.', 'Maryam finished the design. Drag her card to REVIEW.'], hl: 'c3', click: true },
      { c: ['تحركت البطاقة وتغيرت حالتها تلقائياً.', 'The card moved and its status changed automatically.'], cols: C4_BOARD([C4_CARD('c1', ['طلب التصاريح', 'Request permits'], { who: 'khalid', prio: 'normal' }), C4_CARD('c2', ['تجهيز الفريق', 'Prepare the crew'], { who: 'salim', prio: 'low' })], [], [C4_CARD('c3', ['تصميم المسار', 'Design the route'], { who: 'maryam', prio: 'urgent' })], [C4_CARD('c4', ['مسح المواقع', 'Survey sites'], { who: 'salim' })]), hl: 'c3' },
      { c: ['خالد بدأ التصاريح: من TO DO إلى IN PROGRESS.', 'Khalid started the permits: from TO DO to IN PROGRESS.'], cols: C4_BOARD([C4_CARD('c2', ['تجهيز الفريق', 'Prepare the crew'], { who: 'salim', prio: 'low' })], [C4_CARD('c1', ['طلب التصاريح', 'Request permits'], { who: 'khalid', prio: 'normal' })], [C4_CARD('c3', ['تصميم المسار', 'Design the route'], { who: 'maryam', prio: 'urgent' })], [C4_CARD('c4', ['مسح المواقع', 'Survey sites'], { who: 'salim' })]), hl: 'c1' },
      { c: ['بنظرة واحدة: ماذا ينتظر، وماذا يُعمل عليه، وماذا يُراجع.', 'At a glance: what is waiting, what is in progress, and what is in review.'], hl: 'col-rev' }
    ] },
    ex: ['فريق الدعم الفني يعرض اللوحة على شاشة كبيرة في المكتب. عندما يمتلئ عمود «بانتظار العميل» يتصل المشرف بالعملاء لتحريك الطلبات.', 'The IT support team shows the board on a big office screen. When the “Waiting on customer” column fills up, the supervisor calls customers to move requests along.'],
    wrong: ['تحديث الحالة شفهياً في الاجتماع دون تحريك البطاقة.', 'Updating status verbally in the meeting without moving the card.'],
    right: ['حرّك البطاقة فور تغير الحالة؛ اللوحة يجب أن تعكس الواقع.', 'Move the card as soon as the status changes; the board must reflect reality.'],
    quiz: { q: ['ماذا يحدث عند سحب بطاقة إلى عمود آخر في Board؟', 'What happens when you drag a card to another column in Board?'], o: [['تُحذف المهمة', 'The task is deleted'], ['تتغير حالة المهمة', 'The task’s status changes'], ['تُنسخ المهمة', 'The task is copied']], a: 1, why: ['أعمدة اللوحة هي الحالات، فالسحب يغير الحالة.', 'Board columns are statuses, so dragging changes the status.'] }
  },
  calendar: {
    more: ['التقويم يضع المهام على الأيام حسب تواريخها، فترى الأسبوع كاملاً: الأيام المزدحمة والفارغة. السحب في التقويم يغير التاريخ مباشرة. والمهام بلا تاريخ تظهر في شريط «Unscheduled» لتسحبها إلى يوم مناسب. ويمكن مزامنة مهامك مع تقويم Google أو Outlook حسب إعدادات الشركة.', 'Calendar places tasks on days by their dates, so you see the whole week: busy days and free days. Dragging in the calendar changes the date directly. Tasks without dates sit in an “Unscheduled” strip, ready to drag onto a suitable day. You can also sync your tasks with Google or Outlook calendar, depending on company settings.'],
    like: ['مثل أجندة ورقية على المكتب، لكنها تتحدث تلقائياً عندما تتغير المواعيد.', 'Like a paper planner on your desk, but it updates itself when dates change.'],
    demo: { scene: 'calendar', steps: [
      { c: ['هذا عرض Calendar لأسبوع العمل.', 'This is Calendar view for the work week.'], items: [C4R('e1', ['مسح المواقع', 'Survey sites'], { d: 0, c: '#10b981' }), C4R('e2', ['تصميم المسار', 'Design the route'], { d: 1, c: '#7b68ee' }), C4R('e3', ['اجتماع البلدية', 'Municipality meeting'], { d: 1, c: '#0ea5e9' }), C4R('e4', ['مراجعة الميزانية', 'Budget review'], { d: 1, c: '#e8590c' })], uns: [C4R('u1', ['حجز الرافعة', 'Book the crane'])] },
      { c: ['الإثنين مزدحم بثلاث مهام. انقل «مراجعة الميزانية» إلى الأربعاء.', 'Monday is packed with three tasks. Move “Budget review” to Wednesday.'], hl: 'e4', click: true },
      { c: ['تغير التاريخ بمجرد السحب.', 'The date changed just by dragging.'], items: [C4R('e1', ['مسح المواقع', 'Survey sites'], { d: 0, c: '#10b981' }), C4R('e2', ['تصميم المسار', 'Design the route'], { d: 1, c: '#7b68ee' }), C4R('e3', ['اجتماع البلدية', 'Municipality meeting'], { d: 1, c: '#0ea5e9' }), C4R('e4', ['مراجعة الميزانية', 'Budget review'], { d: 3, c: '#e8590c' })], hl: 'e4' },
      { c: ['«حجز الرافعة» بلا موعد. اسحبها إلى الثلاثاء.', '“Book the crane” has no date. Drag it to Tuesday.'], hl: 'u1', click: true },
      { c: ['أصبحت مجدولة، وظهرت في الأسبوع.', 'It is now scheduled and appears in the week.'], items: [C4R('e1', ['مسح المواقع', 'Survey sites'], { d: 0, c: '#10b981' }), C4R('e2', ['تصميم المسار', 'Design the route'], { d: 1, c: '#7b68ee' }), C4R('e3', ['اجتماع البلدية', 'Municipality meeting'], { d: 1, c: '#0ea5e9' }), C4R('e4', ['مراجعة الميزانية', 'Budget review'], { d: 3, c: '#e8590c' }), C4R('u1', ['حجز الرافعة', 'Book the crane'], { d: 2, c: '#87909e' })], uns: [], hl: 'u1' }
    ] },
    ex: ['منسقة التدريب تستخدم التقويم لتوزيع الدورات على الأسابيع، فلا يتزامن تدريبان لنفس الفريق في يوم واحد.', 'The training coordinator uses Calendar to spread sessions across weeks, so no team has two trainings on the same day.'],
    wrong: ['ترك عشرات المهام بلا تاريخ ثم نسيانها.', 'Leaving dozens of tasks undated and then forgetting them.'],
    right: ['راجع شريط Unscheduled أسبوعياً واسحب كل مهمة إلى يوم مناسب.', 'Review the Unscheduled strip weekly and drag each task to a suitable day.'],
    quiz: { q: ['كيف تغير موعد مهمة في عرض التقويم؟', 'How do you change a task’s date in Calendar view?'], o: [['بسحبها إلى يوم آخر', 'By dragging it to another day'], ['بحذفها وإعادة إنشائها', 'By deleting and recreating it'], ['لا يمكن ذلك في التقويم', 'You cannot in Calendar']], a: 0, why: ['السحب في التقويم يغير التاريخ مباشرة.', 'Dragging in the calendar changes the date directly.'] }
  },
  gantt: {
    more: ['غانت يرسم المشروع على خط زمني: كل مهمة شريط من البدء إلى الاستحقاق، والمعالم (Milestones) ماسات تمثل لحظات مهمة مثل الإطلاق. الخطوط بين الأشرطة اعتماديات: «لا يبدأ التمديد قبل انتهاء التصاريح». وخط اليوم الأحمر يريك أين يجب أن تكون الآن. هذا العرض يجيب عن أهم سؤال للمدير: «هل سننتهي في الموعد؟».', 'Gantt draws the project on a timeline: each task is a bar from start to due date, and milestones are diamonds marking key moments such as launch. Lines between bars are dependencies: “installation cannot start before permits finish”. The red today line shows where you should be now. This view answers a manager’s biggest question: “Will we finish on time?”.'],
    like: ['مثل جدول رحلة طويلة بمحطات: لا تصل للمحطة الثالثة قبل الثانية.', 'Like a long trip timetable with stops: you cannot reach the third stop before the second.'],
    demo: { scene: 'gantt', steps: [
      { c: ['كل مهمة شريط على الخط الزمني.', 'Each task is a bar on the timeline.'], rows: C4_GANTT(), today: 1 },
      { c: ['اربط المسح بالتصاريح: اسحب من نهاية شريط المسح إلى بداية التصاريح.', 'Link Survey to Permits: drag from the end of the Survey bar to the start of Permits.'], hl: 'g1', click: true },
      { c: ['ظهر خط الاعتمادية. أضف بقية الروابط.', 'A dependency line appears. Add the other links.'], deps: [['g1', 'g2'], ['g2', 'g3'], ['g3', 'g4']], hl: 'g2' },
      { c: ['الماسة هي معلم الإطلاق: اللحظة التي يترقبها الجميع.', 'The diamond is the Launch milestone: the moment everyone is waiting for.'], hl: 'g4' },
      { c: ['الخط الأحمر هو اليوم. ما يقع قبله يجب أن يكون منجزاً.', 'The red line is today. Anything before it should be done.'], today: 3, hl: 'g1' }
    ] },
    ex: ['مدير مشروع الأبراج يعرض غانت في الاجتماع الشهري. عندما سأل المدير التنفيذي عن موعد الإطلاق، أشار إلى الماسة وشرح ما يعتمد عليها.', 'The towers project manager shows Gantt in the monthly meeting. When the executive asked about launch, he pointed to the diamond and explained what it depends on.'],
    wrong: ['مهام بلا تواريخ بدء فلا تظهر أشرطتها في غانت.', 'Tasks without start dates, so their bars do not show in Gantt.'],
    right: ['أعطِ كل مهمة تاريخ بدء واستحقاق، واربط المتسلسلة منها.', 'Give each task a start and due date, and link the ones in sequence.'],
    quiz: { q: ['ماذا تمثل الماسة في غانت؟', 'What does the diamond represent in Gantt?'], o: [['مهمة متأخرة', 'A late task'], ['معلماً (Milestone) مهماً', 'A key milestone'], ['تعليقاً جديداً', 'A new comment']], a: 1, why: ['الماسة تمثل لحظة مهمة في المشروع مثل الإطلاق.', 'The diamond marks a key moment in the project, such as launch.'] }
  },
  table: {
    more: ['عرض الجدول يشبه جدول بيانات: خلايا تنقر عليها وتعدلها، ويمكنك نسخ ولصق عدة قيم دفعة واحدة. مثالي لتعديل حقول كثيرة بسرعة (مثل تحديث التكاليف لعشرين مهمة)، أو لتجهيز البيانات قبل التصدير إلى Excel. ويمكن تثبيت الأعمدة المهمة وتغيير عرضها.', 'Table view works like a spreadsheet: cells you click and edit, and you can copy and paste several values at once. It is ideal for editing many fields quickly (like updating costs for twenty tasks), or for preparing data before exporting to Excel. You can pin important columns and resize them.'],
    like: ['مثل Excel، لكن كل صف مهمة حقيقية مرتبطة بالفريق.', 'Like Excel, but every row is a real task connected to the team.'],
    demo: { scene: 'table', steps: [
      { c: ['عرض Table: صفوف وأعمدة مثل Excel.', 'Table view: rows and columns like Excel.'], cols: ['Task name', ['المنطقة', 'Region'], ['التكلفة', 'Cost'], 'Status', 'Assignee'], rows: [[['مسح المواقع', 'Survey sites'], ['صلالة', 'Salalah'], '1,200', 'COMPLETE', ['سالم', 'Salim']], [['تصميم المسار', 'Design the route'], ['صلالة', 'Salalah'], '3,500', 'IN PROGRESS', ['مريم', 'Maryam']], [['طلب التصاريح', 'Request permits'], ['ظفار', 'Dhofar'], '—', 'TO DO', ['خالد', 'Khalid']]] },
      { c: ['انقر خلية التكلفة الفارغة واكتب القيمة.', 'Click the empty cost cell and type the value.'], hl: 'c2-2', click: true, edit: [2, 2], type: { k: 'c2-2', x: '800' } },
      { c: ['عدّل المنطقة مباشرة من الخلية.', 'Edit the region straight from the cell.'], rows: [[['مسح المواقع', 'Survey sites'], ['صلالة', 'Salalah'], '1,200', 'COMPLETE', ['سالم', 'Salim']], [['تصميم المسار', 'Design the route'], ['صلالة', 'Salalah'], '3,500', 'IN PROGRESS', ['مريم', 'Maryam']], [['طلب التصاريح', 'Request permits'], ['ظفار', 'Dhofar'], '800', 'TO DO', ['خالد', 'Khalid']]], edit: [1, 1], hl: 'c1-1', click: true, type: { k: 'c1-1', x: ['مرباط', 'Mirbat'] } },
      { c: ['تعديلات سريعة دون فتح أي مهمة. جاهز للتصدير.', 'Quick edits without opening any task. Ready to export.'], rows: [[['مسح المواقع', 'Survey sites'], ['صلالة', 'Salalah'], '1,200', 'COMPLETE', ['سالم', 'Salim']], [['تصميم المسار', 'Design the route'], ['مرباط', 'Mirbat'], '3,500', 'IN PROGRESS', ['مريم', 'Maryam']], [['طلب التصاريح', 'Request permits'], ['ظفار', 'Dhofar'], '800', 'TO DO', ['خالد', 'Khalid']]], edit: null, toast: ['تم حفظ التعديلات', 'Changes saved'] }
    ] },
    ex: ['المحاسب حدّث تكلفة 30 مهمة في عرض الجدول بلصق عمود من ملف Excel، في دقيقتين.', 'The accountant updated the cost of 30 tasks in Table view by pasting a column from Excel, in two minutes.'],
    wrong: ['فتح كل مهمة على حدة لتعديل رقم واحد.', 'Opening each task one by one to change a single number.'],
    right: ['استخدم عرض الجدول للتعديلات الكثيرة على الحقول.', 'Use Table view for many field edits.'],
    quiz: { q: ['متى يفيد عرض الجدول أكثر؟', 'When is Table view most useful?'], o: [['لتعديل حقول كثيرة بسرعة', 'For editing many fields quickly'], ['للعصف الذهني', 'For brainstorming'], ['لتسجيل الوقت', 'For tracking time']], a: 0, why: ['الجدول يتيح التعديل والنسخ واللصق مثل Excel.', 'The table lets you edit, copy and paste like Excel.'] }
  },
  whiteboard: {
    more: ['السبورة لوحة بيضاء لا نهائية يرسم عليها الفريق معاً في نفس الوقت: ملاحظات لاصقة، أشكال، نصوص، أسهم وصور. قوتها الحقيقية أنها متصلة بالعمل: أي ملاحظة تتحول إلى مهمة حقيقية في قائمة، بمسؤول وموعد. هكذا لا تبقى أفكار العصف الذهني صوراً في الهاتف، بل تصبح خطة.', 'A Whiteboard is an endless canvas the team draws on together at the same time: sticky notes, shapes, text, arrows and images. Its real power is that it is connected to the work: any note can become a real task in a List, with an owner and a date. That way brainstorm ideas do not stay as photos on a phone; they become a plan.'],
    like: ['مثل سبورة غرفة الاجتماعات، لكن أفكارها لا تُمسح بعد الاجتماع بل تتحول إلى مهام.', 'Like the meeting room whiteboard, but its ideas are not wiped after the meeting; they turn into tasks.'],
    demo: { scene: 'whiteboard', steps: [
      { c: ['جلسة عصف ذهني: كيف نسرّع التمديد؟', 'Brainstorm session: how do we speed up installation?'], notes: [{ k: 'n1', x: 160, y: 60, t: ['فريق ثانٍ في المساء', 'A second evening crew'], c: '#ffe066' }] },
      { c: ['أضف ملاحظات لاصقة لكل فكرة.', 'Add sticky notes for each idea.'], hl: 'tSticky', click: true, notes: [{ k: 'n1', x: 160, y: 60, t: ['فريق ثانٍ في المساء', 'A second evening crew'], c: '#ffe066' }, { k: 'n2', x: 360, y: 90, t: ['طلب التصاريح مبكراً', 'Request permits earlier'], c: '#a5d8ff' }, { k: 'n3', x: 230, y: 230, t: ['تجهيز المعدات مسبقاً', 'Prepare equipment in advance'], c: '#b2f2bb' }] },
      { c: ['اربط الأفكار المرتبطة بسهم.', 'Connect related ideas with an arrow.'], hl: 'tLine', click: true, arrows: [['n2', 'n3']] },
      { c: ['الفريق اتفق على «طلب التصاريح مبكراً». حدد الملاحظة واختر «Convert to task».', 'The team agreed on “Request permits earlier”. Select the note and choose “Convert to task”.'], hl: 'n2', click: true, menu: true, menuStyle: 'top:160px;left:380px;width:180px' },
      { c: ['أصبحت مهمة حقيقية في القائمة، بمسؤول وموعد.', 'It became a real task in the List, with an owner and a date.'], hl: 'n2', notes: [{ k: 'n1', x: 160, y: 60, t: ['فريق ثانٍ في المساء', 'A second evening crew'], c: '#ffe066' }, { k: 'n2', x: 360, y: 90, t: ['طلب التصاريح مبكراً', 'Request permits earlier'], c: '#a5d8ff', task: true }, { k: 'n3', x: 230, y: 230, t: ['تجهيز المعدات مسبقاً', 'Prepare equipment in advance'], c: '#b2f2bb' }], toast: ['تم إنشاء مهمة في «التخطيط»', 'Task created in “Planning”'] }
    ] },
    ex: ['ورشة تحسين تجربة العملاء جمعت 40 فكرة على السبورة. في آخر 10 دقائق حوّل الفريق أفضل 6 أفكار إلى مهام مسندة بمواعيد.', 'A customer-experience workshop gathered 40 ideas on the Whiteboard. In the last 10 minutes the team turned the best 6 into assigned tasks with dates.'],
    wrong: ['تصوير السبورة بالهاتف ثم نسيان الصورة.', 'Photographing the whiteboard with a phone and then forgetting the photo.'],
    right: ['حوّل الأفكار المتفق عليها إلى مهام قبل نهاية الاجتماع.', 'Turn the agreed ideas into tasks before the meeting ends.'],
    quiz: { q: ['ما الميزة الأهم في سبورة ClickUp؟', 'What is the key strength of a ClickUp Whiteboard?'], o: [['الألوان الكثيرة', 'Lots of colours'], ['تحويل الملاحظات إلى مهام حقيقية', 'Turning notes into real tasks'], ['أنها لا تُحفظ', 'It is never saved']], a: 1, why: ['الربط بين الأفكار والمهام يحول العصف الذهني إلى خطة.', 'Linking ideas to tasks turns a brainstorm into a plan.'] }
  },
  timeline: {
    more: ['الخط الزمني (Timeline) يعرض المهام كأشرطة على الأيام مثل غانت، لكنه مرتب حسب الأشخاص أو المجموعات. فبدلاً من سؤال «ماذا يأتي بعد ماذا؟» يجيب عن «من مشغول بماذا ومتى؟». مفيد عند تقديم خطة الفريق لمدير، أو عند البحث عن شخص متفرغ لمهمة جديدة.', 'Timeline shows tasks as bars across days like Gantt, but arranged by people or groups. So instead of “what comes after what?” it answers “who is busy with what, and when?”. Useful when presenting the team plan to a manager, or when looking for someone free for a new task.'],
    like: ['مثل جدول مناوبات المستشفى: ترى كل شخص ومتى يعمل.', 'Like a hospital shift rota: you see each person and when they work.'],
    demo: { scene: 'gantt', steps: [
      { c: ['الخط الزمني مرتب حسب الأشخاص.', 'Timeline is arranged by people.'], timeline: true, rows: [C4R('p1', ['سالم', 'Salim'], { s: 0, w: 4, c: '#e8590c', who: 'salim' }), C4R('p2', ['مريم', 'Maryam'], { s: 2, w: 3, c: '#0ea5e9', who: 'maryam' }), C4R('p3', ['خالد', 'Khalid'], { s: 5, w: 4, c: '#10b981', who: 'khalid' })] },
      { c: ['سالم مشغول أول أربعة أيام.', 'Salim is busy for the first four days.'], hl: 'p1' },
      { c: ['مريم متفرغة بعد اليوم الخامس، فلنعطها المهمة الجديدة.', 'Maryam is free after day five, so let’s give her the new task.'], hl: 'p2' },
      { c: ['أضفنا مهمة لمريم في وقت فراغها.', 'We added a task for Maryam in her free time.'], rows: [C4R('p1', ['سالم', 'Salim'], { s: 0, w: 4, c: '#e8590c', who: 'salim' }), C4R('p2', ['مريم', 'Maryam'], { s: 2, w: 6, c: '#0ea5e9', who: 'maryam' }), C4R('p3', ['خالد', 'Khalid'], { s: 5, w: 4, c: '#10b981', who: 'khalid' })], hl: 'p2', toast: ['أُسندت المهمة لمريم', 'Task assigned to Maryam'] }
    ] },
    ex: ['مديرة القسم أرادت معرفة من يمكنه استلام طلب عاجل. فتحت الخط الزمني فرأت خلال ثوانٍ أن خالد متفرغ يوم الأربعاء.', 'The department head wanted to know who could take an urgent request. She opened Timeline and saw in seconds that Khalid was free on Wednesday.'],
    wrong: ['إسناد المهام الجديدة دائماً للشخص الأكثر خبرة حتى يُرهق.', 'Always assigning new tasks to the most experienced person until they burn out.'],
    right: ['انظر للخط الزمني وأسند لمن لديه وقت فعلاً.', 'Check the Timeline and assign to whoever actually has time.'],
    quiz: { q: ['بماذا يختلف الخط الزمني عن غانت؟', 'How does Timeline differ from Gantt?'], o: [['لا يعرض تواريخ', 'It shows no dates'], ['مرتب حسب الأشخاص أو المجموعات', 'It is arranged by people or groups'], ['يعرض الخرائط', 'It shows maps']], a: 1, why: ['الخط الزمني يجيب عن «من مشغول ومتى».', 'Timeline answers “who is busy, and when”.'] }
  },
  workload: {
    more: ['عرض عبء العمل يقارن ما أُسند لكل شخص بقدرته اليومية (مثلاً 8 ساعات). الخلايا الحمراء تعني ضغطاً أكثر من الطاقة، والزرقاء تعني وقتاً متاحاً. يعتمد على تقديرات الوقت أو عدد المهام، لذلك أضف تقديراً لكل مهمة ليكون دقيقاً. وعرض الفريق (Team) يعرض مهام كل عضو تحت اسمه ليتابع القائد الجميع.', 'The Workload view compares what each person is assigned with their daily capacity (for example 8 hours). Red cells mean more load than capacity, blue cells mean spare time. It is based on time estimates or task counts, so add an estimate to each task to make it accurate. The Team view lists each member’s tasks under their name so the lead can follow everyone.'],
    like: ['مثل ميزان: إذا مال لشخص كثيراً، انقل بعض الحمل للآخر.', 'Like a scale: if it tips too far for one person, move some weight to another.'],
    demo: { scene: 'workload', steps: [
      { c: ['كل خلية: ساعات العمل المسندة لهذا الشخص في هذا اليوم.', 'Each cell: hours assigned to that person on that day.'], extraTabs: [['workload', 'workload', 'Workload']], people: [{ who: 'salim', h: [6, 11, 9, 7, 5] }, { who: 'maryam', h: [4, 3, 6, 5, 4] }, { who: 'khalid', h: [8, 7, 8, 2, 3] }] },
      { c: ['سالم يوم الإثنين: 11 ساعة. أكثر من طاقته (الأحمر).', 'Salim on Monday: 11 hours. More than his capacity (red).'], hl: 'salim-1' },
      { c: ['مريم يوم الإثنين: 3 ساعات فقط. لديها وقت.', 'Maryam on Monday: only 3 hours. She has time.'], hl: 'maryam-1' },
      { c: ['انقل مهمة (4 ساعات) من سالم إلى مريم.', 'Move a 4-hour task from Salim to Maryam.'], people: [{ who: 'salim', h: [6, 7, 9, 7, 5] }, { who: 'maryam', h: [4, 7, 6, 5, 4] }, { who: 'khalid', h: [8, 7, 8, 2, 3] }], hl: 'salim-1', toast: ['أصبح الحمل متوازناً', 'The load is balanced now'] }
    ] },
    ex: ['فني الألياف كان يعمل 12 ساعة يومياً لأسابيع دون أن يلاحظ أحد. بعد تفعيل عرض عبء العمل ظهر اسمه أحمر، فوُزّعت مهامه على اثنين آخرين.', 'A fibre technician worked 12 hours a day for weeks without anyone noticing. With the Workload view his row showed red, and his tasks were shared with two others.'],
    wrong: ['مهام بلا تقديرات وقت، فيبدو الجميع متفرغاً.', 'Tasks with no time estimates, so everyone looks free.'],
    right: ['أضف تقديراً تقريبياً لكل مهمة ليصبح العرض صادقاً.', 'Add a rough estimate to every task so the view tells the truth.'],
    quiz: { q: ['ماذا تعني الخلية الحمراء في عرض عبء العمل؟', 'What does a red cell mean in the Workload view?'], o: [['مهمة متأخرة', 'A late task'], ['عمل أكثر من طاقة الشخص في ذلك اليوم', 'More work than the person’s capacity that day'], ['يوم عطلة', 'A day off']], a: 1, why: ['الأحمر يعني تجاوز القدرة اليومية.', 'Red means the daily capacity is exceeded.'] }
  },
  activity: {
    more: ['عرض النشاط سجل زمني لكل ما يحدث في مكان ما: إنشاء المهام، تغيير الحالات، التعليقات، الإسناد والمرفقات، مع اسم الشخص والوقت. تصفيه حسب الشخص أو نوع التغيير. وفي كل مهمة يوجد سجل نشاط خاص بها، فتعرف بدقة من غيّر الموعد ومتى، دون اتهامات أو تخمين.', 'The Activity view is a timeline of everything that happens in a place: tasks created, statuses changed, comments, assignments and attachments, with the person’s name and the time. Filter it by person or type of change. Every task also has its own activity log, so you know exactly who changed the date and when, with no guessing or blame.'],
    like: ['مثل كاميرا المراقبة في المتجر: تسجل كل حركة لترجع إليها عند الحاجة.', 'Like a shop’s security camera: it records every move so you can look back when needed.'],
    demo: { scene: 'activity', steps: [
      { c: ['عرض Activity: ما حدث في القائمة مؤخراً.', 'Activity view: what happened in the List recently.'], extraTabs: [['activity', 'clock', 'Activity']], feed: [{ k: 'f1', who: 'maryam', x: ['غيّرت حالة «تصميم المسار» إلى REVIEW', 'changed “Design the route” to REVIEW'], t: ['قبل 5 دقائق', '5 min ago'] }, { k: 'f2', who: 'khalid', x: ['علّق على «طلب التصاريح»', 'commented on “Request permits”'], t: ['قبل ساعة', '1 h ago'] }] },
      { c: ['كل تغيير يظهر مع الاسم والوقت.', 'Every change appears with the name and time.'], feed: [{ k: 'f0', who: 'salim', x: ['نقل موعد «التمديد» إلى 23 أكتوبر', 'moved “Installation” due date to Oct 23'], t: ['الآن', 'just now'] }, { k: 'f1', who: 'maryam', x: ['غيّرت حالة «تصميم المسار» إلى REVIEW', 'changed “Design the route” to REVIEW'], t: ['قبل 5 دقائق', '5 min ago'] }, { k: 'f2', who: 'khalid', x: ['علّق على «طلب التصاريح»', 'commented on “Request permits”'], t: ['قبل ساعة', '1 h ago'] }], hl: 'f0' },
      { c: ['صفِّ حسب الشخص لترى نشاط سالم فقط.', 'Filter by person to see only Salim’s activity.'], feed: [{ k: 'f0', who: 'salim', x: ['نقل موعد «التمديد» إلى 23 أكتوبر', 'moved “Installation” due date to Oct 23'], t: ['الآن', 'just now'] }, { k: 'f3', who: 'salim', x: ['أكمل «مسح المواقع»', 'completed “Survey sites”'], t: ['أمس', 'yesterday'] }], flt: ['الشخص: سالم', 'Person: Salim'], hl: 'feedf' }
    ] },
    ex: ['بعد إجازة أسبوع، فتحت مريم عرض النشاط وقرأت في 5 دقائق كل ما تغير في مشروعها بدلاً من سؤال كل زميل.', 'After a week’s leave, Maryam opened the Activity view and caught up on every change in her project in 5 minutes instead of asking each colleague.'],
    wrong: ['سؤال الفريق «من غيّر هذا؟» في المجموعة.', 'Asking the group “who changed this?”.'],
    right: ['افتح سجل النشاط وستجد الجواب بالاسم والوقت.', 'Open the activity log and find the answer with name and time.'],
    quiz: { q: ['ما الذي يعرضه سجل النشاط؟', 'What does the activity log show?'], o: [['التغييرات مع الشخص والوقت', 'Changes with the person and the time'], ['كلمات المرور', 'Passwords'], ['الفواتير فقط', 'Only invoices']], a: 0, why: ['السجل يحفظ من غيّر ماذا ومتى.', 'The log records who changed what, and when.'] }
  },
  docsforms: {
    more: ['المستند (Doc) يضم المعرفة: أدلة العمل، محاضر الاجتماعات، الإجراءات. ميزته أنه يعيش بجانب المهام: تربط مهمة داخل المستند، أو تنشئ مهمة من نص فيه. أما النموذج (Form) فهو باب دخول الطلبات: يملؤه أي شخص (حتى من خارج القائمة)، وكل إرسال يصبح مهمة كاملة بحقولها في القائمة، دون نسخ يدوي من البريد.', 'A Doc holds knowledge: work guides, meeting minutes, procedures. Its strength is that it lives next to the tasks: you link a task inside the Doc, or create a task from its text. A Form is the front door for requests: anyone can fill it in (even people outside the List), and every submission becomes a full task with its fields in the List, with no manual copying from email.'],
    like: ['المستند مثل كتيّب التعليمات، والنموذج مثل شباك الاستقبال: يستلم الطلب ويحوله للقسم المختص.', 'A Doc is like an instruction booklet, and a Form is like a reception desk: it takes the request and passes it to the right team.'],
    demo: { scene: 'form', steps: [
      { c: ['أضف عرض Form للقائمة. على اليسار حقول جاهزة للسحب.', 'Add a Form view to the List. On the side are fields ready to drag.'], extraTabs: [['form', 'form', 'Form']], palette: true, fields: [{ k: 'f1', l: ['اسم مقدم الطلب', 'Requester name'], req: true }] },
      { c: ['اسحب حقل «الموقع» ثم «نوع العطل».', 'Drag in a “Site” field, then “Fault type”.'], hl: 'fp-dd', click: true, fields: [{ k: 'f1', l: ['اسم مقدم الطلب', 'Requester name'], req: true }, { k: 'f2', l: ['الموقع', 'Site'], req: true }, { k: 'f3', l: ['نوع العطل', 'Fault type'] }] },
      { c: ['موظف يملأ النموذج من الرابط.', 'An employee fills in the form from the link.'], palette: false, hl: 'f1-v', click: true, type: { k: 'f1-v', x: ['نورة الشكيلية', 'Noura Al Shukaili'] } },
      { c: ['يكمل الحقول ويضغط Submit.', 'They complete the fields and click Submit.'], fields: [{ k: 'f1', l: ['اسم مقدم الطلب', 'Requester name'], req: true, v: ['نورة الشكيلية', 'Noura Al Shukaili'] }, { k: 'f2', l: ['الموقع', 'Site'], req: true, v: ['برج صلالة 7', 'Salalah tower 7'] }, { k: 'f3', l: ['نوع العطل', 'Fault type'], v: ['انقطاع كهرباء', 'Power outage'] }], hl: 'submit', click: true },
      { c: ['الطلب أصبح مهمة في قائمة الطلبات فوراً.', 'The request instantly became a task in the Requests List.'], out: [C4R('r1', ['انقطاع كهرباء - برج صلالة 7', 'Power outage - Salalah tower 7'], { who: 'khalid' })], hl: 'r1', toast: ['وصل طلب جديد', 'New request received'] }
    ] },
    ex: ['قسم المرافق كان يستقبل الطلبات بالهاتف والبريد والواتساب. بعد نموذج واحد في ClickUp أصبحت كل الطلبات في قائمة واحدة، ولم يضع أي طلب.', 'Facilities used to take requests by phone, email and WhatsApp. With one ClickUp Form every request lands in one List, and none get lost.'],
    wrong: ['نسخ الطلبات يدوياً من البريد إلى المهام.', 'Copying requests by hand from email into tasks.'],
    right: ['شارك رابط نموذج؛ كل إرسال يصبح مهمة تلقائياً.', 'Share a form link; every submission becomes a task automatically.'],
    quiz: { q: ['ماذا يحدث عند إرسال نموذج في ClickUp؟', 'What happens when a ClickUp Form is submitted?'], o: [['يصل بريد فقط', 'Only an email arrives'], ['تُنشأ مهمة في القائمة تلقائياً', 'A task is created in the List automatically'], ['لا شيء حتى يوافق المسؤول', 'Nothing until an admin approves']], a: 1, why: ['كل إرسال يصبح مهمة بحقولها.', 'Every submission becomes a task with its fields.'] }
  },
  mindmap: {
    more: ['هذه ثلاث نظرات من بعيد. لوحة المعلومات تجمع الأرقام والرسوم من عدة قوائم. الخريطة الذهنية (Mind Map) ترسم فكرة رئيسية وفروعها كشجرة، ويمكن أن تكون الفروع مهام حقيقية، فتخطط بصرياً ثم تحصل على قائمة مهام. وعرض الخريطة (Map) يضع المهام على خريطة جغرافية حسب حقل الموقع، مثالي للفرق الميدانية والأبراج والفروع.', 'These are three views from a distance. A Dashboard gathers numbers and charts from several Lists. A Mind Map draws a main idea and its branches as a tree, and branches can be real tasks, so you plan visually and end up with a task list. The Map view places tasks on a geographic map by a Location field, perfect for field teams, towers and branches.'],
    like: ['الخريطة الذهنية مثل شجرة العائلة لمشروعك، وعرض الخريطة مثل خرائط Google لمهامك.', 'A Mind Map is like your project’s family tree, and the Map view is like Google Maps for your tasks.'],
    demo: { scene: 'mindmap', steps: [
      { c: ['في الوسط الهدف الكبير: إطلاق خدمة الألياف.', 'In the centre, the big goal: launch the fibre service.'], nodes: [{ k: 'm0', x: 250, y: 190, n: ['إطلاق الألياف', 'Fibre launch'] }] },
      { c: ['أضف الفروع الرئيسية: التصاريح، المعدات، التسويق.', 'Add the main branches: permits, equipment, marketing.'], nodes: [{ k: 'm0', x: 250, y: 190, n: ['إطلاق الألياف', 'Fibre launch'] }, { k: 'm1', p: 'm0', x: 470, y: 90, n: ['التصاريح', 'Permits'] }, { k: 'm2', p: 'm0', x: 470, y: 190, n: ['المعدات', 'Equipment'] }, { k: 'm3', p: 'm0', x: 470, y: 290, n: ['التسويق', 'Marketing'] }], hl: 'm2' },
      { c: ['قسّم كل فرع إلى أعمال أصغر.', 'Split each branch into smaller pieces of work.'], nodes: [{ k: 'm0', x: 120, y: 190, n: ['إطلاق الألياف', 'Fibre launch'] }, { k: 'm1', p: 'm0', x: 330, y: 90, n: ['التصاريح', 'Permits'] }, { k: 'm2', p: 'm0', x: 330, y: 190, n: ['المعدات', 'Equipment'] }, { k: 'm3', p: 'm0', x: 330, y: 290, n: ['التسويق', 'Marketing'] }, { k: 'm4', p: 'm2', x: 520, y: 160, n: ['طلب الكوابل', 'Order cables'] }, { k: 'm5', p: 'm2', x: 520, y: 220, n: ['حجز الرافعة', 'Book the crane'] }], hl: 'm4' },
      { c: ['حوّل الفروع النهائية إلى مهام حقيقية.', 'Turn the final branches into real tasks.'], nodes: [{ k: 'm0', x: 120, y: 190, n: ['إطلاق الألياف', 'Fibre launch'] }, { k: 'm1', p: 'm0', x: 330, y: 90, n: ['التصاريح', 'Permits'] }, { k: 'm2', p: 'm0', x: 330, y: 190, n: ['المعدات', 'Equipment'] }, { k: 'm3', p: 'm0', x: 330, y: 290, n: ['التسويق', 'Marketing'] }, { k: 'm4', p: 'm2', x: 520, y: 160, n: ['طلب الكوابل', 'Order cables'], task: true }, { k: 'm5', p: 'm2', x: 520, y: 220, n: ['حجز الرافعة', 'Book the crane'], task: true }], hl: 'm5', toast: ['تم إنشاء مهمتين', '2 tasks created'] }
    ] },
    ex: ['فريق صيانة الأبراج أضاف حقل «الموقع» لكل مهمة. في عرض Map رأى المشرف أن 5 أعطال متجاورة في ظفار، فأرسل فريقاً واحداً لها كلها.', 'The tower maintenance team added a Location field to every task. In Map view the supervisor saw 5 faults close together in Dhofar and sent one crew to fix them all.'],
    wrong: ['التخطيط على ورقة ثم إعادة كتابة كل شيء كمهام.', 'Planning on paper and then retyping everything as tasks.'],
    right: ['خطط في الخريطة الذهنية وحوّل الفروع إلى مهام مباشرة.', 'Plan in a Mind Map and turn branches into tasks directly.'],
    quiz: { q: ['ماذا يحتاج عرض الخريطة (Map) ليعمل؟', 'What does the Map view need to work?'], o: [['حقل موقع (Location) في المهام', 'A Location field on the tasks'], ['لوحة معلومات', 'A Dashboard'], ['حساب Google', 'A Google account']], a: 0, why: ['عرض الخريطة يضع المهام حسب حقل الموقع.', 'The Map view places tasks by their Location field.'] }
  },

  /* ---------------- AI ---------------- */
  brain: {
    more: ['Brain يختلف عن أي ذكاء اصطناعي عام لأنه يرى سياق عملك: المهام والمستندات والتعليقات التي لديك صلاحية رؤيتها، ولا يرى ما ليس لك. تستطيع أن تطلب منه: لخّص هذه المهمة، اكتب تحديثاً، اقترح مهاماً فرعية، ترجم، أو اسأله عن أي شيء في مساحة العمل. تذكّر قاعدتين: راجع كل ما يكتبه قبل استخدامه، ولا تُدخل بيانات حساسة إلا إذا سمحت بذلك سياسة الشركة المعتمدة. الميزات المتاحة تعتمد على خطة الاشتراك وإعدادات المسؤولين.', 'Brain differs from general AI because it sees the context of your work: the tasks, Docs and comments you are allowed to see, and nothing that is not yours. You can ask it to summarise a task, write an update, suggest subtasks, translate, or answer anything about the Workspace. Remember two rules: review everything it writes before using it, and do not enter sensitive data unless an approved company policy allows it. Available features depend on the plan and admin settings.'],
    like: ['مثل زميل ذكي قرأ كل ملفات المشروع، يجيبك فوراً، لكنك تراجع عمله قبل إرساله.', 'Like a smart colleague who has read all the project files and answers instantly, but you check their work before sending it.'],
    demo: { scene: 'ai', steps: [
      { c: ['مهمة طويلة بها نقاش كثير. اضغط Ask AI.', 'A long task with a lot of discussion. Click Ask AI.'], ctx: { t: ['تصميم مسار الألياف', 'Design the fibre route'], lines: [['مريم: اقترحت المسار الشمالي لتجنب الطريق الرئيسي.', 'Maryam: proposed the northern route to avoid the main road.'], ['سالم: الشمالي أطول بـ 2 كم لكن تصاريحه أسرع.', 'Salim: northern is 2 km longer but its permits are faster.'], ['خالد: البلدية وافقت مبدئياً على الشمالي.', 'Khalid: the municipality gave initial approval for northern.']] }, chat: [], hl: 'askAI', click: true },
      { c: ['اطلب: «لخّص هذه المهمة في ثلاث نقاط».', 'Ask: “Summarise this task in three points”.'], hl: 'aiInput', click: true, type: { k: 'aiInput', x: ['لخّص هذه المهمة في ثلاث نقاط', 'Summarise this task in three points'] } },
      { c: ['Brain يقرأ المهمة وتعليقاتها…', 'Brain reads the task and its comments…'], ask: null, chat: [C4_AIQ('q1', 'me', ['لخّص هذه المهمة في ثلاث نقاط', 'Summarise this task in three points'])], thinking: true },
      { c: ['الملخص جاهز، من سياق المهمة نفسها.', 'The summary is ready, from the task’s own context.'], thinking: false, chat: [C4_AIQ('q1', 'me', ['لخّص هذه المهمة في ثلاث نقاط', 'Summarise this task in three points']), C4_AIQ('a1', 'ai', ['ملخص:', 'Summary:'], { list: [['المسار الشمالي هو المقترح.', 'The northern route is proposed.'], ['أطول بـ 2 كم وتصاريحه أسرع.', '2 km longer, faster permits.'], ['موافقة مبدئية من البلدية.', 'Initial municipality approval.']] })], hl: 'a1' },
      { c: ['راجع الملخص قبل نسخه إلى تحديث المدير.', 'Review the summary before copying it into the manager update.'], hl: 'a1', toast: ['راجعه دائماً قبل الإرسال', 'Always review before sending'] }
    ] },
    ex: ['مشرفة الجودة كانت تقضي 20 دقيقة في قراءة نقاش طويل قبل كل اجتماع. الآن تطلب ملخصاً من Brain، تراجعه في دقيقتين، وتدخل الاجتماع مستعدة.', 'The quality supervisor used to spend 20 minutes reading a long thread before each meeting. Now she asks Brain for a summary, checks it in two minutes, and walks in prepared.'],
    wrong: ['نسخ ناتج الذكاء الاصطناعي وإرساله للمدير دون قراءة.', 'Copying the AI output and sending it to the manager without reading it.'],
    right: ['استخدمه للمسودة الأولى، وراجع الأسماء والأرقام قبل الإرسال.', 'Use it for the first draft, and check names and numbers before sending.'],
    quiz: { q: ['ما الذي يميز ClickUp Brain عن ذكاء اصطناعي عام؟', 'What makes ClickUp Brain different from a general AI?'], o: [['يرى سياق عملك المسموح لك به', 'It sees the work context you are allowed to see'], ['لا يخطئ أبداً', 'It never makes mistakes'], ['يرى بيانات كل الشركات', 'It sees every company’s data']], a: 0, why: ['Brain يعمل على مهامك ومستنداتك ضمن صلاحياتك، وما زال يحتاج مراجعة.', 'Brain works on your tasks and Docs within your permissions, and still needs review.'] }
  },
  knowledge: {
    more: ['مدير المعرفة يحوّل مساحة العمل إلى مكتبة يمكن سؤالها. بدلاً من البحث بكلمة ثم فتح عشرة مستندات، تسأل سؤالاً كاملاً بلغتك فيبحث في المهام والمستندات (وفي التطبيقات المربوطة إن فُعّلت)، ويكتب الجواب مع روابط المصادر التي اعتمد عليها. افتح المصادر دائماً للتأكد، خاصة قبل أي قرار.', 'The Knowledge Manager turns the Workspace into a library you can question. Instead of searching a word and opening ten Docs, you ask a full question in your own words; it looks through tasks and Docs (and connected apps if enabled) and writes the answer with links to the sources it used. Always open the sources to check, especially before a decision.'],
    like: ['مثل أمين مكتبة يعرف مكان كل كتاب، ويعطيك الجواب مع رقم الصفحة.', 'Like a librarian who knows where every book is and gives you the answer with the page number.'],
    demo: { scene: 'ai', steps: [
      { c: ['اسأل سؤالاً كاملاً، كما تسأل زميلاً.', 'Ask a full question, as you would ask a colleague.'], ctx: { ic: 'doc', t: ['مستندات المشروع', 'Project Docs'], lines: [['محضر اجتماع 10 أكتوبر', 'Minutes of Oct 10 meeting'], ['دليل التصاريح', 'Permits guide'], ['خطة الإطلاق', 'Launch plan']] }, chat: [], hl: 'aiInput', click: true, type: { k: 'aiInput', x: ['ما آخر قرار بخصوص مسار الألياف؟', 'What was the latest decision on the fibre route?'] } },
      { c: ['Brain يبحث في المهام والمستندات المسموح لك بها.', 'Brain searches the tasks and Docs you can access.'], ask: null, chat: [C4_AIQ('q1', 'me', ['ما آخر قرار بخصوص مسار الألياف؟', 'What was the latest decision on the fibre route?'])], thinking: true, hl: 'cl0' },
      { c: ['الجواب مع رابط المصدر: محضر 10 أكتوبر.', 'The answer comes with the source link: the Oct 10 minutes.'], thinking: false, chat: [C4_AIQ('q1', 'me', ['ما آخر قرار بخصوص مسار الألياف؟', 'What was the latest decision on the fibre route?']), C4_AIQ('a1', 'ai', ['تقرر اعتماد المسار الشمالي في اجتماع 10 أكتوبر، بشرط موافقة البلدية النهائية.', 'The northern route was approved in the Oct 10 meeting, pending final municipality approval.'], { src: ['محضر اجتماع 10 أكتوبر', 'Minutes of Oct 10 meeting'] })], hl: 'a1' },
      { c: ['اسأل متابعة: «من المسؤول عن التصاريح؟».', 'Ask a follow-up: “Who is responsible for the permits?”.'], chat: [C4_AIQ('q1', 'me', ['ما آخر قرار بخصوص مسار الألياف؟', 'What was the latest decision on the fibre route?']), C4_AIQ('a1', 'ai', ['تقرر اعتماد المسار الشمالي في اجتماع 10 أكتوبر، بشرط موافقة البلدية النهائية.', 'The northern route was approved in the Oct 10 meeting, pending final municipality approval.'], { src: ['محضر اجتماع 10 أكتوبر', 'Minutes of Oct 10 meeting'] }), C4_AIQ('q2', 'me', ['من المسؤول عن التصاريح؟', 'Who is responsible for the permits?']), C4_AIQ('a2', 'ai', ['خالد، ومهمة «طلب التصاريح» مستحقة في 18 أكتوبر.', 'Khalid; the “Request permits” task is due Oct 18.'], { src: ['طلب تصاريح البلدية', 'Request municipality permits'] })], hl: 'a2' }
    ] },
    ex: ['موظف جديد سأل «ما خطوات طلب إجازة في قسمنا؟» فوجد الجواب من دليل القسم مع الرابط، بدلاً من انتظار رد زميل مشغول.', 'A new employee asked “what are the steps to request leave in our team?” and got the answer from the team guide with a link, instead of waiting for a busy colleague.'],
    wrong: ['الاعتماد على الجواب دون فتح المصدر.', 'Relying on the answer without opening the source.'],
    right: ['افتح رابط المصدر وتأكد، خاصة قبل القرارات.', 'Open the source link and check, especially before decisions.'],
    quiz: { q: ['لماذا تفتح روابط المصادر في جواب مدير المعرفة؟', 'Why open the source links in a Knowledge Manager answer?'], o: [['للتأكد من صحة الجواب', 'To check the answer is correct'], ['لأنها إعلانات', 'Because they are adverts'], ['لا حاجة لفتحها', 'There is no need to open them']], a: 0, why: ['المصدر هو الدليل؛ الذكاء الاصطناعي قد يخطئ في التفاصيل.', 'The source is the evidence; AI can get details wrong.'] }
  },
  pm: {
    more: ['مدير المشاريع في Brain يقرأ ما حدث فعلاً في المهام (ما اكتمل، ما تأخر، من يعمل على ماذا) ويكتب منه تقارير جاهزة: تحديث التقدم الأسبوعي، ملخص اجتماع الصباح (Standup)، أو ملخص ما فعله كل شخص. الأرقام تأتي من بياناتكم، لذلك جودة التقرير تعتمد على تحديث الفريق للحالات بانتظام.', 'The Project Manager in Brain reads what actually happened in the tasks (what finished, what slipped, who is working on what) and writes ready reports from it: the weekly progress update, the morning standup summary, or a summary of what each person did. The numbers come from your data, so the report is only as good as the team’s habit of updating statuses.'],
    like: ['مثل سكرتير يحضر كل الاجتماعات ويكتب التقرير الأسبوعي نيابة عنك.', 'Like an assistant who sits in on everything and writes the weekly report for you.'],
    demo: { scene: 'ai', steps: [
      { c: ['نهاية الأسبوع. اطلب تحديث تقدم للقائمة.', 'End of the week. Ask for a progress update for the List.'], ctx: { ic: 'list', t: ['قائمة التخطيط', 'Planning List'], lines: [['✓ مسح المواقع (سالم)', '✓ Survey sites (Salim)'], ['● تصميم المسار - مراجعة (مريم)', '● Design the route - review (Maryam)'], ['! التصاريح متأخرة يومين (خالد)', '! Permits 2 days late (Khalid)']] }, chat: [], aiTitle: 'AI Project Manager', hl: 'aiInput', click: true, type: { k: 'aiInput', x: ['اكتب تحديث تقدم لهذا الأسبوع', 'Write a progress update for this week'] } },
      { c: ['يقرأ الحالات والتواريخ الفعلية…', 'It reads the real statuses and dates…'], ask: null, chat: [C4_AIQ('q1', 'me', ['اكتب تحديث تقدم لهذا الأسبوع', 'Write a progress update for this week'])], thinking: true },
      { c: ['التحديث جاهز: ما اكتمل، ما قيد العمل، وما يحتاج انتباهاً.', 'The update is ready: done, in progress, and needing attention.'], thinking: false, chat: [C4_AIQ('q1', 'me', ['اكتب تحديث تقدم لهذا الأسبوع', 'Write a progress update for this week']), C4_AIQ('a1', 'ai', ['تحديث الأسبوع:', 'This week:'], { list: [['اكتمل: مسح المواقع.', 'Done: site survey.'], ['قيد المراجعة: تصميم المسار.', 'In review: route design.'], ['يحتاج انتباهاً: التصاريح متأخرة يومين.', 'Needs attention: permits 2 days late.']] })], hl: 'a1' },
      { c: ['راجعه وأرسله في قناة الفريق أو لمديرك.', 'Review it and post it in the team channel or send it to your manager.'], toast: ['تم نسخ التحديث', 'Update copied'] }
    ] },
    ex: ['قائد فريق الشبكات كان يقضي ساعة كل خميس في كتابة التقرير. الآن يطلبه من Brain ويراجعه في 10 دقائق.', 'The network team lead spent an hour every Thursday writing the report. Now he asks Brain for it and reviews it in 10 minutes.'],
    wrong: ['حالات غير محدثة، ثم تقرير آلي خاطئ.', 'Out-of-date statuses, then a wrong automatic report.'],
    right: ['حدّث الحالات يومياً، فيصبح التقرير الآلي دقيقاً.', 'Update statuses daily, and the automatic report becomes accurate.'],
    quiz: { q: ['من أين يأخذ مدير المشاريع بالذكاء الاصطناعي أرقام التقرير؟', 'Where does the AI Project Manager get the report’s numbers?'], o: [['من بيانات المهام الفعلية', 'From the actual task data'], ['يخترعها', 'It makes them up'], ['من الإنترنت', 'From the internet']], a: 0, why: ['التقرير مبني على حالات وتواريخ مهامكم، لذا حدّثوها.', 'The report is built on your task statuses and dates, so keep them updated.'] }
  },
  sop: {
    more: ['إجراء العمل القياسي (SOP) يضمن أن العمل يُنجز بنفس الطريقة مهما تغير الشخص. كتابته من الصفر مملة، فاطلب من الذكاء الاصطناعي مسودة منظمة: الهدف، النطاق، المسؤوليات، الخطوات، والاستثناءات. ثم يأتي الجزء الأهم: تعدّلها لتطابق طريقة فريقك الفعلية، وتضع أسماء المسؤولين الحقيقيين، وتعتمدها مع مالك العملية.', 'A standard operating procedure (SOP) makes sure work is done the same way whoever does it. Writing one from scratch is tedious, so ask the AI for a structured draft: purpose, scope, responsibilities, steps and exceptions. Then comes the most important part: edit it to match how your team really works, add the real owners, and get the process owner to approve it.'],
    like: ['مثل وصفة طعام مكتوبة: أي طاهٍ يتبعها يحصل على نفس الطبق.', 'Like a written recipe: any cook who follows it gets the same dish.'],
    demo: { scene: 'doc', steps: [
      { c: ['أنشئ Doc جديداً واكتب / لتظهر الأوامر.', 'Create a new Doc and type / to see the commands.'], title: ['إجراء استقبال طلب صيانة', 'Procedure: receiving a maintenance request'], blocks: [], slash: 'sAI', hl: 'sAI', click: true },
      { c: ['اختر «Write with AI» واكتب ما تريد.', 'Choose “Write with AI” and describe what you want.'], slash: null, aiBox: ['اكتب SOP لاستقبال طلب صيانة: الهدف، الخطوات، المسؤوليات', 'Write an SOP for receiving a maintenance request: purpose, steps, owners'], hl: 'aiGo', click: true },
      { c: ['المسودة تُكتب أمامك بعناوين وخطوات.', 'The draft is written in front of you with headings and steps.'], aiGen: true, aiBox: ['اكتب SOP لاستقبال طلب صيانة: الهدف، الخطوات، المسؤوليات', 'Write an SOP for receiving a maintenance request: purpose, steps, owners'], blocks: [{ k: 'h1', ty: 'h', x: ['الهدف', 'Purpose'] }, { k: 'p1', ty: 'p', x: ['ضمان استقبال كل طلب صيانة وتسجيله والرد عليه خلال يوم عمل.', 'Make sure every maintenance request is received, logged and answered within one working day.'] }] },
      { c: ['اكتملت المسودة. الآن عدّلها لتطابق الواقع.', 'The draft is complete. Now edit it to match reality.'], aiGen: false, aiBox: null, blocks: [{ k: 'h1', ty: 'h', x: ['الهدف', 'Purpose'] }, { k: 'p1', ty: 'p', x: ['ضمان استقبال كل طلب صيانة وتسجيله والرد عليه خلال يوم عمل.', 'Make sure every maintenance request is received, logged and answered within one working day.'] }, { k: 'h2', ty: 'h', x: ['الخطوات', 'Steps'] }, { k: 'l1', ty: 'li', n: '1', x: ['يصل الطلب عبر النموذج.', 'The request arrives through the form.'] }, { k: 'l2', ty: 'li', n: '2', x: ['يراجعه مشرف المناوبة ويحدد الأولوية.', 'The shift supervisor reviews it and sets priority.'] }, { k: 'l3', ty: 'li', n: '3', x: ['يُسند لفني ويُبلغ مقدم الطلب.', 'It is assigned to a technician and the requester is informed.'] }], hl: 'l2' },
      { c: ['أضف المسؤول الحقيقي، ثم اعرضها على مالك العملية للاعتماد.', 'Add the real owner, then send it to the process owner for approval.'], blocks: [{ k: 'h1', ty: 'h', x: ['الهدف', 'Purpose'] }, { k: 'p1', ty: 'p', x: ['ضمان استقبال كل طلب صيانة وتسجيله والرد عليه خلال يوم عمل.', 'Make sure every maintenance request is received, logged and answered within one working day.'] }, { k: 'h2', ty: 'h', x: ['الخطوات', 'Steps'] }, { k: 'l1', ty: 'li', n: '1', x: ['يصل الطلب عبر النموذج.', 'The request arrives through the form.'] }, { k: 'l2', ty: 'li', n: '2', x: ['يراجعه مشرف المناوبة (خالد) ويحدد الأولوية.', 'The shift supervisor (Khalid) reviews it and sets priority.'] }, { k: 'l3', ty: 'li', n: '3', x: ['يُسند لفني ويُبلغ مقدم الطلب.', 'It is assigned to a technician and the requester is informed.'] }, { k: 'ap', ty: 'task', x: ['اعتماد الإجراء من مالك العملية', 'Process owner approves the SOP'], who: 'maryam' }], hl: 'ap', toast: ['أُرسل للاعتماد', 'Sent for approval'] }
    ] },
    ex: ['قسم المشتريات كتب 6 إجراءات في يوم واحد بمسودات من الذكاء الاصطناعي، ثم راجعها مع المدير خلال أسبوع واعتمدها.', 'Procurement drafted 6 procedures in one day with AI drafts, then reviewed them with the manager over a week and approved them.'],
    wrong: ['نشر مسودة الذكاء الاصطناعي كإجراء رسمي فوراً.', 'Publishing the AI draft as an official procedure straight away.'],
    right: ['المسودة بداية: عدّلها، أضف الأسماء، واعتمدها مع مالك العملية.', 'The draft is a start: edit it, add names, and get the process owner’s approval.'],
    quiz: { q: ['ما الخطوة الأهم بعد أن يكتب الذكاء الاصطناعي مسودة الإجراء؟', 'What is the most important step after AI drafts the SOP?'], o: [['نشرها فوراً', 'Publish it immediately'], ['تعديلها واعتمادها مع مالك العملية', 'Edit it and get the process owner’s approval'], ['ترجمتها فقط', 'Only translate it']], a: 1, why: ['المسودة لا تعرف طريقة فريقك الحقيقية؛ أنت تعرفها.', 'The draft does not know how your team really works; you do.'] }
  },
  superagent: {
    more: ['الوكيل الذكي (Super Agent) يعمل كزميل رقمي له وظيفة محددة. تعطيه: المهمة (ماذا يفعل)، والمُشغّلات (متى يعمل، مثل وصول طلب جديد أو الإشارة إليه)، والأدوات والصلاحيات (ما الذي يستطيع تغييره)، والمعرفة (أي مستندات يعتمد عليها). تنشئه من قسم AI بوصف بلغتك، ويسألك المنشئ أسئلة ليفهم التفاصيل. ابدأ بمهمة صغيرة وواضحة، وجرّبه قبل استخدامه في العمل الحقيقي. التوفر يعتمد على الخطة وإعدادات المسؤول.', 'A Super Agent works like a digital teammate with a specific job. You give it: the job (what it does), triggers (when it runs, such as a new request arriving or being @mentioned), tools and access (what it may change), and knowledge (which Docs it relies on). You create it from the AI area by describing it in your own words, and the builder asks you questions to understand the details. Start with a small, clear job and test it before using it on real work. Availability depends on the plan and admin settings.'],
    like: ['مثل توظيف متدرب ذكي: تكتب له وصفاً وظيفياً واضحاً وتحدد صلاحياته قبل أن يبدأ.', 'Like hiring a smart intern: you write a clear job description and set their access before they start.'],
    demo: { scene: 'agent', steps: [
      { c: ['من AI اختر Create Agent وصف ما تريد بكلماتك.', 'From AI choose Create Agent and describe what you want in your own words.'], nav: 'ai', chat: [], agent: {}, hl: 'bInput', click: true, type: { k: 'bInput', x: ['أريد وكيلاً يستقبل طلبات الصيانة ويحدد أولويتها ويسندها', 'I want an agent that takes maintenance requests, sets priority and assigns them'] } },
      { c: ['المنشئ يسألك ليفهم التفاصيل.', 'The builder asks questions to understand the details.'], ask: null, chat: [C4_AIQ('m1', 'me', ['أريد وكيلاً يستقبل طلبات الصيانة ويحدد أولويتها ويسندها', 'I want an agent that takes maintenance requests, sets priority and assigns them']), C4_AIQ('m2', 'ai', ['متى يعمل؟ ولمن يسند الطلبات العاجلة؟', 'When should it run? And who gets urgent requests?'])], agent: { name: ['وكيل الصيانة', 'Maintenance agent'], job: ['فرز طلبات الصيانة وتحديد أولويتها وإسنادها', 'Sort maintenance requests, set priority and assign them'] }, hl: 'aJob' },
      { c: ['أجبت: عند وصول طلب جديد، والعاجل لمشرف المناوبة.', 'You answer: when a new request arrives; urgent ones go to the shift supervisor.'], chat: [C4_AIQ('m1', 'me', ['أريد وكيلاً يستقبل طلبات الصيانة ويحدد أولويتها ويسندها', 'I want an agent that takes maintenance requests, sets priority and assigns them']), C4_AIQ('m2', 'ai', ['متى يعمل؟ ولمن يسند الطلبات العاجلة؟', 'When should it run? And who gets urgent requests?']), C4_AIQ('m3', 'me', ['عند وصول طلب جديد، والعاجل لخالد', 'When a new request arrives; urgent ones to Khalid'])], agent: { name: ['وكيل الصيانة', 'Maintenance agent'], job: ['فرز طلبات الصيانة وتحديد أولويتها وإسنادها', 'Sort maintenance requests, set priority and assign them'], trig: [['مهمة جديدة في «الطلبات»', 'New task in “Requests”'], ['@الإشارة إليه', '@mention']], tools: [['تعديل الأولوية', 'Set priority'], ['الإسناد', 'Assign'], ['قائمة الطلبات فقط', 'Requests List only']] }, hl: 'aTools' },
      { c: ['أضف المعرفة: دليل الصيانة، ثم فعّله.', 'Add knowledge: the maintenance guide, then activate it.'], agent: { name: ['وكيل الصيانة', 'Maintenance agent'], job: ['فرز طلبات الصيانة وتحديد أولويتها وإسنادها', 'Sort maintenance requests, set priority and assign them'], trig: [['مهمة جديدة في «الطلبات»', 'New task in “Requests”'], ['@الإشارة إليه', '@mention']], tools: [['تعديل الأولوية', 'Set priority'], ['الإسناد', 'Assign'], ['قائمة الطلبات فقط', 'Requests List only']], know: [['دليل الصيانة', 'Maintenance guide']] }, hl: 'activate', click: true },
      { c: ['يعمل الآن. وصل طلب: حدد أولويته وأسنده وكتب سجلاً بما فعل.', 'It is live. A request arrives: it sets priority, assigns it and logs what it did.'], agent: { name: ['وكيل الصيانة', 'Maintenance agent'], job: ['فرز طلبات الصيانة وتحديد أولويتها وإسنادها', 'Sort maintenance requests, set priority and assign them'], trig: [['مهمة جديدة في «الطلبات»', 'New task in “Requests”'], ['@الإشارة إليه', '@mention']], tools: [['تعديل الأولوية', 'Set priority'], ['الإسناد', 'Assign'], ['قائمة الطلبات فقط', 'Requests List only']], know: [['دليل الصيانة', 'Maintenance guide']], active: true, log: [['«انقطاع كهرباء - برج 7»: أولوية عاجل', '“Power outage - tower 7”: priority Urgent'], ['أُسند إلى خالد', 'Assigned to Khalid']] }, hl: 'log1' }
    ] },
    ex: ['مكتب الخدمات المشتركة أنشأ وكيلاً يرد على الأسئلة المتكررة في قناة الدعم من دليل الإجراءات. خفّت الأسئلة التي تصل للموظفين بشكل واضح، وبقيت الأسئلة الصعبة للبشر.', 'The shared-services desk created an agent that answers repeat questions in the support channel from the procedures guide. Questions reaching staff dropped noticeably, and the hard ones stayed with people.'],
    wrong: ['وكيل بصلاحيات على كل مساحة العمل ووصف غامض مثل «ساعد الفريق».', 'An agent with access to the whole Workspace and a vague job like “help the team”.'],
    right: ['وظيفة محددة، ومشغلات واضحة، وأقل صلاحيات تكفي، وتجربة قبل التشغيل.', 'A specific job, clear triggers, the least access needed, and testing before going live.'],
    quiz: { q: ['ما الذي يجب تحديده بوضوح عند إنشاء وكيل ذكي؟', 'What must be clearly defined when creating a Super Agent?'], o: [['لونه المفضل', 'Its favourite colour'], ['وظيفته ومتى يعمل وصلاحياته', 'Its job, when it runs, and its access'], ['لا شيء، يعرف وحده', 'Nothing; it figures it out alone']], a: 1, why: ['الوكيل الجيد له وظيفة ومشغلات وصلاحيات محددة.', 'A good agent has a defined job, triggers and access.'] }
  },
  'superagent-edit': {
    more: ['الوكيل يتحسن بالتعديل مثل أي موظف جديد يتعلم. راجع سجل ما فعله: هل أعطى أولوية خاطئة؟ هل أسند لشخص غير مناسب؟ ثم عدّل التعليمات بأمثلة واضحة («الانقطاع الذي يؤثر على أكثر من 100 عميل = عاجل»)، وأضف حدوداً («لا تغلق أي طلب»)، وحدّث المعرفة إن تغيرت الإجراءات. التعليمات المحددة أفضل من الطويلة.', 'An agent improves with editing, like any new employee learning. Review its log: did it set a wrong priority? Assign to the wrong person? Then edit the instructions with clear examples (“an outage affecting more than 100 customers = Urgent”), add limits (“never close a request”), and refresh its knowledge if procedures change. Specific instructions beat long ones.'],
    like: ['مثل تدريب موظف جديد: تراجع عمله، وتعطيه ملاحظات محددة، فيتحسن.', 'Like coaching a new hire: you review their work, give specific feedback, and they improve.'],
    demo: { scene: 'agent', steps: [
      { c: ['الوكيل يعمل منذ أسبوع. راجع سجله.', 'The agent has run for a week. Review its log.'], nav: 'ai', chat: [], agent: { name: ['وكيل الصيانة', 'Maintenance agent'], job: ['فرز طلبات الصيانة وتحديد أولويتها وإسنادها', 'Sort maintenance requests, set priority and assign them'], trig: [['مهمة جديدة في «الطلبات»', 'New task in “Requests”']], tools: [['تعديل الأولوية', 'Set priority'], ['الإسناد', 'Assign']], know: [['دليل الصيانة', 'Maintenance guide']], active: true, log: [['«عطل مكيف المكتب»: عاجل ✗', '“Office AC fault”: Urgent ✗'], ['«انقطاع برج 3»: عادي ✗', '“Tower 3 outage”: Normal ✗']] }, hl: 'log0' },
      { c: ['أعطى أولويات خاطئة. اضغط Edit agent.', 'It gave wrong priorities. Click Edit agent.'], hl: 'activate', click: true },
      { c: ['أضف قاعدة واضحة بمثال.', 'Add a clear rule with an example.'], hl: 'bInput', click: true, type: { k: 'bInput', x: ['الانقطاع المؤثر على العملاء = عاجل. أعطال المكاتب = عادي.', 'Outages affecting customers = Urgent. Office faults = Normal.'] } },
      { c: ['أضف حدّاً: لا يغلق أي طلب بنفسه.', 'Add a limit: it never closes a request by itself.'], ask: null, chat: [C4_AIQ('e1', 'me', ['الانقطاع المؤثر على العملاء = عاجل. أعطال المكاتب = عادي.', 'Outages affecting customers = Urgent. Office faults = Normal.']), C4_AIQ('e2', 'ai', ['تم. وأضفت: لا يُغلق أي طلب دون إنسان.', 'Done. I also added: never close a request without a person.'])], agent: { name: ['وكيل الصيانة', 'Maintenance agent'], job: ['فرز طلبات الصيانة وتحديد أولويتها وإسنادها', 'Sort maintenance requests, set priority and assign them'], trig: [['مهمة جديدة في «الطلبات»', 'New task in “Requests”']], tools: [['تعديل الأولوية', 'Set priority'], ['الإسناد', 'Assign'], ['بدون إغلاق', 'No closing']], know: [['دليل الصيانة', 'Maintenance guide']], active: true, log: [] }, hl: 'aTools2' },
      { c: ['النتيجة بعد التعديل: أولويات صحيحة.', 'The result after editing: correct priorities.'], agent: { name: ['وكيل الصيانة', 'Maintenance agent'], job: ['فرز طلبات الصيانة وتحديد أولويتها وإسنادها', 'Sort maintenance requests, set priority and assign them'], trig: [['مهمة جديدة في «الطلبات»', 'New task in “Requests”']], tools: [['تعديل الأولوية', 'Set priority'], ['الإسناد', 'Assign'], ['بدون إغلاق', 'No closing']], know: [['دليل الصيانة', 'Maintenance guide']], active: true, log: [['«انقطاع برج 3»: عاجل ✓', '“Tower 3 outage”: Urgent ✓'], ['«عطل مكيف المكتب»: عادي ✓', '“Office AC fault”: Normal ✓']] }, hl: 'log0' }
    ] },
    ex: ['بعد أسبوعين من التعديلات الصغيرة، أصبح وكيل الفرز يصيب في أغلب الأولويات، وصار المشرف يراجع الحالات الصعبة فقط.', 'After two weeks of small edits, the sorting agent got most priorities right, and the supervisor only reviewed the hard cases.'],
    wrong: ['ترك الوكيل يعمل شهوراً دون مراجعة سجله.', 'Leaving the agent running for months without reviewing its log.'],
    right: ['راجع السجل أسبوعياً وعدّل التعليمات بأمثلة محددة.', 'Review the log weekly and adjust instructions with specific examples.'],
    quiz: { q: ['كيف تحسّن وكيلاً يخطئ في الأولويات؟', 'How do you improve an agent that gets priorities wrong?'], o: [['احذفه فوراً', 'Delete it immediately'], ['أضف قواعد وأمثلة واضحة في تعليماته', 'Add clear rules and examples to its instructions'], ['أعطه صلاحيات أكثر', 'Give it more access']], a: 1, why: ['الأمثلة المحددة تعلّم الوكيل ما تقصده بالضبط.', 'Specific examples teach the agent exactly what you mean.'] }
  },
  'ai-ui': {
    more: ['الذكاء الاصطناعي ليس في مكان واحد. في المهمة: لخّص، اقترح مهام فرعية، اكتب تحديثاً. في المستند: اكتب، أعد الصياغة، بسّط، ترجم، حوّل إلى جدول. في التعليقات: صغ رداً مهذباً. في البحث الشامل: اسأل عن أي شيء. وفي مركز الذكاء الاصطناعي (AI Hub) تجد الوكلاء والإعدادات. القاعدة: طلب واضح = نتيجة أفضل. قل من الجمهور، وماذا تريد، وبأي شكل.', 'AI is not in one place. In a task: summarise, suggest subtasks, write an update. In a Doc: write, rephrase, simplify, translate, turn into a table. In comments: draft a polite reply. In enterprise search: ask anything. And in the AI Hub you find agents and settings. The rule: a clear request = a better result. Say who the audience is, what you want, and in which format.'],
    like: ['مثل علبة أدوات: لكل عمل أداة، والذكاء الاصطناعي موجود في أكثر من درج.', 'Like a toolbox: each job has a tool, and AI sits in more than one drawer.'],
    demo: { scene: 'doc', steps: [
      { c: ['في مستند، حدد فقرة تقنية صعبة.', 'In a Doc, select a difficult technical paragraph.'], title: ['شرح الخدمة للعملاء', 'Explaining the service to customers'], blocks: [{ k: 'p1', ty: 'p', x: ['تعتمد الخدمة على شبكة ألياف ضوئية من نوع FTTH بسرعات متماثلة وزمن استجابة منخفض.', 'The service relies on an FTTH fibre network with symmetric speeds and low latency.'] }], hl: 'p1', click: true },
      { c: ['اطلب من الذكاء الاصطناعي: «بسّطها لعميل عادي».', 'Ask the AI: “Simplify it for an everyday customer”.'], aiBox: ['بسّط هذه الفقرة لعميل عادي', 'Simplify this paragraph for an everyday customer'], hl: 'aiGo', click: true },
      { c: ['النتيجة أوضح وأقرب للعميل.', 'The result is clearer and friendlier.'], aiBox: null, blocks: [{ k: 'p1', ty: 'p', x: ['تعتمد الخدمة على شبكة ألياف ضوئية من نوع FTTH بسرعات متماثلة وزمن استجابة منخفض.', 'The service relies on an FTTH fibre network with symmetric speeds and low latency.'] }, { k: 'p2', ty: 'ai', x: ['إنترنت سريع جداً يصل لبيتك بالألياف، بنفس السرعة في التحميل والرفع، وبدون تأخير يذكر.', 'Very fast internet to your home over fibre, the same speed for downloading and uploading, with almost no delay.'] }], hl: 'p2' },
      { c: ['واطلب ترجمتها للإنجليزية بنقرة.', 'And ask for an English translation in one click.'], aiBox: ['ترجم إلى الإنجليزية', 'Translate to English'], hl: 'aiGo', click: true },
      { c: ['جرّب الذكاء الاصطناعي أيضاً في المهام والتعليقات والبحث.', 'Try AI in tasks, comments and search too.'], aiBox: null, blocks: [{ k: 'p2', ty: 'ai', x: ['إنترنت سريع جداً يصل لبيتك بالألياف، بنفس السرعة في التحميل والرفع، وبدون تأخير يذكر.', 'Very fast internet to your home over fibre, the same speed for downloading and uploading, with almost no delay.'] }, { k: 'p3', ty: 'ai', x: ['Very fast fibre internet to your home, with the same upload and download speed and almost no delay.', 'Very fast fibre internet to your home, with the same upload and download speed and almost no delay.'] }], hl: 'askAI' }
    ] },
    ex: ['موظفة خدمة العملاء تكتب الرد بسرعة ثم تطلب «اجعله ألطف وأقصر». توفر وقتاً وتبقى الردود مهذبة ومتسقة.', 'A customer service agent writes a reply quickly, then asks “make it friendlier and shorter”. She saves time and replies stay polite and consistent.'],
    wrong: ['طلبات غامضة مثل «حسّن هذا».', 'Vague requests like “improve this”.'],
    right: ['حدد الجمهور والهدف والشكل: «اجعلها رسالة قصيرة ودودة لعميل».', 'Say the audience, goal and format: “make it a short, friendly message for a customer”.'],
    quiz: { q: ['أي طلب سيعطي نتيجة أفضل؟', 'Which request will give a better result?'], o: [['«حسّن هذا»', '“Improve this”'], ['«اجعلها رسالة قصيرة ودودة لعميل في 3 أسطر»', '“Make it a short, friendly 3-line message for a customer”'], ['«اكتب شيئاً»', '“Write something”']], a: 1, why: ['الطلب الواضح يحدد الجمهور والشكل والطول.', 'A clear request states the audience, format and length.'] }
  },
  notetaker: {
    more: ['مدوّن الاجتماعات يمكنه الانضمام لاجتماعات الفيديو المربوطة بتقويمك، فيسجل وينسخ الحديث، ثم يكتب ملخصاً ويستخرج «بنود العمل»: من سيفعل ماذا. أفضل خطوة بعد الاجتماع: راجع البنود وحوّل المتفق عليه إلى مهام مسندة بمواعيد. تذكّر: أبلغ الحضور قبل التسجيل، ولا تسجل نقاشات حساسة إلا إذا سمحت السياسة. يعتمد على الخطة وإعدادات الشركة.', 'The AI Notetaker can join video meetings connected to your calendar, record and transcribe them, then write a summary and pull out “action items”: who will do what. The best step after the meeting: review the items and turn the agreed ones into assigned tasks with dates. Remember: tell attendees before recording, and do not record sensitive discussions unless policy allows it. It depends on the plan and company settings.'],
    like: ['مثل كاتب محضر محترف يجلس في كل اجتماع ولا ينسى أي قرار.', 'Like a professional minute-taker who sits in every meeting and never forgets a decision.'],
    demo: { scene: 'meeting', steps: [
      { c: ['اجتماع المشروع بدأ، ومدوّن الاجتماعات انضم وبدأ التسجيل.', 'The project meeting starts, and the Notetaker joins and starts recording.'], rec: true, speaker: 'maryam', tab: 'tr', lines: [{ w: 'maryam', x: ['لنراجع موعد الإطلاق.', 'Let’s review the launch date.'] }] },
      { c: ['ينسخ الحديث وهو يجري، باسم كل متحدث.', 'It transcribes the talk as it happens, with each speaker’s name.'], speaker: 'khalid', lines: [{ w: 'maryam', x: ['لنراجع موعد الإطلاق.', 'Let’s review the launch date.'] }, { w: 'khalid', x: ['التصاريح ستتأخر يومين.', 'The permits will be two days late.'] }, { w: 'salim', x: ['سأجهز فريقاً إضافياً لتعويض الوقت.', 'I will prepare an extra crew to make up time.'] }] },
      { c: ['بعد الاجتماع: الملخص جاهز.', 'After the meeting: the summary is ready.'], rec: false, speaker: null, tab: 'sum', sum: [['التصاريح تتأخر يومين.', 'Permits will be two days late.'], ['فريق إضافي لتعويض الوقت.', 'An extra crew will make up the time.'], ['موعد الإطلاق يبقى كما هو.', 'The launch date stays the same.']], hl: 'nt-sum', click: true },
      { c: ['وبنود العمل: من سيفعل ماذا.', 'And the action items: who will do what.'], tab: 'act', acts: [{ k: 'a1', x: ['تجهيز فريق إضافي', 'Prepare an extra crew'], w: 'salim' }, { k: 'a2', x: ['متابعة البلدية يومياً', 'Follow up with the municipality daily'], w: 'khalid' }], mk: true, hl: 'nt-act', click: true },
      { c: ['حوّلها إلى مهام مسندة بنقرة.', 'Turn them into assigned tasks in one click.'], acts: [{ k: 'a1', x: ['تجهيز فريق إضافي', 'Prepare an extra crew'], w: 'salim', task: true }, { k: 'a2', x: ['متابعة البلدية يومياً', 'Follow up with the municipality daily'], w: 'khalid', task: true }], mk: false, hl: 'a1' }
    ] },
    ex: ['قبل المدوّن كانت قرارات الاجتماع الأسبوعي تُنسى خلال يومين. الآن تخرج المهام من الاجتماع مسندة بمواعيد، ويتابعها الجميع في ClickUp.', 'Before the Notetaker, weekly meeting decisions were forgotten within two days. Now tasks leave the meeting assigned with dates, and everyone follows them in ClickUp.'],
    wrong: ['تسجيل الاجتماع دون إبلاغ الحضور.', 'Recording a meeting without telling the attendees.'],
    right: ['أبلغ الحضور، ثم راجع البنود وحوّلها إلى مهام.', 'Tell attendees, then review the items and turn them into tasks.'],
    quiz: { q: ['ما أهم ما تفعله بعد انتهاء الاجتماع المسجل؟', 'What is the key thing to do after a recorded meeting ends?'], o: [['حذف التسجيل', 'Delete the recording'], ['مراجعة بنود العمل وتحويلها إلى مهام مسندة', 'Review the action items and turn them into assigned tasks'], ['لا شيء', 'Nothing']], a: 1, why: ['القرار بلا مهمة ومسؤول وموعد يُنسى.', 'A decision without a task, owner and date gets forgotten.'] }
  }
});
