/* ==========================================================================
   Course: "Mastering ClickUp: the essentials" (1 section, 13 lectures).
   Follows the outline the user supplied, with clearer titles where the
   original lecture names repeated ("What we can found", "How to add space 2").
   The running example is a fictional media team that runs a video channel:
   sponsorships, affiliates, consultations and videos (script, filming,
   editing). Names and data are fictional. Menus can move between versions.
   ========================================================================== */
const ESS_SECTIONS = [{ id: 'e-all', ic: 'compass', c: '#059669', t: ['أساسيات ClickUp خطوة بخطوة', 'ClickUp essentials, step by step'] }];
const ESS_TREE = () => [{ k: 'sp-yt', l: 0, t: 'space', n: ['قناة الفيديو', 'Video channel'], c: '#e03131' }, { k: 'fd-vid', l: 1, t: 'folder', n: ['الفيديوهات', 'Videos'] }, { k: 'ls-scr', l: 2, t: 'list', n: ['النصوص', 'Scripts'], cnt: 4 }, { k: 'ls-edit', l: 2, t: 'list', n: ['المونتاج', 'Editing'], cnt: 3 }, { k: 'fd-spn', l: 1, t: 'folder', n: ['الرعايات', 'Sponsorships'] }];
const ESS_VIDS = () => [
  C4R('v1', ['فيديو: 5 نصائح للإنترنت المنزلي', 'Video: 5 home internet tips'], { st: 'prog', who: 'maryam', due: C4D(12), prio: 'high', tags: [['يوتيوب', 'YouTube']] }),
  C4R('v2', ['نص فيديو: كيف تدفع فاتورتك', 'Script: how to pay your bill'], { st: 'todo', who: 'khalid', due: C4D(14), prio: 'normal', tags: [['نص', 'Script']] }),
  C4R('v3', ['مونتاج فيديو الإطلاق', 'Edit the launch video'], { st: 'rev', who: 'noura', due: C4D(10), prio: 'urgent', tags: [['مونتاج', 'Editing']] }),
  C4R('v4', ['تصوير لقاء العميل', 'Film the customer interview'], { st: 'done', who: 'salim', due: C4D(6), prio: 'normal', tags: [['تصوير', 'Filming']] })
];

const ESS_TOPICS = () => [
  { sec: 'e-all', id: 'e-intro', t: ['مقدمة: إنشاء حساب واختيار الخطة', 'Introduction: create an account and choose a plan'],
    explain: ['تبدأ ClickUp بطريقتين: تسجيل جديد بعنوان بريدك، أو رابط دعوة يرسله لك زميل فتنضم إلى مساحة عمل فريقك مباشرة. والخطة المجانية (Free Forever) تكفي الفرق الصغيرة لتبدأ.', 'You start ClickUp in one of two ways: sign up with your email, or open an invitation link from a colleague to join your team’s Workspace directly. The Free Forever plan is enough for small teams to begin.'],
    more: ['في الشركات غالباً تصلك دعوة من المسؤول، فلا تنشئ مساحة عمل جديدة بنفسك؛ اضغط Join من البريد. صفحة الأسعار تقارن الخطط: المجانية، ثم خطط مدفوعة تضيف مساحة تخزين أكبر وميزات متقدمة. ابدأ بالمجانية للتجربة، والقرار في الشركة عادة لفريق تقنية المعلومات.', 'At work you usually get an invitation from an admin, so do not create a new Workspace yourself; click Join in the email. The pricing page compares plans: Free, then paid plans that add more storage and advanced features. Start free to try it; at a company the plan decision usually belongs to IT.'],
    like: ['مثل بطاقة دخول المبنى: إما تسجّل كزائر جديد، أو يعطيك زميلك بطاقة الفريق مباشرة.', 'Like a building pass: either you register as a new visitor, or a colleague hands you the team’s pass directly.'],
    doit: [['افتح بريد الدعوة واضغط Join Workspace (أو سجّل من clickup.com).', 'Open the invitation email and click Join Workspace (or sign up at clickup.com).'], ['أكمل اسمك واختر كلمة مرور قوية.', 'Fill in your name and choose a strong password.'], ['اطّلع على صفحة الأسعار لتعرف ما تتضمنه الخطة المجانية.', 'Look at the pricing page to see what the Free plan includes.']],
    tip: ['استخدم بريد العمل في حساب العمل؛ ولا تخلط مهامك الشخصية بمساحة عمل الشركة.', 'Use your work email for your work account, and keep personal tasks out of the company Workspace.'],
    demo: { scene: 'login', steps: [
      { c: ['صفحة التسجيل: اكتب بريد العمل.', 'The sign-up page: type your work email.'], hl: 'email', type: { k: 'email', x: 'ashjan@media.example.com' } },
      { c: ['اضغط Continue.', 'Click Continue.'], email: 'ashjan@media.example.com', hl: 'go', click: true },
      { c: ['أو الطريقة الأسهل في العمل: رابط دعوة من زميلتك.', 'Or the easiest way at work: an invitation link from a colleague.'], view: 'invite', hl: 'mail' },
      { c: ['اضغط Join Workspace لتنضم لفريقك مباشرة.', 'Click Join Workspace to join your team directly.'], hl: 'join', click: true, toast: ['انضممت إلى مساحة العمل', 'You joined the Workspace'] }
    ] },
    ex: ['انضمت موظفة جديدة في فريق الإعلام عبر رابط الدعوة، فوجدت مساحة «قناة الفيديو» ومهامها جاهزة من أول دقيقة.', 'A new member of the media team joined through the invitation link and found the “Video channel” Space and her tasks ready from the first minute.'],
    wrong: ['إنشاء مساحة عمل جديدة بدل قبول دعوة الفريق.', 'Creating a new Workspace instead of accepting the team’s invitation.'],
    right: ['اقبل الدعوة من البريد لتدخل مساحة العمل الصحيحة.', 'Accept the invitation from the email to enter the right Workspace.'],
    quiz: { q: ['وصلتك دعوة من فريقك. ماذا تفعل؟', 'You received an invitation from your team. What do you do?'], o: [['أنشئ مساحة عمل جديدة', 'Create a new Workspace'], ['أضغط Join Workspace في البريد', 'Click Join Workspace in the email'], ['أتجاهلها', 'Ignore it']], a: 1, why: ['الدعوة تدخلك مساحة عمل الفريق نفسها بمهامها وأعضائها.', 'The invitation takes you into the team’s own Workspace with its tasks and members.'] } },

  { sec: 'e-all', id: 'e-account', t: ['الحساب والتعرف على أدوات التحكم الرئيسية', 'Your account and the main controls'],
    explain: ['بعد الدخول تعرّف على أربعة أماكن: الشريط العلوي (البحث وزر Create)، والقائمة الجانبية الداكنة (Home وInbox وغيرها)، وشريط المساحات، ومنطقة العمل في الوسط. ويمكنك تثبيت تطبيق سطح المكتب إن لم ترد العمل من المتصفح.', 'After you log in, get to know four places: the top bar (Search and the Create button), the dark side rail (Home, Inbox and more), the Spaces sidebar, and the work area in the middle. You can install the desktop app if you prefer not to use the browser.'],
    more: ['تطبيق سطح المكتب متاح لـ Windows وMac وLinux في كل الخطط، ويقرّب الأفعال المتكررة: إنشاء مهمة، والتذكيرات، والبحث، والإشعارات. والتنظيم كله يقوم على هرم: مساحة العمل ← المساحات ← المجلدات ← القوائم ← المهام ← المهام الفرعية. احفظ Ctrl+K: يبحث في كل شيء.', 'The desktop app is available for Windows, Mac and Linux on every plan, and keeps frequent actions close: creating tasks, reminders, search and notifications. Everything is organised in a pyramid: Workspace → Spaces → Folders → Lists → tasks → subtasks. Remember Ctrl+K: it searches everything.'],
    like: ['مثل أول يوم في مبنى جديد: تعرف المدخل والمصعد والممرات، فلا تضيع بعد ذلك.', 'Like your first day in a new building: learn the entrance, the lift and the corridors, and you never get lost again.'],
    doit: [['سجّل الدخول من المتصفح أو ثبّت تطبيق سطح المكتب من clickup.com/download.', 'Log in from the browser or install the desktop app from clickup.com/download.'], ['مرّر على أيقونات القائمة الجانبية لترى أسماءها.', 'Hover the side-rail icons to see their names.'], ['اضغط Ctrl+K وجرّب البحث.', 'Press Ctrl+K and try searching.'], ['افتح مساحة ثم قائمة ثم مهمة لترى الهرم.', 'Open a Space, then a List, then a task to see the pyramid.']],
    tip: ['ثبّت تطبيق سطح المكتب واجعله يعمل عند بدء التشغيل؛ تصلك الإشعارات دون فتح المتصفح.', 'Install the desktop app and let it start with your computer; notifications reach you without a browser.'],
    demo: { scene: 'shell', steps: [
      { c: ['هذه واجهة ClickUp الرئيسية.', 'This is the main ClickUp screen.'], tree: ESS_TREE(), sel: 'ls-scr', title: ['النصوص', 'Scripts'], rows: ESS_VIDS() },
      { c: ['القائمة الجانبية الداكنة: Home وInbox والذكاء الاصطناعي والمستندات…', 'The dark side rail: Home, Inbox, AI, Docs…'], hl: 'nav' },
      { c: ['شريط المساحات: هرم عملك من المساحة إلى القائمة.', 'The Spaces sidebar: your work’s pyramid from Space to List.'], hl: 'side' },
      { c: ['البحث (Ctrl+K) يجد أي شيء.', 'Search (Ctrl+K) finds anything.'], hl: 'search', click: true, searchOn: true },
      { c: ['وزر Create لإنشاء أي شيء بسرعة.', 'And the Create button makes anything quickly.'], searchOn: false, hl: 'create' }
    ] },
    ex: ['محرر الفيديو ثبّت تطبيق سطح المكتب، فصار يرى إشعار «جاهز للمونتاج» فور تغيير الحالة دون البحث في المتصفح.', 'The video editor installed the desktop app, so he sees the “ready for editing” notification the moment the status changes, without hunting through the browser.'],
    wrong: ['البحث يدوياً بين المساحات عن مهمة نسيت مكانها.', 'Clicking through Spaces by hand to find a task you lost.'],
    right: ['اضغط Ctrl+K واكتب جزءاً من اسمها.', 'Press Ctrl+K and type part of its name.'],
    quiz: { q: ['ما الترتيب الصحيح للهرم في ClickUp؟', 'What is the right order of the ClickUp pyramid?'], o: [['قائمة ← مساحة ← مهمة', 'List → Space → task'], ['مساحة العمل ← مساحة ← مجلد ← قائمة ← مهمة', 'Workspace → Space → Folder → List → task'], ['مهمة ← مجلد ← مساحة العمل', 'Task → Folder → Workspace']], a: 1, why: ['كل مستوى يحتوي الذي تحته، والمهام تعيش داخل القوائم.', 'Each level holds the one below, and tasks live inside Lists.'] } },

  { sec: 'e-all', id: 'e-settings', t: ['الإعدادات والإجراءات السريعة', 'Settings and quick actions'],
    explain: ['زر Create يفتح إجراءات سريعة: مهمة، تذكير، رسالة دردشة، مستند، لوح أبيض، لوحة معلومات. وصفحة My Tasks (Home) وصندوق Inbox يجمعان عملك وإشعاراتك في مكان واحد.', 'The Create button opens quick actions: task, reminder, chat message, Doc, Whiteboard, Dashboard. The My Tasks page (Home) and the Inbox collect your work and notifications in one place.'],
    more: ['عند إنشاء مهمة من النافذة السريعة تختار القائمة والمسؤول والتاريخ والأولوية قبل الحفظ. التذكير شخصي لك فقط. وفي الإعدادات (من صورتك) تضبط ملفك، والإشعارات التي تصلك، والمنطقة الزمنية. My Tasks يرتب مهامك إلى: اليوم، متأخرة، القادمة، بلا موعد.', 'When you create a task from the quick window you choose the List, assignee, date and priority before saving. A reminder is just for you. In Settings (from your avatar) you set your profile, which notifications you get, and your time zone. My Tasks sorts your work into Today, Overdue, Next and Unscheduled.'],
    like: ['مثل لوحة التحكم في السيارة: أزرار سريعة لأكثر ما تحتاجه دون التوقف.', 'Like the controls on a steering wheel: quick buttons for what you need most, without stopping.'],
    doit: [['اضغط Create في الأعلى وجرّب Task.', 'Click Create at the top and try Task.'], ['أنشئ تذكيراً لنفسك لاجتماع الغد.', 'Create a reminder for tomorrow’s meeting.'], ['افتح My Tasks وراجع أقسام اليوم والمتأخرة.', 'Open My Tasks and review Today and Overdue.'], ['من صورتك ← Settings اضبط المنطقة الزمنية والإشعارات.', 'From your avatar → Settings, set your time zone and notifications.']],
    tip: ['ابدأ يومك من My Tasks لا من القوائم؛ يجمع لك ما يخصك من كل المساحات.', 'Start your day in My Tasks, not in Lists; it gathers your work from every Space.'],
    demo: { scene: 'mywork', steps: [
      { c: ['صفحة My Tasks: عملك مرتب حسب الوقت.', 'The My Tasks page: your work sorted by time.'], nav: 'home', rows: [{ k: 'm1', sec: 'today', n: ['مراجعة نص فيديو الفاتورة', 'Review the bill video script'], st: 'prog', due: ['اليوم', 'Today'] }, { k: 'm2', sec: 'overdue', n: ['إرسال عقد الرعاية', 'Send the sponsorship contract'], due: C4D(1) }, { k: 'm3', sec: 'next', n: ['تصوير لقاء العميل', 'Film the customer interview'], due: C4D(8) }] },
      { c: ['اضغط Create.', 'Click Create.'], hl: 'create', click: true },
      { c: ['قائمة الإجراءات السريعة: مهمة، تذكير، دردشة، مستند…', 'The quick actions: task, reminder, chat, Doc…'], createMenu: true, hl: 'cMenu' },
      { c: ['اختر Reminder.', 'Choose Reminder.'], createMenu: 'cm-rem', hl: 'cm-rem', click: true },
      { c: ['اكتب التذكير واحفظه.', 'Type the reminder and save it.'], createMenu: null, rem: { x: ['الاتصال بالراعي قبل النشر', 'Call the sponsor before publishing'], t: ['غداً 9:00', 'Tomorrow 9:00'] }, hl: 'remSave', click: true }
    ] },
    ex: ['منسقة الرعايات كانت تكتب تذكيراتها على أوراق لاصقة. الآن تضغط Create ← Reminder، فيظهر التذكير في My Tasks وعلى جوالها.', 'The sponsorship coordinator used to write reminders on sticky notes. Now she clicks Create → Reminder, and it shows in My Tasks and on her phone.'],
    wrong: ['فتح كل قائمة على حدة كل صباح لتعرف ما عليك.', 'Opening every List one by one each morning to see what is yours.'],
    right: ['ابدأ من My Tasks واستخدم Create للإضافة السريعة.', 'Start from My Tasks and use Create for quick additions.'],
    quiz: { q: ['أين تجد إنشاء تذكير أو لوح أبيض بسرعة؟', 'Where do you quickly create a reminder or a Whiteboard?'], o: [['زر Create في الأعلى', 'The Create button at the top'], ['إعدادات مساحة العمل', 'Workspace settings'], ['صفحة الأسعار', 'The pricing page']], a: 0, why: ['Create يجمع الإجراءات السريعة لكل الأنواع.', 'Create gathers quick actions for every type.'] } },

  { sec: 'e-all', id: 'e-build', t: ['ماذا يمكنك أن تبني؟ مثال قناة فيديو', 'What you can build: a video channel example'],
    explain: ['قاعدة بسيطة: مساحة عمل واحدة للمؤسسة، ومساحة لكل قناة أو قسم، ثم مجلدات للمشاريع (الرعايات، التسويق بالعمولة، الاستشارات، الفيديوهات)، وقوائم للمراحل، ومهام فرعية للخطوات مثل كتابة النص والمونتاج.', 'A simple rule: one Workspace for the organisation, one Space per channel or department, then Folders for projects (sponsorships, affiliates, consultations, videos), Lists for stages, and subtasks for steps such as writing the script and editing.'],
    more: ['لا تنشئ مساحة عمل ثانية لكل فريق: الأشخاص والتقارير يتفرقون. المساحة تحدد من يرى ماذا، والمجلد يجمع المشروع، والقائمة تجمع نوعاً من العمل. مهمة «فيديو جديد» يمكن أن تحوي مهاماً فرعية: النص، التصوير، المونتاج، النشر، ولكل منها مسؤول.', 'Do not create a second Workspace for each team: people and reports get split up. A Space sets who sees what, a Folder groups the project, and a List groups one kind of work. A “New video” task can hold subtasks: script, filming, editing, publishing, each with its own owner.'],
    like: ['مثل شجرة: جذع واحد (مساحة العمل)، وأغصان كبيرة (المساحات)، وأغصان صغيرة (المجلدات والقوائم)، وأوراق (المهام).', 'Like a tree: one trunk (the Workspace), big branches (Spaces), small branches (Folders and Lists) and leaves (tasks).'],
    doit: [['ارسم هيكلك على ورقة: مساحة لكل قناة أو قسم.', 'Sketch your structure on paper: one Space per channel or department.'], ['حدد المجلدات: مشروع أو مجال عمل لكل مجلد.', 'Decide the Folders: one project or work area each.'], ['حدد القوائم والمراحل داخل كل مجلد.', 'Decide the Lists and stages inside each Folder.'], ['ابنِ الهيكل في ClickUp كما رسمته.', 'Build it in ClickUp as you sketched it.']],
    tip: ['إن احترت بين مجلد وقائمة: إذا كان له بداية ونهاية فهو مشروع (مجلد)؛ وإن كان عملاً مستمراً فهو قائمة.', 'If unsure between a Folder and a List: if it has a start and an end it is a project (Folder); if it is ongoing work it is a List.'],
    demo: { scene: 'tree', steps: [
      { c: ['مساحة عمل واحدة لفريق الإعلام.', 'One Workspace for the media team.'], level: 'ws', nodes: [{ k: 'b0', l: 0, t: 'ws', n: ['فريق الإعلام', 'Media team'] }] },
      { c: ['مساحة لكل قناة: الفيديو والبودكاست.', 'One Space per channel: video and podcast.'], level: 'space', nodes: [{ k: 'b0', l: 0, t: 'ws', n: ['فريق الإعلام', 'Media team'] }, { k: 'b1', l: 1, t: 'space', n: ['قناة الفيديو', 'Video channel'] }, { k: 'b2', l: 1, t: 'space', n: ['البودكاست', 'Podcast'] }], hl: 'b1' },
      { c: ['مجلدات للمجالات: الرعايات، العمولة، الاستشارات، الفيديوهات.', 'Folders for areas: sponsorships, affiliates, consultations, videos.'], level: 'folder', nodes: [{ k: 'b0', l: 0, t: 'ws', n: ['فريق الإعلام', 'Media team'] }, { k: 'b1', l: 1, t: 'space', n: ['قناة الفيديو', 'Video channel'] }, { k: 'b3', l: 2, t: 'folder', n: ['الرعايات', 'Sponsorships'] }, { k: 'b4', l: 2, t: 'folder', n: ['التسويق بالعمولة', 'Affiliates'] }, { k: 'b5', l: 2, t: 'folder', n: ['الفيديوهات', 'Videos'] }, { k: 'b2', l: 1, t: 'space', n: ['البودكاست', 'Podcast'] }], hl: 'b5' },
      { c: ['قوائم ومهام داخل «الفيديوهات».', 'Lists and tasks inside “Videos”.'], level: 'task', nodes: [{ k: 'b0', l: 0, t: 'ws', n: ['فريق الإعلام', 'Media team'] }, { k: 'b1', l: 1, t: 'space', n: ['قناة الفيديو', 'Video channel'] }, { k: 'b3', l: 2, t: 'folder', n: ['الرعايات', 'Sponsorships'] }, { k: 'b5', l: 2, t: 'folder', n: ['الفيديوهات', 'Videos'] }, { k: 'b6', l: 3, t: 'list', n: ['قيد الإنتاج', 'In production'] }, { k: 'b7', l: 4, t: 'task', n: ['فيديو: 5 نصائح للإنترنت', 'Video: 5 internet tips'] }, { k: 'b2', l: 1, t: 'space', n: ['البودكاست', 'Podcast'] }], hl: 'b7' }
    ] },
    ex: ['فريق الإعلام كان يستخدم ثلاث مساحات عمل مختلفة فضاعت التقارير. دمجوها في مساحة عمل واحدة بمساحة لكل قناة، فصار المدير يرى كل شيء في لوحة واحدة.', 'The media team used three separate Workspaces and reports got lost. They merged them into one Workspace with a Space per channel, and the manager now sees everything on one Dashboard.'],
    wrong: ['مساحة عمل جديدة لكل فريق أو مشروع.', 'A new Workspace for every team or project.'],
    right: ['مساحة عمل واحدة، ومساحة لكل قناة، ومجلد لكل مشروع.', 'One Workspace, a Space per channel, a Folder per project.'],
    quiz: { q: ['كم مساحة عمل تحتاج المؤسسة عادة؟', 'How many Workspaces does an organisation usually need?'], o: [['واحدة', 'One'], ['واحدة لكل موظف', 'One per employee'], ['واحدة لكل مهمة', 'One per task']], a: 0, why: ['مساحة عمل واحدة تجمع الناس والتقارير؛ والتقسيم يكون بالمساحات.', 'One Workspace keeps people and reports together; you divide work with Spaces.'] } },

  { sec: 'e-all', id: 'e-hier', t: ['هيكل ClickUp: مساحة العمل والأعضاء والحالات', 'The ClickUp hierarchy: Workspace, members and statuses'],
    explain: ['عند إنشاء مساحة عمل تختار استخدامها (عمل، دراسة، شخصي)، ثم تدعو الأعضاء، ثم تنشئ المساحات وتخصصها بأيقونة ولون وقالب وحالات مهام مثل: TO DO، IN PROGRESS، COMPLETE.', 'When you create a Workspace you choose its use (work, school, personal), invite members, then create Spaces and customise them with an icon, colour, template and task statuses such as TO DO, IN PROGRESS and COMPLETE.'],
    more: ['الحالات هي مراحل العمل، وتُضبط على مستوى المساحة أو المجلد أو القائمة. ابدأ بثلاث حالات بسيطة ثم أضف ما يلزم فعلاً، مثل «مراجعة» أو «بانتظار الراعي». الحالة النهائية (Closed) تعني أن العمل انتهى، وتُخفى المهام المغلقة من القوائم افتراضياً.', 'Statuses are the stages of work, set at Space, Folder or List level. Start with three simple statuses, then add only what you really need, such as “Review” or “Waiting for sponsor”. The final (Closed) status means the work is done, and closed tasks are hidden from lists by default.'],
    like: ['الحالات مثل محطات القطار: كل مهمة تمر بها بالترتيب حتى تصل إلى المحطة الأخيرة.', 'Statuses are like train stations: every task passes them in order until it reaches the last stop.'],
    doit: [['أنشئ مساحة عمل واختر نوع الاستخدام.', 'Create a Workspace and choose how you will use it.'], ['ادعُ الأعضاء ببريدهم.', 'Invite members by email.'], ['أنشئ مساحة واختر لها أيقونة ولوناً.', 'Create a Space and pick an icon and colour.'], ['اضبط الحالات: TO DO وIN PROGRESS وCOMPLETE.', 'Set the statuses: TO DO, IN PROGRESS and COMPLETE.']],
    tip: ['لا تتجاوز خمس حالات في البداية؛ كثرة الحالات تجعل الناس يتجاهلون تحديثها.', 'Do not go beyond five statuses at first; too many and people stop updating them.'],
    demo: { scene: 'list', steps: [
      { c: ['مساحة عمل جديدة لفريق الإعلام.', 'A new Workspace for the media team.'], tree: [{ k: 'sp-yt', l: 0, t: 'space', n: ['قناة الفيديو', 'Video channel'], c: '#e03131' }], sel: 'sp-yt', title: ['قناة الفيديو', 'Video channel'], group: 'none', rows: [], hl: 'ws' },
      { c: ['أضف مساحة جديدة من «+» بجانب Spaces.', 'Add a new Space with “+” next to Spaces.'], hl: 'addSpace', click: true },
      { c: ['المساحة الجديدة بلونها وأيقونتها.', 'The new Space with its colour and icon.'], tree: [{ k: 'sp-yt', l: 0, t: 'space', n: ['قناة الفيديو', 'Video channel'], c: '#e03131' }, { k: 'sp-pod', l: 0, t: 'space', n: ['البودكاست', 'Podcast'], c: '#7b68ee' }, { k: 'ls-ep', l: 1, t: 'list', n: ['الحلقات', 'Episodes'], cnt: 3 }], sel: 'ls-ep', title: ['الحلقات', 'Episodes'], hl: 'sp-pod' },
      { c: ['المهام مجمّعة حسب الحالات: TO DO ثم IN PROGRESS ثم COMPLETE.', 'Tasks grouped by status: TO DO, then IN PROGRESS, then COMPLETE.'], group: 'status', rows: [C4R('e1', ['حلقة: مستقبل الإنترنت', 'Episode: the future of the internet'], { st: 'todo', who: 'khalid', due: C4D(15) }), C4R('e2', ['حلقة: الأمان الرقمي', 'Episode: digital safety'], { st: 'prog', who: 'maryam', due: C4D(9) }), C4R('e3', ['حلقة: قصة نجاح', 'Episode: a success story'], { st: 'done', who: 'salim', due: C4D(2) })], hl: 'g-prog' }
    ] },
    ex: ['البودكاست كان يستخدم 9 حالات فلا يحدّثها أحد. خفضوها إلى أربع: فكرة، تسجيل، مونتاج، منشور؛ فصارت محدثة دائماً.', 'The podcast used 9 statuses and nobody updated them. They cut them to four: idea, recording, editing, published; now they are always up to date.'],
    wrong: ['عشر حالات من أول يوم «احتياطاً».', 'Ten statuses from day one, “just in case”.'],
    right: ['ثلاث حالات بسيطة، وأضف حالة فقط عندما تحتاجها فعلاً.', 'Three simple statuses, and add one only when you really need it.'],
    quiz: { q: ['أين تُضبط حالات المهام؟', 'Where are task statuses set?'], o: [['على مستوى المساحة أو المجلد أو القائمة', 'At Space, Folder or List level'], ['في صفحة الأسعار', 'On the pricing page'], ['في ملفك الشخصي', 'In your profile']], a: 0, why: ['الحالات جزء من إعداد المساحة أو المجلد أو القائمة.', 'Statuses are part of the Space, Folder or List setup.'] } },

  { sec: 'e-all', id: 'e-space', t: ['كيف تضيف مساحة (Space)', 'How to add a Space'],
    explain: ['اضغط «+» بجانب Spaces، سمِّ المساحة، واختر لوناً وأيقونة، ثم قالباً أو إعدادات (الحالات، الأتمتة، الميزات). بعدها أنشئ المهام وجرّب طرق العرض: القائمة، واللوحة، والتقويم، ولوحة المعلومات.', 'Click “+” next to Spaces, name the Space, pick a colour and icon, then a template or settings (statuses, automations, features). Then create tasks and try the views: List, Board, Calendar and Dashboard.'],
    more: ['القالب يوفر عليك الإعداد: حالات وحقول جاهزة لنوع العمل (إدارة مشاريع، محتوى، دعم). الأتمتة ترتب العمل المتكرر، مثل إسناد المهمة للمحرر عند تغيير حالتها إلى «مونتاج». طرق العرض لا تنسخ المهام؛ هي نفس المهام بأشكال مختلفة.', 'A template saves setup time: statuses and fields ready for a type of work (project management, content, support). Automations handle repeated work, such as assigning the editor when a task moves to “Editing”. Views do not copy tasks; they are the same tasks shown in different ways.'],
    like: ['مثل غرفة جديدة في البيت: تختار اسمها ولونها، ثم الأثاث (القالب)، ثم تقرر كيف تنظر إليها.', 'Like a new room in a house: choose its name and colour, then the furniture (template), then how you look at it.'],
    doit: [['اضغط «+» بجانب Spaces.', 'Click “+” next to Spaces.'], ['اكتب الاسم واختر اللون والأيقونة.', 'Type the name and choose the colour and icon.'], ['اختر قالباً أو حالات مناسبة، ثم Create.', 'Pick a template or suitable statuses, then Create.'], ['أنشئ مهمة وجرّب Board وCalendar.', 'Create a task and try Board and Calendar.']],
    tip: ['استخدم لوناً مختلفاً لكل مساحة؛ يتعرّف عليها الجميع من نظرة في الشريط الجانبي.', 'Give each Space its own colour; everyone recognises it at a glance in the sidebar.'],
    demo: { scene: 'list', steps: [
      { c: ['اضغط «+» بجانب Spaces.', 'Click “+” next to Spaces.'], tree: [{ k: 'sp-pod', l: 0, t: 'space', n: ['البودكاست', 'Podcast'], c: '#7b68ee' }], sel: 'sp-pod', group: 'none', rows: [], title: ['البودكاست', 'Podcast'], hl: 'addSpace', click: true },
      { c: ['ظهرت مساحة «قناة الفيديو» باللون الأحمر.', 'The “Video channel” Space appears in red.'], tree: ESS_TREE().concat([{ k: 'sp-pod', l: 0, t: 'space', n: ['البودكاست', 'Podcast'], c: '#7b68ee' }]), sel: 'ls-scr', title: ['النصوص', 'Scripts'], hl: 'sp-yt' },
      { c: ['أنشئ مهمة في القائمة.', 'Create a task in the List.'], group: 'status', rows: ESS_VIDS().slice(0, 2), hl: 'addTask', type: { k: 'newTask', x: ['مونتاج فيديو الإطلاق', 'Edit the launch video'] } },
      { c: ['نفس المهام بطرق عرض أخرى: اضغط Board.', 'The same tasks in other views: click Board.'], rows: ESS_VIDS().slice(0, 3), newTask: null, hl: 'tab-board', click: true },
      { c: ['أو أضف عرضاً جديداً مثل Calendar أو Dashboard.', 'Or add a new view such as Calendar or Dashboard.'], pop: 'views', hl: 'v-calendar' }
    ] },
    ex: ['فريق الإعلام أنشأ مساحة «قناة الفيديو» من قالب محتوى. وجدوا حالات النشر جاهزة، فبدأوا العمل في نفس الساعة.', 'The media team created the “Video channel” Space from a content template. The publishing statuses were ready, so they started work within the hour.'],
    wrong: ['إنشاء مساحة بلا قالب ثم بناء كل الحالات يدوياً.', 'Creating a Space with no template, then building every status by hand.'],
    right: ['ابدأ من قالب قريب من عملك ثم عدّل.', 'Start from a template close to your work, then adjust.'],
    quiz: { q: ['هل ينسخ عرض Board المهام؟', 'Does the Board view copy your tasks?'], o: [['نعم، نسخة جديدة', 'Yes, a new copy'], ['لا، هي نفس المهام بشكل مختلف', 'No, they are the same tasks shown differently'], ['يحذف القائمة', 'It deletes the List']], a: 1, why: ['كل طرق العرض تعرض نفس المهام، وأي تغيير يظهر في كل مكان.', 'Every view shows the same tasks, and any change appears everywhere.'] } },

  { sec: 'e-all', id: 'e-space2', t: ['إضافة مساحة - الجزء 2: المجلدات والصلاحيات', 'Adding a Space, part 2: Folders and permissions'],
    explain: ['داخل المساحة أنشئ مجلدات بأسماء واضحة، مثل «العملاء» و«مشاريع يوتيوب». حدد من يرى كل مساحة أو مجلد، وضع بجانب العمل مستنداته ولوحات المعلومات واللوح الأبيض.', 'Inside the Space, create clearly named Folders, such as “Clients” and “YouTube projects”. Decide who can see each Space or Folder, and keep Docs, Dashboards and Whiteboards next to the work.'],
    more: ['الصلاحيات: مساحة خاصة (Private) لا يراها إلا من تضيفه، ويمكن مشاركة مجلد أو قائمة مع شخص معيّن بمستوى: عرض، تعليق، تعديل، أو كامل. المستندات ولوحات المعلومات تعيش أيضاً داخل المساحة، فيجدها الفريق حيث يعمل.', 'Permissions: a Private Space is visible only to people you add, and you can share a Folder or List with someone at a level: view, comment, edit or full. Docs and Dashboards also live inside the Space, so the team finds them where they work.'],
    like: ['مثل مكتب بأدراج مقفلة: كل درج له مفتاح يعطى لمن يحتاجه فقط.', 'Like a desk with locked drawers: each drawer has a key given only to those who need it.'],
    doit: [['مرّر على المساحة واضغط «+» ثم Folder.', 'Hover the Space, click “+”, then Folder.'], ['أنشئ «العملاء» و«مشاريع يوتيوب».', 'Create “Clients” and “YouTube projects”.'], ['من «···» ← Sharing & Permissions حدد من يرى «العملاء».', 'From “···” → Sharing & Permissions, choose who sees “Clients”.'], ['أضف مستنداً ولوحة معلومات داخل المساحة.', 'Add a Doc and a Dashboard inside the Space.']],
    tip: ['اجعل مجلد «العملاء» خاصاً إن كان فيه أسعار وعقود؛ وشارك فقط من يحتاج.', 'Make the “Clients” Folder private if it holds prices and contracts, and share it only with those who need it.'],
    demo: { scene: 'list', steps: [
      { c: ['مساحة «قناة الفيديو» تحتاج تنظيماً.', 'The “Video channel” Space needs organising.'], tree: [{ k: 'sp-yt', l: 0, t: 'space', n: ['قناة الفيديو', 'Video channel'], c: '#e03131' }], sel: 'sp-yt', title: ['قناة الفيديو', 'Video channel'], group: 'none', rows: [] },
      { c: ['أضف مجلدي «العملاء» و«مشاريع يوتيوب».', 'Add the “Clients” and “YouTube projects” Folders.'], tree: [{ k: 'sp-yt', l: 0, t: 'space', n: ['قناة الفيديو', 'Video channel'], c: '#e03131' }, { k: 'fd-cl', l: 1, t: 'folder', n: ['العملاء', 'Clients'] }, { k: 'fd-ytp', l: 1, t: 'folder', n: ['مشاريع يوتيوب', 'YouTube projects'] }], hl: 'fd-ytp' },
      { c: ['أضف المستندات ولوحة المعلومات واللوح الأبيض داخل المساحة.', 'Add Docs, a Dashboard and a Whiteboard inside the Space.'], tree: [{ k: 'sp-yt', l: 0, t: 'space', n: ['قناة الفيديو', 'Video channel'], c: '#e03131' }, { k: 'fd-cl', l: 1, t: 'folder', n: ['العملاء', 'Clients'] }, { k: 'fd-ytp', l: 1, t: 'folder', n: ['مشاريع يوتيوب', 'YouTube projects'] }, { k: 'dc1', l: 1, t: 'doc', n: ['دليل أسلوب القناة', 'Channel style guide'] }, { k: 'db1', l: 1, t: 'dash', n: ['أرقام القناة', 'Channel numbers'] }, { k: 'wb1', l: 1, t: 'wb', n: ['أفكار الفيديوهات', 'Video ideas'] }], hl: 'db1' },
      { c: ['اجعل «العملاء» خاصاً بمن يحتاجه فقط.', 'Make “Clients” private to those who need it.'], hl: 'fd-cl', click: true, toast: ['«العملاء» صار خاصاً', '“Clients” is now private'] }
    ] },
    ex: ['مجلد «العملاء» فيه عقود الرعاية. جعلته المديرة خاصاً بفريق المبيعات، بينما بقي مجلد «مشاريع يوتيوب» مفتوحاً للفريق كله.', 'The “Clients” Folder holds sponsorship contracts. The manager made it private to the sales team, while “YouTube projects” stays open to the whole team.'],
    wrong: ['وضع العقود والأسعار في مجلد يراه الجميع.', 'Putting contracts and prices in a Folder everyone can see.'],
    right: ['مجلد خاص للمعلومات الحساسة، ومشاركة بمستوى مناسب لكل شخص.', 'A private Folder for sensitive information, shared at the right level with each person.'],
    quiz: { q: ['من يرى مساحة خاصة (Private)؟', 'Who can see a Private Space?'], o: [['كل الإنترنت', 'Everyone on the internet'], ['فقط من تمت إضافتهم', 'Only people who were added'], ['لا أحد، ولا حتى أنت', 'No one, not even you']], a: 1, why: ['الخاصة تظهر فقط لمن أضفتهم إليها.', 'A private Space shows only to people you added.'] } },

  { sec: 'e-all', id: 'e-list', t: ['كيف تضيف قائمة (List) وتبني أعمدتها', 'How to add a List and its columns'],
    explain: ['القائمة مكان المهام. أنشئها، ثم أضف المهام بأسمائها، وأسندها للأشخاص، وحدد تواريخ التسليم، وأضف أعمدة (حقولاً) مثل الوسوم، والمهام الفرعية للخطوات.', 'A List is where tasks live. Create it, add tasks with names, assign them to people, set due dates, and add columns (fields) such as Tags, plus subtasks for the steps.'],
    more: ['زر «+» في رأس الأعمدة يضيف عموداً: حقل جاهز (مثل الوسوم والتقدير الزمني) أو حقل مخصص (قائمة منسدلة، رقم، مال، تاريخ). يمكنك دعوة متعاون للقائمة دون إعطائه المساحة كلها. الوسوم (Tags) كلمات قصيرة تساعد على التصفية، مثل «يوتيوب» أو «مونتاج».', 'The “+” at the end of the column headers adds a column: a built-in field (such as Tags or Time estimate) or a Custom Field (dropdown, number, money, date). You can invite a collaborator to a List without giving them the whole Space. Tags are short words that help filtering, such as “YouTube” or “Editing”.'],
    like: ['مثل جدول Excel ذكي: كل صف عمل حقيقي، وكل عمود معلومة عنه.', 'Like a smart Excel sheet: each row is real work, each column a fact about it.'],
    doit: [['مرّر على المجلد واضغط «+» ثم List.', 'Hover the Folder, click “+”, then List.'], ['اضغط Add Task واكتب اسم المهمة ثم Enter.', 'Click Add Task, type the name, then Enter.'], ['أسند المهمة واختر تاريخ التسليم من الأعمدة.', 'Assign the task and pick a due date from the columns.'], ['اضغط «+» في رأس الأعمدة وأضف Tags.', 'Click “+” in the column headers and add Tags.']],
    tip: ['اكتب اسم المهمة بفعل واضح: «صوّر لقاء العميل» أفضل من «لقاء العميل».', 'Name tasks with a clear verb: “Film the customer interview” beats “Customer interview”.'],
    demo: { scene: 'list', steps: [
      { c: ['قائمة «النصوص» الجديدة.', 'The new “Scripts” List.'], tree: ESS_TREE(), sel: 'ls-scr', title: ['النصوص', 'Scripts'], group: 'none', cols: ['assignee', 'due'], rows: ESS_VIDS().slice(0, 1) },
      { c: ['اضغط Add Task واكتب اسم المهمة.', 'Click Add Task and type the task name.'], hl: 'addTask', type: { k: 'newTask', x: ['نص فيديو: كيف تدفع فاتورتك', 'Script: how to pay your bill'] } },
      { c: ['أسندها إلى خالد.', 'Assign it to Khalid.'], newTask: null, rows: ESS_VIDS().slice(0, 1).concat([C4R('v2', ['نص فيديو: كيف تدفع فاتورتك', 'Script: how to pay your bill'], { st: 'todo' })]), hl: 'v2-assignee', click: true, pop: 'assignee' },
      { c: ['اختر خالد ثم حدد تاريخ التسليم.', 'Choose Khalid, then set the due date.'], pop: 'assignee', hl: 'p-khalid', click: true },
      { c: ['أضف عمود Tags من «+».', 'Add a Tags column with “+”.'], rows: ESS_VIDS().slice(0, 1).concat([C4R('v2', ['نص فيديو: كيف تدفع فاتورتك', 'Script: how to pay your bill'], { st: 'todo', who: 'khalid', due: C4D(14) })]), hl: 'addCol', click: true },
      { c: ['ظهر عمود الوسوم: «يوتيوب» و«نص».', 'The Tags column appears: “YouTube” and “Script”.'], cols: ['assignee', 'due', 'tags'], rows: ESS_VIDS().slice(0, 2), hl: 'col-tags' }
    ] },
    ex: ['كاتب النصوص يصفّي القائمة بوسم «نص» فيرى عمله فقط، والمحرر يصفّي بوسم «مونتاج».', 'The script writer filters the List by the “Script” tag to see only his work, and the editor filters by “Editing”.'],
    wrong: ['مهام بلا مسؤول ولا تاريخ؛ لا يعرف أحد من يعمل عليها ومتى.', 'Tasks with no owner and no date; nobody knows who does them or when.'],
    right: ['لكل مهمة مسؤول واحد وتاريخ تسليم، ووسوم للتصفية.', 'Every task gets one owner and a due date, plus tags for filtering.'],
    quiz: { q: ['كيف تضيف عموداً جديداً إلى القائمة؟', 'How do you add a new column to a List?'], o: [['زر «+» في نهاية رأس الأعمدة', 'The “+” at the end of the column headers'], ['تغيير اسم القائمة', 'Renaming the List'], ['من صفحة الأسعار', 'From the pricing page']], a: 0, why: ['«+» يفتح قائمة الحقول الجاهزة والمخصصة.', '“+” opens the list of built-in and Custom Fields.'] } },

  { sec: 'e-all', id: 'e-boardb', t: ['أساسيات عرض اللوحة (Board)', 'Board view basics'],
    explain: ['في عرض Board تظهر كل حالة كعمود وكل مهمة كبطاقة. اسحب البطاقة من «قيد العمل» إلى «مكتمل» فتتغير حالتها. خصص البطاقات بالألوان والصور (الغلاف) والوسوم، وتابع التواريخ والأولويات.', 'In Board view each status is a column and each task is a card. Drag a card from “In progress” to “Complete” and its status changes. Customise cards with colours, cover images and tags, and keep an eye on dates and priorities.'],
    more: ['من «Customize» تختار ما يظهر على البطاقة: المسؤول، التاريخ، الأولوية، الوسوم، وصورة الغلاف (أول صورة مرفقة). العمود المزدحم يكشف عنق الزجاجة: إذا امتلأ عمود «مراجعة» فالمراجعة هي ما يؤخر الفريق.', 'From “Customize” you choose what shows on a card: assignee, date, priority, tags, and a cover image (the first attached image). A crowded column reveals the bottleneck: if “Review” is full, review is what slows the team.'],
    like: ['مثل لوح الأوراق اللاصقة على الحائط، لكنه يتحدث تلقائياً للجميع.', 'Like a sticky-note wall, but it updates itself for everyone.'],
    doit: [['افتح القائمة واضغط Board.', 'Open the List and click Board.'], ['اسحب بطاقة إلى العمود التالي.', 'Drag a card to the next column.'], ['من Customize فعّل الغلاف والوسوم.', 'In Customize, turn on cover images and tags.'], ['راقب أي عمود يمتلئ أكثر.', 'Watch which column fills up most.']],
    tip: ['أرفق صورة مصغرة الفيديو بالمهمة؛ تصبح غلاف البطاقة ويتعرف عليها الفريق فوراً.', 'Attach the video thumbnail to the task; it becomes the card cover and the team recognises it instantly.'],
    demo: { scene: 'board', steps: [
      { c: ['لوحة إنتاج الفيديو.', 'The video production board.'], title: ['الفيديوهات', 'Videos'], cols: [{ st: 'todo', cards: [{ k: 'k2', n: ['نص: كيف تدفع فاتورتك', 'Script: how to pay your bill'], who: 'khalid', due: C4D(14), prio: 'normal', tags: [['نص', 'Script']] }] }, { st: 'prog', cards: [{ k: 'k1', n: ['5 نصائح للإنترنت', '5 internet tips'], who: 'maryam', due: C4D(12), prio: 'high', cover: '#e03131', tags: [['يوتيوب', 'YouTube']] }] }, { st: 'rev', cards: [{ k: 'k3', n: ['مونتاج فيديو الإطلاق', 'Edit the launch video'], who: 'noura', due: C4D(10), prio: 'urgent', cover: '#7b68ee' }] }, { st: 'done', cards: [] }] },
      { c: ['البطاقة فيها غلاف ووسم ومسؤول وتاريخ وأولوية.', 'The card shows a cover, tag, owner, date and priority.'], hl: 'k1' },
      { c: ['انتهى المونتاج: اسحب البطاقة إلى COMPLETE.', 'Editing is done: drag the card to COMPLETE.'], cols: [{ st: 'todo', cards: [{ k: 'k2', n: ['نص: كيف تدفع فاتورتك', 'Script: how to pay your bill'], who: 'khalid', due: C4D(14), prio: 'normal', tags: [['نص', 'Script']] }] }, { st: 'prog', cards: [{ k: 'k1', n: ['5 نصائح للإنترنت', '5 internet tips'], who: 'maryam', due: C4D(12), prio: 'high', cover: '#e03131', tags: [['يوتيوب', 'YouTube']] }] }, { st: 'rev', cards: [] }, { st: 'done', cards: [{ k: 'k3', n: ['مونتاج فيديو الإطلاق', 'Edit the launch video'], who: 'noura', due: C4D(10), prio: 'urgent', cover: '#7b68ee' }] }], hl: 'k3' },
      { c: ['وبدأ خالد كتابة النص: اسحبها إلى IN PROGRESS.', 'And Khalid started the script: drag it to IN PROGRESS.'], cols: [{ st: 'todo', cards: [] }, { st: 'prog', cards: [{ k: 'k1', n: ['5 نصائح للإنترنت', '5 internet tips'], who: 'maryam', due: C4D(12), prio: 'high', cover: '#e03131', tags: [['يوتيوب', 'YouTube']] }, { k: 'k2', n: ['نص: كيف تدفع فاتورتك', 'Script: how to pay your bill'], who: 'khalid', due: C4D(14), prio: 'normal', tags: [['نص', 'Script']] }] }, { st: 'rev', cards: [] }, { st: 'done', cards: [{ k: 'k3', n: ['مونتاج فيديو الإطلاق', 'Edit the launch video'], who: 'noura', due: C4D(10), prio: 'urgent', cover: '#7b68ee' }] }], hl: 'k2' }
    ] },
    ex: ['في اجتماع الأحد يفتح الفريق اللوحة. لاحظوا أن عمود «مراجعة» ممتلئ، فخصصت المديرة ساعة يومياً للمراجعة.', 'In the Sunday meeting the team opens the board. They saw the “Review” column was full, so the manager set aside an hour a day for review.'],
    wrong: ['تحديث الحالة شفهياً في الاجتماع دون تحريك البطاقة.', 'Updating the status out loud in the meeting without moving the card.'],
    right: ['حرّك البطاقة بنفسك فور تغير العمل.', 'Move the card yourself as soon as the work changes.'],
    quiz: { q: ['ماذا يحدث عند سحب بطاقة إلى عمود آخر في Board؟', 'What happens when you drag a card to another column in Board?'], o: [['تُحذف المهمة', 'The task is deleted'], ['تتغير حالة المهمة', 'The task’s status changes'], ['تُنسخ المهمة', 'The task is copied']], a: 1, why: ['كل عمود حالة، فالسحب يغيّر الحالة.', 'Each column is a status, so dragging changes the status.'] } },

  { sec: 'e-all', id: 'e-fields', t: ['المهام والمسؤولون والأولويات والمواعيد', 'Tasks, assignees, priorities and deadlines'],
    explain: ['أضف المهام، وأسند كل واحدة لشخص، وحدد أولويتها (عاجلة، عالية، عادية، منخفضة) وموعد تسليمها. ثم حرّكها بين الحالات وتابع التقدم وحمل كل شخص.', 'Add tasks, assign each one to a person, set its priority (Urgent, High, Normal, Low) and deadline. Then move it between statuses and follow progress and each person’s workload.'],
    more: ['الأولوية تخبر الفريق بما يبدأ أولاً، لا بما هو مهم فقط؛ لا تجعل كل شيء «عاجلاً». التاريخ المتأخر يظهر باللون الأحمر. التجميع حسب المسؤول يريك حمل كل شخص بسرعة، فإن كان أحدهم مثقلاً انقل مهمة لزميل.', 'Priority tells the team what to start first, not just what matters; do not make everything “Urgent”. Overdue dates show in red. Grouping by assignee shows each person’s load quickly; if someone is overloaded, move a task to a colleague.'],
    like: ['مثل طابور المطعم: الطلب العاجل يتقدم، والكل يعرف دوره وموعده.', 'Like a restaurant queue: the urgent order goes first, and everyone knows their turn and time.'],
    doit: [['أضف مهمة واضغط على عمود الأولوية.', 'Add a task and click its priority column.'], ['اختر Urgent فقط إن كانت فعلاً لا تنتظر.', 'Choose Urgent only if it truly cannot wait.'], ['حدد تاريخ التسليم والمسؤول.', 'Set the due date and assignee.'], ['جمّع حسب Assignee لترى حمل كل شخص.', 'Group by Assignee to see each person’s load.']],
    tip: ['اتفقوا كفريق على معنى كل أولوية؛ مثلاً «عاجل = خلال 24 ساعة».', 'Agree as a team on what each priority means; for example, “Urgent = within 24 hours”.'],
    demo: { scene: 'list', steps: [
      { c: ['مهام الفيديو مجمّعة حسب الحالة.', 'The video tasks grouped by status.'], tree: ESS_TREE(), sel: 'ls-edit', title: ['المونتاج', 'Editing'], rows: ESS_VIDS() },
      { c: ['الأولوية: «مونتاج الإطلاق» عاجلة.', 'Priority: “Edit the launch video” is urgent.'], hl: 'v3-prio' },
      { c: ['جمّع حسب المسؤول لترى حمل كل شخص.', 'Group by assignee to see each person’s load.'], group: 'assignee', hl: 'g-maryam' },
      { c: ['انتهى النص: غيّر حالته إلى IN PROGRESS للتصوير.', 'The script is done: move it to IN PROGRESS for filming.'], group: 'status', rows: ESS_VIDS().map(r => r.k === 'v2' ? Object.assign({}, r, { st: 'prog' }) : r), hl: 'v2', toast: ['التقدم: 1 من 4 مكتملة', 'Progress: 1 of 4 complete'] }
    ] },
    ex: ['كانت كل مهام القناة «عاجلة». بعد الاتفاق على أن العاجل خلال 24 ساعة فقط، صار الفريق يعرف بماذا يبدأ صباحاً.', 'Every channel task used to be “Urgent”. After agreeing that urgent means within 24 hours, the team knows what to start with each morning.'],
    wrong: ['جعل كل المهام عاجلة.', 'Making every task urgent.'],
    right: ['أولويات قليلة العاجل، ومعنى متفق عليه لكل مستوى.', 'Few urgent tasks, and an agreed meaning for each level.'],
    quiz: { q: ['كيف ترى بسرعة إن كان شخص مثقلاً بالمهام؟', 'How do you quickly see if someone has too many tasks?'], o: [['التجميع حسب المسؤول', 'Group by assignee'], ['تغيير لون المساحة', 'Change the Space colour'], ['حذف المهام', 'Delete tasks']], a: 0, why: ['التجميع حسب المسؤول يضع مهام كل شخص تحت اسمه.', 'Grouping by assignee puts each person’s tasks under their name.'] } },

  { sec: 'e-all', id: 'e-task', t: ['داخل المهمة: التواريخ والتقدير والمرفقات والتصويت', 'Inside a task: dates, estimates, attachments and votes'],
    explain: ['افتح المهمة لتدير تفاصيلها: المسؤول، وتاريخ البدء والتسليم، والأولوية، والتقدير الزمني، والمرفقات، وقائمة التحقق (Checklist)، وحتى التصويت لمعرفة رأي الفريق.', 'Open a task to manage its details: owner, start and due dates, priority, time estimate, attachments, a checklist, and even votes to learn what the team thinks.'],
    more: ['تاريخ البدء مع تاريخ التسليم يرسم المهمة كشريط في عرض Gantt والتقويم. التقدير الزمني يساعد Workload على حساب الحمل. قائمة التحقق لخطوات صغيرة لا تحتاج مسؤولاً منفصلاً. التصويت حقل مخصص (Voting) يفيد في اختيار الأفكار أو الأولويات.', 'A start date plus a due date draws the task as a bar in Gantt and Calendar. A time estimate helps Workload measure the load. A checklist is for small steps that do not need their own owner. Voting is a Custom Field that helps choose ideas or priorities.'],
    like: ['مثل ملف ورقي لكل عمل: فيه المواعيد والمرفقات والملاحظات وورقة توقيعات الموافقة.', 'Like a paper folder for each job: dates, attachments, notes and a sign-off sheet.'],
    doit: [['افتح مهمة واضغط على Dates وحدد البدء والتسليم.', 'Open a task, click Dates and set start and due.'], ['أضف تقديراً زمنياً.', 'Add a time estimate.'], ['أرفق ملفاً بالسحب والإفلات.', 'Attach a file by drag and drop.'], ['أضف Checklist بالخطوات الصغيرة.', 'Add a Checklist with the small steps.'], ['إن كان مفعلاً: صوّت على المهمة.', 'If it is turned on: vote on the task.']],
    tip: ['استخدم Checklist لخطوات النشر الثابتة: العنوان، الصورة المصغرة، الوصف، الوسوم.', 'Use a Checklist for fixed publishing steps: title, thumbnail, description, tags.'],
    demo: { scene: 'task', steps: [
      { c: ['مهمة «فيديو: 5 نصائح للإنترنت».', 'The task “Video: 5 internet tips”.'], title: ['فيديو: 5 نصائح للإنترنت المنزلي', 'Video: 5 home internet tips'], title2: ['الفيديوهات', 'Videos'], st: 'prog', who: ['maryam'], prio: 'high', due: C4D(12) },
      { c: ['أضف تاريخ البدء: صارت المهمة شريطاً زمنياً.', 'Add a start date: the task becomes a time bar.'], start: C4D(8), hl: 'tStart' },
      { c: ['أضف تقديراً زمنياً: 6 ساعات.', 'Add a time estimate: 6 hours.'], est: ['6 ساعات', '6h'], hl: 'tEst' },
      { c: ['أرفق النص والصورة المصغرة.', 'Attach the script and the thumbnail.'], files: [{ n: 'script-v2.docx', ic: 'doc' }, { n: 'thumbnail.png', ic: 'eye' }], hl: 'f1' },
      { c: ['قائمة تحقق لخطوات النشر.', 'A checklist for the publishing steps.'], check: [{ k: 'ck1', n: ['العنوان', 'Title'], done: true }, { k: 'ck2', n: ['الصورة المصغرة', 'Thumbnail'], done: true }, { k: 'ck3', n: ['الوصف والوسوم', 'Description and tags'] }], hl: 'ck3' },
      { c: ['والتصويت: الفريق يصوّت لهذه الفكرة.', 'And votes: the team votes for this idea.'], votes: 4, voted: true, hl: 'tVotes', click: true }
    ] },
    ex: ['قبل كل نشر، تفتح المحررة المهمة فتجد النص والصورة المصغرة مرفقين، وقائمة التحقق تذكرها بالوصف والوسوم.', 'Before every upload the editor opens the task and finds the script and thumbnail attached, and the checklist reminds her of the description and tags.'],
    wrong: ['إرسال الملفات في الدردشة فتضيع بين الرسائل.', 'Sending files in chat where they get lost among messages.'],
    right: ['أرفق الملفات بالمهمة نفسها لتبقى مع العمل.', 'Attach files to the task itself so they stay with the work.'],
    quiz: { q: ['ما فائدة إضافة تاريخ البدء مع تاريخ التسليم؟', 'What is the benefit of adding a start date with the due date?'], o: [['تظهر المهمة شريطاً في Gantt والتقويم', 'The task shows as a bar in Gantt and Calendar'], ['تُحذف المهمة بعد التاريخ', 'The task is deleted after the date'], ['تتغير الأولوية', 'The priority changes']], a: 0, why: ['البدء والتسليم معاً يحددان مدة المهمة على الخط الزمني.', 'Start and due together set the task’s length on the timeline.'] } },

  { sec: 'e-all', id: 'e-team', t: ['استخدام عرض الفريق (Team view)', 'Using Team view'],
    explain: ['عرض الفريق (Team view، كان اسمه Box view) يضع كل شخص في صندوق: ماذا ينجز، وماذا أنجز، وكم عليه. غيّر الفترة (اليوم، 7 أيام، 14 يوماً، أسبوع، شهر) وجمّع حسب الحالة أو الأولوية.', 'Team view (formerly Box view) puts each person in a box: what they are working on, what they finished, and how much they have. Change the period (today, 7 days, 14 days, week, month) and group by status or priority.'],
    more: ['الشريط الملون في كل صندوق يقسم مهام الشخص حسب الحالة. إن كان أحدهم مثقلاً، اسحب مهمة من صندوقه إلى صندوق زميل لإعادة التوزيع. ولقياس الساعات والسعة اليومية بدقة، استخدم عرض Workload.', 'The coloured bar in each box splits the person’s tasks by status. If someone is overloaded, drag a task from their box to a colleague’s to rebalance. To measure hours and daily capacity precisely, use the Workload view.'],
    like: ['مثل لوحة المدرب في المباراة: يرى كل لاعب وأين يقف.', 'Like a coach’s board in a match: every player and where they stand.'],
    doit: [['أضف عرضاً جديداً واختر Team.', 'Add a new view and choose Team.'], ['اختر الفترة: 7 أيام أو 14 يوماً.', 'Pick the period: 7 or 14 days.'], ['جمّع حسب الحالة أو الأولوية.', 'Group by status or priority.'], ['اسحب مهمة بين الصناديق لإعادة التوزيع.', 'Drag a task between boxes to rebalance.']],
    tip: ['افتح عرض الفريق كل خميس لتوزيع عمل الأسبوع القادم قبل أن يبدأ.', 'Open Team view every Thursday to share out next week’s work before it starts.'],
    demo: { scene: 'team', steps: [
      { c: ['عرض الفريق: صندوق لكل شخص.', 'Team view: one box per person.'], tree: ESS_TREE(), sel: 'ls-edit', title: ['الفيديوهات', 'Videos'], people: [{ who: 'maryam', n: [2, 3, 1, 1], tasks: [{ k: 't1', n: ['5 نصائح للإنترنت', '5 internet tips'], st: 'prog', prio: 'high' }, { k: 't2', n: ['فيديو الإطلاق', 'Launch video'], st: 'rev', prio: 'urgent' }] }, { who: 'khalid', n: [1, 1, 0, 2], tasks: [{ k: 't3', n: ['نص الفاتورة', 'Bill script'], st: 'prog' }] }, { who: 'noura', n: [0, 1, 0, 3], tasks: [{ k: 't4', n: ['مونتاج المقدمة', 'Edit the intro'], st: 'prog' }] }] },
      { c: ['مريم عندها 7 مهام: أكثر من زملائها.', 'Maryam has 7 tasks: more than her colleagues.'], hl: 'tb-maryam' },
      { c: ['غيّر الفترة إلى 14 يوماً.', 'Change the period to 14 days.'], range: '14', hl: 'tr-14', click: true },
      { c: ['انقل «فيديو الإطلاق» إلى نورة.', 'Move “Launch video” to Noura.'], people: [{ who: 'maryam', n: [2, 3, 0, 1], tasks: [{ k: 't1', n: ['5 نصائح للإنترنت', '5 internet tips'], st: 'prog', prio: 'high' }] }, { who: 'khalid', n: [1, 1, 0, 2], tasks: [{ k: 't3', n: ['نص الفاتورة', 'Bill script'], st: 'prog' }] }, { who: 'noura', n: [0, 1, 1, 3], tasks: [{ k: 't4', n: ['مونتاج المقدمة', 'Edit the intro'], st: 'prog' }, { k: 't2', n: ['فيديو الإطلاق', 'Launch video'], st: 'rev', prio: 'urgent' }] }], hl: 't2', toast: ['توزّع العمل بشكل أفضل', 'The work is better balanced'] }
    ] },
    ex: ['لاحظت المديرة في عرض الفريق أن المحرر عنده 9 مهام وزميله 2. نقلت ثلاث مهام فانتهى المونتاج قبل موعده.', 'In Team view the manager saw one editor had 9 tasks and his colleague 2. She moved three tasks and the editing finished early.'],
    wrong: ['توزيع المهام دون معرفة حمل كل شخص.', 'Handing out tasks without knowing each person’s load.'],
    right: ['انظر إلى عرض الفريق قبل الإسناد، ووزّع بالسحب.', 'Check Team view before assigning, and rebalance by dragging.'],
    quiz: { q: ['ما الاسم السابق لعرض الفريق (Team view)؟', 'What was Team view called before?'], o: [['Box view', 'Box view'], ['Mind Map', 'Mind Map'], ['Doc view', 'Doc view']], a: 0, why: ['Team view هو الاسم الجديد لـ Box view.', 'Team view is the new name for Box view.'] } },

  { sec: 'e-all', id: 'e-map', t: ['خريطة الفريق: عرض Map', 'Team map: the Map view'],
    explain: ['عرض Map يضع المهام على خريطة حسب حقل الموقع (Location). مفيد لمواقع التصوير أو زيارات العملاء: ترى أين كل مهمة، وتنسخ رابط العرض لمشاركته، أو تحذفه عندما لا تحتاجه.', 'The Map view places tasks on a map using a Location field. It is useful for filming locations or client visits: you see where each task is, copy the view’s link to share it, or delete the view when you no longer need it.'],
    more: ['أضف أولاً حقلاً مخصصاً من نوع Location للمهام، واكتب العنوان (يعتمد على خرائط Google). ثم أضف عرض Map. لون الدبوس يمكن أن يتبع الحالة أو الأولوية. من «···» على العرض: نسخ الرابط، إعادة التسمية، أو الحذف. لا تنشر عناوين خاصة برابط عام.', 'First add a Location Custom Field to the tasks and type the address (it is based on Google Maps). Then add a Map view. The pin colour can follow status or priority. From the view’s “···”: copy link, rename or delete. Never publish private addresses with a public link.'],
    like: ['مثل خرائط Google لمهامك: كل دبوس عمل ينتظرك في مكان.', 'Like Google Maps for your tasks: every pin is work waiting for you somewhere.'],
    doit: [['أضف حقل Location إلى القائمة واكتب العناوين.', 'Add a Location field to the List and type the addresses.'], ['اضغط «+ View» واختر Map.', 'Click “+ View” and choose Map.'], ['اضغط دبوساً لترى المهمة.', 'Click a pin to see the task.'], ['من «···» انسخ الرابط أو احذف العرض.', 'From “···” copy the link or delete the view.']],
    tip: ['لوّن الدبابيس حسب الحالة؛ ترى المواقع التي انتهى تصويرها بنظرة.', 'Colour pins by status; you see at a glance which locations are already filmed.'],
    demo: { scene: 'map', steps: [
      { c: ['مواقع تصوير الفيديوهات على الخريطة.', 'The video filming locations on the map.'], title: ['مواقع التصوير', 'Filming locations'], pins: [{ k: 'pn1', x: 30, y: 60, c: '#10b981', n: ['تصوير لقاء العميل - مسقط', 'Customer interview - Muscat'] }, { k: 'pn2', x: 55, y: 40, c: '#5b45d6', n: ['تصوير المتجر - صحار', 'Store shoot - Sohar'] }, { k: 'pn3', x: 75, y: 25, c: '#87909e', n: ['تصوير البرج - صلالة', 'Tower shoot - Salalah'] }] },
      { c: ['اضغط دبوساً لترى مهمته.', 'Click a pin to see its task.'], open: 'pn2', hl: 'pn2', click: true },
      { c: ['الدبوس الأخضر: تصوير مكتمل.', 'The green pin: filming complete.'], open: 'pn1', hl: 'pn1' },
      { c: ['من «···» انسخ رابط العرض أو احذفه.', 'From “···” copy the view link or delete it.'], open: null, vmenu: [['Copy link', 'link'], ['Rename', 'tag'], ['Delete view', 'trash']], hl: 'vm0', click: true, toast: ['نُسخ الرابط', 'Link copied'] }
    ] },
    ex: ['فريق التصوير يرتب زياراته من عرض Map: الدبابيس القريبة من بعضها في يوم واحد، فوفّروا يوم سفر كاملاً.', 'The filming crew plans visits from Map view: nearby pins on the same day, which saved a whole day of travel.'],
    wrong: ['كتابة العناوين في الوصف فلا تظهر على الخريطة.', 'Writing addresses in the description, so they never show on the map.'],
    right: ['استخدم حقل Location ليظهر كل موقع دبوساً على الخريطة.', 'Use a Location field so every place shows as a pin on the map.'],
    quiz: { q: ['ماذا يحتاج عرض Map ليضع المهام على الخريطة؟', 'What does Map view need to place tasks on the map?'], o: [['حقل Location', 'A Location field'], ['وسم «خريطة»', 'A “map” tag'], ['لوحة معلومات', 'A Dashboard']], a: 0, why: ['الدبوس يُرسم من عنوان حقل Location.', 'Each pin is drawn from the Location field’s address.'] } }
];
