/* ==========================================================================
   Clicky knowledge base: questions employees commonly ask about ClickUp,
   written in plain words for this hub (Arabic + English). Topics follow the
   public ClickUp Help Center and University course catalogue; wording is our
   own. Menus can move between ClickUp versions and plans, so answers say
   where to look rather than promise exact pixel positions.
   Each row: [tour part, id, [q ar, q en], [a ar, a en], extra keywords, link]
   ========================================================================== */
const CLICKY_KB = [
  /* ---- Getting started and navigation ---- */
  ['start', 'kb-what', ['ما هو ClickUp؟', 'What is ClickUp?'], ['ClickUp منصة عمل واحدة تجمع المهام والمستندات والمحادثات واللوحات والأهداف. تنظّم فيها عمل فريقك وتتابع من يفعل ماذا ومتى.', 'ClickUp is one work platform for tasks, Docs, chat, dashboards and goals. Your team organizes its work there and sees who does what, and by when.'], 'platform tool app about منصة برنامج تطبيق'],
  ['start', 'kb-login', ['كيف أدخل إلى ClickUp؟', 'How do I log in to ClickUp?'], ['افتح app.clickup.com أو تطبيق الجوال وادخل ببريد العمل. إن كانت شركتك تستخدم الدخول الموحّد (SSO) فاختر «Continue with SSO». إن لم تصلك دعوة فاطلبها من مسؤول مساحة العمل.', 'Open app.clickup.com or the mobile app and sign in with your work email. If your company uses single sign-on (SSO), choose the SSO option. No invite yet? Ask your Workspace admin.'], 'login log sign signin password invite دخول تسجيل كلمة مرور دعوة'],
  ['start', 'kb-password', ['نسيت كلمة المرور، ماذا أفعل؟', 'I forgot my password. What do I do?'], ['في صفحة الدخول اختر «Forgot password» وستصلك رسالة لإعادة التعيين. إن كان الدخول عبر SSO فكلمة المرور هي كلمة مرور الشركة، فتواصل مع دعم تقنية المعلومات.', 'On the login page choose "Forgot password" and you get a reset email. If you sign in with SSO, it is your company password, so contact IT support.'], 'forgot reset password locked نسيت كلمه المرور مقفل'],
  ['start', 'kb-sidebar', ['ما هو الشريط الجانبي في ClickUp؟', 'What is the ClickUp sidebar?'], ['الشريط الجانبي على اليسار يعرض مساحاتك ومجلداتك وقوائمك، ومعها الصفحة الرئيسية وصندوق الوارد والمستندات واللوحات. يمكنك تصغيره أو تثبيت ما تستخدمه كثيراً في المفضلة.', 'The sidebar on the left shows your Spaces, Folders and Lists, plus Home, Inbox, Docs and Dashboards. You can collapse it and keep what you use often in Favorites.'], 'sidebar menu left panel navigate navigation شريط قائمة جانبي تنقل'],
  ['start', 'kb-favorites', ['كيف أضيف قائمة إلى المفضلة؟', 'How do I add a List to Favorites?'], ['مرّر المؤشر على القائمة أو المستند في الشريط الجانبي، افتح قائمة النقاط (…) واختر «Add to Favorites». تظهر في قسم المفضلة أعلى الشريط.', 'Hover the List or Doc in the sidebar, open the ellipsis (…) menu and choose "Add to Favorites". It appears in the Favorites section at the top.'], 'favorite favorites pin star shortcut مفضلة تثبيت نجمة'],
  ['start', 'kb-home', ['ما هي صفحة «مهامي» (Home)؟', 'What is the My Tasks (Home) page?'], ['صفحة «مهامي»، وكانت تُسمّى Home، تجمع المهام المسندة إليك والتذكيرات والتقويم في مكان واحد. ابدأ يومك منها.', 'The My Tasks page, formerly called Home, gathers the tasks assigned to you, your reminders and your calendar in one place. Start your day there.'], 'home my tasks today dashboard personal الرئيسية مهامي اليوم'],
  ['start', 'kb-inbox', ['ما هو صندوق الوارد (Inbox)؟', 'What is the Inbox?'], ['صندوق الوارد يجمع الإشعارات: الإشارات إليك، والتعليقات، وتغييرات المهام التي تتابعها. علّم الإشعار كمقروء أو «Clear» عند الانتهاء منه.', 'The Inbox collects your notifications: mentions, comments and changes on tasks you watch. Mark items as read or clear them when you are done.'], 'inbox notification unread وارد صندوق غير مقروء'],
  ['start', 'kb-workspace-switch', ['كيف أنتقل بين مساحات العمل؟', 'How do I switch Workspaces?'], ['اضغط على صورة حسابك أو اسم مساحة العمل في الزاوية العلوية واختر مساحة العمل الأخرى. معظم الموظفين يعملون في مساحة عمل واحدة للشركة.', 'Click your avatar or the Workspace name in the top corner and pick the other Workspace. Most employees work in one company Workspace.'], 'switch workspace another account change تبديل انتقل مساحة عمل'],
  ['start', 'kb-profile', ['كيف أغيّر صورتي أو اسمي؟', 'How do I change my photo or name?'], ['اضغط صورة حسابك ثم «Settings» أو «My Settings». من هناك غيّر الصورة والاسم والمنطقة الزمنية.', 'Click your avatar, then Settings (My Settings). Change your photo, name and time zone there.'], 'profile photo picture avatar name settings صورة اسم ملف شخصي اعدادات'],
  ['start', 'kb-timezone', ['مواعيد المهام تظهر بتوقيت خاطئ', 'Due times show in the wrong time zone'], ['تأكد من المنطقة الزمنية في إعداداتك الشخصية (My Settings). اختر توقيت مسقط (GMT+4) لتظهر المواعيد صحيحة.', 'Check the time zone in your personal settings (My Settings). Choose Muscat (GMT+4) so due times show correctly.'], 'timezone zone clock wrong hour توقيت منطقه زمنيه ساعه خطا'],
  ['start', 'kb-dark', ['هل يوجد وضع داكن؟', 'Is there a dark mode?'], ['نعم. من إعداداتك اختر المظهر (Theme) ثم الوضع الداكن أو التلقائي حسب جهازك.', 'Yes. In your settings open the theme options and choose dark, or auto to follow your device.'], 'dark mode theme night colors داكن ليلي مظهر الوان'],
  ['start', 'kb-shortcuts', ['ما هي اختصارات لوحة المفاتيح؟', 'What keyboard shortcuts are there?'], ['فعّل الاختصارات أولاً من إعداداتك (Preferences). أمثلة: Ctrl/Cmd+K للبحث السريع، T لمهمة جديدة، R لتذكير، M لإسناد المهمة لنفسك، Shift+S لتغيير الحالة. قد تختلف حسب الإصدار.', 'Turn shortcuts on in your Preferences first. Examples: Ctrl/Cmd+K to search, T for a new task, R for a reminder, M to assign to yourself, Shift+S for status. They may vary by version.'], 'keyboard shortcut shortcuts hotkey keys اختصار اختصارات مفاتيح لوحه'],
  ['start', 'kb-university', ['أين أتعلّم ClickUp أكثر؟', 'Where can I learn more ClickUp?'], ['ابدأ بدروس هذه المنصة وورشها. وتوفّر ClickUp University دورات مجانية بالإنجليزية، ويوجد مركز المساعدة help.clickup.com لكل ميزة.', 'Start with this hub’s lessons and workshops. ClickUp University also has free courses in English, and help.clickup.com explains every feature.'], 'learn learning course training university help center تعلم دوره تدريب جامعه'],

  /* ---- Structure ---- */
  ['structure', 'kb-hierarchy', ['ما الفرق بين المساحة والمجلد والقائمة؟', 'What is the difference between a Space, Folder and List?'], ['مساحة العمل هي الشركة. المساحة (Space) لقسم أو فريق. المجلد (Folder) لمشروع أو مجموعة. القائمة (List) تحمل المهام نفسها. والمهمة تحتوي مهام فرعية وقوائم تحقق.', 'The Workspace is the company. A Space is for a department or team. A Folder groups a project. A List holds the tasks themselves. Tasks can hold subtasks and checklists.'], 'difference hierarchy space folder list levels structure فرق مساحه مجلد قائمه مستويات'],
  ['structure', 'kb-new-space', ['كيف أنشئ مساحة جديدة؟', 'How do I create a new Space?'], ['في الشريط الجانبي اضغط «+» بجانب المساحات أو «Create Space»، اختر الاسم واللون والأعضاء والـ ClickApps. قد يحتاج ذلك صلاحية مسؤول.', 'In the sidebar click "+" next to Spaces (Create Space), set a name, color, members and ClickApps. This may need admin rights.'], 'create new space add إنشاء انشاء مساحه جديده'],
  ['structure', 'kb-new-list', ['كيف أنشئ قائمة جديدة؟', 'How do I create a new List?'], ['مرّر على المساحة أو المجلد واضغط «+» ثم «List». سمّها باسم واضح مثل «طلبات الصيانة 2026».', 'Hover a Space or Folder, click "+" then "List". Give it a clear name like "Maintenance requests 2026".'], 'create new list add إنشاء انشاء قائمه جديده'],
  ['structure', 'kb-move-list', ['كيف أنقل قائمة إلى مجلد آخر؟', 'How do I move a List to another Folder?'], ['اسحب القائمة في الشريط الجانبي إلى المجلد الجديد، أو افتح قائمة النقاط (…) واختر «Move».', 'Drag the List in the sidebar to the new Folder, or open its ellipsis (…) menu and choose "Move".'], 'move list folder drag relocate نقل قائمه مجلد اسحب'],
  ['structure', 'kb-archive', ['ما الفرق بين الأرشفة والحذف؟', 'What is the difference between archive and delete?'], ['الأرشفة تخفي القائمة أو المهمة مع بقاء كل شيء، ويمكن استعادتها في أي وقت. الحذف ينقلها إلى سلة المهملات لمدة 30 يوماً تقريباً ثم تُحذف نهائياً.', 'Archiving hides a List or task but keeps everything, and you can restore it anytime. Deleting moves it to Trash for about 30 days, then it is gone for good.'], 'archive archived delete difference hide أرشفه ارشيف حذف فرق اخفاء'],
  ['structure', 'kb-trash', ['حذفت مهمة بالخطأ، كيف أستعيدها؟', 'I deleted a task by mistake. How do I get it back?'], ['افتح سلة المهملات (Trash) من الشريط الجانبي أو الإعدادات، ابحث عن المهمة واضغط «Restore». العناصر تبقى هناك نحو 30 يوماً. التعليقات وسجلات الوقت المحذوفة لا تُستعاد.', 'Open Trash from the sidebar or settings, find the task and click "Restore". Items stay there for about 30 days. Deleted comments and time entries cannot be restored.'], 'deleted mistake restore recover undo trash bin حذفت خطا استعاده استرجاع سله المهملات'],
  ['structure', 'kb-everything', ['كيف أرى كل المهام في كل المساحات؟', 'How do I see every task across all Spaces?'], ['استخدم عرض «Everything» في أعلى الشريط الجانبي. يعرض المهام من كل مكان، ثم صفِّها بالمسؤول أو الحالة أو التاريخ.', 'Use the Everything view at the top of the sidebar. It shows tasks from everywhere; then filter by assignee, status or date.'], 'everything all tasks across spaces overview كل المهام جميع'],

  /* ---- Tasks ---- */
  ['tasks', 'kb-new-task', ['كيف أنشئ مهمة؟', 'How do I create a task?'], ['داخل القائمة اضغط «+ Task» أو «Add Task»، اكتب الاسم واضغط Enter. أو اضغط زر «Create» / الاختصار T من أي مكان.', 'Inside a List click "+ Task" (Add Task), type a name and press Enter. Or use the Create button, or the T shortcut, from anywhere.'], 'create new task add make إنشاء انشاء مهمه جديده اضافه'],
  ['tasks', 'kb-good-task', ['كيف أكتب مهمة جيدة؟', 'How do I write a good task?'], ['ابدأ الاسم بفعل ونتيجة: «أرسل عرض السعر لمورد الألياف». أضف مسؤولاً واحداً، وتاريخ استحقاق، ووصفاً قصيراً بما هو «منتهٍ»، وأرفق الملفات.', 'Start the name with a verb and a result: "Send the quote to the fibre vendor". Add one assignee, a due date, a short description of "done", and attach files.'], 'good task write best practice name clear مهمه جيده اكتب واضح'],
  ['tasks', 'kb-description', ['كيف أضيف وصفاً أو مرفقاً لمهمة؟', 'How do I add a description or attachment to a task?'], ['افتح المهمة واكتب في حقل الوصف؛ يدعم العناوين والقوائم والجداول. للمرفقات اسحب الملف إلى المهمة أو استخدم «Attach».', 'Open the task and type in the description; it supports headings, lists and tables. For attachments drag the file onto the task or use Attach.'], 'description attach attachment file upload pdf image وصف مرفق ملف رفع صوره'],
  ['tasks', 'kb-multi-assign', ['هل يمكن إسناد مهمة لأكثر من شخص؟', 'Can a task have more than one assignee?'], ['نعم إن كانت ميزة «Multiple Assignees» مفعّلة في المساحة. لكن الأفضل مسؤول واحد واضح، والباقون متابعون (Watchers).', 'Yes, if the Multiple Assignees ClickApp is on for the Space. Still, one clear owner is best; add others as watchers.'], 'multiple assignees two people several more than one اكثر من شخص عده اشخاص'],
  ['tasks', 'kb-watchers', ['ما هم المتابعون (Watchers)؟', 'What are watchers?'], ['المتابع يتلقى إشعارات تحديثات المهمة دون أن يكون مسؤولاً عنها. أضف مديرك متابعاً ليرى التقدّم دون متابعة يدوية.', 'A watcher gets notifications about a task without owning it. Add your manager as a watcher so they see progress without chasing you.'], 'watcher watchers follow follower متابع متابعين'],
  ['tasks', 'kb-multi-list', ['هل يمكن وضع المهمة في أكثر من قائمة؟', 'Can one task live in more than one List?'], ['نعم عبر «Tasks in Multiple Lists» إن كانت مفعّلة. تبقى المهمة واحدة وتظهر في القائمتين، فأي تحديث يظهر في المكانين.', 'Yes, with Tasks in Multiple Lists turned on. It stays one task shown in both Lists, so any update appears in both places.'], 'multiple lists two lists same task both اكثر من قائمه قائمتين'],
  ['tasks', 'kb-move-task', ['كيف أنقل مهمة إلى قائمة أخرى؟', 'How do I move a task to another List?'], ['افتح المهمة، ثم قائمة النقاط (…) واختر «Move». أو حدّد عدة مهام في عرض القائمة واستخدم شريط الإجراءات بالأسفل.', 'Open the task, then the ellipsis (…) menu and choose "Move". Or select several tasks in List view and use the bulk action bar.'], 'move task another list transfer نقل مهمه قائمه اخرى'],
  ['tasks', 'kb-bulk', ['كيف أعدّل عدة مهام مرة واحدة؟', 'How do I edit many tasks at once?'], ['في عرض القائمة حدّد المربعات بجانب المهام، فيظهر شريط إجراءات جماعية لتغيير الحالة أو المسؤول أو التاريخ أو النقل أو الحذف.', 'In List view tick the boxes next to the tasks and a bulk action bar appears: change status, assignee or dates, move or delete.'], 'bulk many several multiple at once select all جماعي عده مهام مره واحده تحديد'],
  ['tasks', 'kb-duplicate', ['كيف أنسخ مهمة؟', 'How do I duplicate a task?'], ['من قائمة النقاط (…) في المهمة اختر «Duplicate» واختر ما يُنسخ: المهام الفرعية، التعليقات، المرفقات. للمهام المتكررة استخدم التكرار أو القوالب.', 'From the task’s ellipsis (…) menu choose "Duplicate" and pick what to copy: subtasks, comments, attachments. For repeating work use recurrence or templates.'], 'duplicate copy clone نسخ تكرار نسخه'],
  ['tasks', 'kb-merge', ['كيف أدمج مهمتين مكررتين؟', 'How do I merge two duplicate tasks?'], ['افتح إحدى المهمتين، ثم قائمة النقاط (…) واختر «Merge»، واختر المهمة الأخرى. تنتقل التعليقات والمرفقات إلى مهمة واحدة.', 'Open one task, then the ellipsis (…) menu, choose "Merge" and pick the other task. Comments and attachments combine into one task.'], 'merge combine duplicate دمج مكرره'],
  ['tasks', 'kb-link', ['كيف أربط مهمتين ببعض؟', 'How do I link two related tasks?'], ['افتح المهمة واختر «Relationships» أو «Add relationship» ثم «Link» وابحث عن المهمة الأخرى. للربط بين قوائم مختلفة يمكن استخدام حقل علاقة مخصّص.', 'Open the task, choose Relationships (Add relationship), then Link, and search for the other task. For links between different Lists you can use a relationship Custom Field.'], 'link related relationship connect relate ربط علاقه مرتبطه'],
  ['tasks', 'kb-milestone', ['ما هي المعالم (Milestones)؟', 'What are milestones?'], ['المَعلم مهمة تمثل نقطة مهمة في المشروع، مثل «إطلاق الخدمة». يظهر بشكل ماسة في مخطط غانت. من قائمة النقاط في المهمة اختر «Mark as Milestone».', 'A milestone is a task that marks a key point, like "Service launch". It shows as a diamond in Gantt. From the task menu choose "Mark as Milestone".'], 'milestone milestones diamond key date معلم معالم محطه'],
  ['tasks', 'kb-task-id', ['ما هو رقم المهمة وكيف أشاركه؟', 'What is a task ID and how do I share it?'], ['لكل مهمة رقم فريد يظهر أعلاها. يمكن للمسؤول تفعيل أرقام مخصّصة مثل IT-120. انسخ رابط المهمة من الأعلى وأرسله لزميلك.', 'Every task has a unique ID at the top. Admins can turn on custom IDs like IT-120. Copy the task link from the top and send it to a colleague.'], 'task id number custom link url share copy رقم معرف رابط نسخ'],
  ['tasks', 'kb-task-types', ['ما هي أنواع المهام؟', 'What are task types?'], ['يمكن تسمية نوع المهمة، مثل «طلب» أو «خلل» أو «اجتماع»، بأيقونة خاصة. يساعد ذلك على الفرز والتقارير. يضبطها المسؤول من إعدادات مساحة العمل.', 'Tasks can have a type, like Request, Bug or Meeting, with its own icon. It helps filtering and reports. Admins set types in Workspace settings.'], 'task type types kind category نوع انواع المهام'],
  ['tasks', 'kb-priority', ['كيف أحدد أولوية المهمة؟', 'How do I set a task priority?'], ['اضغط علم الأولوية في المهمة واختر: عاجل، مرتفع، عادي، منخفض. ثم رتّب أو صفِّ العرض حسب الأولوية.', 'Click the priority flag on the task and choose Urgent, High, Normal or Low. Then sort or filter your view by priority.'], 'priority priorities urgent high low flag important اولويه عاجل مهم علم'],
  ['tasks', 'kb-tags', ['ما هي الوسوم (Tags)؟', 'What are tags?'], ['الوسوم تسميات سريعة مثل «عميل» أو «مسقط» تضيفها للمهام لتجميعها والبحث عنها. للبيانات المنظّمة استخدم الحقول المخصّصة بدلاً منها.', 'Tags are quick labels like "client" or "Muscat" you add to tasks to group and find them. For structured data use Custom Fields instead.'], 'tag tags label labels وسم وسوم تسميه'],
  ['tasks', 'kb-reminder', ['كيف أضع تذكيراً لنفسي؟', 'How do I set a reminder for myself?'], ['أنشئ تذكيراً من زر «Create» أو الاختصار R، واختر الوقت. التذكير لا يحتاج قائمة، ويظهر في «مهامي». يمكن أيضاً إرسال تذكير لزميل.', 'Create a reminder from the Create button or the R shortcut and pick a time. A reminder needs no List and shows in My Tasks. You can also send one to a colleague.'], 'reminder remind alarm remember تذكير ذكرني تنبيه'],
  ['tasks', 'kb-dates', ['ما الفرق بين تاريخ البدء وتاريخ الاستحقاق؟', 'What is the difference between start date and due date?'], ['تاريخ البدء متى يبدأ العمل، وتاريخ الاستحقاق متى يجب أن ينتهي. معاً يرسمان شريط المهمة في غانت والجدول الزمني.', 'The start date is when work begins; the due date is when it must be done. Together they draw the task bar in Gantt and Timeline.'], 'start date due date difference begin end بدء استحقاق فرق'],
  ['tasks', 'kb-overdue', ['كيف أرى المهام المتأخرة؟', 'How do I see overdue tasks?'], ['صفِّ العرض بتاريخ الاستحقاق «Overdue» أو افتح «مهامي» حيث تظهر المتأخرة أولاً. يمكن أيضاً إضافة بطاقة المتأخرات في لوحة المعلومات.', 'Filter the view by due date "Overdue", or open My Tasks where late tasks show first. You can also add an overdue card on a Dashboard.'], 'overdue late missed delayed past متاخره فات موعد متاخر'],
  ['tasks', 'kb-private-task', ['كيف أجعل مهمة خاصة؟', 'How do I make a task private?'], ['من زر المشاركة (Share) في المهمة اجعلها خاصة وحدد من يراها. تذكّر أن المسؤولين قد يرون كل شيء حسب إعدادات الشركة.', 'From the task’s Share button make it private and choose who can see it. Remember admins may still see everything depending on company settings.'], 'private hide secret confidential only me خاصه سري اخفاء'],

  /* ---- Statuses ---- */
  ['tasks', 'kb-status', ['كيف أغيّر حالة المهمة؟', 'How do I change a task status?'], ['اضغط الحالة في أعلى المهمة، أو اسحب البطاقة إلى عمود آخر في عرض اللوحة. الاختصار Shift+S يعمل أيضاً إن كانت الاختصارات مفعّلة.', 'Click the status at the top of the task, or drag the card to another column in Board view. Shift+S also works if shortcuts are on.'], 'status change progress done complete حاله تغيير منجز مكتمل'],
  ['tasks', 'kb-custom-status', ['كيف أضيف حالة جديدة مثل «بانتظار الموافقة»؟', 'How do I add a status like "Waiting for approval"?'], ['من إعدادات القائمة أو المساحة اختر «Statuses» وأضف حالة جديدة بلونها. يمكن حفظ مجموعة الحالات كقالب لاستخدامها في قوائم أخرى.', 'In the List or Space settings open Statuses and add a new status with a color. You can save the set as a status template for other Lists.'], 'custom status new add approval waiting review حاله جديده موافقه انتظار مراجعه'],
  ['tasks', 'kb-closed', ['لماذا اختفت المهمة بعد إغلاقها؟', 'Why did the task disappear after I closed it?'], ['المهام المغلقة تُخفى افتراضياً. فعّل «Show closed» من إعدادات العرض لرؤيتها، أو ابحث عنها بالبحث.', 'Closed tasks are hidden by default. Turn on "Show closed" in the view settings to see them, or find them with search.'], 'closed disappeared hidden gone complete done vanished اختفت مغلقه مخفيه'],

  /* ---- Subtasks and checklists ---- */
  ['tasks', 'kb-subtask-vs-checklist', ['متى أستخدم مهمة فرعية ومتى قائمة تحقق؟', 'When do I use a subtask vs a checklist?'], ['المهمة الفرعية لها مسؤول وتاريخ وحالة خاصة، فاستخدمها عندما يعمل عليها شخص آخر. قائمة التحقق خطوات بسيطة تُعلَّم بصح داخل المهمة نفسها.', 'A subtask has its own assignee, date and status; use it when someone else works on it. A checklist is simple tick-off steps inside the same task.'], 'subtask checklist difference when vs فرعيه قائمه تحقق فرق متى'],
  ['tasks', 'kb-checklist-template', ['كيف أعيد استخدام قائمة تحقق؟', 'How do I reuse a checklist?'], ['في المهمة افتح قائمة النقاط بجانب قائمة التحقق واختر «Save as template». ثم أضفها لأي مهمة من «Add checklist» ← القوالب.', 'In the task open the checklist’s ellipsis menu and choose "Save as template". Then add it to any task from Add checklist, then Templates.'], 'reuse checklist template save same steps اعاده استخدام قائمه تحقق'],

  /* ---- Views ---- */
  ['views', 'kb-add-view', ['كيف أضيف طريقة عرض جديدة؟', 'How do I add a new view?'], ['في أعلى القائمة اضغط «+ View» واختر: قائمة، لوحة، تقويم، غانت، جدول، عبء العمل وغيرها. العرض يغيّر الشكل فقط؛ المهام نفسها لا تتغير.', 'At the top of the List click "+ View" and choose List, Board, Calendar, Gantt, Table, Workload and more. A view only changes the layout; the tasks stay the same.'], 'add new view create tab اضافه عرض جديد'],
  ['views', 'kb-board', ['ما فائدة عرض اللوحة (Board)؟', 'What is Board view for?'], ['يعرض المهام كبطاقات في أعمدة حسب الحالة، فترى أين يتوقف العمل. اسحب البطاقة لتغيير حالتها.', 'It shows tasks as cards in columns by status, so you see where work gets stuck. Drag a card to change its status.'], 'board kanban cards columns لوحه بطاقات اعمده كانبان'],
  ['views', 'kb-gantt', ['كيف أستخدم مخطط غانت؟', 'How do I use Gantt view?'], ['أضف عرض Gantt، واعطِ المهام تاريخ بدء واستحقاق. اسحب الأشرطة لتغيير التواريخ، واربط بينها لتحديد الاعتماديات.', 'Add a Gantt view and give tasks start and due dates. Drag bars to change dates and connect them to set dependencies.'], 'gantt timeline plan schedule project غانت جدول زمني خطه'],
  ['views', 'kb-workload', ['كيف أعرف من عنده عمل كثير في الفريق؟', 'How do I see who is overloaded on the team?'], ['استخدم عرض Workload (عبء العمل). يظهر لكل شخص حجم مهامه في كل يوم حسب التقديرات أو عدد المهام.', 'Use the Workload view. It shows each person’s load per day based on estimates or task count.'], 'workload capacity overloaded busy team balance عبء العمل ضغط سعه'],
  ['views', 'kb-filter', ['كيف أصفّي المهام في العرض؟', 'How do I filter tasks in a view?'], ['اضغط «Filter» في أعلى العرض وأضف شرطاً مثل المسؤول = أنا أو الأولوية = عاجل. احفظ العرض ليبقى الفلتر لكل الفريق.', 'Click Filter at the top of the view and add a rule like Assignee = me or Priority = Urgent. Save the view so the filter stays for the team.'], 'filter filters show only narrow تصفيه فلتر'],
  ['views', 'kb-group', ['كيف أجمّع المهام حسب المسؤول أو الأولوية؟', 'How do I group tasks by assignee or priority?'], ['من إعدادات العرض اختر «Group by» ثم المسؤول أو الأولوية أو التاريخ أو حقل مخصّص.', 'In view settings choose "Group by", then assignee, priority, due date or a Custom Field.'], 'group grouping group by sort order تجميع ترتيب فرز'],
  ['views', 'kb-me-mode', ['كيف أرى مهامي فقط في القائمة؟', 'How do I see only my tasks in a List?'], ['فعّل «Me mode» أو زر «Me» في أعلى العرض، أو أضف فلتر المسؤول = أنا.', 'Turn on "Me mode" (the Me button) at the top of the view, or add the filter Assignee = me.'], 'only mine my own me mode فقط مهامي انا'],
  ['views', 'kb-private-view', ['هل تغييرات العرض تظهر للجميع؟', 'Do my view changes show for everyone?'], ['العروض المشتركة يراها الجميع. لتجربة ترتيبك الخاص أنشئ عرضاً خاصاً (Private view) أو لا تحفظ التغييرات.', 'Shared views are seen by everyone. To try your own layout, create a Private view or do not save the changes.'], 'private view personal save changes everyone عرض خاص تغييرات'],
  ['views', 'kb-columns', ['كيف أضيف عموداً في عرض القائمة أو الجدول؟', 'How do I add a column in List or Table view?'], ['اضغط «+» في نهاية رؤوس الأعمدة واختر حقلاً موجوداً أو أنشئ حقلاً مخصّصاً جديداً.', 'Click "+" at the end of the column headers and pick an existing field or create a new Custom Field.'], 'column columns add show hide field عمود اعمده اضافه'],

  /* ---- Custom fields ---- */
  ['fields', 'kb-field-types', ['ما أنواع الحقول المخصّصة؟', 'What types of Custom Fields are there?'], ['منها: نص، رقم، مبلغ مالي، قائمة منسدلة، تاريخ، مربع اختيار، تقدّم، تقييم، ملفات، أشخاص، علاقة، ومعادلة. اختر ما يناسب نوع البيانات.', 'They include text, number, money, dropdown, date, checkbox, progress, rating, files, people, relationship and formula. Pick the one that fits your data.'], 'custom field types kinds dropdown number money formula حقول مخصصه انواع قائمه منسدله رقم مبلغ'],
  ['fields', 'kb-formula', ['هل يمكن عمل معادلة في حقل؟', 'Can a field calculate a formula?'], ['نعم بحقل «Formula». مثلاً: الكمية × السعر، أو عدد الأيام بين تاريخين. ويمكن جمع الأرقام في أسفل عرض القائمة.', 'Yes, with a Formula field. For example quantity × price, or days between two dates. Number columns can also show totals at the bottom of List view.'], 'formula calculate calculation sum total math معادله حساب مجموع'],
  ['fields', 'kb-required', ['كيف أجعل الحقل إلزامياً؟', 'How do I make a field required?'], ['في إعدادات الحقل فعّل «Required» إن كانت متاحة في خطتك، فلا تُنشأ المهمة دون تعبئته. في النماذج اجعل السؤال مطلوباً.', 'In the field settings turn on "Required" if your plan has it, so tasks cannot be created without it. In Forms mark the question as required.'], 'required mandatory must fill الزامي مطلوب اجباري'],

  /* ---- Collaboration ---- */
  ['collab', 'kb-mention', ['كيف أشير إلى زميل في تعليق؟', 'How do I mention a colleague in a comment?'], ['اكتب @ ثم اسم الزميل واختره. يصله إشعار في صندوق الوارد. استخدم @فريق لإشارة فريق كامل.', 'Type @ and the colleague’s name and pick them. They get a notification in their Inbox. Use @team to mention a whole team.'], 'mention tag colleague @ notify اشاره زميل منشن'],
  ['collab', 'kb-assign-comment', ['ما هو التعليق المُسند؟', 'What is an assigned comment?'], ['يمكن إسناد تعليق لشخص ليعمل عليه، فيظهر كعنصر يجب حلّه. عندما يُنجز يضغط «Resolve». مفيد لطلبات صغيرة داخل مهمة.', 'You can assign a comment to someone as an action item. When done they click "Resolve". Useful for small asks inside a task.'], 'assigned comment action item resolve تعليق مسند حل'],
  ['collab', 'kb-edit-comment', ['كيف أعدّل أو أحذف تعليقي؟', 'How do I edit or delete my comment?'], ['مرّر على تعليقك وافتح قائمة النقاط (…) واختر تعديل أو حذف. التعليق المحذوف لا يُستعاد.', 'Hover your comment, open the ellipsis (…) menu and choose edit or delete. A deleted comment cannot be restored.'], 'edit delete comment remove change تعديل حذف تعليق'],
  ['collab', 'kb-chat', ['ما هي قنوات المحادثة (Chat)؟', 'What are Chat channels?'], ['Chat في ClickUp قنوات محادثة للفريق مرتبطة بالمساحات والمهام، ورسائل مباشرة بين الزملاء. يمكن تحويل الرسالة إلى مهمة.', 'ClickUp Chat gives team channels linked to your Spaces and tasks, plus direct messages. You can turn a message into a task.'], 'chat channel channels message dm direct محادثه قناه رساله مباشره دردشه'],
  ['collab', 'kb-docs', ['كيف أنشئ مستنداً (Doc)؟', 'How do I create a Doc?'], ['من الشريط الجانبي أو زر «Create» اختر «Doc». اكتب بالعناوين والجداول، واربط المهام داخله، وأضف صفحات فرعية لبناء دليل أو ويكي للقسم.', 'From the sidebar or the Create button choose "Doc". Write with headings and tables, link tasks inside, and add sub-pages to build a guide or wiki.'], 'doc docs document wiki page write مستند مستندات وثيقه صفحه ويكي'],
  ['collab', 'kb-share-doc', ['كيف أشارك مستنداً مع شخص من خارج الشركة؟', 'How do I share a Doc with someone outside the company?'], ['من زر «Share» في المستند يمكن دعوة ضيف أو إنشاء رابط عام إن سمح المسؤول بذلك. استشر سياسة الشركة قبل النشر الخارجي.', 'From the Doc’s Share button you can invite a guest or create a public link if your admin allows it. Check company policy before sharing outside.'], 'share doc public link outside external guest مشاركه مستند رابط عام خارجي'],
  ['collab', 'kb-whiteboard', ['ما هي السبورة (Whiteboard)؟', 'What is a Whiteboard?'], ['لوحة رسم مشتركة للعصف الذهني ورسم الخطط. يمكن تحويل الملاحظات اللاصقة والأشكال مباشرة إلى مهام.', 'A shared canvas for brainstorming and drawing plans. You can turn sticky notes and shapes straight into tasks.'], 'whiteboard brainstorm draw canvas diagram سبوره رسم عصف ذهني'],
  ['collab', 'kb-clips', ['كيف أسجّل شاشتي لأشرح مشكلة؟', 'How do I record my screen to explain a problem?'], ['استخدم «Clip» من زر التسجيل في التعليق أو من «Create». سجّل الشاشة مع صوتك، ويُحفظ الرابط لتشاركه في مهمة أو محادثة.', 'Use Clip from the record button in a comment or from Create. Record your screen with your voice, and share the link in a task or chat.'], 'clip clips record screen video recording تسجيل شاشه فيديو'],
  ['collab', 'kb-email', ['هل يمكن الرد على تعليق من البريد؟', 'Can I reply to a comment from email?'], ['نعم، إشعارات البريد تسمح بالرد مباشرة فيُضاف ردّك كتعليق. ويمكن أيضاً إرسال بريد إلى قائمة لإنشاء مهمة إن فعّل المسؤول ذلك.', 'Yes, email notifications let you reply and your reply becomes a comment. You can also email a List to create a task if your admin enabled it.'], 'email mail reply outlook gmail بريد ايميل رد'],

  /* ---- Notifications ---- */
  ['collab', 'kb-notif-settings', ['كيف أتحكم في الإشعارات؟', 'How do I control my notifications?'], ['من إعداداتك افتح «Notifications» واختر لكل نوع: داخل التطبيق، البريد، الجوال. قلّل البريد واترك الإشارات إليك فقط إن كانت كثيرة.', 'In your settings open Notifications and choose per type: in-app, email, mobile. If there are too many, turn off email and keep only mentions.'], 'notification settings control manage turn off mute اعدادات الاشعارات تحكم ايقاف كتم'],
  ['collab', 'kb-unwatch', ['كيف أوقف إشعارات مهمة معيّنة؟', 'How do I stop notifications from one task?'], ['افتح المهمة واضغط على أيقونة العين (المتابعون) ثم أزل نفسك من المتابعين.', 'Open the task, click the eye icon (watchers) and remove yourself.'], 'stop unwatch one task mute specific ايقاف مهمه معينه متابعه'],

  /* ---- Time ---- */
  ['time', 'kb-timer', ['كيف أسجّل الوقت على مهمة؟', 'How do I track time on a task?'], ['افتح المهمة واضغط زر المؤقت «Start» ثم «Stop» عند التوقف، أو أضف الوقت يدوياً. يمكن رؤية المجموع في التقارير ولوحات المعلومات.', 'Open the task, click the timer Start, then Stop when you finish, or add time manually. Totals show in reports and Dashboards.'], 'time track timer log hours timesheet سجل الوقت مؤقت ساعات'],
  ['time', 'kb-estimate', ['كيف أضع تقديراً للوقت؟', 'How do I add a time estimate?'], ['في المهمة اضغط «Time estimate» واكتب مثلاً 3h. تُستخدم التقديرات في عرض عبء العمل للتخطيط.', 'In the task click Time estimate and type e.g. 3h. Estimates feed the Workload view for planning.'], 'estimate estimation hours plan تقدير ساعات'],
  ['time', 'kb-dependency', ['ما هي الاعتماديات (Dependencies)؟', 'What are dependencies?'], ['الاعتمادية تعني أن مهمة تنتظر أخرى: «ينتظر» أو «يعيق». أضفها من «Relationships» في المهمة، وتظهر كخطوط في غانت.', 'A dependency means one task waits on another: "waiting on" or "blocking". Add it from Relationships in the task; it shows as lines in Gantt.'], 'dependency dependencies blocking waiting blocked اعتماديه ينتظر يعيق معلق'],
  ['time', 'kb-sprints', ['ما هي السبرنتات (Sprints)؟', 'What are Sprints?'], ['السبرنت فترة عمل قصيرة، أسبوعان مثلاً، بقائمة مهام محددة. تُفعَّل من ClickApps، وتعطيك نقاط الجهد ومخططات التقدّم. مفيدة لفرق التطوير.', 'A Sprint is a short work period, like two weeks, with a set list of tasks. Turn it on in ClickApps; you get sprint points and burndown charts. Useful for agile teams.'], 'sprint sprints agile scrum points burndown سبرنت اجايل'],
  ['time', 'kb-calendar-sync', ['هل يتزامن ClickUp مع تقويم Outlook أو Google؟', 'Does ClickUp sync with Outlook or Google Calendar?'], ['نعم. تقويم Google يتزامن في الاتجاهين. Outlook وiCal يعرضان مهام ClickUp باتجاه واحد عبر رابط اشتراك. الإعداد من التكاملات أو عرض التقويم، وقد يحتاج موافقة تقنية المعلومات.', 'Yes. Google Calendar syncs both ways. Outlook and iCal show ClickUp tasks one way through a subscription link. Set it up from Integrations or the Calendar view; IT approval may be needed.'], 'outlook google calendar sync meeting ical تقويم مزامنه اوتلوك'],

  /* ---- Dashboards and reports ---- */
  ['dash', 'kb-dashboard', ['كيف أنشئ لوحة معلومات (Dashboard)؟', 'How do I create a Dashboard?'], ['من الشريط الجانبي اختر «Dashboards» ثم «+ New». أضف بطاقات: مخطط دائري للحالات، عدد المتأخرات، عبء العمل، أو مؤشر رقمي. شاركها مع مديرك.', 'From the sidebar choose Dashboards, then + New. Add cards: a pie of statuses, overdue count, workload, or a number KPI. Share it with your manager.'], 'create dashboard new cards widgets انشاء لوحه معلومات بطاقات'],
  ['dash', 'kb-report-export', ['كيف أرسل تقريراً لمديري كل أسبوع؟', 'How do I send my manager a report every week?'], ['أنشئ لوحة معلومات واجدول إرسالها بالبريد إن كانت خطتك تدعم ذلك، أو شارك رابط اللوحة ليرى البيانات مباشرة. أتمتة أسبوعية يمكنها إنشاء مهمة تذكير بالتقرير.', 'Build a Dashboard and schedule it by email if your plan supports it, or share the Dashboard link so they see live data. A weekly automation can also create a reminder task for the report.'], 'weekly report manager send schedule email تقرير اسبوعي مدير ارسال'],

  /* ---- Automations ---- */
  ['auto', 'kb-auto-how', ['كيف أنشئ أتمتة؟', 'How do I create an automation?'], ['في القائمة اضغط «Automate» أو أيقونة البرق ← «Add automation». اختر المُشغِّل (مثل: تغيّرت الحالة) والإجراء (مثل: أسند إلى فلان). ابدأ بأتمتة واحدة بسيطة وجرّبها.', 'In the List click Automate (the lightning icon), then Add automation. Pick a trigger (e.g. status changes) and an action (e.g. assign to someone). Start with one simple automation and test it.'], 'create automation how set up trigger action انشاء اتمته مشغل اجراء'],
  ['auto', 'kb-auto-limit', ['هل للأتمتة حدّ في عدد مرات التشغيل؟', 'Is there a limit on automation runs?'], ['نعم، لكل خطة عدد تشغيلات شهري. إن توقفت الأتمتة فقد يكون الحد انتهى أو تغيّرت الحالة أو الشخص المستخدم فيها. راجع سجل الأتمتة (Activity).', 'Yes, each plan has a monthly number of runs. If an automation stops, the limit may be reached, or a status or person it uses changed. Check the automation activity log.'], 'automation limit runs quota stopped not working حد تشغيل توقفت لا تعمل'],
  ['auto', 'kb-auto-examples', ['ما أمثلة الأتمتة المفيدة للموظفين؟', 'What are useful automation examples?'], ['أمثلة: عند إنشاء مهمة أسندها لمسؤول الفريق. عند تغيّر الحالة إلى «مكتمل» أبلغ المدير. عند اقتراب الاستحقاق غيّر الأولوية. عند وصول نموذج أنشئ مهمة بقائمة تحقق.', 'Examples: when a task is created, assign the team lead. When status becomes Complete, notify the manager. When a due date is near, raise priority. When a form arrives, create a task with a checklist.'], 'automation examples ideas useful common امثله اتمته افكار'],

  /* ---- Forms ---- */
  ['forms', 'kb-form-create', ['كيف أنشئ نموذج طلبات؟', 'How do I create a request form?'], ['في القائمة أضف عرض «Form». اسحب الحقول التي تريدها، واجعل المهم منها مطلوباً، ثم شارك الرابط. كل إرسال يصبح مهمة في القائمة.', 'In the List add a Form view. Drag in the fields you need, make the important ones required, then share the link. Every submission becomes a task in the List.'], 'create form request intake survey انشاء نموذج طلبات استبيان'],
  ['forms', 'kb-form-logic', ['هل يمكن أن يتغيّر النموذج حسب الإجابة؟', 'Can a form change based on the answer?'], ['نعم، بالمنطق الشرطي (Conditional logic) تظهر أسئلة معيّنة حسب اختيار سابق، إن كانت متاحة في خطتك.', 'Yes, conditional logic shows certain questions based on an earlier choice, if your plan includes it.'], 'conditional logic form branch depends شرطي منطق نموذج'],

  /* ---- Goals ---- */
  ['dash', 'kb-goals', ['كيف أتابع الأهداف (Goals)؟', 'How do I track Goals?'], ['أنشئ هدفاً وأضف له مستهدفات: رقم، نعم/لا، مبلغ، أو مهام. يتحدّث التقدّم تلقائياً عندما تُنجز المهام المرتبطة. توفرها قد يختلف حسب الإصدار.', 'Create a Goal and add targets: number, true/false, currency or tasks. Progress updates automatically as linked tasks are done. Availability may vary by version.'], 'goal goals okr target track progress هدف اهداف مستهدف'],

  /* ---- Sharing, roles, security ---- */
  ['share', 'kb-roles', ['ما الفرق بين المالك والمسؤول والعضو والضيف؟', 'What is the difference between Owner, Admin, Member and Guest?'], ['المالك يملك مساحة العمل كاملة. المسؤول يدير الإعدادات والأعضاء. العضو يعمل في ما يُتاح له. العضو المحدود والضيف يريان فقط ما شُورك معهما، ومناسبان للموردين.', 'The Owner owns the whole Workspace. Admins manage settings and members. Members work in what they can access. Limited Members and Guests only see what is shared with them, which suits vendors.'], 'roles owner admin member guest limited difference permission دور ادوار مالك مسؤول عضو ضيف'],
  ['share', 'kb-invite', ['كيف أضيف زميلاً إلى مساحة العمل؟', 'How do I add a colleague to the Workspace?'], ['يدعو المسؤول الأعضاء من إعدادات الأشخاص (People) بالبريد. إن لم تكن مسؤولاً فاطلب من مسؤول مساحة العمل، أو شارك معه القائمة كضيف إن سُمح.', 'Admins invite members from People settings by email. If you are not an admin, ask your Workspace admin, or share the List with them as a guest if allowed.'], 'invite add colleague member new user people دعوه اضافه زميل عضو'],
  ['share', 'kb-permissions', ['ما مستويات صلاحية المشاركة؟', 'What are the sharing permission levels?'], ['عند المشاركة تختار: مشاهدة فقط، تعليق، تعديل، أو تحكم كامل. أعطِ أقل صلاحية تكفي للعمل.', 'When sharing you choose View only, Comment, Edit or Full access. Give the lowest level that gets the job done.'], 'permission levels view edit comment full access صلاحيه مشاهده تعديل'],
  ['share', 'kb-2fa', ['كيف أفعّل التحقق بخطوتين؟', 'How do I turn on two-factor authentication?'], ['من إعداداتك الشخصية افتح الأمان وفعّل 2FA عبر تطبيق المصادقة أو الرسائل. قد يفرضه المسؤول على الجميع. إن كان الدخول عبر SSO فالأمان تديره الشركة.', 'In your personal settings open Security and turn on 2FA with an authenticator app or SMS. Admins may require it for everyone. With SSO, your company manages sign-in security.'], '2fa two factor authentication security verify otp تحقق خطوتين امان'],
  ['share', 'kb-leaver', ['موظف غادر الفريق، ماذا نفعل بمهامه؟', 'An employee left the team. What happens to their tasks?'], ['قبل إزالته أعد إسناد مهامه المفتوحة: صفِّ بالمسؤول = اسمه وغيّر المسؤول جماعياً. المسؤول يزيل الحساب من إعدادات الأشخاص.', 'Before removing them, reassign their open tasks: filter Assignee = their name and bulk-change the assignee. An admin then removes the account in People settings.'], 'left leaver resigned quit someone company colleague remove employee reassign ترك الشركه غادر استقال ازاله اعاده اسناد'],

  /* ---- AI ---- */
  ['power', 'kb-brain', ['ما هو ClickUp Brain؟', 'What is ClickUp Brain?'], ['Brain هو الذكاء الاصطناعي في ClickUp. يلخّص المهام والتعليقات، يكتب ويعيد صياغة النصوص، ينشئ مهاماً فرعية، ويجيب عن أسئلة حول عملك. ميزاته تعتمد على الخطة وإعدادات الشركة.', 'Brain is ClickUp’s AI. It summarizes tasks and comments, writes and rewrites text, creates subtasks and answers questions about your work. Features depend on your plan and company settings.'], 'brain ai assistant artificial intelligence ذكاء اصطناعي مساعد'],
  ['power', 'kb-ai-write', ['كيف أستخدم الذكاء الاصطناعي لكتابة وصف مهمة؟', 'How do I use AI to write a task description?'], ['في الوصف اكتب / أو اضغط زر الذكاء الاصطناعي، واطلب مثلاً «اكتب خطوات تسليم الموقع». راجع النص دائماً قبل الإرسال، ولا تضع بيانات سرية.', 'In the description type / or click the AI button, and ask e.g. "write the steps to hand over the site". Always review the text, and do not paste confidential data.'], 'ai write description generate draft text كتابه وصف توليد نص'],
  ['power', 'kb-ai-notetaker', ['هل يمكن للذكاء الاصطناعي تدوين محضر الاجتماع؟', 'Can AI take meeting notes?'], ['نعم، AI Notetaker يمكنه الانضمام للاجتماعات وتلخيصها وتحويل القرارات إلى مهام إن كان مفعّلاً في خطتكم. أبلغ الحضور قبل التسجيل.', 'Yes, the AI Notetaker can join meetings, summarize them and turn decisions into tasks if enabled on your plan. Tell attendees before recording.'], 'meeting notes minutes notetaker transcript محضر اجتماع ملاحظات تدوين'],
  ['power', 'kb-ai-agents', ['ما هم وكلاء Autopilot؟', 'What are Autopilot Agents?'], ['وكلاء ذكاء اصطناعي يعملون تلقائياً داخل قائمة أو قناة، مثل الرد على الأسئلة المتكررة أو كتابة تحديث يومي. تتوفر حسب الخطة ويضبطها المسؤولون.', 'AI agents that work on their own in a List or channel, like answering repeat questions or writing a daily update. They depend on your plan and are set up by admins.'], 'autopilot agent agents bot automatic ai وكيل وكلاء'],
  ['power', 'kb-ai-search', ['كيف أبحث في كل شيء بالذكاء الاصطناعي؟', 'How do I search everything with AI?'], ['البحث الشامل (Enterprise Search) مع Brain يبحث في المهام والمستندات والمحادثات والتطبيقات المربوطة، ويجيب بجملة مع الروابط. ابدأ بـ Ctrl/Cmd+K.', 'Enterprise Search with Brain looks across tasks, Docs, chat and connected apps and answers in a sentence with links. Start with Ctrl/Cmd+K.'], 'search ai find everything enterprise ask بحث شامل ذكي'],
  ['power', 'kb-ai-safe', ['هل استخدام الذكاء الاصطناعي آمن لبيانات الشركة؟', 'Is AI safe for company data?'], ['اتبع سياسة Omantel: لا تُدخل بيانات عملاء أو كلمات مرور أو معلومات سرية. راجع كل نص ينتجه الذكاء الاصطناعي، واسأل فريق الأمن عند الشك.', 'Follow Omantel policy: do not enter customer data, passwords or confidential information. Review every AI output, and ask the security team when in doubt.'], 'ai safe secure data privacy policy confidential امان بيانات خصوصيه سياسه'],

  /* ---- Import, export, templates ---- */
  ['power', 'kb-import-steps', ['ما خطوات استيراد ملف Excel؟', 'What are the steps to import an Excel file?'], ['جهّز الملف: صف أول للعناوين، عمود لكل حقل، والتواريخ بصيغة واحدة. ثم من الإعدادات ← Import/Export اختر CSV أو Excel، طابق الأعمدة مع الحقول، وراجع قبل التأكيد.', 'Prepare the file: a header row, one column per field, dates in one format. Then in Settings open Import/Export, choose CSV or Excel, map columns to fields, and review before confirming.'], 'import excel steps csv spreadsheet upload استيراد خطوات اكسل'],
  ['power', 'kb-import-tools', ['هل يمكن الاستيراد من Trello أو Asana أو Jira؟', 'Can I import from Trello, Asana or Jira?'], ['نعم، لدى ClickUp أدوات استيراد جاهزة لأدوات شائعة مثل Trello وAsana وJira وMonday. تجدها في Import/Export ضمن الإعدادات.', 'Yes, ClickUp has ready importers for common tools like Trello, Asana, Jira and Monday. Find them under Import/Export in settings.'], 'trello asana jira monday migrate import tool from نقل من'],
  ['power', 'kb-export', ['كيف أصدّر المهام إلى Excel؟', 'How do I export tasks to Excel?'], ['في عرض القائمة أو الجدول افتح قائمة النقاط أو «Export» واختر CSV أو Excel. يُصدَّر ما يظهر في العرض بفلاتره وأعمدته.', 'In List or Table view open the ellipsis menu (Export) and choose CSV or Excel. It exports what the view shows, with its filters and columns.'], 'export excel csv download table تصدير اكسل تحميل'],
  ['power', 'kb-template-save', ['كيف أحفظ قائمة أو مهمة كقالب؟', 'How do I save a List or task as a template?'], ['من قائمة النقاط (…) للقائمة أو المهمة اختر «Templates» ← «Save as template». سمّه بوضوح واختر ما يُحفظ مثل المهام الفرعية والحقول.', 'From the List’s or task’s ellipsis (…) menu choose Templates, then Save as template. Name it clearly and choose what to keep, like subtasks and fields.'], 'save template reuse create حفظ قالب انشاء'],
  ['power', 'kb-template-center', ['أين أجد القوالب الجاهزة؟', 'Where do I find ready-made templates?'], ['افتح «Template Center» من زر «+» أو قائمة القوالب. ابحث بكلمة مثل «Project» أو «IT» واختر قالباً ثم عدّله لفريقك.', 'Open the Template Center from "+" or the Templates menu. Search a word like "Project" or "IT", pick one and adapt it for your team.'], 'template center gallery ready find library مركز القوالب جاهزه'],
  ['power', 'kb-clickapps', ['ما هي ClickApps؟', 'What are ClickApps?'], ['ClickApps مفاتيح لتشغيل ميزات إضافية في المساحة، مثل تتبع الوقت والنقاط والتواريخ المتعددة والأولويات. يفعّلها المسؤول من إعدادات المساحة.', 'ClickApps are switches that turn on extra features in a Space, like time tracking, sprint points, multiple assignees and priorities. Admins turn them on in Space settings.'], 'clickapps clickapp features enable turn on ميزات تفعيل'],
  ['power', 'kb-integrations', ['ما التكاملات المتاحة مع ClickUp؟', 'What integrations does ClickUp have?'], ['يتكامل مع Microsoft Teams وOutlook وGoogle Drive وSlack وGitHub وZoom وغيرها. التفعيل من «App Center» أو التكاملات، وقد يحتاج موافقة تقنية المعلومات.', 'It integrates with Microsoft Teams, Outlook, Google Drive, Slack, GitHub, Zoom and more. Turn them on from the App Center (Integrations); IT approval may be needed.'], 'integration integrations teams slack drive zoom connect تكامل ربط تيمز'],
  ['power', 'kb-teams', ['هل يعمل ClickUp مع Microsoft Teams؟', 'Does ClickUp work with Microsoft Teams?'], ['نعم، تكامل Teams يعرض إشعارات المهام وروابطها داخل Teams ويسمح بإنشاء مهام من الرسائل، بعد تفعيله من المسؤول.', 'Yes, the Teams integration shows task notifications and link previews in Teams and lets you create tasks from messages, once an admin enables it.'], 'teams microsoft تيمز مايكروسوفت'],

  /* ---- Mobile and offline ---- */
  ['start', 'kb-mobile-app', ['هل يوجد تطبيق جوال؟', 'Is there a mobile app?'], ['نعم لأجهزة iPhone وAndroid. يمكنك إنشاء المهام وتحديث الحالة والتعليق وإرفاق الصور من الموقع، وتصلك الإشعارات.', 'Yes, for iPhone and Android. You can create tasks, update status, comment and attach photos from site, and get notifications.'], 'mobile app phone iphone android download تطبيق جوال هاتف'],
  ['start', 'kb-offline', ['هل يعمل ClickUp دون إنترنت؟', 'Does ClickUp work offline?'], ['بشكل محدود. تطبيق الجوال يسمح بإنشاء بعض المهام والتذكيرات دون اتصال ويزامنها لاحقاً. معظم الميزات تحتاج إنترنت.', 'Only partly. The mobile app lets you create some tasks and reminders offline and syncs them later. Most features need internet.'], 'offline no internet connection without اتصال انترنت بدون'],
  ['start', 'kb-desktop', ['هل يوجد تطبيق سطح مكتب؟', 'Is there a desktop app?'], ['نعم لـ Windows وMac، ويعمل أيضاً في المتصفح. التطبيق يعطي إشعارات سطح المكتب واختصارات أسرع.', 'Yes, for Windows and Mac, and it also runs in the browser. The app gives desktop notifications and faster shortcuts.'], 'desktop windows mac computer laptop سطح المكتب حاسوب ويندوز'],

  /* ---- Troubleshooting ---- */
  ['start', 'kb-cant-see', ['لا أرى مساحة أو قائمة يراها زميلي', 'I cannot see a Space or List my colleague sees'], ['غالباً ليست مشاركة معك. اطلب من صاحبها أو المسؤول إضافتك من زر «Share». وتأكد أنك في مساحة العمل الصحيحة.', 'Most likely it is not shared with you. Ask its owner or an admin to add you from the Share button. Also check you are in the right Workspace.'], 'cannot see missing access not visible hidden no permission لا ارى مفقوده لا تظهر وصول'],
  ['start', 'kb-slow', ['ClickUp بطيء، ماذا أفعل؟', 'ClickUp is slow. What can I do?'], ['حدّث الصفحة، أغلق التبويبات الكثيرة، واستخدم فلاتر لتقليل عدد المهام في العرض. جرّب التطبيق أو متصفحاً آخر. إن استمر فأبلغ الدعم.', 'Refresh, close extra tabs, and use filters so the view loads fewer tasks. Try the app or another browser. If it continues, tell support.'], 'slow loading lag freeze performance بطيء تحميل تعليق'],
  ['start', 'kb-undo', ['كيف أتراجع عن تغيير؟', 'How do I undo a change?'], ['بعد كثير من الإجراءات يظهر زر «Undo» لثوانٍ. وسجل النشاط (Activity) في المهمة يبيّن من غيّر ماذا ومتى.', 'After many actions an Undo button shows for a few seconds. The task’s Activity log shows who changed what, and when.'], 'undo revert history activity changed who تراجع سجل النشاط من غير'],
  ['start', 'kb-history', ['كيف أعرف من عدّل المهمة؟', 'How do I see who changed a task?'], ['افتح المهمة وانظر إلى سجل النشاط (Activity) بجانب التعليقات. يعرض كل تغيير في الحالة والمسؤول والتاريخ.', 'Open the task and look at the Activity feed next to the comments. It lists every change to status, assignee and dates.'], 'who changed edited history activity log audit من عدل سجل'],
  ['start', 'kb-support', ['من أسأل إن لم أجد الإجابة؟', 'Who do I ask if I cannot find the answer?'], ['اسأل زملاءك في منتدى هذه المنصة، أو أرسل سؤالك لفريق الدعم من صفحة «اسأل الفريق». ولدى ClickUp مركز مساعدة ودعم عبر المحادثة.', 'Ask colleagues in this hub’s forum, or send your question to the support team from Ask the team. ClickUp also has a Help Center and chat support.'], 'help support contact ask team question مساعده دعم تواصل', '#/support']
];
